(function () {
  var SSC_JE_PYG = { esemain: [] };
  function P(q, a, h, s) { return { q: q, a: a, h: h || "", s: s || "" }; }
  function E(exam, q, a, h, s) { var x = P(q, a, h, s); x.exam = exam; return x; }
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | TOM", "What is a kinematic pair? How are kinematic pairs classified? Explain.", "A kinematic pair is the assembly of two links joined together such that their relative motion is completely constrained. Classification: (a) nature of contact - lower pair (surface contact) and higher pair (point/line contact); (b) nature of mechanical constraint - closed pair (links held together mechanically) and unclosed/forced-closed pair (kept in contact by external force, e.g. cam and follower under spring force); (c) nature of relative motion - sliding, turning (revolute), rolling, screw (helical) and spherical pairs.", "Relative motion of the two elements is completely constrained", "Lower-pair examples: piston-cylinder (sliding), shaft in bearing (turning), nut on screw (screw). Higher-pair examples: gear teeth, cam-follower, ball/roller bearing, a rolling wheel on a rail. In a kinematic chain every link forms two pairs; making one link fixed converts the chain into a mechanism. DOF is found with Gruebler's criterion n = 3(l - 1) - 2j - h."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | Machining", "In a machining operation a tolerance of +/- 0.5 mm is kept. Explain the meaning of unilateral and bilateral tolerances.", "Tolerance is the total permissible variation in the size of a part. A bilateral tolerance allows deviation on both sides of the nominal size (e.g. 50 +/- 0.5 mm, the actual size may lie anywhere between 49.5 and 50.5 mm). A unilateral tolerance allows deviation on only one side of the basic size (e.g. 50+0.5/0 or 50+0.0/-0.5).", "Both signs with one number - bilateral; deviation on one side only - unilateral", "In production drawings shafts and holes are normally given unilateral tolerances using the basic-hole or basic-shaft system so that the maximum material condition rests on the safe side. The given +/- 0.5 mm is a bilateral tolerance. ESE expects each term to be explained with an example dimension and a note on which type is preferred for interchangeable manufacture."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | Machine Design", "A hollow shaft for a marine engine is to be designed for a power of 5 MW at 100 r.p.m. Point out how the two sides of the problem will be handled.", "Two sides: strength and rigidity (stiffness). Strength side: the torque is found from power, T = (P x 60)/(2*pi*N) = (5 x 10^6 x 60)/(2*pi*100) = 4.775 x 10^5 N.m, and the hollow section is sized against the induced shear stress tau = T/Zp where Zp = (pi/16) Do^3(1 - a^4), a = Di/Do, using a safe allowable shear stress. Rigidity side: limit the angle of twist with theta = T.L/(G.J) <= theta-allow where J for a hollow shaft = (pi/32) Do^4(1 - a^4). The larger of the two diameters governs; wall thickness t = Do(1 - a)/2.", "Strength: tau <= tau-allow with tau = T/Zp; Rigidity: theta = T.L/(G.J) <= theta-allow", "Choose a = Di/Do in the range 0.5-0.6 for hollow shafts. Compute Do from the strength equation and separately Do from the torsion (rigidity) equation for the shaft length, then select the larger. Marine shafts are usually long, so the rigidity check frequently governs."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | Machine Design", "For a 3-armed crane, the load transmitted to the mast is wx, whereas the mast is subjected to an axial force P and a bending moment M. Describe how the maximum and minimum stresses will be evaluated (direct stress combined with bending).", "Superpose the direct and bending stresses. Direct axial stress sigma-a = P/A is uniform over the section; the bending stress is sigma-b = M/Z, tension on one face and compression on the other. Result: sigma-max = P/A + M/Z (where the two add) and sigma-min = P/A - M/Z (where they oppose). Safety requires both to lie within the permissible stress range.", "sigma-max = P/A + M/Z; sigma-min = P/A - M/Z", "sigma-b is evaluated at the extreme fibre with Z = I/y. If P/A > M/Z the whole section stays in tension; if P/A < M/Z part of the section reverses sign and a stress neutral axis exists. Combined direct-plus-bending is the standard ESE treatment for crane masts, columns and eccentrically loaded bases."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | SOM", "Define coefficient of fluctuation of speed and coefficient of steadiness of a flywheel.", "Coefficient of fluctuation of speed Cs = (omega-max - omega-min)/omega-mean = (Nmax - Nmin)/Nmean. Coefficient of steadiness = 1/Cs = omega-mean/(omega-max - omega-min). A small Cs means a steady speed.", "Cs = (omega-max - omega-min)/omega-mean; steadiness = reciprocal of Cs", "The fluctuation of energy dE stored in the flywheel is related to Cs by dE = I.omega-mean^2.Cs, from which the required moment of inertia I and hence the rim dimensions are found. State the definitions both with angular velocities and with r.p.m. as ESE asks."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | Machining", "A steel shaft is supported on two bearings and machined on a lathe between centers with the usual dead and live centers. How is the shaft aligned and supported during turning?", "The work is mounted between the headstock center and the tailstock dead center; the axis of rotation is the line joining the two centers, so the centers define the alignment. A carrier (lathe dog) fixed to the work engages a pin on the faceplate so the headstock drives the rotation. Alignment of the tailstock to the headstock center is set by shifting the tailstock barrel so both center points lie on the lathe axis.", "Between centers on the axis joining the two centers; driven by a carrier (dog)", "Long slender shafts need steady rests or follower rests to prevent deflection under cutting forces. Alignment is verified by turning a test bar and checking with a dial indicator, or by the two-center alignment setup, so the turned diameter is uniform along the length."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | Machine Design", "An axially loaded rod has its minimum cross-sectional area limited by stress. Determine the shaft diameter under three failure theories for a bending moment M = 7.5 kN.m and twisting moment T = 10 kN.m with allowable stress 160 MPa, and give the probable reason for the difference in diameters.", "Section modulus A = pi.d^3/32, sigma = 32M/(pi d^3), tau = 16T/(pi d^3). Principal stresses: sigma-1 = sigma/2 + sqrt(sigma^2/4 + tau^2), sigma-2 = sigma/2 - sqrt(sigma^2/4 + tau^2). (i) Max shear stress theory (Guest): tau-max = sqrt(sigma^2/4 + tau^2) <= sigma-allow/2, giving d = 86.0 mm. (ii) Max strain energy theory (Haigh, nu = 0.24): sigma-1^2 + sigma-2^2 - 2.nu.sigma-1.sigma-2 = sigma-allow^2 gives d = 88.5 mm. (iii) Max shear strain energy theory (von Mises-Hencky): sigma-1^2 - sigma-1.sigma-2 + sigma-2^2 = sigma-allow^2 gives d = 90.0 mm. The diameters differ because each theory uses a different equivalent-stress criterion; the energy theories give a slightly larger (safer) shaft than the classical maximum-shear criterion.", "MSST: (16/pi d^3) sqrt(M^2 + T^2) <= sigma-allow/2; Haigh and Mises use the principal-stress equations given", "Quick path only if asked: M = 7.5, T = 10 kN.m, sigma-allow = 160 MPa. (i) Meq = sqrt(M^2 + T^2) = 12.5 kN.m -> sigma = 32 Meq/(pi d^3) <= 160 MPa -> d = 86.0 mm. (ii) sigma-1 = 320000/A, sigma-2 = -80000/A with A = pi.d^3/32; strain-energy equation with nu = 0.24 -> d = 88.5 mm. (iii) Mises equation -> d = 90.0 mm. Show principal-stress derivation and the reason for differing diameters for full marks."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | FM", "A jet of water issues horizontally from a fireman's nozzle of diameter 25 mm at a height of 28 m above the ground and strikes the ground 12 m in front of the nozzle. Estimate the rate of discharge.", "Area A = (pi/4)(0.025)^2 = 4.909 x 10^-4 m^2. For a horizontal jet the vertical fall is independent of the jet speed: y = (1/2) g t^2 gives t = sqrt(2y/g) = sqrt(56/9.81) = 2.389 s; the horizontal reach gives V = x/t = 12/2.389 = 5.02 m/s. Discharge Q = A.V = 4.909 x 10^-4 x 5.02 = 2.47 x 10^-3 m^3/s = 2.47 L/s.", "x = V.t; y = (1/2) g t^2; Q = A.V", "t = sqrt(2 x 28/9.81) = 2.389 s, V = 12/2.389 = 5.02 m/s, Q = (pi/4)(0.025)^2 x 5.02 = 2.47 x 10^-3 m^3/s. Note: in the textbook hose-stream problem a vertical-jet or inclined-jet variant is often set; quote this self-consistent solution and state your assumption."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '19 | FM", "A two-dimensional flat plate of width 0.3 m is towed at 2 m/s in water (nu = 1.02 x 10^-6 m^2/s). For the laminar boundary layer: (i) estimate the boundary layer thickness at 10 cm from the leading edge, (ii) indicate its slope at that point, (iii) estimate the drag.", "(i) Blasius laminar thickness delta = sqrt(60.nu.x/U); at x = 0.1 m, delta = sqrt(60 x 1.02 x 10^-6 x 0.1/2) = 1.75 mm. (ii) Slope d(delta)/dx = delta/(2x) = 1.75 x 10^-3/0.2 = 8.75 x 10^-3. (iii) Momentum thickness at the trailing edge x = 0.3 m, theta = delta/15 = 2.02 x 10^-4 m; mean skin-friction coefficient CD = 2.theta/L = 1.35 x 10^-3; drag D = CD.(1/2).rho.U^2.A = 1.35 x 10^-3 x 0.5 x 1000 x 4 x (0.3 x 1) = 0.81 N.", "delta = sqrt(60.nu.x/U); slope = delta/(2x); CD = 2.theta/L", "delta grows as x^(1/2) and the local skin friction decays along the plate. For comparison the turbulent value is delta = 0.37 x/Re^0.2, which ESE sometimes contrasts with the laminar result. Use rho = 1000 kg/m^3 for water."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '22 | Engineering Mechanics", "The rotor of a turbojet engine has a mass of 250 kg and radius of gyration 25 cm; it rotates at 12000 r.p.m. clockwise viewed from the front. The aircraft, flying at 1500 km/hr, turns to the right on a radius of 2 km. Compute the gyroscopic moment exerted on the structure and state whether the nose tends to rise or fall.", "I = m.k^2 = 250 x 0.25^2 = 15.625 kg.m^2; omega = 2.pi x 12000/60 = 1256.6 rad/s; precession omega-p = V/R = (1500/3.6)/2000 = 0.2083 rad/s. Gyroscopic couple C = I.omega.omega-p = 15.625 x 1256.6 x 0.2083 = 4.09 x 10^3 N.m = 4.09 kN.m. The nose tends to RISE.", "C = I.omega.omega-p = 4.09 kN.m; nose rises", "Sense rule: rotor spins clockwise viewed from the front, so its angular-momentum vector points forward along the flight axis; turning right sweeps the momentum vector downward as seen from the rear, and the reaction couple applied to the structure pitches the nose upward (classic result: clockwise-from-front rotor, right turn -> nose rises)."));
  SSC_JE_PYG.esemain.push(E("ESE Mains '22 | TOM", "What is a planetary (epicyclic) gear train? State its main uses. In the train shown, sun gear C is fixed, gear B is on the input shaft at 1000 r.p.m. counter-clockwise seen from the right, and gear F is on the output shaft; the arm A carrying compound planets D-E rotates freely on the output shaft. Using the tabular method, outline how the output speed is obtained.", "An epicyclic gear train is one in which the axes of some gears (the planets) are not fixed - they rotate about axes that themselves move on a rotating arm/carrier. Uses: automobile differentials, planetary gearboxes, hoists/wire-rope drives, watch trains and machine-tool drives - all giving large speed ratios in a compact space. Tabular method: (1) lock the arm and give a unit relative rotation; fill the speed of every gear relative to the arm from the tooth ratios; (2) add the arm's actual speed to each entry; (3) set the fixed sun (C) to zero absolute speed; this is the datum that lets the single unknown (output F speed) be solved.", "Row = gear; column entries = arm-locked speeds + arm speed; then enforce the fixed-gear condition", "Tooth-count data is needed to evaluate the train value e0 (= product of driver teeth / product of driven teeth). With C fixed the equation reduces to n-F = n-A(1 + e0); substitute n-B, the ratios and the signs (a negative result means reversal). ESE gives full credit for the table outline plus the statement that the numeric speed follows from the tooth counts."));


  if (typeof window !== 'undefined') {
    window.SSC_JE_PYG = SSC_JE_PYG;
  }
  if (typeof module !== 'undefined') {
    module.exports = SSC_JE_PYG;
  }
})();
