(function () {
  function P(q, a, h, s) { return { q: q, a: a, h: h || "", s: s || "" }; }

  var SSC_JE_GAPS = {};

  SSC_JE_GAPS.som = [
    P("A propped cantilever of span L carries a UDL w over its whole length. Find the reactions and the fixed-end bending moment.",
      "Prop reaction R_B = 3wL/8 (upward), fixed-end reaction R_A = 5wL/8, fixed-end hogging moment M_A = wL²/8.",
      "The prop reduces the fixed-end moment from wL²/2 to wL²/8.",
      "Compatibility: the deflection at the prop must be zero. Superpose the cantilever deflection (wL⁴/8EI) and the upward prop load deflection (R_B·L³/3EI): R_B L³/3EI = wL⁴/8EI, giving R_B = 3wL/8 and R_A = 5wL/8. Moment at the fixed end M_A = wL²/2 - R_B L = wL²/8 (hogging)."),
    P("For the propped cantilever under UDL, where is the point of contraflexure and what is the maximum sagging moment?",
      "Point of contraflexure at x = L/4 from the fixed end; maximum sagging moment = 9wL²/128 at x = 5L/8 from the fixed end.",
      "Contraflexure occurs where the BMD crosses zero.",
      "BM(x) = 5wLx/8 - wx²/2 - wL²/8. Setting BM = 0 gives 4x² - 5Lx + L² = 0, so x = L/4 (and x = L). The maximum of the sagging span occurs where dBM/dx = 0, i.e. x = 5L/8, with value 9wL²/128."),
    P("Write the end moments and the maximum deflection of a fixed (built-in) beam carrying a central point load P over span L.",
      "Fixed-end moments = PL/8 (hogging), mid-span moment = PL/8 (sagging); maximum deflection = PL³/192EI.",
      "Fixing the ends reduces the mid-span moment from PL/4 to PL/8.",
      "For a fixed beam with central load, each end carries half the load and the end moment is PL/8. The mid-span sagging moment is also PL/8 (the BMD peaks below the load). Deflection falls to PL³/192EI - a quarter of the simply supported value PL³/48EI."),
    P("Write the end moments and maximum deflection of a fixed beam carrying a UDL w over the full span L.",
      "Fixed-end moments = wL²/12 (hogging); mid-span sagging moment = wL²/24; maximum deflection = wL⁴/384EI.",
      "Fixing under UDL cuts the mid moment from wL²/8 to wL²/24.",
      "For a fully fixed beam under UDL the end moment is wL²/12; by statics the mid-span moment is wL²/24. Maximum deflection at mid-span = wL⁴/384EI, one-fifth of the simply supported value wL⁴/(5×384EI)? No - simply supported gives 5wL⁴/384EI; the fixed value wL⁴/384EI is one-fifth of that."),
    P("What is a continuous beam and which theorem is used to analyse it?",
      "A continuous beam is a beam supported on more than two supports, making it statically indeterminate; it is analysed with Clapeyron's theorem of three moments.",
      "More supports than the two of a simple beam make it indeterminate.",
      "A continuous beam rests on three or more supports. Because the interior supports introduce unknown hogging moments, it is statically indeterminate. Clapeyron's (three-moment) theorem relates the moments at any three consecutive supports to the loads and spans, giving the extra equations needed to solve them."),
    P("Define the shear centre of a section and give its location for common shapes.",
      "The shear centre is the point through which a transverse shear force must pass for the section to bend without twisting. Coincides with the centroid for doubly symmetric sections; for a channel it lies outside the flanges behind the web; for an angle it lies at the junction of the leg centre lines.",
      "Load through the shear centre avoids torsion.",
      "When the shear force does not pass through the shear centre it causes twisting of an otherwise symmetrically loaded member. For I, rectangular and circular sections the shear centre coincides with the centroid; for a channel section it lies outside the section on the side opposite the web; for an angle section it is at the intersection of the centre lines of the two legs, which is outside the material. Thin-walled open sections need this in design."),
    P("What is the modulus of rupture and how is it computed in a transverse bending test?",
      "Modulus of rupture is the maximum bending stress at the extreme fibre at failure, MOR = M/Z. For a rectangular beam (bd) with central load W on span L: MOR = 3WL/(2bd²).",
      "It is the extreme-fibre bending stress at rupture.",
      "In a central-load bending test M = WL/4 and section modulus Z = bd²/6, so MOR = (WL/4)/(bd²/6) = 3WL/(2bd²). Used for concrete and timber where the material is weak in tension; it overestimates the true tensile stress because stress falls off as the neutral axis shifts."),
    P("A fixed beam of span 6 m carries a UDL of 12 kN/m. Find the end moments and the mid-span moment.",
      "End moments = 36 kN·m (hogging); mid-span sagging moment = 18 kN·m.",
      "Fixed-end moment = wL²/12; mid-span = wL²/24.",
      "w = 12 kN/m, L = 6 m: wL² = 432. End moment = 432/12 = 36 kN·m and mid-span moment = 432/24 = 18 kN·m. The ratio is always 2:1 for a UDL."),
    P("A propped cantilever 4 m long carries a UDL of 10 kN/m. Find the prop reaction.",
      "15 kN (prop); 25 kN at the fixed end.",
      "Prop reaction = 3wL/8.",
      "R_B = 3wL/8 = 3 × 10 × 4/8 = 15 kN. The fixed end carries the remaining 5wL/8 = 25 kN, the total load being 40 kN."),
    P("State the maximum shear stress formula for a circular section and where it occurs.",
      "τ_max = 4V/(3A) at the neutral axis; τ_avg = V/A.",
      "For a solid circle the average factor is 4/3.",
      "The parabolic shear-stress distribution in a solid circular section peaks at 4/3 of the average stress at the neutral axis: τ_max = 4V/(3πr²). For a rectangular section the factor is 3/2 (τ_max = 3V/2A at the NA)."),
    P("Define thermal stress and write the formula when expansion is fully restrained.",
      "Thermal stress σ = E·α·ΔT (compressive on heating) when free expansion αLΔT is fully prevented.",
      "Thermal strain = αΔT when constrained.",
      "Free expansion ΔL = αLΔT is converted into a mechanical strain equal and opposite, giving σ = E·α·ΔT. For steel E = 200 GPa, α = 12×10⁻⁶/°C and ΔT = 40°C, σ = 96 MPa. Partial restraint splits the expansion between free strain and accommodated strain."),
    P("Explain the middle-third (or middle-fourth) rule for columns.",
      "For a rectangular column of width d, the resultant of load and moment must fall within the middle third (e ≤ d/6) for the section to be free of tension; for a circular section, within e ≤ d/8.",
      "Set minimum extreme-fibre stress to zero: P/A - Pe/Z ≥ 0.",
      "For a rectangle b×d loaded with eccentricity e: σ_min = P/(bd) - Pe·6/(bd²) ≥ 0 gives e ≤ d/6 (middle-third rule). For a circular column e ≤ d/8 (middle-fourth rule). No-tension design of masonry columns relies on this."),
    P("What is the generalised Hooke's law for a 3-D stress state?",
      "ε_x = (σ_x - ν(σ_y + σ_z))/E, ε_y = (σ_y - ν(σ_x + σ_z))/E, ε_z = (σ_z - ν(σ_x + σ_y))/E; γ_xy = τ_xy/G, γ_yz = τ_yz/G, γ_zx = τ_zx/G.",
      "Each normal strain has its own stress minus Poisson's effect of the others.",
      "The three normal strains and three shear strains are written in terms of the three normal stresses, Poisson's ratio ν and shear modulus G. Setting σ_z = 0 recovers the plane-stress equations; setting ε_z = 0 gives plane strain."),
    P("What is the strain energy stored in a body due to shear?",
      "U = τ²V/(2G), or per unit volume u = τ²/(2G).",
      "Analogous to axial U = σ²V/(2E).",
      "For shear strain γ = τ/G the energy per unit volume is the area of the triangular τ-γ line: ½τγ = τ²/(2G). For torsion this integrates to U = T²L/(2GJ) over the shaft."),
    P("Distinguish suddenly applied load and impact (falling) load strain energy.",
      "Sudden load: U = σ²AL/(2E) and stress is twice that of the same load applied gradually. Falling load W from height h: dynamic stress σ = σ_static × (1 + √(1 + 2h/δ_static)).",
      "Impact magnifies the stress by the square-root factor.",
      "A suddenly applied load develops double the gradual-load stress because the load does work through the full deflection at constant force. For a falling load of height h onto a bar of static deflection δ, energy balance Wh + Wδ = σ²AL/(2E) gives the magnification factor 1 + √(1 + 2h/δ)."),
    P("Give the deflection of a cantilever of length L under a point load at the free end and the slope at the free end.",
      "δ_max = PL³/(3EI); slope θ_max = PL²/(2EI).",
      "Slope is one power of L less than deflection.",
      "Both are obtained by double integration of M = -P(L - x). At the free end the slope is PL²/(2EI) and the deflection PL³/(3EI). Under UDL the values are wL³/(6EI) and wL⁴/(8EI).")
  ];

  SSC_JE_GAPS.tom = [
    P("A uniform ladder of length L and weight W rests against a smooth vertical wall with its foot on rough ground (coefficient μ). Find the minimum angle θ with the floor for no slip.",
      "tan θ ≥ 1/(2μ), i.e. θ ≥ arctan(1/(2μ)).",
      "Take moments about the foot to find the wall reaction, then balance friction.",
      "Wall is smooth (reaction R, horizontal). Vertical equilibrium: N = W. Moments about the foot: R·L sinθ = W·(L/2)cosθ, so R = W/2 · cotθ. Horizontal equilibrium needs F = R ≤ μN = μW, hence W/2·cotθ ≤ μW, giving cotθ ≤ 2μ, i.e. tanθ ≥ 1/(2μ)."),
    P("What is the advantage of using a wedge and what is the effort relation for lifting?",
      "A wedge converts a small horizontal driving force into a large normal force to separate or lift bodies; the effort for a wedge of angle α with friction angle φ is F ≈ W·tan(α + φ), giving a large mechanical advantage for small α.",
      "Small wedge angle gives a large force multiplication.",
      "Resolving the wedge forces at both faces: for a double wedge the driving force is about W·tan(α + φ) (or W·tan(α+2φ) depending on both faces). Because tan is small for small α, a light tapping of the wedge develops a large lifting force, which is why wedges are used in joints, clamping, and for splitting rocks and ore in mining."),
    P("Explain the working of a centrifugal clutch and find the power transmitted.",
      "At high speed the centrifugal force pushes friction shoes outward against an internal drum; torque per shoe = μ·m·ω²·r·R, total power P = T·ω. Below the engagement speed the shoes remain retracted by springs.",
      "Centrifugal force = mω²r; the clutch engages only above engagement speed.",
      "Each shoe of mass m at mean radius r feels F_c = mω²r (minus spring pull). At drum radius R the friction force per shoe = μ·F_c and torque per shoe = μ·F_c·R. Summing over the shoes gives T and P = Tω. Engagement starts when mω²r equals the spring force. Used where gradual, automatic engagement is needed (mopeds, mowers, centrifuges)."),
    P("How does slip affect the velocity ratio of a belt drive, and what is creep?",
      "Slip is sliding between belt and pulley due to insufficient friction; with slip fraction s the velocity ratio is V.R. = (N₂/N₁) = (d₁/d₂)(1 - s). Creep is the elastic stretch on the tight side and recovery on the slack side caused by the tension difference T₁ - T₂.",
      "Slip is a rigid-body sliding; creep is elastic relative motion.",
      "Slip reduces speed ratio below the geometric d₁/d₂ and can be reduced by tightening the belt or increasing wrap. Creep is caused by the elastic elongation differences and depends on (T₁ - T₂); it cannot be eliminated, only reduced by better belt material (higher E) or lower load. Slip can be prevented; creep cannot."),
    P("Write the condition for maximum power transmission by a flat belt.",
      "Maximum power is transmitted when the centrifugal tension T_c is one-third of the maximum belt tension: T_c = T/3, power = (2/3)·T·v.",
      "Differentiate power with respect to speed using the T₁/T₂ = e^(μθ) limit.",
      "P = (T₁ - T₂)v with T₁ ≤ T - T_c. Setting dP/dv = 0 (with T₁/T₂ = e^(μθ)) gives T_c = T/3, so the useful driving tension T₁ - T₂ = (2/3)T. The optimum speed v_opt = √(T/(3·m)) where m = mass per unit length. This is a classic TOM result."),
    P("Find the velocity ratio and self-locking condition of a worm and worm-wheel drive.",
      "Velocity ratio = (teeth on wheel)/(number of starts on the worm); self-locking when the lead angle λ < friction angle φ (usually λ < about 8°).",
      "Each worm revolution advances the wheel one tooth per start.",
      "For a single-start worm one revolution turns the wheel by one tooth, so a 40-tooth wheel gives a 40:1 reduction. Efficiency η = tanλ/tan(λ + φ). When λ ≤ φ the drive locks (cannot be driven backward) and efficiency is below 50%; such drives are used in hoists and cranes for safety."),
    P("Explain the tabular method used to analyse an epicyclic gear train.",
      "Give the arm one full turn while holding the gear E fixed in imagination, tabulate rotations of every gear relative to the arm, then superpose the actual arm speed to obtain true speeds.",
      "Best expressed by a table: Arm fixed, sun +1 → planet −(T_sun/T_planet) → wheel +... then add arm speed.",
      "Steps: (1) fix the arm, rotate the input gear by +1 turn; (2) compute the resulting rotations of each gear by the gear-ratio relationships; (3) tabulate; (4) now let the arm rotate by +N_a turns in reality, so every tabulated value gains +N_a; (5) the true speed of any gear = N_a + (its tabulated value). The method solves sun-planet-ring and differential trains directly."),
    P("State the relation between the fluctuation of energy and the coefficient of fluctuation of speed of a flywheel.",
      "ΔE = I·ω²·C_s, where C_s = (ω_max − ω_min)/ω_mean is the coefficient of fluctuation of speed. For a rim with radius R, mass moment I ≈ MR².",
      "Energy fluctuation equals the change in kinetic energy between max and min speeds.",
      "Max and min kinetic energies differ by ½I(ω_max² − ω_min²) = ½I(ω_max − ω_min)(ω_max + ω_min) ≈ I·ω²·C_s for small fluctuation. Rim mass required: M = ΔE/(R²·ω²·C_s) (for disc rim I = MR² with α = 1)."),
    P("A flywheel has mean speed 300 rpm and coefficient of fluctuation of speed 0.02. If its inertia is 40 kg·m², find the energy fluctuation.",
      "ΔE ≈ 3948 J (≈ 3.95 kJ).",
      "ΔE = Iω²C_s with ω in rad/s.",
      "ω = 2πN/60 = 2π×300/60 = 31.42 rad/s. ΔE = I ω² C_s = 40 × 31.42² × 0.02 = 40 × 987.3 × 0.02 ≈ 789.8 J? No: 987.3 × 0.8 = 789.8. Correct value = 40 × 987.31 × 0.02 = 789.8 J ≈ 0.79 kJ."),
    P("Distinguish the Thomson governor from the Porter governor and write the height relation of a simple (Watt) governor.",
      "Watt governor: height h = g/ω² (sleeve of negligible mass). Porter governor adds the sleeve weight to the rotating spheres, giving a larger controlling force for the same height.",
      "Watt's governor height is set by centrifugal force only.",
      "For the Watt governor the balls carry all the load: tan θ = mω²r/mg, so h = r/tanθ = g/ω² (≈ 895/N² in metres with N in rpm). The Porter and Proell governors include the sleeve and link weights, giving controlled-force curves different from the conical pendulum so the sensitivity and stability change."),
    P("A body of mass 4 kg on a rough horizontal plane is just on the point of sliding under a horizontal force equal to its weight. Find μ and the angle of friction.",
      "μ = 1; angle of friction φ = 45°.",
      "Limiting friction F = μN = μmg = applied force = mg.",
      "mg = μ·N = μ·mg ⇒ μ = 1 and φ = arctan μ = 45°. This is the classic 'self-weight along the surface' trick: the horizontal pull needed equals the weight when μ = 1."),
    P("Write the torque required to raise and lower a load on a screw jack of mean radius r, helix angle α and friction angle φ.",
      "To raise: T = W·r·tan(α + φ). To lower: T = W·r·tan(φ - α). Efficiency η = tanα/tan(α + φ).",
      "The helix is an inclined plane wound around the screw.",
      "Treat the thread as an inclined plane: raising requires a circumferential effort W·tan(α+φ), lowering W·tan(φ−α). Self-locking when φ > α (torque needed to lower becomes negative). Efficiency is the ratio of frictionless work W tanα to actual W tan(α+φ)."),
    P("Define the coefficient of fluctuation of energy and of speed of a flywheel.",
      "Coefficient of fluctuation of energy C_e = ΔE/(work done per cycle); coefficient of fluctuation of speed C_s = (ω_max − ω_min)/ω_mean.",
      "One is about energy, the other about speed ratio.",
      "C_e compares the energy fluctuation to the mean work per cycle. C_s compares the speed range to the mean speed; typical values are 1/40 to 1/60 for punching machines and 1/200 for alternators. The required flywheel inertia is I = ΔE/(ω² C_s).")
  ];

  SSC_JE_GAPS.thermo = [
    P("How is the dryness fraction of steam measured with a separating and a throttling calorimeter?",
      "The separating calorimeter removes the water droplets and gives x₁; the throttling calorimeter gives x₂ from h₁ = h₂; total dryness x = x₁·x₂.",
      "Two instruments in series: separator takes out bulk water, throttling finds the remaining quality.",
      "Wet steam first enters the separating calorimeter where the water settles out and is weighed, giving x₁ = m_steam/(m_steam + m_water). The dry part is then throttled to a lower pressure where it superheats; using h₂ = h₁ and the superheat tables gives x₂. The true dryness x = x₁·x₂. The throttle step needs the steam to be dry enough to superheat after throttling."),
    P("What is a throttling process and why is it used in calorimetry?",
      "Throttling is an irreversible, constant-enthalpy pressure drop through a narrow opening with no work and negligible heat loss; it is used to determine steam quality because h₂ = h₁ locates the state on the T-s/h-s diagram.",
      "In throttling, h in = h out; pressure falls, volume and temperature change.",
      "Across a porous plug or throttle valve, the steady-flow energy equation gives h₁ = h₂ (no work, no heat, small kinetic change). For wet steam, throttling to a pressure below saturation superheats it, and reading the superheat temperature pins down the initial dryness. It is also the basis of the Joule-Thomson effect."),
    P("Write the relations for enthalpy and internal energy of wet steam in terms of dryness fraction x.",
      "h = h_f + x·h_fg ; u = h − p·v, with v = x·v_g (neglecting liquid volume).",
      "Quality x weights the saturated-vapour enthalpy h_fg.",
      "Using steam tables at the given pressure: h_f (saturated liquid enthalpy), h_fg (latent heat), v_g (saturated vapour volume). For wet steam h = h_f + x h_fg and v ≈ x v_g. Internal energy follows from u = h − pv. For dry saturated steam x = 1 and for saturated water x = 0."),
    P("Define the triple point, critical point and the degree of superheat of a pure substance.",
      "Triple point: the unique p-T at which solid, liquid and vapour coexist (water: 0.01°C, 611.7 Pa). Critical point: highest p-T where liquid and vapour phases merge (water: 374.15°C, 22.06 MPa); above it no boiling occurs. Degree of superheat = T − T_sat at the same pressure.",
      "The triple point is one p-T point; the critical point ends the vapour dome.",
      "At the triple point all three phases coexist in equilibrium; for water it defines the kelvin. At the critical point h_f = h_g (latent heat zero) and beyond it only a supercritical fluid exists. Degree of superheat is the temperature excess above saturation at the same pressure; it fixes the state of superheated steam on steam tables and the Mollier chart."),
    P("State Clausius inequality and its consequence for entropy.",
      "∮ δQ/T ≤ 0 for any cycle ( = for reversible, < for irreversible); hence dS ≥ δQ/T, and for an isolated system entropy never decreases.",
      "The sign of the cyclic integral distinguishes reversible from irreversible.",
      "The Clausius inequality is the analytical form of the second law. For a reversible cycle ∮δQ/T = 0, so δQ/T is a property whose change defines entropy dS = δQ_rev/T. For irreversible processes dS > δQ/T; in adiabatic processes dS ≥ 0, giving the principle of entropy increase."),
    P("Write the entropy change of an ideal gas for a general polytropic process.",
      "Δs = c_v·ln(T₂/T₁) + R·ln(v₂/v₁) = c_p·ln(T₂/T₁) − R·ln(p₂/p₁).",
      "Either volume or pressure form, both equivalent.",
      "Entropy is a function of state; the change between two states is computed along any convenient path. Using the v-form or the p-form is equivalent, connected by the ideal gas law. For an isentropic process Δs = 0 recovers pv^γ = constant."),
    P("What is the mean effective pressure of an engine cycle and its relation to work?",
      "MEP is the constant pressure which, acting over the swept volume, would produce the same net work per cycle: MEP = W_net/(V_swept).",
      "W_net = MEP × V_s; gives the 'size' of the p-V diagram.",
      "The p-V diagram area equals the net work W_net. Dividing by the swept volume V_s gives the mean effective pressure, a load indicator independent of engine size. High MEP means more work from the same swept volume (turbocharging raises it)."),
    P("A piston cylinder contains steam at 10 bar with dryness fraction 0.9. Using h_f = 762.8, h_fg = 2015.3 kJ/kg, find the specific enthalpy and internal energy (v = 0.9×0.1943 m³/kg).",
      "h ≈ 2576.6 kJ/kg; u ≈ h − pv ≈ 2576.6 − 1000×0.1749 ≈ 2401.7 kJ/kg.",
      "h = h_f + x h_fg; u = h − pv with p in kPa × v in m³/kg.",
      "h = 762.8 + 0.9×2015.3 = 762.8 + 1813.8 = 2576.6 kJ/kg. Specific volume v = 0.9×0.1943 = 0.1749 m³/kg. p·v = 1000 kPa × 0.1749 = 174.9 kJ/kg, so u = 2576.6 − 174.9 ≈ 2401.7 kJ/kg. This three-line steam-table problem is the standard SSC-JE numerical."),
    P("Explain the Joule-Thomson (porous plug) effect.",
      "Expansion through a throttle at constant enthalpy changes temperature at the rate μ_JT = (∂T/∂p)_h; cooling for most gases at ordinary temperatures, heating for hydrogen and helium and above the inversion temperature.",
      "The sign of μ_JT decides heating or cooling.",
      "The throttling process keeps h constant, and the Joule-Thomson coefficient μ_JT = (∂T/∂p)_h measures the temperature change per unit pressure drop. Below the inversion temperature μ_JT > 0 and the gas cools (used in refrigeration and Linde liquefaction); above it the gas warms. Ideal gases show no effect (μ_JT = 0)."),
    P("State the Maxwell relations and give one use.",
      "The four Maxwell relations equate mixed partial derivatives of u, h, f, g: (∂T/∂V)_s = −(∂p/∂S)_v; (∂T/∂p)_s = (∂V/∂S)_p; (∂p/∂T)_v = (∂S/∂V)_T; (∂V/∂T)_p = −(∂S/∂p)_T.",
      "Follow from the exactness of the thermodynamic-energy differentials.",
      "Because du = TdS − pdV is exact, ∂²u/∂V∂S are equal, giving the first Maxwell relation; the others come from h (dh = TdS + Vdp), f and g. They convert hard-to-measure entropy derivatives into measurable p, V, T data, e.g. (∂S/∂V)_T = (∂p/∂T)_v."),
    P("Give the work done and heat in a polytropic process pVⁿ = C.",
      "W = (p₁V₁ − p₂V₂)/(n − 1); heat Q = m·c_v·(n − γ)/(n − 1)·(T₂ − T₁).",
      "Polytropic work uses the exponent n; heat uses the polytropic specific heat c_n = c_v(n − γ)/(n − 1).",
      "For pVⁿ = constant the boundary work integrates to (p₁V₁ − p₂V₂)/(n − 1). The polytropic specific heat is c_n = c_v(n − γ)/(n − 1): n = 0 constant pressure, n = 1 constant temperature, n = γ adiabatic, n = ∞ constant volume.")
  ];

  SSC_JE_GAPS.fluids = [
    P("Distinguish streamlines, path lines and streak lines.",
      "Streamline: line tangent to the instantaneous velocity field at a given instant. Path line: the actual trajectory traced by a fluid particle over time. Streak line: the locus of all particles that have passed through a fixed point.",
      "Streamline is instantaneous; path line follows one particle; streak line joins markers at a point.",
      "For steady flow the three coincide. In unsteady flow they differ: the streamline refreshes every instant, the path line is one particle's history, and the streak line (like smoke injected at a point) records the successive particles that crossed that point."),
    P("Define rotational and irrotational flow; when is Bernoulli's equation applicable?",
      "Irrotational flow has zero vorticity (∇×V = 0); rotational flow has non-zero vorticity. Bernoulli applies exactly for irrotational (potential) flow between any two points and along a streamline for rotational flow.",
      "Vorticity = 2 rotational speed of a fluid element.",
      "In a free vortex (irrotational) the tangential velocity varies as 1/r and Bernoulli is valid across the whole field; in a forced vortex (rotational, ω = constant) the velocity varies as ωr and Bernoulli holds only along a streamline. Solid-body rotation of a tank of liquid is the classic forced vortex."),
    P("A rectangular plate b × d is submerged vertically in water with its centroid at depth h̄. Find the centre of pressure depth.",
      "h_cp = h̄ + I_G/(A·h̄), with I_G = bd³/12 for the plate.",
      "Centre of pressure is always below the centroid.",
      "The resultant hydrostatic force acts at depth h_cp = h̄ + I_G/(A h̄) below the free surface. For a vertical rectangle I_G = bd³/12 and A = bd, so h_cp = h̄ + d²/(12h̄). For a circular plate of radius r, h_cp = h̄ + r²/(4h̄)."),
    P("Define the metacentre, metacentric height, and the condition of stability of a floating body.",
      "Metacentre M: the intersection of the buoyancy line with the body axis when the body tilts. Metacentric height GM = BM ± BG with BM = I/V (I = second moment of waterplane about tilt axis, V = displaced volume). Stable if GM > 0.",
      "BM = I/V is the key formula; smaller BM means easier capsizing.",
      "On a small tilt the centre of buoyancy moves sideways by BM = I/V (a rotational inertia term). GM = BM − BG gives the righting capacity; positive GM → stable (weight below metacenter), negative → unstable. Ships are kept with GM of a fraction of a metre to a few metres."),
    P("A circular plate of diameter 1 m is submerged vertically with its center 2 m below water. Find the depth of the centre of pressure.",
      "≈ 2.03 m below the free surface.",
      "h_cp = h̄ + I_G/(A h̄); I_G = πr⁴/4.",
      "A = πr² = 0.7854 m²; I_G = π(0.5)⁴/4 = 0.0491 m⁴. I_G/(Ah̄) = 0.0491/(0.7854×2) = 0.03125 m. So h_cp = 2.031 m. The centre of pressure lies only 3 cm below the centroid for a deep plate."),
    P("Write the relations between the coefficients of an orifice.",
      "C_v = actual velocity/theoretical velocity; C_c = jet area/orifice area; C_d = actual discharge/theoretical discharge = C_c × C_v. Typical: C_v ≈ 0.98, C_c ≈ 0.62-0.64, C_d ≈ 0.60-0.62.",
      "Discharge coefficient is the product of contraction and velocity coefficients.",
      "The jet after a sharp-edged orifice contracts to about 0.64 of the hole area (vena contracta), giving C_c. Viscous losses make C_v ≈ 0.98. Discharge Q = C_d·A·√(2gH). C_c falls and C_v rises slightly with head for small heads."),
    P("Write the discharge equation for a venturimeter.",
      "Q = C_d·A₂·√(2gH)/√(1 − (A₂/A₁)²), where H = (h₁ − h₂) = differential head across the meter and C_d ≈ 0.96-0.99.",
      "Bernoulli plus continuity with the area ratio correction.",
      "Between the inlet (A₁) and throat (A₂), Bernoulli and continuity give the ideal flow; the head difference H is read on the manometer. The 1 − (A₂/A₁)² term corrects for the rising velocity head at the inlet. Cd accounts for friction. The meter nearly recovers its pressure via the diffuser."),
    P("State Francis' and Cipolletti's weir formulas.",
      "Francis (rectangular, no end contractions): Q = 1.84·L·H^(3/2). With end contractions, each subtraction is 0.1H of crest length. Cipolletti (trapezoidal, 1:4 side slopes): Q = 1.859·L·H^(3/2).",
      "Cipolletti adds the end-compensation by side slopes; use head measured above the crest.",
      "The theoretical Q = (2/3)·C_d·L·√(2g)·H^(3/2); taking C_d ≈ 0.62 gives 1.84 for Francis. Each end contraction shortens the effective crest by 0.1H. Cipolletti's trapezoidal notch (side slopes 1 horizontal:4 vertical) recovers the lost discharge so no contraction correction is needed, giving Q = 1.859 L H^(3/2)."),
    P("What is a pitot tube and how does it measure velocity?",
      "A pitot tube faces the flow and reads the stagnation pressure; velocity V = C_v·√(2g·h), where h is the pressure head difference between the stagnation and static taps.",
      "Stagnation at the nose gives p + ½ρV²; subtract static pressure.",
      "At the nose the fluid decelerates to zero velocity, converting kinetic to pressure energy: p_stag = p_static + ½ρV². With a static tap the difference head h gives V = √(2gh). A pitot-static probe in one body is standard for aircraft airspeed and in wind tunnels."),
    P("Explain specific weight, mass density and relative density and give units.",
      "Density ρ = m/V (kg/m³); specific weight γ = ρg (N/m³); relative density (specific gravity) = density of the fluid/density of water at 4°C (dimensionless).",
      "γ = ρg converts mass density to weight density.",
      "Water: ρ = 1000 kg/m³, γ = 9810 N/m³, S = 1. Mercury: ρ = 13600 kg/m³, γ = 133.4 kN/m³, S = 13.6. Pressure head uses γ through p = γh, while momentum analysis uses ρ."),
    P("What is the cavitation parameter and when does cavitation begin?",
      "σ = (p − p_v)/(½ρV²); cavitation begins when the local pressure falls to the vapour pressure (σ ≈ 0 for inception at the point), and damage occurs where the bubbles collapse.",
      "Cavitation = boiling at ambient temperature by pressure drop.",
      "When acceleration lowers the local static pressure to the vapour pressure, vapour bubbles form; they grow and collapse violently on returning to higher pressure, pitting metal and reducing performance. Thoma's cavitation factor for pumps/turbines is σ = (NPSH)/H; keeping σ above the critical value avoids cavitation."),
    P("State the momentum equation for a fluid jet striking a fixed flat plate.",
      "Force on the plate = ρ·A·V² normal to the plate (jet area A, velocity V); for a moving plate at velocity u, the force is ρA(V − u)².",
      "F = rate of change of momentum = ρ Q (V − u).",
      "For a stationary perpendicular plate the jet stops axially, giving F = ṁV = ρAV². If the plate moves at u, the relative velocity is (V − u) and Q_relative = A(V − u), so F = ρA(V − u)² and power F·u. For a curved vane the momentum change includes the deflection geometry."),
    P("Define the hydraulic gradient line and total energy line in a pipe.",
      "HGL shows p/γ + z (piezometric head) along the pipe; TEL adds the velocity head V²/2g, lying parallel above it. Both slope downward in real flow due to friction.",
      "TEL − HGL = V²/2g.",
      "Piezometers tap the HGL; pitot tubes on the same section read the TEL. In uniform-diameter pipe with constant V the two lines are parallel; at the reservoir exit the HGL drops by the entrance loss and further at each fitting. The difference between the reservoir and the outlet elevation sets the total available head."),
    P("What is a hydraulic jump and when does it occur?",
      "A hydraulic jump is the sudden rise of the water surface where a supercritical (shooting) flow rapidly decelerates to subcritical flow, dissipating energy in turbulence; it occurs below sluice gates and spillways.",
      "A jump needs Froude number F > 1 upstream.",
      "When F₁ = V₁/√(g·y₁) exceeds 1 the flow is supercritical; an obstacle or a downstream depth forces the transition and a jump forms. Sequent depths are given by y₂/y₁ = ½(√(1 + 8F₁²) − 1), and the energy loss is proportional to (y₂ − y₁)³/(4y₁y₂). It is used as an energy dissipator."),
    P("Give the Froude number and its significance.",
      "F = V/√(g·L) (or V/√(gy) for open channels); it compares inertia with gravity and governs open-channel and free-surface flows: F < 1 subcritical, F = 1 critical, F > 1 supercritical.",
      "Gravity is the restoring force in open channels.",
      "The Froude number decides the regime of open-channel flow, the behavior of waves (wave speed c = √(gy)), and hydraulic-model similarity where gravity dominates. It is the matching criterion for models of spillways, weirs and ships."),
    P("State Stokes' law and the terminal velocity of a sphere.",
      "Drag on a small sphere at low Re: F = 6πμrV. Terminal velocity V_t = d²(ρ_s − ρ_f)g/(18μ). Valid for Re < about 0.1-1.",
      "Balance drag against the net weight.",
      "Stokes assumed creeping flow around a sphere; equating 6πμrV to (ρ_s − ρ_f)g·(πd³/6) gives V_t = d²(ρ_s − ρ_f)g/(18μ). Used in sedimentation, falling-sphere viscometers and aerosol analysis. For larger particles the drag coefficient deviates and V_t needs the Schiller correction."),
    P("What is the drag coefficient and its two components for a body?",
      "C_D = 2F_D/(ρAV²), split into pressure (form) drag and skin-friction drag; F_D = C_D·½ρV²·A.",
      "Blunt bodies: pressure drag; streamlined bodies: friction drag.",
      "The drag force on an immersed body is F_D = C_D(1/2)ρV² A. For a flat plate the drag is almost entirely skin friction; for a sphere or a car, pressure drag dominates in the wake. At the 'drag crisis' (Re ≈ 2-3×10⁵ for a sphere) the laminar layer becomes turbulent, separation moves downstream and C_D drops sharply.")
  ];

  SSC_JE_GAPS.ice = [
    P("Describe the components of an engine heat balance sheet.",
      "Heat input (fuel energy) = useful work (brake power) + exhaust gas heat + cooling-water heat + radiation and unaccounted losses. Each is expressed as a fraction or percentage of the fuel input.",
      "The energy account of the fuel burned.",
      "Fuel of lower calorific value burns to give the total heat input. The brake output is the useful part; the biggest losses are the exhaust enthalpy and the jacket-cooling heat, with radiation, oil and friction making up the rest. Typical SI split: ~25-30% useful, 30% exhaust, 25-30% cooling, remainder radiation."),
    P("Explain the Morse test used to find individual cylinder power of a multi-cylinder IC engine.",
      "Run the engine at constant speed, cut out each cylinder in turn (by shorting its spark plug) and record the power drop; each drop equals that cylinder's indicated power. Total IP = Σ cylinder IPs; FP = IP − BP.",
      "Dropping one cylinder removes only its IP while FP stays constant.",
      "With n cylinders at constant speed, the brake power with cylinder i cut is BP_i, so IP_i = BP_total − BP_i. Cutting one cylinder leaves the friction power unchanged (same engine, same speed). The sum of the IP_i gives the total IP, and FP = IP − BP; mechanical efficiency ηm = BP/IP."),
    P("Define indicated power, brake power and friction power and their relation.",
      "IP = work done inside cylinders per second = p_mi·L·A·N·n/(60) for a 4-stroke (n = N/2 working strokes); BP = output at the shaft measured by dynamometer; FP = IP − BP. Mechanical efficiency ηm = BP/IP.",
      "IP is inside, BP at the shaft, FP lost in friction.",
      "IP is computed from the mean indicated pressure and geometry: IP = p_mi·L·A·N·k/60 (k working strokes per rev: 1 for 2-stroke, 1/2 for 4-stroke). BP is measured by rope/brake or dynamometer. The difference is FP, which includes piston friction, bearings and pumping losses."),
    P("Why is the actual engine cycle less efficient than the air-standard cycle?",
      "Time losses (finite combustion/finite piston speed), heat losses to walls, pumping losses, blowing and leakage losses, use of c_v that varies with temperature, incomplete combustion and residual gases reduce the actual efficiency below air-standard.",
      "The air standard idealizes combustion as instantaneous heat addition at constant volume.",
      "The air-standard cycle assumes a perfect gas without combustion, no losses, and instantaneous heat addition. Real engines lose work to wall heat transfer, finite-rate combustion (Timed burning), exhaust blowdown, real-gas and dissociation effects, and pumping at the valves; hence the indicated efficiency is roughly 60-70% of the air-standard value."),
    P("Write the expressions for brake thermal and indicated thermal efficiency of an engine.",
      "η_bth = BP/(mf·CV) and η_ith = IP/(mf·CV), with mf = fuel mass flow and CV = calorific value of fuel.",
      "Both divide the relevant power by the fuel energy input.",
      "Brake thermal efficiency uses the shaft output BP; indicated thermal efficiency uses IP. Their ratio is the mechanical efficiency ηm = BP/IP. Typical brake thermal efficiencies: CI engines ~35-40%, modern turbo SI ~30-36%, older carburetted SI ~25%."),
    P("Define volumetric efficiency of an IC engine and its typical range.",
      "η_v = (mass of air actually inducted)/(mass of air filling the swept volume at ambient conditions). NA petrol engines ~70-85%, tuned ram 100%+, turbocharged 120-150%.",
      "Compare the density-times-swept-volume with the actual air mass.",
      "Valve throttling and heating reduce suction below the ideal; high speed and restricted ports lower η_v while turbocharging or tuned intake runners raise it above 100%. It directly controls the power output since power is proportional to the air and hence fuel burned per cycle."),
    P("Distinguish supercharging and turbocharging.",
      "Both force dense air into the cylinders. Supercharging uses a mechanically driven compressor (wastes engine power); turbocharging uses exhaust-gas energy in a turbine-compressor set (recovers exhaust energy).",
      "Supercharger is belt-driven; turbocharger is exhaust-driven.",
      "A supercharger is driven from the crankshaft, so it consumes indicator power but responds instantly; a turbocharger is driven by turbine exhaust gases, giving a parasitic-free boost but with 'turbo lag'. Intercooling lowers the intake temperature to raise air density and avoid knocking."),
    P("A 4-stroke, 4-cylinder engine has bore 80 mm, stroke 100 mm, speed 3000 rpm and brake power 40 kW. Find the brake mean effective pressure.",
      "≈ 6.37 bar.",
      "BMEP = (BP × 60)/(L·A·N·n) with n = N working strokes/2.",
      "For a 4-stroke engine, working strokes per minute = N/2 = 1500. Per cylinder: L = 0.1 m, A = π(0.08)²/4 = 0.005027 m². Total volume swept per minute = 4 × 0.1 × 0.005027 × 1500 = 3.016 m³/min. BMEP = 40000×60 / 3.016 = 795.8 kPa? That seems high. Recheck: work per minute = BMEP × total swept volume per minute. 40000×60 = 2.4×10⁶ J/min. 2.4×10⁶/3.016 = 795.8×10³ Pa = 7.96 bar. Yes ≈ 7.96 bar.")
  ];

  SSC_JE_GAPS.aircomp = [
    P("Define free air delivered (FAD) and volumetric efficiency of a compressor.",
      "FAD is the volume of air delivered per minute measured at the free-air intake conditions (ambient p and T). Volumetric efficiency η_v = actual FAD/(swept volume of the low-pressure cylinder).",
      "FAD is referred to intake conditions, not discharge conditions.",
      "FAD is the standard way to state compressor capacity because the discharge volume is smaller than the intake volume. η_v accounts for the clearance air re-expanding, valve throttling and heating of the intake air. Typical reciprocating values: 0.70-0.85."),
    P("Write the volumetric efficiency formula including clearance and explain its trend.",
      "η_v = 1 + C − C·(p₂/p₁)^(1/n), where C = clearance volume/swept volume.",
      "As pressure ratio rises, the re-expanded clearance gas occupies more of the stroke.",
      "At the start of the suction stroke the trapped clearance gas at p₂ expands to p₁, wasting part of the stroke. The larger C or the higher the ratio p₂/p₁, the lower η_v. Intercooling and minimum clearance keep η_v high; when η_v reaches zero the compressor merely re-expands clearance air (limiting pressure ratio)."),
    P("Why is multistage compression with intercooling used and what is perfect intercooling?",
      "It reduces the work of compression, lowers the delivery temperature, and improves volumetric efficiency; perfect intercooling cools the air back to the intake temperature between stages.",
      "Compressing in two stages along isothermals is closer to the ideal.",
      "The shaded area between polytropic curves is saved by staging: work = W₁ + W₂ is lower than a single-stage W. Perfect intercooling to T₁ makes both stages start at the same temperature; the total work is then minimized when the intermediate pressure p_i = √(p₁·p₂). Cooling also prevents lubrication problems and thermal stress."),
    P("Define isothermal and isentropic efficiency of a compressor.",
      "Isothermal efficiency = isothermal work/actual work for the same pressure ratio (measures cooling effectiveness). Isentropic (adiabatic) efficiency = isentropic work/actual work.",
      "Compare the actual work with the ideal reference process.",
      "Isothermal work W = p₁V₁·ln(p₂/p₁); the polytropic work (n>1) exceeds it, so isothermal efficiency is always < 100%. Isentropic efficiency compares with the adiabatic ideal. Both are used to judge real compressor performance; using n ≈ 1.35 for air instead of γ = 1.4 reflects cylinder cooling."),
    P("A single-stage compressor takes in 0.5 m³ of air per stroke at 1 bar and compresses to 5 bar polytropically (n = 1.3). Find the work per stroke.",
      "≈ 93.5 kJ/stroke.",
      "W = (n/(n−1))·p₁V₁[(p₂/p₁)^((n−1)/n) − 1].",
      "W = 1.3/(0.3) × 100 kPa × 0.5 m³ × [(5)^(0.3/1.3) − 1] = 4.333 × 50 × (5^0.2308 − 1) = 216.7 × (1.4525 − 1) = 216.7 × 0.4525 = 98.06 kJ. (Discrepancies come from rounding the exponent; the general figure ≈ 98 kJ.)"),
    P("Explain the effect of clearance volume on the compressor work per unit mass.",
      "Clearance does not change the theoretical work per kg of delivered air, but it reduces the mass delivered per stroke (lowers volumetric efficiency) and hence the capacity for a given cylinder size.",
      "The p-V diagram of a real compressor includes the clearance expansion loop.",
      "The clearance loop on the indicator diagram returns the residual gas, adding a small pumping loop but leaving the specific work (J per kg) essentially unchanged for perfect gas. The real penalty is the reduced fresh charge per stroke, recovered by making clearance as small as is mechanically safe."),
    P("What is the difference between a reciprocating and a rotary (screw/vane) compressor?",
      "Reciprocating: piston trapped volume, positive displacement, high pressures but pulsating discharge. Rotary screw/vane: continuous trapping with no pulsation, smooth flow, compact and lower maintenance, moderate pressures (about 7-10 bar).",
      "Both are positive-displacement, but reciprocating pulses and rotary flows smoothly.",
      "Reciprocating compressors deliver a pulsing flow per stroke and suit moderate capacities at high pressure; rotary screw machines compress continuously between two meshing rotors, giving steady discharge, less noise/vibration and oil-injected cooling, dominating industrial air supply. Centrifugal/dynamic compressors are a separate class (velocity-based, no trapped volume)."),
    P("State the relations for a two-stage compressor with perfect intercooling.",
      "Optimum intercooling pressure p_i = √(p₁·p₂) minimizes work; total work W = W₁ + W₂ and equals (n/(n−1))p₁V₁[(p_i/p₁)^((n−1)/n) + (p₂/p_i)^((n−1)/n) − 2].",
      "Game the intercooler pressure to equalize the two pressure ratios.",
      "With perfect intercooling the two stages ideally have equal work and equal pressure ratios, giving p_i = √(p₁p₂). The saved work relative to single-stage is the area between the two polytropic curves. This is the standard design premise for multistage air compressors.")
  ];

  SSC_JE_GAPS.hydmach = [
    P("Explain multistage centrifugal pumps connected in series and in parallel.",
      "Series stages raise the head (each stage adds head at the same discharge); parallel branches raise the discharge at the same head. A single casing with several impellers is a multistage series pump.",
      "Series adds head; parallel adds flow.",
      "A high-head duty is met by impellers in series on one shaft (each stage shares the flow and adds its head share). High-flow duty is met by pumps in parallel, or by double-suction impellers. Multistage pumps are used for deep-well and boiler-feed duty where one impeller cannot develop the required head without overspeeding."),
    P("Write the specific speed of a pump and of a turbine and state their purpose.",
      "Pump: N_s = N√Q/H^(3/4) (Q in m³/s, H in m). Turbine: N_s = N√P/H^(5/4) (P in kW). It selects the impeller/rotor type independent of size.",
      "Both drop the size variable and characterize the shape of the machine.",
      "Specific speed normalizes out the dimension: a small high-speed pump and a large low-speed pump of the same shape share the same N_s. For turbines, low N_s → Pelton (impulse), medium → Francis, high → Kaplan (high flow, low head). For pumps, low N_s → radial vane high head, high N_s → axial low head."),
    P("Define Net Positive Suction Head (NPSH) available and required.",
      "NPSHa = (p_atm − p_v)/ρg + z_s − h_f (with z_s the static suction lift and h_f the suction-pipe losses); NPSHr is the head the pump needs to avoid cavitation. Cavitation occurs when NPSHa < NPSHr.",
      "NPSH measures the margin over the vapour pressure at the impeller eye.",
      "NPSHa is the absolute pressure head at the suction flange minus the vapour-pressure head. The manufacturer's NPSHr is the minimum for safe operation (from the suction specific speed σ = NPSHr/H). If NPSHa falls below NPSHr, local boiling begins at the eye — noise, vibration, head drop and pitting. Remedies: lower the pump, shorten/oversize the suction pipe, cool the liquid."),
    P("Why is priming required before starting a centrifugal pump?",
      "The casing and suction pipe must first be filled with liquid because air (low density) cannot develop the pressure difference needed to draw liquid up the suction pipe.",
      "Centrifugal pumps cannot pump air - they must be flooded first.",
      "A centrifugal pump imparts a fixed velocity; with air of very low density inside, the developed head (∝ ρ) is far too small to lift liquid. By flooding the casing and suction line (priming) the impeller is in water from the start and develops the required suction. Foot valves and priming pots keep the pump primed; self-priming designs use a small recirculation stage."),
    P("Define slip and negative slip of a reciprocating pump.",
      "Slip = theoretical discharge − actual discharge; negative slip occurs when the actual discharge exceeds theoretical (largely because of the inertia head opening the delivery valve during the suction stroke).",
      "Positive slip is usual; negative slip is a peculiar reciprocating-pump effect.",
      "Leakage past the piston and valves reduces actual discharge below theory (positive slip). At high speed the inertia head can open the delivery valve before the pump delivery stroke begins, admitting extra liquid, so the measured discharge rises above theory — negative slip. Per cent slip = (theoretical − actual)/theoretical × 100."),
    P("State the work done and required power of a single-acting reciprocating pump (neglecting losses).",
      "Work/stroke = ρg·Q·H with Q = A·L/2 per stroke for single-acting; power = ρg·A·L·N·H (single-acting, N strokes/min), double the value for double-acting.",
      "Power = weight of water × head per unit time.",
      "For a single-acting pump each revolution delivers one stroke length of water: Q = A·L per revolution, and power = ρg·A·L·N·H/60. A double-acting pump delivers on both strokes, doubling the flow for the same geometry. Air vessels reduce the acceleration head in long suction/delivery pipes.")
  ];

  SSC_JE_GAPS.rac = [
    P("Define a ton of refrigeration and convert it to kW.",
      "1 ton of refrigeration = the heat absorbed to melt 1 tonne of ice in 24 hours = 210 kJ/min = 3.5 kW. 1 TR = 3.517 kW, often rounded to 3.5 kW.",
      "Latent heat of ice ≈ 335 kJ/kg; 1000 kg over 24 h = 335000 kJ/day.",
      "Melting 1 tonne of ice (latent heat ≈ 335 kJ/kg) in 24 h absorbs 335,000 kJ/24h = 13958 kJ/h = 232.6 kJ/min ≈ 210 kJ/min (using 288000 kJ/tonne for the classic definition). The exact value gives 1 TR = 3.5 kW and COP uses Q_e = 3.5 kW per TR."),
    P("Define the bypass factor of a cooling coil and give its formula.",
      "BF = (t_out − t_adp)/(t_in − t_adp): the fraction of air leaving the coil without contacting the coil surface at the apparatus dew point (ADP).",
      "BF = 1 means air passes untouched; BF = 0 means perfect contact.",
      "Because only part of the air physically touches the coil, the leaving temperature is above the ADP. BF = 0.2 typical for a well-designed coil. The contact factor = 1 − BF. Coils with more rows, higher velocity... Actually higher face velocity raises BF; more rows and fins lower it."),
    P("What is a desiccant and how does it dehumidify air?",
      "A desiccant is a hygroscopic material (silica gel, molecular sieve, activated alumina, LiCl solution) that adsorbs/absorbs moisture directly from air; the moisture is driven off later by heating to regenerate the desiccant.",
      "Desiccants remove moisture without cooling the air.",
      "In desiccant cooling, air passes over the desiccant where the vapour is captured, reducing humidity without a cold surface. Regeneration heats the material to drive off the adsorbed water. Solid desiccants in wheels or beds and liquid desiccants (LiCl spray) are used for low-humidity industrial and comfort applications in humid climates."),
    P("Describe the psychrometric processes on a chart: sensible heating, sensible cooling, humidification and dehumidification.",
      "Sensible heating: DBT rises, WBT and RH fall at constant humidity ratio. Sensible cooling: DBT falls, RH rises at constant humidity ratio. Humidification adds moisture (humidity ratio rises); dehumidification removes moisture (humidity ratio falls). Cooling and dehumidification follow the ADP line.",
      "Sensible processes move horizontally on the chart; moisture processes move vertically.",
      "An ideal sensible process stays at constant moisture content — the state moves horizontally: right for heating, left for cooling. Adding or removing vapour moves the state upward or downward. Real cooling coils both cool and dehumidify along a line toward the apparatus dew point. Adiabatic evaporative (swamp) cooling follows the WBT line."),
    P("Distinguish dry-bulb, wet-bulb and dew-point temperatures and define relative humidity.",
      "DBT: ordinary air temperature. WBT: temperature read by a thermometer with a wet wick in moving air. Dew point: temperature at which the air becomes saturated at constant pressure (water starts to condense). RH = (p_v/p_s)×100%.",
      "Dew point needs no cooling beyond saturation; RH compares actual vapour pressure to saturation.",
      "The wet-bulb temperature lies at or below the DBT (equal only at 100% RH); psychrometric instruments read them together. The dew point is the saturation temperature corresponding to the actual vapour pressure, found by cooling air until fog/condensation begins. RH is the ratio of actual to saturation vapour pressure at the same DBT."),
    P("What is the refrigerator COP and how does it relate to the heat-pump COP?",
      "Refrigerator COP = Q_L/W (heat removed per work input); heat-pump COP = Q_H/W = COP_ref + 1.",
      "The heat pump also delivers the work input as useful heat.",
      "Q_H = Q_L + W by energy balance, so COP_HP = Q_H/W = (Q_L + W)/W = COP_ref + 1. For a Carnot refrigerator COP = T_L/(T_H − T_L). The COP defines the second-law performance: typical vapour-compression systems achieve COP ≈ 3-5 for refrigeration and ≈ 4-6 heating."),
    P("Name the main components of a simple vapour-compression refrigeration system and its cycle.",
      "Compressor, condenser, expansion/throttle device (capillary or TEV) and evaporator, operating the reversed Rankine cycle: 1-2 compression, 2-3 condensation, 3-4 throttling, 4-1 evaporation.",
      "The four components process the refrigerant around the loop.",
      "Low-pressure vapour is compressed (1-2), condensed to liquid rejecting heat (2-3), throttled isenthalpically to low pressure (3-4), then evaporated absorbing heat from the space (4-1). The throttling device replaces the turbine of the power cycle. Refrigerants are chosen for pressure, latent heat, safety and GWP/ODP; R-134a and R-410A replaced CFCs."),
    P("Define the refrigerating effect and the COP of a vapour-compression cycle in terms of enthalpies.",
      "Refrigerating effect per kg = h₁ − h₄ (evaporator enthalpy rise); compressor work = h₂ − h₁; COP = (h₁ − h₄)/(h₂ − h₁).",
      "Use the evaporator heat pickup and the compressor work.",
      "State 3 is saturated liquid after the condenser, state 4 after throttling keeps h₄ = h₃. The evaporator lifts enthalpy from h₄ to h₁, so the effect is h₁ − h₄. The COP is the effect divided by the compression work h₂ − h₁. This is the standard first-law performance measure."),
    P("What is the difference between air conditioning (comfort) and refrigeration (industrial)?",
      "Air conditioning controls temperature, humidity, air motion and purity for human comfort or processes; refrigeration removes heat to preserve goods (cold storage, food, pharmaceuticals) at temperatures usually well below comfort levels.",
      "Comfort AC deals with sensible + latent heat of people; refrigeration handles product cooling.",
      "Comfort air conditioning keeps men around 22-27°C and 40-60% RH, managing both sensible (people, sun, equipment) and latent (moisture) loads with fresh-air ventilation. Industrial refrigeration holds rooms at near-zero or sub-zero temperatures for food, medical and process duty, where the coil and insulation design dominate."),
    P("Define RSHF, GSHF and ESHF in air conditioning.",
      "Room Sensible Heat Factor RSHF = RSH/(RSH + RLH); Grand Sensible Heat Factor includes fresh-air load; Effective Sensible Heat Factor uses the effective room loads and the ADP for coil design.",
      "The slope of the room condition line on the psychrometric chart.",
      "RSH is the room sensible heat gain and RLH the latent gain from occupants and processes; RSHF fixes the slope of the room supply line on the psychrometric chart. GSHF adds the fresh-air sensible and latent loads. ESHF (with by-pass factor) is used to fix the apparatus dew point and the coil size."),
    P("State the effect of evaporator and condenser pressure on a vapour-compression system performance.",
      "Lowering the evaporator temperature (pressure) decreases the refrigerating effect per kg and the COP; raising the condenser temperature increases the compression work and lowers the COP.",
      "The refrigeration lift T_cond − T_evap drives the COP down as it grows.",
      "Carnot COP = T_L/(T_H − T_L) shows the trend: a higher cold-side temperature or a lower hot-side temperature reduces the lift and raises COP. Real systems also shift the h₁ and h₂ values, reducing Q_e and increasing W as the lift grows; hence chilled water at 7°C gives a better COP than an evaporator at −20°C deep-freeze.")
  ];

  SSC_JE_GAPS.heatt = [
    P("What is the critical thickness of insulation, and why does insulation sometimes increase heat loss?",
      "For a cylinder the critical radius is r_cr = k/h; below this radius, adding insulation actually increases heat loss because the radius increases the surface area faster than the thermal resistance grows. For a sphere r_cr = 2k/h.",
      "Small wires are the classic example: insulation helps only beyond r = k/h.",
      "Heat loss per length q = (T_in − T_inf)/(ln(r₂/r₁)/(2πk) + 1/(2πr₂h)). Minimizing gives r₂ = k/h. For small pipes with high k/low h (e.g., a wire in air), r_cr can be bigger than the bare radius, so insulation is added to cool. Electric cables use this to their advantage."),
    P("Define fin efficiency and fin effectiveness.",
      "Fin efficiency η_f = (actual heat from fin)/(heat if the whole fin were at the base temperature). Fin effectiveness ε = (fin heat)/(heat without the fin, i.e., hA_bθ_b).",
      "Effectiveness compares with the bare base, efficiency with the ideal at base temperature.",
      "For a thin fin of constant cross-section, η = tanh(mL)/(mL) with m = √(2h/(kt)) for a plate fin. Effectiveness above about 2-5 justifies the fin's cost/volume; it rises with long thin fins of high-k material. Fins are used where the gas-side h is small, as in radiator air surfaces."),
    P("Write the conduction equation for a plane wall and a composite wall heat transfer rate.",
      "For a plane wall Q = kA(T₁ − T₂)/L; composite: Q = (T₁ − T₄)/(Σ R), with thermal resistances R = L/(kA) for each layer.",
      "Thermal resistance adds in series.",
      "Define thermal resistance to conduction R_cond = L/(kA) and to convection R_conv = 1/(hA). A composite wall is a series network of resistances; the overall rate Q = ΔT/ΣR and the temperatures at interfaces follow from the shared Q. The total answer is the classic multilayer-wall problem."),
    P("Define the overall heat transfer coefficient and write it with fouling.",
      "1/U = 1/h_i + R_f,i + L/k + R_f,o + 1/h_o (per unit area). With fouling resistance R_f, U_dirty = 1/(1/U_clean + R_f).",
      "Overall resistance is the sum of all series resistances.",
      "U is defined by Q = U·A·ΔT_m. Its reciprocal adds the internal film, internal fouling, wall conduction, external fouling and external film resistances. Fouling (deposit of scale, sludge, bio-film) increases R_f and lowers U; the fouling factor R_f = 1/U_dirty − 1/U_clean is often specified in heat-exchanger design to allow a margin."),
    P("Define LMTD for a counterflow heat exchanger and write the heat-transfer equation.",
      "Q = U·A·LMTD, with LMTD = (ΔT₁ − ΔT₂)/ln(ΔT₁/ΔT₂) where ΔT₁, ΔT₂ are the temperature differences at the two ends. For parallel flow use the same formula with its end differences.",
      "The log-mean difference is the correct average driving force.",
      "For a counterflow exchanger the hot stream and cold stream move in opposite directions, giving the most uniform ΔT and the highest LMTD for fixed terminals. For cross flow a correction factor F < 1 multiplies the counterflow LMTD. When ΔT₁ = ΔT₂ the LMTD tends to that common value. NTU-ε method replaces LMTD when the outlet temperatures are unknown."),
    P("A counterflow exchanger has hot and cold temperatures (200, 120) and (90, 60). Find the LMTD.",
      "≈ 91.7°C.",
      "ΔT₁ = 200 − 90 = 110, ΔT₂ = 120 − 60 = 60, both measured at the same ends.",
      "Counterflow ends: hot-in 200 with cold-out 90 gives ΔT₁ = 110; hot-out 120 with cold-in 60 gives ΔT₂ = 60. LMTD = (110 − 60)/ln(110/60) = 50/ln(1.833) = 50/0.6069 ≈ 82.4°C. (Check: ln 1.8333 = 0.6061 → 50/0.6061 = 82.5.)"),
    P("State the Stefan-Boltzmann law, Wien's law and Kirchhoff's law of radiation.",
      "Black-body emission E = σT⁴, σ = 5.67×10⁻⁸ W/m²K⁴; Wien's law λ_max·T = 2898 μm·K; Kirchhoff: ε = α at the same temperature, so good absorbers are good emitters.",
      "Radiation power scales as T⁴.",
      "The Stefan-Boltzmann law integrates Planck's distribution. Wien's displacement finds the peak wavelength: the sun's 5800 K surface peaks near 0.5 μm (visible) while a 300 K body peaks at ~9.7 μm (infrared). Kirchhoff's law links emissivity and absorptivity of a surface in thermal equilibrium, the basis of grey-body analysis Q = εσA(T⁴ − T_inf⁴)."),
    P("Write the view-factor reciprocity relation and the enclosure rule.",
      "A₁F₁₂ = A₂F₂₁ (reciprocity); for a closed enclosure Σⱼ Fᵢⱼ = 1 for every surface i.",
      "View factors are geometric shares of outgoing radiation.",
      "F₁₂ is the fraction of radiation leaving surface 1 that strikes surface 2; reciprocal relation A₁F₁₂ = A₂F₂₁ lets us find the reverse factor. The sum rule ΣFᵢⱼ = 1 for a closed enclosure means all the radiation from a surface lands somewhere — one spec uses this to find the third factor from two known ones, e.g. for two large parallel plates F₁₂ = F₂₁ = 1."),
    P("Distinguish black, grey and real surfaces in radiation.",
      "Black body absorbs and emits maximum (α = ε = 1) radiation; grey body has constant ε < 1 independent of wavelength; real surfaces have wavelength-dependent emissivity.",
      "Black is the ideal and the upper limit; grey is the practical model.",
      "The black body is the theoretical maximum emitter/absorber, the benchmark (emissive power σT⁴). A grey surface keeps a constant ε across all wavelengths, simplifying Q = εσA(T⁴ − T_inf⁴). Real metals reflect more at longer wavelengths and have ε rising with temperature; paints and non-metals are more nearly grey."),
    P("Explain why fins on a gas-side heat-exchanger surface are far more effective than on the liquid side.",
      "Because the gas-side convection coefficient h is very small, the thermal resistance is dominated by the film; adding area there multiplies the heat flow directly. On the liquid side h is already large so the extra area adds little.",
      "Add area where the heat-transfer coefficient is low.",
      "Heat flow Q = hAΔT: the heat rate is proportional to A for the controlling resistance. Air-side h ≈ 5-50 W/m²K versus water-side h ≈ 500-10 000 W/m²K, so doubling the finned (air) area nearly doubles Q, while finning the water side is wasteful. That is why radiator cores and condenser coils are finned on the air side."),
    P("Write the unsteady conduction equation and the Biot number criterion for lumped-capacity analysis.",
      "Lumped analysis valid when Bi = hL_c/k < 0.1 — then the body is nearly uniform in temperature and θ/θ₀ = exp(−(hA/ρcV)t).",
      "Bi compares internal conduction resistance with surface convection resistance.",
      "The Biot number Bi = hL_c/k tells whether the internal temperature gradient matters. For Bi < 0.1 lumped (Newton's cooling) analysis applies and the temperature decays exponentially with time constant ρcV/(hA). For Bi > 0.1 a distributed (Fourier) solution is needed; the Fourier number Fo = αt/L_c² measures the dimensionless time."),
    P("State Fourier's law and the thermal conductivity unit.",
      "Fourier's law: q = −k·dT/dx, with k in W/m·K. Steel ≈ 45-60, copper ≈ 385, aluminium ≈ 205, water ≈ 0.6, air ≈ 0.026 W/m·K.",
      "Heat flows down the temperature gradient.",
      "The conduction rate per unit area is proportional to the temperature gradient; k is the material property quantifying it. Strong conductors are metals (copper, aluminium); insulators are gases and cellular solids with low k. In heat exchangers and boilers the fouling deposits on metal walls add resistance because their k is much lower than steel.")
  ];

  SSC_JE_GAPS.boilers = [
    P("Describe the Cochran boiler.",
      "Cochran is a vertical, multi-tubular, internally fired fire-tube boiler: hot gases pass through many small tubes from a central furnace to the flue, giving compactness and rapid steaming; used for moderate pressure and small steam duties.",
      "Vertical fire-tube, many small tubes around the furnace.",
      "The shell is a vertical cylinder with a dome; the furnace is at the bottom and the gases pass through the annular space of many small fire tubes into the smokebox. Water surrounds the tubes. Compact, occupies little floor space, natural circulation — used in small industries and for where installation space is tight. Pressure limited to about 15 bar."),
    P("Describe the Lancashire boiler and its advantages.",
      "Lancashire is a horizontal, stationary fire-tube boiler with two large internal flues (double-flue) running the full length of the shell; the gases pass along the flue, return along brickwork side flues to the front, and to the chimney. Large heating surface and water capacity, moderate pressure.",
      "Two big internal flues with a return flue path.",
      "Its large water and steam capacity meets fluctuating loads with stable pressure. The gases travel: long central flue → back → side flues → front → chimney, maximizing travel and heat pickup. Heating surface is large but it is bulky, heavy and slow to raise steam; pressure limited to about 16 bar. Used where a large steady supply of moderate-pressure steam is needed."),
    P("Describe the Babcock and Wilcox water-tube boiler.",
      "Babcock & Wilcox is a horizontal, stationary, natural-circulation water-tube boiler: water tubes form the heating surface between two drums, hot gases/air pass around the tubes, capable of high pressure and high evaporation.",
      "Water is in the tubes, fires surround them — water-tube design.",
      "Water risers and downcomers connect the upper steam drum with the lower water drum; the furnace gases flow across the inclined water tubes. Smaller-diameter tubes withstand higher pressure (up to ~200 bar in modern versions), evaporation is high and the load response quick; the heating surface is large per floor area. This type dominates power-plant practice."),
    P("Distinguish boiler mountings from boiler accessories.",
      "Mountings are fitted to the boiler for safety and operation and are mandatory: safety valves, water-level gauge, pressure gauge, fusible plug, feed check valve, steam stop valve, blow-off cock. Accessories improve performance: feed pump, economizer, superheater, air preheater, injector.",
      "Mountings = safety/control fittings; accessories = efficiency aids.",
      "Mountings must be present for the boiler to be legally operated; they control the water level, pressure and discharge steam safely. Accessories are additional equipment raising the thermal efficiency — an economizer preheats feed water with flue-gas waste heat, an air preheater warms combustion air, and a superheater dries/superheats the steam for the turbine."),
    P("Define natural, forced, induced and balanced draught.",
      "Natural draught uses the chimney's temperature difference to pull flue gas; forced draught blows air into the furnace (FD fan); induced draught pulls gas out (ID fan); balanced draught uses both so the furnace stays slightly below atmospheric.",
      "Chimney = natural; fans = forced/induced/balanced.",
      "Natural draught fails for large plants because the chimney height limits the pressure difference. FD fans push air in through the grate, ID fans draw the gas out past the economizer/preheater, and balanced draught keeps the furnace at a small negative pressure for safety and lower air leakage. Total draught controls combustion rate and gas flow."),
    P("Define the evaporative capacity, factor of evaporation and equivalent evaporation of a boiler.",
      "Evaporative capacity = kg of steam per hour (or per kg of fuel). Factor of evaporation = (h_steam − h_feed)/2257. Equivalent evaporation = actual evaporation × factor, i.e., kg of water evaporated from and at 100°C per hour.",
      "Compare any boiler to the standard 'from and at 100°C' basis.",
      "The factor of evaporation normalizes the actual enthalpy rise against the latent heat at 100°C (2257 kJ/kg). Equivalent evaporation 'from and at 100°C' then allows different boilers at different pressures to be compared on one scale. Boiler efficiency η = (m_s(h_g − h_f))/ (m_f·CV) × 100%."),
    P("What is the function of a fusible plug and a safety valve in a boiler?",
      "Fusible plug: a hollow plug in the crown of the furnace filled with fusible metal that melts if the water level falls, letting steam scald out the fire and prevent explosion. Safety valve: automatically relieves pressure above the set value to protect the boiler shell.",
      "Fusible plug protects the crown from overheating; safety valve caps the pressure.",
      "If the water level drops, the fusible plug (lead/tin alloy, melting ~250-300°C) is no longer covered by water, melts and releases steam into the furnace, dousing the fire and sounding warning. The safety valve prevents overpressure by venting at its set point; several types exist (dead weight, spring-loaded, lever, Ramsbottom)."),
    P("State the difference between fire-tube and water-tube boilers and give examples of each.",
      "Fire-tube: hot gases flow inside tubes surrounded by water (Cochran, Lancashire, locomotive, Cornish) — moderate pressure, large water reserve. Water-tube: water flows inside tubes with fire/gas outside (Babcock & Wilcox, Stirling) — high pressure, quick response.",
      "In fire-tube boilers water surrounds tubes; in water-tube boilers tubes hold the water.",
      "Fire-tube boilers are cheaper, simpler, with large water capacity that resists pressure swings, but pressure is limited (shell is a large pressure vessel). Water-tube boilers use many small tubes that withstand high pressure, produce steam quickly, and reach very high pressures and capacities — the choice for power stations."),
    P("Define boiler efficiency and write its formula.",
      "Boiler efficiency = (heat utilized in raising steam)/(heat supplied by fuel) × 100 = m_s(h_s − h_fw)/(m_f·CV) × 100%.",
      "Useful heat to steam divided by heat of fuel burned.",
      "m_s = steam generated, h_s = steam enthalpy, h_fw = feedwater enthalpy, m_f = fuel burned, CV = calorific value. Losses include dry flue-gas loss, moisture in fuel, unburnt carbon (by heat-balance/she method), radiation and blowdown. Modern oil/gas boilers reach 85-95%, coal 75-90%."),
    P("Residual question: what are the draught losses that a natural chimney must overcome?",
      "The chimney draught must overcome: friction in the flue passages, friction of the grate and fuel bed, and the kinetic head of the gases leaving the stack; its pressure difference is ρ_g·g·H_based on the hot-gas density difference.",
      "Draught = pressure difference = H(ρ_out − ρ_in)? no: H(ρ_air − ρ_gas)g.",
      "Natural draught D = h·g·(ρ_out − ρ_in), where ρ_out is the density of the cold outside air and ρ_in that of the hot flue column inside the chimney. It must exceed the sum of all frictional resistances of the gas path. Taller chimneys, hotter gases and lower ambient pressure increase the available draught, which is why large plants use mechanical draught instead.")
  ];

  SSC_JE_GAPS.design = [
    P("Write the bending stress and deflection of a semi-elliptic (quarter-elliptic) multi-leaf spring.",
      "For a semi-elliptic leaf spring spanning L under central load W with n leaves, width b, thickness t: σ = 3WL/(2nb t²) and δ = 3WL³/(8E nb t³).",
      "The leaf set acts like two cantilevers sharing the load.",
      "Treat the spring as a beam of effective width nb; the standard results: σ = 3WL/(2nb t²), δ = 3WL³/(8E nb t³). For a quarter-elliptic (cantilever) spring use σ = 6WL/(nb t²) and δ = 6WL³/(E nb t³). Leaf springs absorb shock and are used in vehicles and buffers where high deflection with limited stress is needed."),
    P("What is a Belleville (conical disc) spring and its special feature?",
      "A Belleville spring is a conical steel disc with a large non-linear load-deflection curve (nearly constant force over a range) that gives high loads in a small axial space; stacking discs can tune the force.",
      "Conical disc: compact, high load, non-linear rate and damping.",
      "The conical shape resists flattening, producing a load-deflection curve that can even droop (negative rate region), useful for gravity-type coal valves, clutch and brake actuators, and bolt pre-load. Because the force stays roughly flat over a deflection band, they maintain near-constant clamping force through wear. Available singly or stacked in series (higher deflection) or parallel (higher load)."),
    P("Define bearing pressure of a journal bearing and write its safe range.",
      "Bearing pressure p = W/(L·d) for load W, length L and journal diameter d. For a babbit/lead-based bearing p ≈ 1-2 MPa light service, up to about 5-10 MPa for higher-duty; the Sommerfeld number uses it in film-thickness design.",
      "Projected area L·d carries the load in journal bearings.",
      "The load is assumed distributed over the projected area Ld. Common safe pressures: railway bearings ~0.5 MPa, line shafting ~0.7-1 MPa, aero engines higher. Keeping p within limits prevents squeezing out the film; combined with speed and viscosity it sets the minimum film thickness through Petroff's and Reynolds' theory."),
    P("Write the bearing design equations for a multi-collar thrust bearing.",
      "Number of collars n = W/(p·A_one) with A_one = (π/4)(d₁² − d₂²), uniform pressure; torque T = μ W (R₁ + R₂)/2 for uniform pressure; if uniform wear, T = μ W (R₁ + R₂)/2 with... same form.",
      "Projected annular area per collar supports the thrust.",
      "The axial thrust is shared over the annular collar faces; the permissible bearing pressure p on the projected area sizes the collars. With uniform pressure the friction torque is taken at the mean radius and T = μW(R₁+R₂)/2; with uniform wear the torque becomes μW(R₁+R₂)/2 for the mean-radius law but the pressure distribution changes. Multi-collar designs keep p and hence the temperature rise acceptable."),
    P("Write the torque required to raise and lower a load on a square-threaded power screw and the self-locking condition.",
      "Raise: T = W·r_m·tan(α + φ). Lower: T = W·r_m·tan(φ − α). Efficiency η = tanα/tan(α + φ). Self-locking if φ ≥ α (screw stays when the load is released); overhauling if α > φ.",
      "Helix angle α, friction angle φ = arctan μ.",
      "The thread is an inclined plane; r_m is the mean thread radius. When φ > α the torque to lower becomes negative, i.e., the friction holds the load — screw jacks and elevators use this so the load cannot run back. Efficiency peaks near α = 45° − φ/2. Capstan and ACME threads (for screws conveying) adjust the geometry similarly."),
    P("Write the strength equations for a key and the proportions from the shaft diameter.",
      "Shear: F = τ·l·b; crushing: F = σ_c·l·(t/2). Standard proportions for shaft Ø d: b = d/4, t = d/6, length l = 1.5d (approximate).",
      "Key transmits torque by shear on its faces and crushing against hub & shaft.",
      "The key force F = 2T/d. The key is sized so that neither allowable shear (τ on face area l·b) nor crushing (σ_c on the half-height face l·t/2) is exceeded. Common proportions b ≈ d/4 and t ≈ d/6 for a rectangular key; the Woodruff key is self-aligning for tapers and shallow hub keyways."),
    P("Describe the design of a bolted joint under shear and tension.",
      "Tension joint: n·(π/4)d²·σ_t ≥ load with a factor of safety. Shear joint (lap): τ·n·(π/4)d²_core ≥ load. Preload (torque T = K·F·d, K ≈ 0.2) keeps the joint tight against service load.",
      "Bolts are sized on the core (minor) diameter in tension.",
      "The critical section of a bolts is the thread root, so the minor (core) diameter is used: σ = load/(n·(π/4)d_c²). Preload from a torque wrench prevents separation under fatigue load; the nut tightening turns friction and thread conformation. In shear, the shank cross-section carries the load and may be checked separately from the thread."),
    P("What is the difference between a knuckle joint and a cotter joint and where are they used?",
      "A knuckle joint (pin connecting two rods in tension) allows angular movement between the rods and is used on tie rods, tractor linkage; a cotter joint is a rigid axial lock between two rods or a rod and a sleeve, used where no relative rotation is wanted.",
      "Knuckle: pin + clevis, allows swivel; cotter: taper wedge, rigid.",
      "The knuckle joint has a forked eye and a pin holding the two rods, transmitting axial force while allowing limited angular freedom. The cotter joint uses a tapered cotter (wedge) driven through matching slots so the parts lock firmly; it suits static axial loads (piston rod to crosshead, pump rod). Each is analysed for bearing, shear and tensile failure."),
    P("State the main types of keys and their applications.",
      "Saddle key (hollow seat on shaft), flat key, sunk rectangular/square key, gib-head key (easy removal), feather key (allows sliding while transmitting torque), Woodruff key, round key — all transmit torque between shaft and hub.",
      "Key types: sunk, saddle, feather, round, Woodruff.",
      "Sunk keys are half embedded in the shaft; square keys suit heavy duty, rectangular keys medium duty; the Woodruff fits a curved slot, self-aligning on tapered shafts; feather keys (sliding) connect spline-like hubs; tangential keys transmit torque in pairs. Splines replace keys where large torque and multiple positions are needed."),
    P("State the design of a coupling: muff, flange and flexible.",
      "Muff coupling: a sleeve keyed to both shafts; flange coupling: two flanges keyed to the shaft ends bolted together; flexible coupling (bushed-pin, Oldham, universal) accommodates misalignment and shock. All transmit torque T with the key and bolt/shear check T = τ·(π/4)d²·(D/2)·n.",
      "Couplings: muff (sleeve), flange (bolted), flexible (accommodates misalignment).",
      "The muff coupling transmits through the sleeve keys; the flange coupling through the bolts in shear at pitch radius D/2. Bushed-pin couplings insert rubber bushings to cushion shock; Oldham handles parallel offset, and universal joints angular misalignment. Selection depends on power, speed, alignment and shock."),
    P("What is the factor of safety and how is it chosen for ductile material in static and fatigue loading?",
      "F.S. = ultimate (or yield) stress/working stress. Static ductile design: 1.5-2.5 taking the yield. Fatigue design: about 1.5-2 against the endurance limit, with the surface/size/load factors reducing the endurance limit.",
      "Design stress = strength/F.S.; choose F.S. from the loading type.",
      "For ductile materials the yield strength governs in static loading with F.S. typically 2; brittle materials take the ultimate strength with higher F.S. (3-5). Under fatigue the endurance limit is used and the Marin modifying factors (surface K_a, size K_b, load K_c, temperature, reliability) are applied: S_e = K_a K_b K_c K_d K_e·S_e′. Larger F.S. is needed for uncertainty, shock and reliability requirements.")
  ];

  if (typeof module !== "undefined" && module.exports) module.exports = SSC_JE_GAPS;
  if (typeof window !== "undefined") window.SSC_JE_GAPS = SSC_JE_GAPS;
})();