const fs = require('fs');
const path = require('path');
const filePath = path.resolve(__dirname, '..', '3d-globe.html');
let html = fs.readFileSync(filePath, 'utf8');

function esc(s) { return (s || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t'); }

function entry(n, la, ln, sub, desc, fact) {
  return `  {n:'${esc(n)}',la:${la},ln:${ln},sub:'${esc(sub)}',desc:'${esc(desc)}',fact:'${esc(fact)}'},`;
}

const inserts = {
  w_bay: [
    entry('Bay of Bengal',15,90,'Indian Ocean · 2,172,000 km²','Largest bay in the world. Bordered by India, Bangladesh, Myanmar, Sri Lanka. Major rivers: Ganges, Brahmaputra, Godavari, Mahanadi. Andaman & Nicobar Islands. Cyclone-prone. Bay of Bengal Initiative (BIMSTEC).','Largest bay (2.17M km²) · India, Bangladesh, Myanmar, Sri Lanka · Ganges-Brahmaputra · Cyclones · BIMSTEC'),
    entry('Bay of Fundy',45,-65,'Canada · 16,000 km² · Highest tides','World\'s highest tides — up to 16m. Between New Brunswick and Nova Scotia. 160 billion tonnes of seawater flow in/out daily. Hopewell Rocks. Bay of Fundy National Park. Whale watching. UNESCO Biosphere Reserve.','16m tides (world\'s highest) · New Brunswick-Nova Scotia · Hopewell Rocks · Fundy NP · Whale watching'),
    entry('San Francisco Bay',37.8,-122.4,'USA · California · 1,600 km²','Natural harbor on California coast. Golden Gate Bridge connects to Pacific. Major ports: Oakland, SF, Richmond. Silicon Valley on south shore. Angel Island and Alcatraz. Bay Area population 8M.','Golden Gate Bridge · Oakland/SF ports · Alcatraz · Silicon Valley · 8M population'),
    entry('Hudson Bay',60,-86,'Canada · 1,230,000 km² · Arctic','Large inland sea in northeastern Canada. Connected to Atlantic via Hudson Strait. Named after Henry Hudson (1610). James Bay southern extension. Beluga whale habitat. Churchill polar bears. Port of Churchill.','1.23M km² · James Bay · Henry Hudson 1610 · Polar bears (Churchill) · Beluga whales'),
    entry('Chesapeake Bay',38,-76.5,'USA · Maryland/Virginia · 11,600 km²','Largest estuary in the US. Susquehanna River feeds from north. Famous for blue crabs, oysters, rockfish. Baltimore, Annapolis, Norfolk on shores. Chesapeake Bay Bridge-Tunnel. Bay restoration since 1983.','Largest US estuary · Blue crabs · Baltimore & Annapolis · Bridge-Tunnel · Restoration program'),
    entry('Bay of Biscay',44.5,-4,'Europe · 223,000 km²','Rough waters of the North Atlantic between France and Spain. Known for fierce storms and high waves. Major ports: Bilbao, Santander, La Rochelle, Brest. Fishing grounds. Basque Country coastline. Famous shipping route.','France-Spain coast · Rough seas · Basque Country · Bilbao & Santander · Shipping lanes'),
    entry('Bay of Plenty',-37.5,177,'New Zealand · North Island','Large bay on north-eastern NZ coast. Cities: Tauranga, Rotorua. White Island active volcano offshore. Rich marine life — dolphins, orcas, seals. Kiwifruit capital. Beautiful beaches (Mount Maunganui).','Tauranga · White Island volcano · Dolphins & seals · Kiwifruit · Mount Maunganui beach'),
    entry('Bay of Kotor',42.5,18.7,'Montenegro · Adriatic','Stunning fjord-like bay in southern Adriatic. Medieval towns: Kotor, Perast, Risan, Tivat. UNESCO World Heritage. Orjen and Lovcen mountains backdrop. Palaces and churches. Popular cruise destination.','Dramatic fjord-like bay · Kotor (UNESCO) · Orjen mountains · Medieval towns · Adriatic cruise port'),
    entry('Bay of Naples',40.8,14.3,'Italy · Tyrrhenian Sea','Beautiful bay on Italy\'s southwest coast. Cities: Naples, Pompeii, Herculaneum, Sorrento. Mount Vesuvius overlooks. Amalfi Coast begins at south. Capri, Ischia, Procida islands. Famous for pizza, archaeology.','Naples · Vesuvius · Pompeii & Herculaneum · Capri & Ischia · Amalfi Coast start'),
    entry('Manila Bay',14.5,120.8,'Philippines · 1,994 km²','Natural harbor on Luzon island. Manila, the capital city. Battle of Manila Bay (1898 — Dewey defeats Spain). Corregidor Island fortress. Sunset views. Reclamation projects. Pollution challenges. Port of Manila.','Manila capital · Battle of Manila Bay 1898 · Corregidor · Famous sunsets · Major port'),
    entry('Tokyo Bay',35.5,139.8,'Japan · 1,500 km²','Bay on eastern coast of Honshu. Tokyo, Yokohama, Kawasaki on shores. Tokyo Disneyland on reclaimed land. Rainbow Bridge and Tokyo Gate Bridge. Haneda Airport on artificial island. Industrial and commercial hub.','Tokyo & Yokohama · Tokyo Disneyland · Rainbow Bridge · Haneda Airport · Reclaimed islands'),
    entry('Ha Long Bay',20.9,107.1,'Vietnam · 1,553 km²','UNESCO World Heritage site. 1,600+ limestone karsts and islets. Legend: dragons descending from heaven. Floating villages. Sung Sot Cave, Thien Cung Cave. Popular for cruises and kayaking. Cat Ba Island.','1,600 karst islets · UNESCO WHS · Floating villages · Dragon legend · Cave exploration'),
    entry('Phang Nga Bay',8.3,98.5,'Thailand · Andaman Sea','Dramatic limestone karst bay in Phuket region. James Bond Island (The Man with the Golden Gun). Koh Tapu (nail-shaped island). Sea gypsy villages. Canoeing through caves. Marine national park. Mu Ko Similan.','James Bond Island · Limestone karsts · Canoe caves · Sea gypsies · Phuket region'),
    entry('Monterey Bay',36.8,-121.9,'USA · California · Monterey','Deep submarine canyon offshore. Monterey Bay Aquarium (world-famous). Cannery Row (Steinbeck). Whale watching (gray whales, blue whales, orcas). Sea otters, sea lions, elephant seals. National Marine Sanctuary.','Monterey Aquarium · Cannery Row · Whale watching capital · Sea otters · Marine sanctuary'),
    entry('Bay of Campeche',20,-94,'Mexico · 6,000 km²','Southern Gulf of Mexico bay. Major oil production (Campeche Sound — 80% of Mexico oil). Important fishing grounds. Shallow waters. Campeche city (UNESCO). Pirate history. Maya ruins nearby.','80% of Mexico oil · Campeche Sound · Fishing grounds · Pirate history · Maya sites'),
    entry('Walvis Bay',-23,-14.5,'Namibia · Atlantic coast','Natural deep-water harbor on Namibian coast. Important bird area — flamingos, pelicans, penguins. Sandwich Harbour lagoon. Salt pans. Dune 7 (highest in Namibia). Dolphin and seal cruises. German colonial architecture.','Deep-water harbor · Flamingos & pelicans · Sandwich Harbour · Dune 7 · Seal cruises'),
    entry('False Bay',-34.2,18.7,'South Africa · Cape Peninsula','Large bay southeast of Cape Peninsula. Simon\'s Town naval base. Boulders Beach penguin colony. Great white shark research. Cape of Good Hope nearby. Kalk Bay fishing village. Whales in season.','Simon\'s Town · Boulders Beach penguins · Great white sharks · Cape Peninsula · Whale watching'),
    entry('Galveston Bay',29.5,-94.8,'USA · Texas · 1,400 km²','Large estuary on Texas Gulf Coast. Houston Ship Channel connects to Gulf. Port of Houston (busiest US port). Galveston Island — tourism and beaches. Hurricane Ike (2008) devastated. NASA Johnson Space Center on shore.','Port of Houston · Houston Ship Channel · Galveston Island · NASA JSC · Hurricane Ike 2008'),
    entry('Tampa Bay',27.7,-82.6,'USA · Florida · 1,000 km²','Large natural harbor on Florida\'s Gulf Coast. Tampa, St. Petersburg, Clearwater. Sunshine Skyway Bridge. Busch Gardens. Cuban/Ybor City history. Manatee winter refuge. Thunder Beach. Major retirement destination.','Tampa & St. Petersburg · Skyway Bridge · Ybor City · Manatees · Busch Gardens'),
    entry('Kotor Bay',42.5,18.7,'Montenegro · Adriatic Sea','Submerged river canyon — Europe\'s southernmost fjord. Four interconnected gulfs. UNESCO protected. Lovcen mountain backdrop. Medieval stone villages. Our Lady of the Rocks artificial island.','Southernmost fjord in Europe · UNESCO · Lovcen mountain · Our Lady of the Rocks · Kotor'),
    entry('Lagoa dos Patos',-31,-51,'Brazil · 10,000 km²','Largest lagoon in Brazil — connected to Atlantic. Porto Alegre at northern end. Rio Grande southern port. Fishing, agriculture, industry. Canal do Norte connects to ocean.','Largest Brazilian lagoon · Porto Alegre · Rio Grande port · Fishing & agriculture'),
    entry('Bay of Islands',-35.2,174.2,'New Zealand · Northland','144 islands on north-eastern NZ coast. Waitangi Treaty Grounds (1840). Russell — first capital. Dolphins, whales, sailing. Paihia tourism hub. Cape Brett and Hole in the Rock. Deep-sea fishing.','144 islands · Waitangi Treaty · Russell (first capital) · Dolphin cruises · Hole in the Rock'),
    entry('Guanabara Bay',-22.9,-43.1,'Brazil · Rio de Janeiro','Second largest bay in Brazil. Rio de Janeiro city on west shore. Sugarloaf Mountain, Christ the Redeemer. Niteroi on east. 130 islands. 2016 Olympics sailing. Pollution — restoration efforts.','Rio de Janeiro · Sugarloaf Mountain · Christ Redeemer · Niteroi · 2016 Olympics sailing'),
    entry('Guantanamo Bay',19.9,-75.1,'Cuba · 48 km²','US Naval Base since 1903 (lease in perpetuity). Controversial detention camp (2002-present). Natural deep-water harbor. Cactus-covered hills. Cuban side: fishing villages. Base population 6,000.','US Naval Base · Gitmo detention camp · Leased since 1903 · Deep-water harbor · Controversial'),
    entry('Delaware Bay',39,-75.2,'USA · Delaware/New Jersey','Major estuary on US East Coast. Delaware River feeds. Important for horseshoe crabs (May spawning). Shorebird migration stopover. Cape May-Lewes Ferry. Ports: Wilmington, Philadelphia. Oyster and crab fisheries.','Horseshoe crab spawning · Shorebird migration · Cape May-Lewes Ferry · Delaware River · Oysters'),
  ],
  w_cave: [
    entry('Mammoth Cave',37.2,-86.1,'USA · Kentucky · 676 km mapped','Longest cave system in the world — 676km mapped. Part of Mammoth Cave National Park (UNESCO). Over 130 species of wildlife. Guided tours available from easy to strenuous. 10 million visitors since 1941.','676km (world\'s longest cave) · Mammoth Cave NP (UNESCO) · 130+ species · Guided tours'),
    entry('Waitomo Caves',-38.3,175.1,'New Zealand · North Island','Famous for glowworm grotto — thousands of bioluminescent glowworms. Waitomo River system. Ruakuri Cave, Aranui Cave. Black water rafting (tubing). Stunning limestone formations. 400+ caves in region.','Glowworm grotto · Bioluminescent · Black water rafting · Ruakuri Cave · Limestone formations'),
    entry('Carlsbad Caverns',32.2,-104.5,'USA · New Mexico · 119 caves','Deep limestone cave system in Guadalupe Mountains. Big Room — largest single cave chamber in NA (1.2km long). Bat flight at sunset (400,000 bats). Carlsbad Caverns NP. Natural entrance 230m deep.','Big Room (largest NA chamber) · 400,000 bats · Carlsbad Caverns NP · Limestone · 119 caves'),
    entry('Sơn Đoòng Cave',17.5,106.3,'Vietnam · Quang Binh · World\'s largest','Largest cave passage in the world — 5.5km long, 200m high, 150m wide. Discovered 1991, explored 2009. Contains its own jungle and river. Cave pearls the size of baseballs. ADGAT (expedition team).','World\'s largest passage · Own jungle & river · Discovered 1991 · Cave pearls · Phong Nha-Ke Bang'),
    entry('Phong Nha Cave',17.6,106.3,'Vietnam · 7,729m','Famous for its underground river (longest in Asia). Paradise Cave — 31km discovered. Spectacular stalactites and stalagmites. Accessible by boat. Phong Nha-Ke Bang UNESCO site. Used by Cham people historically.','Longest underground river in Asia · Paradise Cave (31km) · Boat access · UNESCO · Cham history'),
    entry('Postojna Cave',45.8,14.2,'Slovenia · 24km','One of the largest karst caves in Europe. Tourist train ride through 5.5km. 33 species of cave animals — olm (human fish) most famous. Concert hall with perfect acoustics. 1819 first tourist cave (oldest).','Olm (cave salamander) · Tourist train · 24km karst cave · Concert hall · First tourist cave 1819'),
    entry('Eisriesenwelt',47.5,13.2,'Austria · 42km · Ice caves','Largest ice cave in the world — 42km total length. 1km of ice accessible to tourists. Temperature below freezing year-round. Funicular and hike to entrance. Salzburg region. 1,645m altitude.','World\'s largest ice cave · 42km total · 1km ice accessible · Year-round ice · Snow-free entrance'),
    entry('Škocjan Caves',45.7,14.0,'Slovenia · 6km','UNESCO World Heritage site. Underground canyon with Reka River. 200m deep collapsed dolines. Hanging bridges 45m above river. Largest underground chamber (12,000 m²). Archaeological finds from Stone Age.','UNESCO WHS · Underground canyon · Reka River · Hanging bridges · Largest chamber 12,000m²'),
    entry('Jeita Grotto',33.9,35.6,'Lebanon · 9km','Upper and lower caves with 2,200m upper gallery. Stalactites up to 8.2m (world\'s longest). Subterranean lake in lower gallery — boat ride. ACRES Award 2009 (World\'s Best Ecotourism). National symbol.','World\'s longest stalactite (8.2m) · Upper & lower caves · Subterranean boat ride · Lebanon icon'),
    entry('Reed Flute Cave',25.0,110.3,'China · Guilin · 240m','Famous Guilin limestone cave named for reeds used for flutes. 1,800 year old inscriptions. Multi-colored LED lighting. Spectacular stalactite and stalagmite formations. Crystal Palace of the Dragon King chamber.','Guilin limestone cave · 1,800 yr inscriptions · Colorful LED lighting · Flute reeds · Crystal Palace'),
    entry('Batu Caves',3.2,101.7,'Malaysia · Selangor','Limestone hill with series of caves and cave temples. 140ft golden statue of Murugan at entrance. 272 steps to the main cave. Hindu temple since 1888. Thaipusam festival — 1M+ pilgrims. Dark and Ramayana caves.','Murugan statue (140ft) · 272 steps · Hindu temple 1888 · Thaipusam festival · Limestone caves'),
    entry('Marble Caves',-46.7,-72.7,'Chile · Patagonia · General Carrera Lake','Unique marble caves on turquoise glacial lake. Carved by 6,000 years of wave action. Marble Cathedral, Marble Chapel, Marble Caverns. Best seen by boat in summer. Patagonia, Chile-Argentina border.','Marble formations on turquoise lake · 6,000 years wave erosion · Boat access · Patagonia beauty'),
    entry('Cueva de los Verdes',29.2,-13.5,'Canary Islands · Lanzarote','Volcanic lava tube formed by 3,000 year old eruption. 1.5km long. Ceiling collapse creates "Jameos". Part of Atlántida Tunnel (longest volcanic tube in the world). Used by locals to hide from pirates. Unique acoustics.','Volcanic lava tube · Atlántida Tunnel link · Pirate hideout · Lanzarote · Concert venue'),
    entry('Soreq Cave (Avshalom)',31.8,35.1,'Israel · Judean Hills','Active limestone cave discovered 1968. Exceptional stalactite and stalagmite formations. Constant 22°C, 92% humidity. Protected nature reserve. Over 500 stalactites measured. Unique aragonite crystals.','Active limestone cave · 500+ stalactites · Aragonite crystals · 22°C constant · Bet Shemesh'),
    entry('Cango Caves',-33.4,22.2,'South Africa · 4km','Dripstone cave system in Swartberg mountains. Guided tours through six chambers. Van Zyl Hall — 107m long. Famous for "Devil\'s Postbox" and "Organ Pipes". Oldest known cave in SA (used by Khoisan ancestors).','Dripstone · Swartberg range · Van Zyl Hall (107m) · Devil\'s Postbox · Khoisan history'),
    entry('Fingal\'s Cave',56.4,-6.3,'UK · Scotland · Staffa Island','Sea cave on uninhabited Staffa island. Hexagonal basalt columns (Giant\'s Causeway geology). 72m deep, 20m high. Mendelssohn\'s Hebrides Overture inspired by. Gaelic: Uamh-Binn (Cave of Melody).','Hexagonal basalt columns · Mendelssohn inspiration · Staffa Island · Sea cave · Cave of Melody'),
    entry('Ajanta Caves',20.5,75.7,'India · Maharashtra · 30 caves','UNESCO Buddhist cave temples (2nd c. BCE — 6th c. CE). Famous murals and paintings. Carved into horseshoe-shaped cliff. 26 viharas (monasteries) and 4 chaityas (shrines). Ellora nearby.','UNESCO WHS · Buddhist murals · 30 caves · Viharas & chaityas · Ancient monastic complex'),
    entry('Ellora Caves',20.0,75.2,'India · Maharashtra · 34 caves','UNESCO rock-cut cave temples (600-1000 CE). Kailasa Temple (Cave 16) — world\'s largest monolith carving. Buddhist, Hindu, Jain caves. Cut from basalt cliff. 200 years to build. 1.5M visitors annually.','Kailasa Temple (largest monolith) · Buddhist, Hindu, Jain · 34 caves · UNESCO WHS · 1.5M visitors'),
    entry('Elephanta Caves',18.9,72.9,'India · Mumbai · Gharapuri Island','UNESCO rock-cut cave temples (5th-7th c.). Trimurti Sadashiva — 6m high three-faced Shiva. Main cave 39m deep. Ferry from Mumbai Gateway of India. Portuguese named after elephant statue found.','Trimurti Shiva (6m) · Mumbai ferry · UNESCO WHS · 5th-7th century · Portuguese discovery'),
    entry('Blue Grotto',40.6,14.2,'Italy · Capri','Sea cave on Capri island glowing blue via sunlight through underwater cavity. 60m long, 25m wide. Only accessible by small rowboat when sea calm. Enter through 1.3m high opening. Roman emperors had private grotto.','Sunlight creates blue glow · Small rowboat access · Capri island · Low entrance · Roman baths'),
    entry('Hang Én Cave',17.5,106.3,'Vietnam · Quang Binh · 2km','Third largest cave in the world. Underground river, beaches, and jungle. 90m high entrance. Used by WW1 deserters as hideout. Bird\'s nest soup harvested here. Son Doong exploration base camp.','World\'s 3rd largest · Underground beach & river · WW1 hideout · Son Doong basecamp'),
    entry('Dunhuang Caves (Mogao)',40.0,94.8,'China · Gansu · 492 cells','UNESCO Buddhist cave temples on Silk Road. 45,000 m² of murals (world\'s largest Buddhist art). Library Cave (Cave 17) — 50,000 manuscripts. 492 decorated caves. Carved 4th-14th centuries. Cave of the Thousand Buddhas.','World\'s largest Buddhist art · 45,000m² murals · Library Cave (50k manuscripts) · Silk Road · UNESCO'),
  ],
  w_gorge: [
    entry('Grand Canyon',36.1,-112.1,'USA · Arizona · 446km long','One of the world\'s most famous natural wonders. Carved by Colorado River over 6 million years. 1.8km deep, up to 29km wide. Exposes 2 billion years of geology. UNESCO WHS. Grand Canyon NP. 6M+ visitors/yr.','1.8km deep · 446km long · Colorado River · 2B yrs geology · UNESCO WHS · 6M visitors/yr'),
    entry('Tiger Leaping Gorge',27.2,100.1,'China · Yunnan · 15km','One of the deepest and most spectacular gorges in the world. Jinsha River (upper Yangtze) between Jade Dragon and Haba snow mountains. 3,900m gorge depth at points. Famous trekking trail. 28 bends of river.','3,900m deep · Yunnan · Jade Dragon Mountain · Jinsha River · World-class trekking · 28 bends'),
    entry('Samaria Gorge',35.3,23.9,'Greece · Crete · 16km','Europe\'s longest gorge at 16km. White Mountains (Lefka Ori). Samaria National Park. Unique Cretan wildlife — kri-kri (wild goat). Walkable May-October only (flash flood risk). Iron Gates — 3.5m wide (narrowest).','Europe\'s longest (16km) · Crete · Kri-kri goats · Iron Gates (3.5m wide) · Lefka Ori mountains'),
    entry('Tara River Canyon',43.2,19.0,'Montenegro/Bosnia · 82km','Deepest canyon in Europe at 1,300m deep. Tara River, emerald-green water. Durmitor National Park (UNESCO). World-class rafting. Đavolja Gora (Devil\'s Mountain). Bridge on Tara (1937) — popular attraction.','Deepest European canyon (1,300m) · Tara River rafting · Durmitor NP (UNESCO) · Emerald water'),
    entry('Colca Canyon',-15.6,-71.9,'Peru · 100km','One of the world\'s deepest canyons at 3,270m (twice Grand Canyon depth). Colca Valley — pre-Inca terraces. Andean condors at Cruz del Condor. Hot springs. Traditional villages. Trekking and rafting.','3,270m deep · Andean condors · Pre-Inca terraces · Cruz del Condor · Hot springs · Trekking'),
    entry('Cotahuasi Canyon',-15.3,-72.9,'Peru · 100km','Deepest canyon in the Americas at 3,535m. Cotahuasi Valley. Remote — few tourists. Sipia waterfall. Hot springs. Pre-Inca terraced agriculture. Condors. Trekking from Arequipa. UNESCO Reserve.','3,535m deep (Americas deepest) · Remote · Sipia waterfall · Pre-Inca terraces · Arequipa'),
    entry('Blyde River Canyon',-24.6,30.8,'South Africa · Mpumalanga · 26km','Third largest canyon in the world. Part of Drakensberg escarpment. God\'s Window, Bourke\'s Luck Potholes, Three Rondavels. Rich in fossils. Green canyon (vegetation-covered). Panorama Route.','World\'s 3rd largest · Drakensberg · God\'s Window · Three Rondavels · Panorama Route · Green canyon'),
    entry('Fish River Canyon',-27.2,17.6,'Namibia · 161km','Second largest canyon in Africa. Southern Namibia. 550m deep. Gravel road access. Fish River hiking trail — 5 days (90km). 86km of tourist road with viewpoints. Arid, lunar landscape. Often dry riverbed.','Africa\'s 2nd largest · Namibia · 550m deep · 5-day hiking trail · Arid landscape'),
    entry('Waimea Canyon',22.0,-159.7,'USA · Hawaii · Kauai','Called the "Grand Canyon of the Pacific". Waimea River carved volcanic rock. 16km long, 900m deep. Red and green canyon walls. Koke\'e State Park overlooks. Napali Coast nearby.','Grand Canyon of the Pacific · Kauai · 900m deep · Koke\'e SP · Napali Coast · Red volcanic rock'),
    entry('New River Gorge',38.0,-81.1,'USA · West Virginia · 530m deep','New River Gorge National Park (designated 2020). America\'s newest national park. World-class whitewater rafting. New River Gorge Bridge — 876m span (one of world\'s longest steel arches). Bridge Day — BASE jumping.','Newest US national park · Whitewater rafting · New River Gorge Bridge (876m) · Bridge Day · 530m deep'),
    entry('Verdon Gorge',43.7,6.3,'France · Provence · 25km','One of Europe\'s most beautiful gorges. Verdon River — stunning turquoise water. 700m deep limestone canyon. Rock climbing, kayaking, hiking. Sentier Martel trail (14km). Lac de Sainte-Croix.','Turquoise water · 700m deep · Limestone canyon · Rock climbing · Sentier Martel · Provence'),
    entry('Vikos Gorge',39.9,20.7,'Greece · Zagori · 20km','Guinness World Record — deepest gorge relative to width (depth 990m, width only 1,400m). Vikos-Aoos National Park. Zagori stone villages. Voidomatis River — crystal clear. Stone arched bridges.','Guinness: deepest per width · 990m deep · Zagori villages · Voidomatis River · Stone bridges'),
    entry('Yarlung Tsangpo Gorge',29.8,95.0,'Tibet/India · 240km','Deepest gorge in the world (Namcha Barwa — 6,009m deep). Yarlung Tsangpo (Brahmaputra) makes U-turn. 240km long. Namcha Barwa (7,782m) and Gyala Peri. Last great unexplored region. Potential for world\'s largest hydro.','Deepest in world (6,009m) · Namcha Barwa · Brahmaputra River · Unexplored · Tibet'),
    entry('Kali Gandaki Gorge',28.7,83.6,'Nepal · Mustang · 120km','Deepest gorge in the world (Dhaulagiri 8,167m and Annapurna 8,091m on either side — 5,571m depth). Kali Gandaki River. Muktinath temple. Fossilized ammonites (shaligram) found here. Upper Mustang trekking.','Dhaulagiri-Annapurna gap (5,571m) · Fossil ammonites · Muktinath · Upper Mustang · Trekking'),
    entry('Columbia River Gorge',45.7,-121.5,'USA · Oregon/Washington · 120km','Only sea-level passage through Cascades. 1,000m deep. Multnomah Falls — 189m (2nd highest US year-round). Historic Columbia River Highway. Windsurfing capital (Hood River). 90+ waterfalls.','1,000m deep · Multnomah Falls · Historic Highway · Windsurfing (Hood River) · 90+ waterfalls'),
    entry('Taroko Gorge',24.2,121.5,'Taiwan · Hualien · 19km','Marble-walled canyon in Taroko National Park. Liwu River carved through marble. Tunnel of Nine Turns trail. Eternal Spring Shrine. Swallow Grotto. 1.2M visitors annually. Indigenous Truku people.','Marble canyon · Taroko NP · Liwu River · Tunnel of Nine Turns · Eternal Spring Shrine · Truku'),
  ],
  w_archipelago: [
    entry('Maldives',4,73,'Indian Ocean · 1,192 islands · 26 atolls','Lowest country in the world (avg 1.5m above sea level). 26 coral atolls. 1,192 islands — only 200 inhabited. Tourism — overwater bungalows, diving. Population 540,000. Capital Male. Threatened by sea-level rise.','Lowest country (1.5m) · 1,192 islands · 26 atolls · Overwater bungalows · Sea-level threat · Male'),
    entry('Hawaiian Islands',20.5,-157.5,'USA · 137 islands · Pacific','Volcanic archipelago spanning 2,400km. 8 main islands: Hawaii (Big Island), Maui, Oahu, Kauai, Molokai, Lanai, Niihau, Kahoolawe. Kilauea active volcano. Pearl Harbor. Surfing capital. World\'s most isolated island chain.','8 main islands · Active volcano (Kilauea) · Pearl Harbor · Surfing capital · Most isolated chain'),
    entry('Galapagos Islands',-0.5,-90.5,'Ecuador · 19 islands · Pacific','Volcanic archipelago unique for wildlife that inspired Darwin\'s evolution theory. 19 islands. Giant tortoises, marine iguanas, blue-footed boobies. 97% endemic species. Strict protection. UNESCO WHS.','Inspiration for Darwin\'s theory · Giant tortoises · Marine iguanas · 97% endemic · UNESCO WHS'),
    entry('Canary Islands',28.5,-15.5,'Spain · 7 main islands · Atlantic','Volcanic archipelago off African coast. 7 main: Tenerife, Gran Canaria, Lanzarote, Fuerteventura, La Palma, La Gomera, El Hierro. Mount Teide (3,718m — Spain\'s highest). Year-round spring climate. Tourism. 2.2M population.','Mount Teide (Spain\'s highest) · 7 islands · Year-round spring · Volcanic beaches · 2.2M population'),
    entry('Azores',38.5,-27.5,'Portugal · 9 islands · Atlantic','Remote volcanic archipelago 1,500km from mainland. 9 volcanic islands. Lush green landscape. Lake-filled calderas — Sete Cidades. Whale watching — 25 species. Furnas hot springs. Pico Mountain (2,351m). Wine culture.','9 volcanic islands · Sete Cidades caldera · Whale watching · Furnas hot springs · Pico Mountain'),
    entry('Seychelles',-4.5,55.5,'Indian Ocean · 115 islands','Granitic coral island nation. 115 islands. Aldabra atoll — world\'s largest raised coral atoll. Vallée de Mai — Coco de Mer palm. Giant Aldabra tortoises. Pristine beaches (Anse Lazio, Anse Source d\'Argent). 100,000 population.','115 islands · Aldabra atoll · Coco de Mer · Giant tortoises · Anse Source d\'Argent · Praslin'),
    entry('Fiji',-17,179,'South Pacific · 330 islands · 106 inhabited','Melanesian archipelago. 330 islands spread over 1.3M km². Viti Levu (Suva, Nadi) and Vanua Levu are largest. Coral reefs — Great Astrolabe Reef. Known as "Soft Coral Capital". 333,000 km² exclusive economic zone. Kava ceremony.','330 islands · Soft coral capital · Suva & Nadi · Kava · Great Astrolabe Reef · Friendly people'),
    entry('Philippines',12,122,'Southeast Asia · 7,641 islands','Second largest archipelago in the world. Luzon, Visayas, Mindanao groups. 7,641 islands at low tide. 109M population. Manila capital. Puerto Princesa Underground River. Chocolate Hills. Tubbataha Reef.','7,641 islands (2nd largest archipelago) · 109M population · Manila · Chocolate Hills · Tubbataha'),
    entry('Indonesian Archipelago',0,120,'Southeast Asia · 17,508 islands','World\'s largest archipelago by area. 17,508 islands. 6,000 inhabited. Sumatra, Java, Kalimantan, Sulawesi, Papua. 275M population (4th globally). Bali major tourist destination. Komodo dragons. Orangutans in Borneo.','World\'s largest · 17,508 islands · 275M people · Bali · Komodo dragons · Orangutans'),
    entry('Japanese Archipelago',36,138,'East Asia · 6,852 islands','4 main: Honshu, Hokkaido, Kyushu, Shikoku. 6,852 total islands. 125M population. Tokyo — world\'s largest metro area. Mount Fuji. Active volcanoes (Fuji, Sakurajima, Aso). Hot springs (onsen) culture. Cherry blossoms.','6,852 islands · Tokyo · Mount Fuji · Onsen · Cherry blossoms · Bullet trains · 125M population'),
    entry('British Isles',53,-3,'NW Europe · 6,000+ islands','Great Britain and Ireland plus 6,000+ smaller islands. UK (England, Scotland, Wales, NI) + Republic of Ireland. Hebrides, Orkney, Shetland, Isle of Man, Channel Islands. 72M population. London, Dublin, Edinburgh, Cardiff.','6,000+ islands · UK & Ireland · London & Dublin · Hebrides & Orkney · 72M · Greenwich meridian'),
    entry('Greek Islands',37,25,'Mediterranean · 6,000 islands · 227 inhabited','6,000 islands and islets. 227 inhabited. Crete, Santorini, Mykonos, Rhodes, Corfu. Cyclades, Dodecanese, Ionian, Sporades groups. Ancient history — Minoan, Classical, Byzantine. White-blue architecture. 10M population.','6,000 islands · 227 inhabited · Santorini & Mykonos · Minoan history · White-blue houses · Crete'),
    entry('Bahamas',25,-76,'Caribbean · 700 islands · 2,400 cays','700 islands, 2,400 cays. Coral-based archipelago. Nassau capital. Atlantis Resort on Paradise Island. Exuma Cays — swimming pigs. Third deepest blue hole (Dean\'s Blue Hole, 202m). 400,000 population. Famous beaches.','700 islands · Nassau · Atlantis Resort · Swimming pigs · Dean\'s Blue Hole (202m) · Coral cays'),
    entry('Svalbard',78,18,'Norway · Arctic Ocean · 62,000 km²','Remote Arctic archipelago. 60% glaciated. Longyearbyen — world\'s northernmost town (2,500 pop). Polar bears outnumber humans. Global Seed Vault. Northern lights. Midnight sun. Coal mining history. Treaty 1920.','Polar bears > humans · Global Seed Vault · Longyearbyen · Arctic wilderness · Svalbard Treaty'),
    entry('Andaman & Nicobar Islands',12,93,'India · Bay of Bengal · 572 islands','572 islands, 37 inhabited. Port Blair capital. Cellular Jail (Kala Pani). Indigenous tribes (Sentinelese, Jarawa, Onge). Pristine coral reefs. Radhanagar Beach (Asia\'s best beach). Havelock Island. Andaman Trunk Road.','572 islands · Cellular Jail · Sentinelese tribe · Radhanagar Beach · Coral reefs · Havelock'),
    entry('Tierra del Fuego',-54,-70,'Argentina/Chile · 73,746 km²','Archipelago at southern tip of South America. Shared by Chile and Argentina. Ushuaia — southernmost city in the world. Beagle Channel. Cape Horn. Named by Magellan (1520). Glaciers, penguins, rugged landscapes.','Southernmost archipelago · Ushuaia · Beagle Channel · Cape Horn · Magellan 1520 · Penguins'),
    entry('Cape Verde',16,-24,'Atlantic · 10 islands · West Africa','Volcanic archipelago 570km off West Africa. 10 islands, 9 inhabited. Praia capital. Mindelo on Sao Vicente. Morna music — Cesaria Evora. Sal & Boa Vista beaches. Hurricane-free. Cape Verdean diaspora worldwide.','10 volcanic islands · Cesaria Evora · Praia · Mindelo · Sal beaches · West African culture'),
    entry('Cyclades',37,25,'Greece · 220 islands · Aegean Sea','Group of 220 islands in southern Aegean. Santorini (caldera views), Mykonos (nightlife), Naxos (largest), Paros, Milos, Syros. Whitewashed villages, blue domes. Ancient Cycladic civilization. Famous for marble figurines.','Santorini caldera · Mykonos nightlife · White & blue architecture · Cycladic figurines · Naxos'),
    entry('Lofoten Islands',68.2,14.5,'Norway · Arctic Circle · Dramatic peaks','Dramatic archipelago above Arctic Circle. Sharp peaks, fjords, fishing villages. Reine, Henningsvær, Å. Midnight sun (May-July). Northern lights (Sep-Apr). Cod fishing tradition (stockfish). Hiking, surfing, kayaking. UNSEEN Norway.','Above Arctic Circle · Midnight sun · Northern lights · Stockfish · Reine village · Dramatic peaks'),
    entry('Mergui Archipelago',12,98,'Myanmar · 800+ islands · Andaman Sea','Remote archipelago of 800+ islands in Andaman Sea. Home to Moken (Sea Gypsies). Pristine coral reefs. Diving and snorkeling paradise. Only recently opened to tourism. Lampi Island Marine National Park. Sea gypsy culture.','800+ islands · Moken sea gypsies · Pristine reefs · Diving paradise · Lampi NP · Remote'),
  ],
  w_geyser: [
    entry('Old Faithful',44.5,-110.8,'USA · Yellowstone NP · Wyoming','World\'s most famous geyser. Erupts every 44-125 min (~90 min average). 32-56m high. 14,000-32,000L water. 95°C water. Named by Washburn Expedition 1870. Yellowstone Lake nearby. 4M visitors/yr.','Every ~90 min · 32-56m high · 14k-32kL water · Yellowstone · Most famous geyser'),
    entry('Steamboat Geyser',44.7,-110.7,'USA · Yellowstone NP','World\'s tallest active geyser — 91-122m. Unpredictable eruptions (weeks to decades apart). Active 1960s, dormant 1991-2018. Entered active phase 2018 — 100+ eruptions. Norris Geyser Basin. 95°C+ water.','World\'s tallest (91-122m) · Unpredictable · Active since 2018 · Norris Basin · Steamboat phase'),
    entry('Grand Geyser',44.5,-110.8,'USA · Yellowstone NP','Tallest predictable geyser (up to 60m). Upper Geyser Basin. Erupts every 6-13 hours. Lasts 9-12 minutes. Series of powerful bursts. Erupts with Vent and Turban geysers. Winter eruptions spectacular.','Tallest predictable (60m) · 6-13 hrs apart · Upper Basin · 9-12 min duration · Winter beauty'),
    entry('Strokkur',64.3,-20.3,'Iceland · Haukadalur','Most reliable geyser in Iceland — erupts every 5-10 minutes. 20-30m high (occasionally 40m). Blue water bubble before eruption. 120°C water. Near the original Geysir (which is now mostly dormant).','Every 5-10 min · 20-30m high · Iceland favorite · Blue bubble · Near Geysir'),
    entry('Geysir',64.3,-20.3,'Iceland · Haukadalur','The original geyser — all geysers named after it. Known since 1294. Erupted up to 170m in 1845. Now mostly dormant. Active after earthquakes. Strokkur nearby in same geothermal field.','The original geyser · Known since 1294 · Erupted 170m (1845) · Now dormant · Word origin'),
    entry('El Tatio',-22.4,-68.0,'Chile · Atacama · 4,320m altitude','World\'s highest geyser field (4,320m). 80+ active geysers. Spectacular at sunrise — steam contrasts with cold air. 3rd largest geyser field. Borax deposits. Salt flats nearby. Extremely remote. Llama sightings.','Highest geyser field (4,320m) · 80+ geysers · Atacama Desert · Sunrise spectacle · Borax deposits'),
    entry('Pohutu Geyser',-38.2,176.5,'New Zealand · Rotorua · Te Puia','New Zealand\'s largest active geyser. Erupts up to 20 times daily. 30m high. Near Maori carved meeting house. Rotorua thermal area. Boiling mud pools nearby. Tāwhiao Bridge. Prince of Wales Feathers geyser.','NZ\'s largest · Rotorua · 20x/day · 30m high · Te Puia Maori culture · Boiling mud pools'),
    entry('Lady Knox Geyser',-38.3,176.2,'New Zealand · Wai-o-Tapu','Famous for daily "assisted" eruption — soap added to trigger. 10-20m high. Erupts at 10:15am daily. Discovered by prisoners. Part of Wai-o-Tapu thermal wonderland. Champagne Pool nearby.','Daily 10:15am eruption · Soap triggered · Wai-o-Tapu · 10-20m high · Thermal wonderland'),
    entry('Beowawe Geyser',40.6,-116.6,'USA · Nevada · 2,300m','Once the world\'s tallest geyser (peak 300m in 1950s). Dormant after geothermal power plant construction in 1985. Power reduced flow. Flash steam still erupts. Beowawe geothermal area. Near Battle Mountain.','Once world\'s tallest (300m) · Dormant since 1985 · Geothermal plant impact · Nevada · Flash steam'),
    entry('Castle Geyser',44.5,-110.8,'USA · Yellowstone NP','Massive cone geyser — cone built up over centuries. 27m high eruption. Erupts every 10-12 hours. Old Upper Geyser Basin. Splendid geyser nearby. Oldest cone in the basin. Spectacular at sunset.','Large cone · 27m high · 10-12 hour cycle · Oldest cone in Upper Basin · Sunset favorite'),
    entry('Great Fountain Geyser',44.6,-110.7,'USA · Yellowstone NP','Predictable fountain-type geyser. Erupts every 9-15 hours. 30-60m high. Spectacular terraced pools. Firehole Lake Drive. Turquoise pool after eruption. Winter photography classic.','9-15 hour cycle · 30-60m high · Fountain type · Terraced pools · Firehole Lake Drive'),
    entry('Waimangu Geyser',-38.3,176.4,'New Zealand · Rotorua','Once the largest geyser in the world (1900-1904). Erupted up to 460m — world\'s highest. Destroyed by landslide. Now the lake-filled Waimangu Valley. Hot springs, boiling lakes, terraces. Tour accessible.','World\'s former highest (460m) · 1900-1904 · Waimangu Valley · Hot springs · Eco tour'),
    entry('Upptyppingar',65.0,-16.5,'Iceland · Krafla','Recently discovered geothermal area (1990s). Cold-water geysers up to 130m. Unique phenomenon — ice-cold water (not typical hot water). Non-volcanic. Continuous stream of pops. In the Krafla volcanic system.','Cold geyser phenomenon · 130m high · Krafla · Iceland · Recently discovered'),
  ],
  w_isthmus: [
    entry('Isthmus of Panama',9,-79.5,'Panama · 80km · Connects NA and SA','Narrow isthmus connecting North and South America. Created 3 million years ago (Great American Interchange). Panama Canal (1914) — 82km shipping route. 5% of world trade passes through. Panama City. Colon. Darien Gap.','80km wide · Panama Canal (82km) · 5% world trade · Great American Interchange · Darien Gap'),
    entry('Isthmus of Kra',10.5,99,'Thailand · 44km · Malay Peninsula','Narrowest part of Malay Peninsula. 44km wide at Kra Buri. Proposed Kra Canal (Thai Canal) to bypass Malacca Strait. Never built due to cost, environmental, and security concerns. Southern Thailand. Phuket region.','44km wide · Proposed Kra Canal · Malay Peninsula · Bypass Malacca · Never built'),
    entry('Isthmus of Suez',30.5,32.5,'Egypt · 125km · Connects Africa and Asia','Connects Africa and Asia. Suez Canal (1869) — 193km artificial sea-level waterway. 12% of global trade. Alternative to Cape of Good Hope route (saves 7,000km). Egypt nationalized 1956. Ever Given blockage 2021.','125km wide · Suez Canal (193km) · 12% global trade · Connects Africa-Asia · Nationalized 1956'),
    entry('Isthmus of Corinth',37.9,23.0,'Greece · 6.3km · Connects Peloponnese','Narrow isthmus connecting Peloponnese peninsula to mainland Greece. Corinth Canal (1893) — 6.3km. 21m wide, 8m deep. Ancient Diolkos ship track (6th c. BC). Near ancient Corinth. 22km shorter than circumnavigating Peloponnese.','6.3km wide · Corinth Canal 1893 · Ancient Diolkos · Peloponnese connector · Narrowest isthmus'),
    entry('Isthmus of Tehuantepec',17.2,-94.7,'Mexico · 200km · Gulf to Pacific','Narrowest region between Gulf of Mexico and Pacific in Mexico. Interoceanic Corridor of Tehuantepec. Proposed railway/industrial alternative to Panama Canal. Strong winds — wind energy potential. Zapotec & Mixe cultures.','200km wide · Proposed interoceanic corridor · Wind energy · Zapotec culture · Mexico'),
    entry('Isthmus of Avalon',47.6,-53.5,'Canada · Newfoundland · 5km','Narrow isthmus connecting Avalon Peninsula to Newfoundland mainland. Only 5km wide. Route to St. John\'s. Historic importance for settlement. Site of early transatlantic telegraph cable landings.','5km wide · Connects Avalon Peninsula · Route to St. John\'s · Telegraph cable history'),
    entry('Karelian Isthmus',60.5,29.5,'Russia · 45-110km · Gulf of Finland to Lake Ladoga','Between Gulf of Finland and Lake Ladoga. Site of heavy fighting WWII (Winter War, Continuation War). Vyborg (Viipuri) major city. Formerly Finnish, now Russian. Fortress of Korela. Saint Petersburg metro region.','Winter War 1939-40 · Vyborg · Gulf of Finland to Lake Ladoga · Russian/Finnish history · SPb region'),
    entry('Isthmus of Chignecto',45.8,-64.3,'Canada · 24km · Nova Scotia-New Brunswick','Narrow isthmus connecting Nova Scotia to mainland Canada. Chignecto Bay (Bay of Fundy). Tidal marshlands. Fort Beausejour. Proposed Chignecto Canal never built. Trans-Canada Highway. Highest tides in world.','24km wide · Connects Nova Scotia · Fundy tides · Fort Beausejour · Proposed canal never built'),
    entry('Isthmus of Perekop',46.2,33.7,'Ukraine · 30km · Crimea connected','Narrow isthmus connecting Crimea to Ukrainian mainland. Tartar wall (Perekop defensive line). Razor\'s edge in Crimean conflicts. Crimea annexed 2014. North Crimean Canal — water supply to Crimea.','30km wide · Crimea connector · Tartar wall · 2014 annexation · North Crimean Canal'),
  ],
  w_spring: [
    entry('Pamukkale',37.9,29.1,'Turkey · Denizli','Travertine terraces formed by calcium-rich hot springs. White "cotton castle" cascades. Used since Roman times — Hierapolis ancient city. Cleopatra\'s Pool. UNESCO WHS. 35°C thermal water.','White travertine terraces · Hierapolis · Cotton Castle · Cleopatra\'s Pool · UNESCO WHS · Thermal 35°C'),
    entry('Grand Prismatic Spring',44.5,-110.8,'USA · Yellowstone NP','Largest hot spring in the US (113m diameter, 50m deep). Striking rainbow colors — thermophiles create red, orange, yellow, green, blue bands. 70°C central water. Third largest in the world. Midway Geyser Basin.','Largest US hot spring · 113m wide · Rainbow colors · Thermophiles · Yellowstone · 70°C'),
    entry('Morning Glory Pool',44.5,-110.8,'USA · Yellowstone NP','Famous for its deep blue center and rainbow rim. Color changed from pure blue to varied due to debris. 2.7m diameter. Upper Geyser Basin. 65°C. Named for morning glory flower due to shape. 1880s discovery.','Deep blue center · Rainbow rim · Color changed by debris · Upper Basin · Morning glory shape'),
    entry('Mammoth Hot Springs',44.9,-110.7,'USA · Yellowstone NP','Large hot spring terraces created by limestone deposition. Canary Spring, Minerva Terrace. Travertine steps. Active formations evolve rapidly. 72°C water. Fort Yellowstone nearby. Herding elk.','Travertine terraces · Minerva Terrace · Limestone deposition · Evolving formations · 72°C'),
    entry('Blue Lagoon',63.9,-22.5,'Iceland · Grindavík','Iceland\'s most famous geothermal spa. Man-made lagoon from Svartsengi power plant. 37-40°C milky blue water. Silica mud masks. Rich in minerals (silica, sulfur, algae). 1M+ visitors/year. Reykjanes Peninsula.','Geothermal spa · Milky blue water · Silica mud · 1M+ visitors/yr · Reykjanes Peninsula · 38°C'),
    entry('Deildartunguhver',64.7,-21.4,'Iceland · 97°C','Highest-flowing hot spring in Europe — 180L/sec at 97°C. Water piped to nearby towns for heating. Part of Reykholt area. Snorri Sturluson\'s home nearby. The water travels 64km to Akranes.','Highest flow in Europe (180L/s) · 97°C · District heating · Reykholt · Snorri Sturluson'),
    entry('Banff Upper Hot Springs',51.2,-115.6,'Canada · Alberta','Hot spring at 1,585m elevation in Banff NP. 37-40°C mineral water. Natural cave and bath house built 1932. Sulphur Mountain gondola nearby. Part of Canadian Rockies UNESCO. Aboriginal use predates discovery.','Banff NP elevation 1,585m · 37-40°C · 1932 bath house · Sulphur Mountain · Rocky Mountains'),
    entry('Beppu Hot Springs',33.3,131.5,'Japan · Oita · 8 hells','One of Japan\'s most famous onsen towns. 8 "hells" (Jigoku) — boiling pools, each with unique character. Umi Jigoku (Sea Hell) — 98°C cobalt blue pond. Blood Pond Hell — red clay. Beppu has more hot water than any other city.','Japan\'s onsen capital · 8 hells (Jigoku) · Sea Hell (98°C, blue) · Blood Pond Hell · Most hot water'),
    entry('Huanglong',32.7,103.8,'China · Sichuan · 3,500m','UNESCO travertine pools in Huanglong Valley. Colorful calcite pools — golden, turquoise, green. Snow-capped mountains (Minshan range). 3.6km travertine stream. Giant panda habitat. 3,500m altitude.','Golden travertine pools · UNESCO · 3,500m altitude · Snow mountains · Panda habitat · Sichuan'),
    entry('Jiuzhaigou',33.2,104.2,'China · Sichuan · Valley of Nine Villages','UNESCO biosphere famous for turquoise, emerald, and blue lakes. Travertine dams create multi-level pools. Nuorilang Waterfall. Five Flower Lake — fallen trees visible through clear water. Autumn colors spectacular.','Turquoise lakes · Travertine dams · Nuorilang Waterfall · Five Flower Lake · Autumn colors'),
    entry('Ojo Caliente',36.3,-106.0,'USA · New Mexico','One of the oldest natural health resorts in North America. Unique mineral water — lithia, soda, arsenic, iron. Pueblo people used for centuries. 4 spring-fed pools at 32-41°C. Adobe architecture. Kiva fireplace.','Oldest health resort in US · Lithia spring · 4 mineral pools · Pueblo history · 32-41°C'),
    entry('Glenwood Springs',39.6,-107.3,'USA · Colorado','World\'s largest natural hot springs pool (120m x 30m). 34-36°C. 15M+ litres daily flow. Yampah Vapor Caves. Underground steam caves. Doc Holliday died here. Iron Mountain Hot Springs nearby.','World\'s largest pool · 120m x 30m · Yampah caves · Doc Holliday · Colorado mountains'),
    entry('Saturnia Springs',42.7,11.5,'Italy · Tuscany','Natural thermal cascades — free public access. 37.5°C year-round. Sulphur-rich waters — therapeutic. Ancient Roman baths. Maremma countryside. "Cascate del Mulino" — most famous cascading pool. Etruscan heritage.','Free thermal cascades · 37.5°C · Tuscany · Sulphur water · Roman baths · Cascate del Mulino'),
    entry('Takachiho Onsen',32.7,131.3,'Japan · Miyazaki','Mountain onsen in Kyushu. Gokase River valley. Nearby Takachiho Gorge — volcanic columnar jointing and waterfalls. Manai Falls. Open-air bath (rotenburo) by river. Ama-no-Iwato Shrine. Japanese mythology.','Takachiho Gorge · Manai Falls · Rotenburo by river · Japanese myth · Miyazaki Kyushu'),
    entry('Budapest Thermal Baths',47.5,19.0,'Hungary · Budapest','"City of Spas" — 123 thermal springs. 15M litres/day of 21-78°C water. Széchenyi Baths (outdoor, largest in Europe). Gellért Baths (Art Nouveau). Rudas Baths (Turkish 1566). Falls into Danube. Roman and Turkish history.','City of Spas · 123 thermal springs · Széchenyi & Gellért · Turkish origins · Largest in Europe'),
  ],
  w_coast: [
    entry('Amalfi Coast',40.6,14.5,'Italy · Campania · 50km','UNESCO coastline along southern Sorrentine Peninsula. Vertical cliffs, pastel villages — Positano, Amalfi, Ravello, Atrani. Emerald Grotto. Limoncello. Path of the Gods hiking trail.','UNESCO WHS · Positano & Amalfi · Pastel villages · Limoncello · Path of the Gods'),
    entry('Cinque Terre',44.1,9.7,'Italy · Liguria · 18km','Five colorful fishing villages on rugged Riviera coastline. Monterosso, Vernazza, Corniglia, Manarola, Riomaggiore. Hiking trail connects all five. UNESCO WHS. Terraced vineyards on steep cliffs.','5 colorful villages · Hiking trails · UNESCO WHS · Terraced vineyards · Ligurian Sea views'),
    entry('Great Ocean Road',-38.7,143.0,'Australia · Victoria · 243km','World\'s longest war memorial — built by WWI veterans. Shipwreck Coast. Twelve Apostles limestone stacks. Loch Ard Gorge. London Arch (formerly London Bridge). Bells Beach surfing. Koalas in wild.','Twelve Apostles · WWII memorial road · 243km coastal drive · Shipwreck coast · Surfing'),
    entry('Big Sur',36.2,-121.7,'USA · California · 140km','Dramatic Pacific coastline between Carmel and San Simeon. Bixby Bridge (85m). Pfeiffer Beach (purple sand). McWay Falls (waterfall on beach). Highway 1 — one of world\'s great drives. Condors at Julia Pfeiffer Burns SP.','Dramatic Pacific cliffs · Bixby Bridge · McWay Falls · Highway 1 · Purple sand beach'),
    entry('Dalmatian Coast',43.0,16.5,'Croatia · 400km','Spectacular Adriatic coastline with 1,244 islands. Dubrovnik, Split, Zadar, Trogir. Plitvice Lakes nearby. Roman ruins (Diocletian\'s Palace). Krka National Park waterfalls. Lavender fields on Hvar. Game of Thrones filming.','1,244 islands · Dubrovnik & Split · Diocletian\'s Palace · Game of Thrones · Crystal Adriatic'),
    entry('French Riviera (Côte d\'Azur)',43.5,7.3,'France · 160km','Mediterranean coastline from Saint-Tropez to Menton. Cannes, Nice, Monaco, Antibes, Saint-Paul-de-Vence. Beaches, luxury yachts, casinos. Cannes Film Festival. Nice Carnival. 300+ sunny days/yr.','Cannes & Nice · Monaco · Film Festival · 300+ sunny days · Riviera glamour'),
    entry('Causeway Coastal Route',55.2,-6.5,'UK · Northern Ireland · 200km','One of the world\'s great road trips — Antrim coast. Giant\'s Causeway (basalt columns, 40,000+). Carrick-a-Rede Rope Bridge. Dunluce Castle ruins. Dark Hedges (Game of Thrones Kingsroad). Bushmills Distillery.','Giant\'s Causeway · Carrick-a-Rede rope bridge · Dunluce Castle · Dark Hedges · Bushmills whiskey'),
    entry('Ring of Kerry',51.95,-10.2,'Ireland · 179km','Scenic circular drive around Iveragh Peninsula. Killarney National Park. Gap of Dunloe. Skellig Michael island (Star Wars). Dingle Peninsula nearby. 32,000km of hedgerows. Castles and stone forts.','Iveragh Peninsula · Killarney NP · Skellig Michael (Star Wars) · Gap of Dunloe · 179km loop'),
    entry('Algarve Coast',37.0,-8.0,'Portugal · 155km','Southern Portugal coastline famous for golden cliffs and sea caves. Ponta da Piedade (limestone grottos). Benagil Cave (sea cave with roof hole). Lagos, Albufeira, Faro. Surfing at Sagres. 3,000 hours sun/yr.','Golden cliffs · Benagil Cave sea grotto · Ponta da Piedade · Lagos & Albufeira · 3,000 hr sun'),
    entry('Bay of Fires',-41.3,148.3,'Australia · Tasmania · 50km','Stunning white sand beaches with vibrant orange lichen-covered granite boulders. The Bay of Fires — named by Captain Tobias Furneaux (1773) for Aboriginal fires. Swim, surf, fish. Clear turquoise water. Mt William NP.','Orange lichen boulders · White sand · Turquoise water · Captain Furneaux 1773 · Tasmania'),
    entry('Turquoise Coast',36.5,30.0,'Turkey · Lycia · 1,500km','Lycian coast of southern Turkey. Kekova sunken city. Ölüdeniz Blue Lagoon. Patara Beach (12km — longest in Turkey). Lycian Way hiking trail (540km). Olympos and Chimera flames.','Lycian coast · Ölüdeniz Blue Lagoon · Kekova sunken city · Patara Beach (12km) · Lycian Way'),
    entry('Jurassic Coast',50.7,-2.9,'UK · England · 155km','UNESCO World Heritage coast in Dorset & East Devon. 185 million years of geological history. Durdle Door (natural limestone arch). Lulworth Cove. Chesil Beach (28km shingle). Fossil collecting on Lyme Regis beaches.','UNESCO WHS · Durdle Door arch · 185M years geology · Lulworth Cove · Fossil hunting'),
    entry('Cabot Trail',46.5,-60.8,'Canada · Nova Scotia · 298km','Scenic highway around Cape Breton Island. Highlands National Park. Skyline Trail. Whale watching. Acadian and Gaelic culture. Fortress of Louisbourg. Fall colours spectacular. Cabot Trail motorcycle dream.','Cape Breton · Skyline Trail · Whale watching · Acadian & Gaelic · Fall colours · 298km'),
    entry('Pacific Coast Highway (CA-1)',36.5,-122.0,'USA · California · 900km','World\'s most scenic coastal drive — San Diego to San Francisco. Big Sur, Monterey, Santa Barbara, Malibu. Hearst Castle. Morro Bay. Golden Gate Bridge. Diverse landscapes — beaches, forests, cliffs.','World\'s most famous coastal drive · Big Sur · Hearst Castle · Golden Gate · 900km'),
    entry('Cornish Coast',50.3,-4.9,'UK · England · 697km','South West coast path — 1,014km. Sandy beaches and rugged cliffs. St Michael\'s Mount (tidal island). Land\'s End — westernmost England. Minack Theatre (clifftop open-air). Eden Project. Porthcurno beach. Cod fishing.','South West Coast Path · St Michael\'s Mount · Land\'s End · Minack Theatre · Eden Project'),
  ],
};
for (const [cat, entries] of Object.entries(inserts)) {
  const marker = `D.${cat} = [`;
  const startIdx = html.indexOf(marker);
  if (startIdx === -1) { console.log(`ERROR: ${cat} not found`); continue; }
  const afterBracket = html.indexOf('[', startIdx) + 1;
  const chunk = html.slice(afterBracket);
  let depth = 1, endIdx = 0;
  let inSQ5 = false, inDQ5 = false, inBT5 = false;
  for (let i = 0; i < chunk.length; i++) {
    const c5 = chunk[i];
    if (inBT5) {
      if (c5 === '\\' && i + 1 < chunk.length) { i++; continue; }
      if (c5 === '`') inBT5 = false;
    } else if (inDQ5) {
      if (c5 === '\\' && i + 1 < chunk.length) { i++; continue; }
      if (c5 === '"') inDQ5 = false;
    } else if (inSQ5) {
      if (c5 === '\\' && i + 1 < chunk.length) { i++; continue; }
      if (c5 === "'") inSQ5 = false;
    } else {
      if (c5 === "'") inSQ5 = true;
      else if (c5 === '"') inDQ5 = true;
      else if (c5 === '`') inBT5 = true;
      else if (c5 === '[') depth++;
      else if (c5 === ']') { depth--; if (depth === 0) { endIdx = i; break; } }
    }
  }
  const arrayContent = chunk.slice(0, endIdx);
  const existingCount = (arrayContent.match(/\{n:'/g) || []).length;
  const insertIdx = afterBracket + endIdx;
  if (existingCount >= entries.length) { console.log(`${cat}: ${existingCount} entries (all done)`); continue; }

  let insertStr = '';
  for (let j = existingCount; j < entries.length; j++) {
    insertStr += '\n' + entries[j];
  }
  if (insertStr) {
    html = html.slice(0, insertIdx) + insertStr + '\n' + html.slice(insertIdx);
  }
  console.log(`${cat}: ${existingCount} → ${existingCount + (entries.length - existingCount)} (added ${entries.length - existingCount})`);
}
fs.writeFileSync(filePath, html, 'utf8');
console.log('Part 5 done');
