$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 5: BUDDHISM AND JAINISM ===================== -->
<h2 id="buddhism-jainism">5. Buddhism and Jainism (6th Century BCE)</h2>

<p>The 6th century BCE was a period of <span class="highlight">intellectual ferment</span> in India, marked by the rise of the <strong>Shramana</strong> (striver/renunciant) movement. Numerous heterodox teachers emerged, rejecting Vedic orthodoxy, the authority of the Brahmanas and Vedas, animal sacrifice, and the caste system. They preached a path of personal effort, asceticism, and individual liberation. Buddhist texts mention <strong>62 schools of thought</strong> in the 6th century BCE. The most influential teachers included <strong>Gautama Buddha</strong> (the Enlightened One), <strong>Mahavira</strong> (the Great Hero, 24th Tirthankara of Jainism), <strong>Purana Kassapa</strong> (amoralism - deeds have no consequence), <strong>Makkhali Gosala</strong> (fatalism/destiny - Ajivika sect), <strong>Ajita Kesakambali</strong> (materialism/lokayata - death is the end), <strong>Pakudha Kacchayana</strong> (atomism - 7 eternal elements), and <strong>Sanjaya Belatthiputta</strong> (scepticism/agnosticism - eel-wriggling). Among these, only Buddhism and Jainism survived as major organised religions.</p>

<h3>Buddhism - Detailed Exposition</h3>

<h4>Life of Gautama Buddha (c. 563-483 BCE)</h4>

<p><span class="highlight">Siddhartha Gautama</span> was born in <strong>Lumbini</strong> (in the Nepal Terai) as a prince of the Shakya clan, a small gana-sangha republic (hence he is also called <strong>Shakyamuni</strong> - sage of the Shakyas). His father <strong>Suddhodana</strong> was the elected chieftain of the Shakya republic; his mother <strong>Maya</strong> died 7 days after his birth and he was raised by his step-mother <strong>Prajapati Gautami</strong> (after whom he was named 'Gautama'). The prophecy at his birth (by Asita) said he would become either a great chakravartin (universal monarch) or a great spiritual teacher. His father shielded him from suffering - the <strong>Four Sights</strong>: at 29 he ventured out of the palace and saw an old man (old age), a sick man (disease), a corpse (death), and a wandering ascetic (renunciation - a sannyasin). This was his <strong>Mahabhinishkramana</strong> (Great Renunciation) - he left his wife <strong>Yashodhara</strong> (also called Bhaddakaccana/Rahulamata) and infant son <strong>Rahula</strong> at midnight, cutting his hair with his sword and exchanging his royal robes for a beggar's rags.</p>

<p>He sought knowledge from two famous teachers: <strong>Alara Kalama</strong> (who taught the attainment of the 'sphere of nothingness' - akincanya-ayatana, a very high meditative state but not liberation) and <strong>Uddaka Ramaputta</strong> (who taught the 'sphere of neither perception nor non-perception' - naivasanjnasanna-ayatana, even higher). Rejecting both as inadequate, he practised extreme asceticism for 6 years at <strong>Uruvela</strong> (Bodh Gaya) with 5 companions (Kondanna, Vappa, Bhaddiya, Mahanama, Assaji), nearly starving himself to death. Realising the futility of self-mortification, he accepted a bowl of rice-milk from the village girl <strong>Sujata</strong> and sat under a <strong>pipal tree (Ficus religiosa)</strong> vowing not to rise until he attained enlightenment. After 49 days of meditation, he achieved <span class="highlight">Nirvana</span> (Enlightenment) at the age of 35, becoming the Buddha - the Awakened One. He then delivered his first sermon at the <strong>Deer Park</strong> (Mrgadava) at <strong>Sarnath</strong> (near Varanasi) to his 5 former companions - this is the <strong>Dhammacakkappavattana Sutta</strong> ('Setting in Motion the Wheel of Dharma'). These 5 became the first bhikkhus (monks), establishing the <strong>Sangha</strong> (monastic order). The <strong>Triratna</strong> (Three Jewels of Buddhism) was born: Buddha (the teacher), Dharma (the teaching), Sangha (the community).</p>

<p>He spent the next 45 years travelling through the Gangetic plain (mostly in Kosala, Magadha, and Vajji), teaching and establishing the Sangha. He visited his home city of Kapilavastu and converted his father, step-mother (who became the first bhikkhuni - nun), son, and cousin <strong>Ananda</strong> (who became his most devoted attendant, memorising all his sermons). His chief disciples: <strong>Sariputta</strong> (foremost in wisdom), <strong>Moggallana</strong> (foremost in psychic powers), <strong>Mahakassapa</strong> (foremost in asceticism, became president of the First Council), <strong>Ananda</strong> (foremost in memory, recorded as 'Thus have I heard...'), <strong>Anuruddha</strong> (foremost in divine eye). <strong>Devadatta</strong>, his ambitious cousin, attempted to kill him and create a schism. He died at age 80 at <strong>Kushinara</strong> (Kushinagar) after eating a meal of sukaramaddava (either pork or a type of truffle offered by the blacksmith Cunda). His last words: 'Decay is inherent in all composite things. Work out your salvation with diligence.' His body was cremated and the relics divided among 8 claimants - enshrined in stupas.</p>

<h4>Core Doctrines of Buddhism</h4>

<p><strong>The Four Noble Truths (Arya-satyani)</strong>: the foundational teaching of Buddhism. <strong>Dukkha</strong> (all existence is suffering/unsatisfactory - birth, aging, sickness, death, separation from loved ones, association with the disliked, not getting what one wants, the five skandhas/aggregates of clinging are dukkha). <strong>Samudaya</strong> (the origin/cause of suffering is tanha/trishna - craving, desire, attachment, thirst for sensual pleasures, existence, and non-existence). <strong>Nirodha</strong> (the cessation of suffering is the cessation of craving - Nirvana, the unconditioned). <strong>Marga</strong> (the way to cessation is the Noble Eightfold Path).</p>

<p><strong>The Noble Eightfold Path (Arya-astangika-marga)</strong>: <span class="highlight">Right View</span> (understanding the Four Noble Truths), <span class="highlight">Right Intention</span> (renunciation, goodwill, harmlessness), <span class="highlight">Right Speech</span> (no lying, slander, harsh words, gossip), <span class="highlight">Right Action</span> (no killing, stealing, sexual misconduct - for monks: celibacy), <span class="highlight">Right Livelihood</span> (avoiding occupations that harm: butchers, arms dealers, poison dealers, slave traders, intoxicants), <span class="highlight">Right Effort</span> (prevent and abandon unwholesome states, cultivate and maintain wholesome states), <span class="highlight">Right Mindfulness</span> (awareness of body, feelings, mind, and phenomena - satipatthana), <span class="highlight">Right Concentration</span> (meditative absorption - jhana/dhyana). The path is divided into three trainings: <strong>Shila</strong> (morality - speech, action, livelihood), <strong>Samadhi</strong> (concentration - effort, mindfulness, concentration), <strong>Prajna</strong> (wisdom - view, intention).</p>

<p><strong>Anatman (Anatta - No-Self/No-Soul)</strong>: The most distinctive and radical Buddhist doctrine. There is no permanent, unchanging, eternal self or soul (atman). What we call a 'person' is merely a temporary aggregation of the <span class="highlight">Five Skandhas</span> (aggregates): <strong>Rupa</strong> (form/materiality), <strong>Vedana</strong> (feeling/sensation - pleasant, unpleasant, neutral), <strong>Sanna/Samjna</strong> (perception/cognition), <strong>Sankhara/Samskara</strong> (mental formations, volitional impulses, karmic formations), <strong>Vinnana/Vijnana</strong> (consciousness that cognises all the other aggregates). At death, the skandhas disperse, and the karmic energy propels a new mental-physical continuum into a new existence - like one flame lighting another. There is no 'thing' that transmigrates, yet there is continuity of karmic causation. This is the Buddhist 'Middle Way' between eternalism (soul exists eternally) and annihilationism (death is total extinction).</p>

<p><strong>Karma and Rebirth</strong>: Actions (karma) driven by intention shape future existences. Good karma leads to favourable rebirths (in heavenly realms or as humans), bad karma to unfavourable ones (as animals, hungry ghosts - pretas, or hell-beings). But even the gods are trapped in samsara - Buddhism teaches that liberation is not heaven but the cessation of all existence. Rebirth is not reincarnation of a soul (since there is no soul) but a causal continuum, like a flame passing from one lamp to another.</p>

<p><strong>Dependent Origination (Pratityasamutpada)</strong>: The <span class="highlight">Twelve Links (Nidanas)</span> showing how suffering arises and ceases through a chain of causation: (1) Ignorance (avidya) → (2) Volitional formations (samskara) → (3) Consciousness (vijnana) → (4) Name-and-form (nama-rupa) → (5) Six sense bases (salayatana) → (6) Contact (sparsha) → (7) Feeling (vedana) → (8) Craving (trishna) → (9) Clinging (upadana) → (10) Becoming (bhava) → (11) Birth (jati) → (12) Aging-and-death (jara-marana). Each link conditions the next. Breaking the chain at any point (especially ignorance and craving) leads to the cessation of the cycle.</p>

<p><strong>Nirvana (Nibbana)</strong>: The 'blowing out' of the fires of greed, hatred, and delusion. The unconditioned, the deathless, the ultimate goal. It is not a 'place' but a state of liberation from all conditioned existence. In Nirvana, the Five Skandhas cease to arise - there is no more becoming, no more rebirth, no more suffering. The Buddha described it as 'the unborn, the unbecome, the unmade, the unconditioned' — if there were not this, there would be no escape from the conditioned.</p>

<h4>Buddhist Monastic Order (Sangha)</h4>

<p>Rules for monks and nuns are codified in the <strong>Vinaya Pitaka</strong>, especially the <strong>Patimokkha</strong> (227 rules for monks, 311 for nuns). The <strong>Upasampada</strong> (higher ordination) requires the candidate to be over 20, free of debt and disease, and with parental consent. Monks owned only 8 requisites: 3 robes, a bowl, a razor, a needle, a belt, a water-strainer. The Sangha was the nucleus of Buddhism - without it, the Dharma could not survive. Major festivals: <strong>Vesak</strong> (Buddha's birth, enlightenment, and death on the full moon of May), <strong>Asalha Puja</strong> (first sermon), <strong>Kathina</strong> (offering of robes).</p>

<h4>Buddhist Councils</h4>

<div class="table-wrap"><table>
<tr><th>Council</th><th>Year</th><th>Place</th><th>Patron</th><th>President</th><th>Outcome</th></tr>
<tr><td><strong>First</strong></td><td>c. 483 BCE</td><td>Rajgir (Sattapanni cave)</td><td>Ajatashatru</td><td>Mahakassapa</td><td>Ananda recited the Sutta Pitaka; Upali recited the Vinaya Pitaka. Tripitaka fixed orally.</td></tr>
<tr><td><strong>Second</strong></td><td>c. 383 BCE</td><td>Vaishali</td><td>Kalashoka</td><td>Sabbakami</td><td>Dispute over 'Ten Points' (monks accepting gold/silver etc.). Schism: Sthaviravadins (orthodox) vs Mahasanghikas (liberal).</td></tr>
<tr><td><strong>Third</strong></td><td>c. 250 BCE</td><td>Pataliputra</td><td>Ashoka</td><td>Moggaliputta Tissa</td><td>Caused by lax monks and heretics infiltrating the Sangha. Tissa composed the Kathavatthu (Points of Controversy). Refined the Abhidhamma Pitaka. Ashoka dispatched missionaries to 9 regions.</td></tr>
<tr><td><strong>Fourth</strong></td><td>1st cent. CE (Theravada) / c. 78 CE (Mahayana)</td><td>Sri Lanka (Tambapanni) / Kashmir (Kundalavana)</td><td>Vattagamani Abhaya (Sri Lanka) / Kanishka (Kashmir)</td><td>Rakkhita (Sri Lanka) / Vasumitra (Kashmir)</td><td>Theravada: Pali Canon written down for the first time on palm leaves. Mahayana: Sarvastivadin Mahavibhasha compiled; Buddhism split into Mahayana and Hinayana clearly.</td></tr>
</table></div>

<h4>Buddhist Sects and Schools</h4>

<p><strong>Hinayana (Theravada)</strong> - 'Lesser Vehicle' (the term is pejorative, coined by Mahayana; Theravadins prefer 'Way of the Elders'). Emphasis on individual liberation (arhat ideal); Buddha is a historical teacher, not a god; no worship of Buddha images originally; Pali language; prominent in Sri Lanka, Myanmar, Thailand, Laos, Cambodia, and among the Tai peoples of Assam. Key text: the Pali Tripitaka.</p>

<p><strong>Mahayana</strong> - 'Greater Vehicle' (c. 1st cent. BCE onward). Emphasis on the <span class="highlight">Bodhisattva ideal</span> - one who postpones their own Nirvana to save all sentient beings. Buddha is a transcendent, cosmic being with many manifestations (the Doctrine of the Three Bodies - Trikaya: Nirmanakaya - earthly form, Sambhogakaya - celestial body of bliss, Dharmakaya - the ultimate reality). Worship of Bodhisattvas (Avalokiteshvara - compassion, Manjushri - wisdom, Maitreya - future Buddha, Kshitigarbha - saviour of hell-beings, Vajrapani - protector). Philosophical schools: <strong>Madhyamaka</strong> (Sunyavada - Emptiness, founded by Nagarjuna, c. 150-250 CE) and <strong>Yogacara</strong> (Vijnanavada - Mind-Only/Consciousness-Only, founded by Asanga and Vasubandhu, c. 300-400 CE). Sanskrit texts; prominent in Central Asia, Tibet, China, Korea, Japan, Vietnam, Nepal.</p>

<p><strong>Vajrayana</strong> - 'Diamond/Thunderbolt Vehicle' (c. 5th cent. CE onward). Esoteric Buddhism incorporating tantric rituals, mantras, mandalas, mudras, and the guru-disciple lineage. Emphasis on attaining Buddhahood in one lifetime through esoteric practices. Developed in Bengal, Odisha, and later Tibet. Texts: Tantras (Guhyasamaja Tantra, Kalachakra Tantra, Hevajra Tantra, Chakrasamvara Tantra, Mahamaya Tantra, etc.). Prominent in Tibet, Bhutan, Mongolia, and Ladakh. The <strong>84 Mahasiddhas</strong> (great adepts) including figures like Naropa, Tilopa, Marpa, and Milarepa are central to Tibetan Buddhist hagiography.</p>

<h3>Jainism - Detailed Exposition</h3>

<p><span class="highlight">Jainism</span> traces its origins to a line of 24 <strong>Tirthankaras</strong> (ford-makers who cross the river of samsara and show the way). The first was <strong>Rishabhanatha</strong> (Adinatha), mentioned in the Rigveda and Puranas, who is said to have lived millions of years ago and to have taught the arts of civilisation (agriculture, writing, governance). Historicity is reliably established only for <strong>Parshvanatha</strong> (23rd Tirthankara, c. 877-777 BCE) and <strong>Mahavira</strong> (24th Tirthankara, c. 599-527 BCE). Parshvanatha taught four principles: non-violence (ahimsa), truthfulness (satya), non-stealing (asteya), and non-attachment (aparigraha). Mahavira added the fifth vow of celibacy (brahmacharya).</p>

<h4>Life of Mahavira</h4>

<p><strong>Vardhamana Mahavira</strong> was born at <strong>Kundagrama</strong> (Vaishali district) in 599 BCE (some traditions say 540 BCE) to King <strong>Siddhartha</strong> of the Jnatrika clan (a Kshatriya ruling family of the Vrijji gana-sangha) and Queen <strong>Trishala</strong> (sister of Chetaka, the Lichchhavi chief). The Jain account of his birth is full of miracles: his mother had 14 auspicious dreams (white elephant, bull, lion, goddess Sri, garlands, full moon, sun, flag, full vase, lotus lake, celestial ocean, celestial chariot, jewel throne, smokeless fire). He married <strong>Yashoda</strong> and had a daughter <strong>Priyadarshana</strong> (or Anavaddha). At age 30, after his parents' death, he renounced the world (taking a vow of silence for two days before renouncing), distributed his wealth, tore out his hair in 5 handfuls (kevala-loch), and became a wandering ascetic wearing no clothes (<strong>digambara</strong> - sky-clad). He endured extreme hardships: 'stinging flies, mosquitos, cold, heat, and other insects do not disturb him.'</p>

<p>After <strong>12 years</strong> of severe asceticism (including 4 months of standing meditation in one spot, fasting for months on end), he attained <span class="highlight">Kevala Jnana</span> (absolute knowledge/liberation) at age 42 at <strong>Jambhiyagrama</strong> on the bank of the Rijupalika river. He then taught for 30 years, organising his followers into 4-fold sangha (monks, nuns, laymen, laywomen). He died at <strong>Pava</strong> (near Rajgir) aged 72 by <strong>sallekhana</strong> (voluntary fasting unto death) — the ideal Jain death. His chief disciples (11 ganadharas) included <strong>Indrabhuti Gautama</strong>, <strong>Sudharma</strong>, <strong>Arya Jambu</strong>. His chief nuns included <strong>Chandana</strong> (his own daughter or, in some accounts, a slave girl).</p>

<h4>Core Jain Doctrines</h4>

<p><strong>Anekantavada (Non-Absolutism)</strong>: Reality is complex and cannot be fully captured by any single viewpoint. All truth claims are partial. This is expressed through two sub-doctrines:</p>
<ul>
<li><strong>Syadvada</strong> (Theory of Conditioned Predication): Every proposition must be prefixed by 'syat' (in some way/maybe). For any object, seven modes of predication are possible: (1) it exists, (2) it does not exist, (3) both exists and does not exist (successively), (4) it is indescribable (simultaneously), (5) it exists and is indescribable, (6) it does not exist and is indescribable, (7) both exists and does not exist and is indescribable. The aim is to avoid dogmatism and appreciate the multi-faceted nature of reality.</li>
<li><strong>Nayavada</strong> (Theory of Standpoints): There are multiple valid standpoints for understanding reality - naigama (teleological), samgraha (generic), vyavahara (practical), rju-sutra (linear/seamless), sabda (verbal), samabhirudha (etymological), evambhuta (actual/functional).</li>
</ul>

<p><strong>Ahimsa Paramodharma (Non-violence is the Supreme Religion)</strong>: Ahimsa is the central and most distinctive Jain teaching — carried to its logical extreme. Jains avoid causing harm to any living being, including insects, plants, even microorganisms in water. Jain monks sweep the ground before walking, strain water before drinking, wear mouth-covers (muhpatti), and never eat at night (to avoid accidentally swallowing insects). The universe is full of <strong>jivas</strong> (souls) — every element (earth, water, fire, air) has its own class of embodied souls (prithvi-kayika jiva, ap-kayika jiva, etc.). Even a single drop of water contains thousands of tiny beings. The laity are expected to follow <strong>anuvratas</strong> (minor vows) while monks follow <strong>mahavratas</strong> (major vows).</p>

<p><strong>Absolute Non-violence (Ahimsa)</strong> — no killing or harming any living being in thought, word, or deed. <strong>Truth (Satya)</strong> — speak only what is true, beneficial, and pleasant. <strong>Non-stealing (Asteya)</strong> — no taking what is not given. <strong>Celibacy (Brahmacharya)</strong> — complete sexual abstinence for monks; limited sexual restraint for laity (chastity within marriage). <strong>Non-attachment (Aparigraha)</strong> — limit material possessions; monks own nothing (except two white garments for Svetambaras or nothing at all for Digambaras).</p>

<p><strong>Karma Theory in Jainism</strong>: Karma is not an abstract moral force but a <span class="highlight">subtle material substance</span> that literally sticks to the jiva (soul) through the kashayas (passions: anger, pride, deceit, greed). The soul is inherently pure consciousness (upayoga) and bliss, but it is weighed down by karmic particles (karma-pudgala). Liberation involves stopping the influx of new karma (samvara), shedding existing karma (nirjara), and ultimately attaining <strong>kevala-jnana</strong> — omniscience — after which the soul rises to the top of the universe (the siddha-shila). The <strong>8 types of karma</strong> are: Jnanavaraniya (knowledge-obscuring), Darshanavaraniya (perception-obscuring), Vedaniya (feeling-producing), Mohniya (deluding — the most dangerous, sub-divided into 28 sub-types), Ayushya (life-span determining), Nama (body-determining), Gotra (status-determining), Antaraya (hindrance/obstacle-producing).</p>

<p><strong>The 9 Tattvas (Fundamental Principles of Jain Philosophy)</strong>: (1) Jiva (soul), (2) Ajiva (non-soul — matter, time, space, motion, rest), (3) Asrava (influx of karma into the soul), (4) Bandha (bondage of karma), (5) Samvara (stopping the influx), (6) Nirjara (shedding of karma), (7) Punya (merit - good karma), (8) Papa (demerit - bad karma), (9) Moksha (liberation). The goal is to attain moksha by understanding and practising these principles.</p>

<h4>Jain Sects - The Great Schism</h4>

<div class="table-wrap"><table>
<tr><th>Aspect</th><th>Digambara (Sky-clad)</th><th>Svetambara (White-clad)</th></tr>
<tr><td>Clothing</td><td>Monks go naked; nuns wear white</td><td>Monks and nuns both wear white</td></tr>
<tr><td>Mahavira's Life</td><td>Mahavira never married and was celibate from birth</td><td>Mahavira married Yashoda and had a daughter</td></tr>
<tr><td>Women's Liberation</td><td>Women cannot attain moksha in female body; must be reborn male</td><td>Women can attain moksha; Malli-natha (19th Tirthankara) was female</td></tr>
<tr><td>Canonical Texts</td><td>Original Agamas lost; rely on later texts (Shatkhandagama, Samayasara)</td><td>Preserved 45 Agamas including the 12 Angas, 12 Upangas, etc.</td></tr>
<tr><td>Major Centres</td><td>Shravanabelagola, Karnataka; Khandagiri-Udayagiri, Odisha</td><td>Gujarat, Rajasthan, Mount Abu, Palitana</td></tr>
<tr><td>Patron Saints</td><td>Acharya Kundakunda, Pushpadanta, Bhutabali, Samantabhadra</td><td>Hemachandra (advisor to Chaulukya king Jayasimha Siddharaja)</td></tr>
</table></div>

<h4>Jain Councils and Literature</h4>

<p>The <strong>First Jain Council</strong> was held at <strong>Pataliputra</strong> (c. 300 BCE) under Chandragupta Maurya's patronage, led by Sthulabhadra, to compile the sacred texts (the 12 Angas). It is said that only 11 Angas survived because the 12th (Drishtivada) was lost. The <strong>Second Council</strong> was at <strong>Valabhi</strong> (Gujarat, c. 456 CE) under Devardhigani Kshamashramana, where the Jain canon was finally written down on palm leaves. <strong>Jain Canonical Texts</strong>: The 12 Angas (Acharanga-sutra - monastic rules, Sutrakritanga - heretical doctrines, Sthananga - numerical lists, Samavayanga - syncretic lists, Vyakhyaprajnapati/Bhagavati-sutra - the largest, containing the 16 Mahajanapadas list, etc.), 12 Upangas, 10 Prakirnakas (miscellaneous texts), 6 Chedasutras (disciplinary texts), 4 Mulasutras (basic texts), and the Nandisutra/Avashyaka (essential rituals). Non-canonical but important texts: <strong>Tattvartha Sutra</strong> (by Umasvati/Umasvami, c. 2nd-5th cent. CE - the definitive systematic Jain text, accepted by both sects), <strong>Shatkhandagama</strong> (Digambara doctrinal text by Pushpadanta and Bhutabali), <strong>Yogashastra</strong> and <strong>Yogadrishtisamuccaya</strong> (by Haribhadra Suri), <strong>Kalpa Sutra</strong> (by Bhadrabahu - contains biographies of the Tirthankaras and the life of Mahavira). <strong>Prakrit</strong> was the language of the Jain scriptures, not Sanskrit — the Ardha-Magadhi Prakrit for the Svetambara canon.</p>

<h4>Contributions of Buddhism and Jainism</h4>

<ul>
<li><strong>Social reform</strong>: Both rejected caste hierarchy and preached social equality. The Buddha said 'Not by birth does one become a Brahmin, but by deeds.' Jainism taught that all souls are inherently equal - the potential for liberation exists in all beings.</li>
<li><strong>Language and literature</strong>: Both used <strong>Prakrit</strong> (and later Pali) to reach common people, breaking the Brahmanical monopoly on Sanskrit. Pali became the sacred language of Theravada Buddhism; Ardha-Magadhi for Jain canon. Mahayana Buddhism later adopted Sanskrit.</li>
<li><strong>Art and architecture</strong>: Inspired magnificent monuments - stupas (Sanchi, Bharhut, Amaravati), cave temples (Ajanta, Ellora, Karla), pillar edicts (Ashoka), universities (Nalanda, Vikramashila, Taxila). Jain temple cities at Dilwara (Mount Abu, white marble), Palitana (Shatrunjaya hills, 863 temples), Shravanabelagola (57-ft Bahubali/Gommateshwara monolith, 981 CE).</li>
<li><strong>Institutions of learning</strong>: Buddhist universities (Nalanda - 10,000 monks, 2000 teachers, 3 libraries - c. 5th-12th cent. CE; Vikramashila - 108 teachers; Odantapuri; Somapura in Bengal) attracted students from China, Tibet, Korea, Sri Lanka, Central Asia. Xuanzang (Hiuen Tsang) studied at Nalanda for 5 years (c. 630 CE), recording its magnificence: 'The whole establishment is surrounded by a brick wall... one principal entrance opens into the great gate... the richly adorned towers and the fairy-like turrets seem to touch the clouds.'</li>
<li><strong>Spread of Indian culture abroad</strong>: Buddhism carried Indian culture, art, and philosophy to Central Asia (Gandhara, Bamiyan - giant Buddha statues, 55m and 38m; the Silk Route), China (Kumarajiva, Bodhidharma, Faxian, Xuanzang), Tibet (Padmasambhava, Atisha), Korea (Monk Hyecho), Japan (Prince Shotoku's 17-Article Constitution - based on Buddhism), Sri Lanka (Mahinda and Sanghamitta - Ashoka's children), and Southeast Asia (Angkor Wat, Borobudur, Shwedagon Pagoda).</li>
</ul>

<div class="warn-box"><div class="warn-title">Common UPSC Mistake: Buddhism vs Jainism Doctrines</div><div class="warn-text"><strong>Don't confuse:</strong> Buddhism rejects the existence of the soul (anatman) as the defining feature that separates it from all other Indian religions. Jainism, by contrast, affirms the existence of infinite souls (jivas) and makes the soul the central focus - the goal is to free the soul from karmic matter. The Buddha rejected extreme asceticism as the Middle Way; Mahavira embraced it fully. The Buddha accepted the existence of gods (devas) but said they were also trapped in samsara; Jainism is consistently non-theistic (gods exist but are subordinate to the Tirthankaras and are also subject to karma).</div></div>

<div class="example-box"><div class="ex-title">Essay Application</div><div class="ex-text">For UPSC essays on 'Tradition vs Modernity', 'Science and Spirituality', or 'Non-violence in World Affairs', consider: Buddhism introduced an empirical, experiential approach to spirituality (test the doctrine like a goldsmith tests gold) that resonates with modern scientific thinking. Jainism's anekantavada is a profound philosophical foundation for tolerance and pluralism that is highly relevant in today's world of ideological conflict. The concept of ahimsa directly influenced Mahatma Gandhi's satyagraha, which in turn inspired Martin Luther King Jr. and Nelson Mandela.</div></div>

<div class="diagram-box"><pre>
  BUDDHISM vs JAINISM - SNAPSHOT
  
  BUDDHISM                  JAINISM
  Middle Way                Ascetic Way
  No soul (Anatman)           Infinite souls (Jiva)
  Compassion (Karuna)       Non-violence (Ahimsa)
  4 Noble Truths              9 Tattvas
  8-Fold Path               Five Vows
  No extreme penance         Extreme penance
  Pali Canon                Ardha-Magadhi/Maharashtri
  
  BOTH: 
  - Rejected Vedas/sacrifices
  - Rejected caste hierarchy  
  - Taught in Prakrit
  - Founded by Kshatriya princes
  - Spread by royal patronage
</pre></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 5 written."
