const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

// ==================== SECTION 9 ====================
c += `<!-- ===================== SECTION 9: POPULATION AND HUMAN GEOGRAPHY ===================== -->\n`;
c += `<h2 id="population">9. Population & Human Geography</h2>\n\n`;

c += `<h3>Population Size and Growth</h3>\n\n`;
c += `<p>India's population is the <span class="highlight">2nd largest in the world</span> (after surpassing China in April 2023 with an estimated 1.428 billion &mdash; according to the UN World Population Prospects 2023), though the officially conducted 2021 Census (the world's largest statistical operation) has been delayed due to the COVID-19 pandemic and is expected to be held in 2025. The <strong>2011 Census</strong> recorded a population of <strong>1.21 billion</strong> (121.06 crores), with 51.5% male (62.4 crore) and 48.5% female (58.6 crore). The decadal growth rate (2001-2011) was <strong>17.64%</strong> &mdash; the lowest in 7 decades, continuing the declining trend from 24.66% in 1961-71, 24.66% in 1971-81, 23.86% in 1981-91, and 21.54% in 1991-2001. The growth rate peaked at 2.5% in the 1970s (the 'Population Explosion' decade) and has declined to about <strong>1.2%</strong> in the 2010s.</p>\n\n`;

c += `<p>The <span class="highlight">Total Fertility Rate (TFR)</span> has reached <strong>2.0</strong> (as per the National Family Health Survey-5, NFHS-5, 2019-21), which is <strong>below the replacement level of 2.1</strong> for the first time in India's demographic history. This is a momentous demographic milestone &mdash; it means that India's population growth is now driven entirely by 'population momentum' (the large number of young people entering their reproductive years, a legacy of past high fertility), and the population is projected to peak at 1.5 billion by 2045-50 and then begin declining (UN projection). As many as <strong>15 states</strong> have already achieved below-replacement fertility: Kerala (1.8), Tamil Nadu (1.7), Punjab (1.6), Himachal Pradesh (1.7), West Bengal (1.6), Andhra Pradesh (1.7), Delhi (1.6), Uttarakhand (1.9), Goa (1.7), Sikkim (1.3), Maharashtra (1.8), Jammu and Kashmir (1.6), and the Union Territories. The high-fertility states are Bihar (2.9), UP (2.4), Jharkhand (2.3), MP (2.2), Rajasthan (2.2), and Chhattisgarh (2.1).</p>\n\n`;

c += `<div class="warn-box"><div class="warn-title">The Population Debate: India as the Most Populous Country</div><div class="warn-text">India overtook China as the world's most populous country in April 2023 (according to the UN World Population Prospects, 2023), with a population of 1.428 billion against China's 1.425 billion. This 'demographic milestone' has been the subject of intense debate. Some commentators frame it as a 'population bomb' and a Malthusian crisis &mdash; that India's resources (water, land, food, jobs) cannot sustain such a large population. Others, particularly economists, focus on the 'demographic dividend' &mdash; India has the youngest population in the world (median age 28, compared to 38 in China, 43 in Europe, 48 in Japan), and this vast working-age population (15-64) could be an engine of economic growth if provided with education, skills, and employment. The reality is complex: India's TFR has already fallen below replacement (2.0), and the total population is estimated to peak around 1.5 billion by 2045-50; the challenge is not the size of the population but its distribution (the densely populated states of the Indo-Gangetic plain vs. the sparsely populated North East), its age structure (the ageing of the population &mdash; the old-age dependency is increasing), and the quality of human capital (education, health, skills). The debate will continue, but the 'population dividend' is not automatic &mdash; it is conditional on the investment in human capital (education, health, skills) and the creation of productive employment (the structural transformation from agriculture to manufacturing and services). India has a 'window of opportunity' of about 30-40 years before it begins to age, and the next decade will be decisive.</div></div>\n\n`;

c += `<h3>Population Distribution</h3>\n\n`;
c += `<p>The population of India is <span class="highlight">very unevenly distributed</span>, with stark contrasts between the densely populated Indo-Gangetic plain and the sparsely populated Himalayan and arid regions. The overall <strong>population density</strong> of India is <strong>382 persons per sq km</strong> (2011 Census) &mdash; the 2nd highest in the world for a large country (after Bangladesh), and far higher than China (147), the US (35), or Brazil (25). However, the state-wise variation is extreme:</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>The Densely Populated States</strong> &mdash; <strong>Bihar</strong> (1,106/sq km &mdash; the highest in India), <strong>West Bengal</strong> (1,030/sq km), <strong>Kerala</strong> (860/sq km), <strong>Uttar Pradesh</strong> (828/sq km &mdash; the highest absolute population, 200 million, the largest state in India by population, equivalent to the 5th largest country in the world by population), <strong>Haryana</strong> (573/sq km), <strong>Tamil Nadu</strong> (555/sq km), <strong>Punjab</strong> (550/sq km), and <strong>Jharkhand</strong> (414/sq km). These states are located in the riverine and coastal alluvial plains, with favourable agricultural conditions (the Indo-Gangetic plain, the coastal deltas), long histories of settlement, and (in some cases) high population momentum from past fertility.</li>\n`;
c += `<li><strong>The Sparsely Populated States and UTs</strong> &mdash; <strong>Ladakh</strong> (3/sq km &mdash; the lowest in India), <strong>Arunachal Pradesh</strong> (17/sq km &mdash; the lowest among the states), <strong>Mizoram</strong> (52/sq km), <strong>Sikkim</strong> (86/sq km), <strong>Meghalaya</strong> (132/sq km), <strong>Nagaland</strong> (119/sq km), and <strong>Himachal Pradesh</strong> (123/sq km). These are the mountainous, forested, or arid regions of the Himalayas and the North East, where rugged terrain, steep slopes, limited agricultural land, and climatic constraints restrict population concentration.</li>\n`;
c += `<li><strong>The Moderate Density States</strong> &mdash; <strong>Delhi</strong> (11,320/sq km &mdash; the highest density of any state/UT, the 'city-state' effect), <strong>Chandigarh</strong> (9,258/sq km), and the UTs of <strong>Puducherry</strong> (2,547/sq km), <strong>Daman & Diu</strong> (2,169/sq km), and <strong>Lakshadweep</strong> (2,013/sq km) show the highest densities due to the concentration of urban population in small territories.</li>\n`;
c += `</ul>\n\n`;

c += `<h3>Urbanisation</h3>\n\n`;
c += `<p>India's urban population (as per the 2011 Census) is <strong>31%</strong> of the total population (377 million people), which is relatively low by international standards (the world average is 55%, China's is 60%, Brazil's is 87%). However, the absolute urban population is the <strong>2nd largest in the world</strong> after China. The urbanisation rate (the 'tempo of urbanisation', measured by the increase in the urban share of the population) has been slow &mdash; from 17% in 1951 to 31% in 2011 &mdash; but the pace has accelerated in the last 2 decades. The Census of India defines 'urban' based on a settlement with a population of 5,000+, a density of 400+/sq km, and at least 75% of the male workforce engaged in non-agricultural pursuits (the 'census town' definition). There are 5 <span class="highlight">megacities</span> (population over 10 million): <strong>Mumbai</strong> (20 million, the largest in India, the 7th largest in the world), <strong>Delhi</strong> (19 million, the 8th largest in the world), <strong>Kolkata</strong> (14 million), <strong>Chennai</strong> (11 million), and <strong>Bengaluru</strong> (10 million). A <strong>6th megacity</strong>, <strong>Hyderabad</strong> (9.5 million, projected to cross 10 million by 2025), is on the threshold. There are <strong>53 million-plus cities</strong> (cities with a population of 1 million+), up from 35 in 2001, reflecting the increasing urbanisation of India.</p>\n\n`;

c += `<p>The <strong>Smart Cities Mission</strong> (launched 2015, 100 cities selected) is the flagship urban development programme, adopting a 'area-based development' approach (retrofitting of 500-acre areas in each city, the 'lighthouse city' model). The urban challenges remain severe: 65 million people live in slums (the largest slum population in the world, with Dharavi in Mumbai being the largest slum in Asia), 50% of urban households lack individual water connections, only 30% of sewage is treated, and the housing shortage is estimated at 18 million units (addressed by the <strong>Pradhan Mantri Awas Yojana (PMAY-Urban)</strong>, which has sanctioned 12 million houses since 2015). The <strong>74th Constitutional Amendment Act 1992</strong> provided constitutional status to Urban Local Bodies (the 'municipal corporations', 'municipal councils', and 'nagar panchayats'), devolving 12th Schedule functions (urban planning, water supply, sanitation, public health) to cities. However, urban governance is weak: the ULBs generate only 30% of their finances from own sources (property tax, user charges), and the rest comes from state government grants, leading to a chronic infrastructure deficit.</p>\n\n`;

c += `<h3>Migration</h3>\n\n`;
c += `<p>Migration (the movement of people across geographical space) is a defining feature of India's population dynamics. The <strong>2011 Census</strong> (the 'migration master' data) recorded <strong>450 million internal migrants</strong> (37% of the population), an increase of 100 million from the 2001 Census. The Census defines a migrant as someone whose 'place of last residence' is different from the 'place of enumeration' (census definition). The migration streams are dominated by <strong>female migration</strong> (70% of all internal migrants, primarily for marriage &mdash; about 70% of female migrants cite marriage as the reason), while <strong>male migration</strong> is primarily economic (70% of male migrants cite employment/business as the reason). The <strong>inter-state migration</strong> (movement across state borders) is about 50 million (12% of all migrants), with the major destination states being Maharashtra, Delhi, Gujarat, Karnataka, Tamil Nadu, and Haryana (the 'high-income states'), and the major source states being Uttar Pradesh, Bihar, Rajasthan, Odisha, Jharkhand, and Madhya Pradesh (the 'low-income states'). The <strong>Gulf migration</strong> (emigration to the Gulf Cooperation Council/GCC countries &mdash; the UAE, Saudi Arabia, Qatar, Kuwait, Oman, Bahrain) is about 15 million NRIs (Non-Resident Indians) and is the single largest overseas migration stream, sending back <strong>remittances of $87 billion</strong> (2023) &mdash; the <strong>largest remittance-receiving country in the world</strong> (ahead of Mexico, China, and the Philippines). The 'Brain Drain' (the emigration of highly skilled professionals &mdash; doctors, engineers, IT professionals, scientists &mdash; to the US, UK, Canada, Australia, and the EU) is a concern, though the 'reverse brain drain' (the return of skilled diaspora to India, facilitated by the 'Make in India' and the 'Startup India' initiatives) is gaining momentum.</p>\n\n`;

c += `<h3>Human Development</h3>\n\n`;
c += `<p>India's <span class="highlight">Human Development Index (HDI)</span> stands at <strong>0.645</strong> (2022, UNDP), ranking <strong>131st out of 193 countries</strong> &mdash; in the 'medium human development' category. The HDI is a composite index of three dimensions: health (life expectancy at birth), education (expected years of schooling and mean years of schooling), and income (GNI per capita, PPP). India's rank is below Sri Lanka (78th), China (75th), Bhutan (127th), and Bangladesh (129th), but above Pakistan (161st) and Nepal (145th). The 'inequality-adjusted HDI' (IHDI) is 0.475 (a loss of 26% due to inequality), reflecting the deep disparities in income, health, and education across and within states.</p>\n\n`;

c += `<p><strong>Key Human Development Indicators</strong>:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Poverty</strong> &mdash; The <strong>National Multidimensional Poverty Index (MPI)</strong> (NITI Aayog, 2023) reports that 14.96% of India's population (about 20 crore people) is multi-dimensionally poor (deprived in health, education, and living standards), a sharp decline from 25% in 2015-16 (NFHS-4), reflecting the 'fastest MPI reduction ever recorded'. The World Bank's $1.90/day (PPP 2011) poverty line estimates India's extreme poverty at about 10% (down from 45% in 1995). The top 10% of earners hold 57% of national income (the highest share in the world, according to the World Inequality Lab), while the bottom 50% hold 13% &mdash; a Gini coefficient of 0.35 (moderate inequality, but rising).</li>\n`;
c += `<li><strong>Education</strong> &mdash; The <strong>literacy rate</strong> (2011 Census) is <strong>74.0%</strong> (male 82.1%, female 65.5%). The top states are <strong>Kerala</strong> (94%, the highest in India, nearly universal literacy), <strong>Mizoram</strong> (91%), <strong>Goa</strong> (89%), and <strong>Delhi</strong> (86%). The bottom states are <strong>Bihar</strong> (62%, the lowest), <strong>Arunachal Pradesh</strong> (66%), <strong>Rajasthan</strong> (67%), and <strong>Jharkhand</strong> (68%). The <strong>female literacy</strong> gap with male literacy is the highest in Rajasthan (28% gap), UP (27%), and Jharkhand (24%). The <strong>School Education</strong> indicators (ASER 2023, the Annual Status of Education Report): 86% of rural youth (age 14-18) are enrolled in school/college, but only 73% can read a Class-2 level text in English, and only 45% can do a simple division (Class-3 level) &mdash; the 'learning crisis' in Indian education. The <strong>Right to Education Act 2009</strong> (the RTE) guarantees free and compulsory education for 6-14 year olds, but the quality-of-learning deficit remains the biggest challenge.</li>\n`;
c += `<li><strong>Health</strong> &mdash; The <strong>Infant Mortality Rate (IMR)</strong> is <strong>30.2 per 1,000 live births</strong> (SRS 2020, the Sample Registration System), down from 57 in 2005. The top states in IMR are Kerala (6, equivalent to developed countries), Tamil Nadu (14), Maharashtra (16), and Punjab (18). The bottom states are Madhya Pradesh (43), Assam (39), Odisha (36), and UP (32). The <strong>Maternal Mortality Ratio (MMR)</strong> is <strong>97 per 100,000 live births</strong> (SRS 2018-20, a reduction of 40% from 2014-16), with the target of 70 under the SDG 3.1. The top states in MMR are Kerala (30), Tamil Nadu (60), and Maharashtra (65). The bottom states are Assam (205), UP (167), and Rajasthan (141). The <strong>Life Expectancy at Birth</strong> is <strong>69.7 years</strong> (male 68.2, female 71.2, SRS 2014-18), up from 58 years in 1970. The <strong>National Family Health Survey-5 (NFHS-5, 2019-21)</strong> data shows that 59% of children (6-59 months) are anaemic, 35% are stunted (low height-for-age), 19% are wasted (low weight-for-height), and 7% are severely wasted &mdash; reflecting the persistent 'triple burden of malnutrition' (undernutrition, micronutrient deficiency, and rising obesity).</li>\n`;
c += `</ul>\n\n`;

c += `<h3>Census of India</h3>\n\n`;
c += `<p>The <strong>Census of India</strong> is the <span class="highlight">largest statistical operation in the world</span>, covering the entire population of India (over 1.4 billion people). The first census in India was conducted in <strong>1872</strong> (during the British period, under Lord Mayo, covering about 200 million people), but the first <strong>synchronous census</strong> (conducted on a single night throughout the territory, with standardised schedules) was in <strong>1881</strong>, and this has been the decennial pattern ever since. The <strong>Census 2021</strong> (the 16th census and the 8th after Independence) was scheduled to be held in 2021 but has been postponed indefinitely due to the COVID-19 pandemic. It will be the <span class="highlight">first 'digital-first' census</span> in Indian history, using a mobile app (the 'Census Mobile App' for enumerators, replacing the traditional paper schedules), a self-enumeration portal (the 'Census 2021 web portal' where citizens can submit their data online), and the mapping of all households with GPS coordinates (linking each household to the Census House Listing and the UIDAI/Aadhaar and the NPR). The 'Digital Census' will be the world's largest digital data collection exercise, creating a comprehensive, geospatially-enabled database of India's population.</p>\n\n`;

c += `<p><strong>The Data on Caste</strong> &mdash; The Census of India has not collected data on caste (beyond the Scheduled Castes and Scheduled Tribes) since 1931. The <strong>Socio-Economic and Caste Census (SECC) 2011</strong> was conducted (separately from the Census, by the Ministry of Rural Development) to collect data on economic status (the 'deprivation criteria' &mdash; 7 exclusion and 14 inclusion criteria) and caste (for the OBC, SC, and ST categories). The SECC 2011 data on caste has not been officially released (the raw caste data is still 'gazetted' by the Ministry of Social Justice and Empowerment but not published), as there is no political consensus on the 'census of castes' (the OBC/EBC communities demand the release of the data to 'know the true population of OBCs', while other communities argue it will 'entrench caste identities'). The 'census of castes' remains one of the most contentious issues in Indian social statistics.</p>\n\n`;

c += `<div class="tip-box"><div class="tip-title">Population and the Indian Economy &mdash; the Demographic Dividend</div><div class="tip-text">India's 'demographic dividend' (the economic growth potential that results from shifts in a population's age structure, when the working-age population (15-64) is larger than the non-working-age share) is the most important economic geography theme for UPSC. India's working-age population is 68% of the total (compared to China's 66% and the world's 65%). The dependency ratio (the ratio of non-working age to working-age) is 48% and declining. However, the 'demographic dividend' is not automatic &mdash; it requires three conditions to be met: (1) the 'skill condition' &mdash; the working-age population must be educated and skilled (currently, only 4% of India's workforce has formal vocational training, compared to 75% in Germany, 52% in the US, and 24% in China); (2) the 'employment condition' &mdash; the economy must generate productive employment for the 1 million youth entering the labour force every month (the 'jobless growth' of the 2010s, where India's GDP grew at 7% but formal sector employment grew at only 2%, is the biggest challenge); and (3) the 'health condition' &mdash; the working population must be healthy (the 35% stunting rate among children is a drag on the cognitive capacity of the future workforce). The <strong>National Education Policy 2020</strong>, the <strong>Skill India Mission</strong> (with 1,500+ ITIs, 3,000+ polytechnics, and the Pradhan Mantri Kaushal Vikas Yojana/PMKVY), and the <strong>Startup India</strong> ecosystem are the three key policy responses to realise the demographic dividend. The 'window of opportunity' will close by 2050 (when India begins to age, and the old-age dependency ratio rises sharply), so the next two decades are critical.</div></div>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 9 complete. Total: ' + c.length + ' chars');
