const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

c += `\n<!-- ===================== SECTION 7: INDUSTRIES ===================== -->\n`;
c += `<h2 id="industries">7. Industries</h2>\n\n`;

c += `<h3>Industrial Location Factors</h3>\n\n`;
c += `<p>The location of industries in a geographical space is determined by a complex interplay of factors. Understanding these factors is essential for UPSC because they explain why certain industries cluster in specific regions and why government policies (like industrial corridors, SEZs, and decentralisation schemes) are shaped the way they are. The major <span class="highlight">industrial location factors</span> are:</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>Raw Material</strong> &mdash; The availability, cost, and quality of raw materials is the most fundamental locational factor. Heavy industries (iron and steel, cement, sugar, paper) are typically <strong>raw-material-oriented</strong>, meaning they are located close to raw material sources to avoid the high transport costs of bulky, heavy inputs. The 'weight-losing' nature of these industries (where the weight of input exceeds the weight of output) makes raw material proximity economically decisive. For example, steel plants are located near iron ore and coal fields; sugar mills are located near sugarcane-growing areas because sugarcane loses 95% of its weight during processing.</li>\n`;
c += `<li><strong>Power/Energy</strong> &mdash; Industries with high energy requirements (aluminium smelting, ferroalloys, textiles, chemicals) are attracted to regions with cheap and reliable power. The availability of the grid, the presence of hydroelectric projects, and now the proximity to renewable energy parks are factors. Aluminium smelters, for instance, are located near bauxite mines but also require proximity to large power plants (e.g., the Hirakud smelter is powered by the Hirakud Dam).</li>\n`;
c += `<li><strong>Labour</strong> &mdash; The availability of skilled and unskilled labour at competitive wages is critical. Labour-intensive industries (textiles, garments, electronics assembly, food processing) tend to locate in regions with high population density and surplus labour. Industrial clusters often develop a 'skill ecosystem' that attracts further industries &mdash; for example, the skilled textile labour of Maharashtra's Solapur district or the IT talent pool of Bengaluru.</li>\n`;
c += `<li><strong>Capital</strong> &mdash; Access to finance, venture capital, and banking infrastructure influences the location of industries, particularly capital-intensive and high-technology industries. Financial hubs like Mumbai (the BSE, NSE, RBI, and major banks) attract corporate headquarters and financial services.</li>\n`;
c += `<li><strong>Market</strong> &mdash; The proximity to consumers reduces transport costs and allows faster response to changing demand. Consumer goods industries (food processing, beverages, packaged goods, furniture) are <strong>market-oriented</strong>. Large urban agglomerations (Delhi-NCR, Mumbai, Bengaluru, Chennai, Kolkata) are both large markets themselves and hubs from which distribution networks radiate.</li>\n`;
c += `<li><strong>Transport</strong> &mdash; The availability of efficient, low-cost transport infrastructure (roads, railways, ports, airports) is a critical factor for industries that require both input and output movement. The 'transport cost' is a major determinant in Weber's theory. The Golden Quadrilateral and the Dedicated Freight Corridors are transforming industrial location in India by reducing transport times and costs.</li>\n`;
c += `<li><strong>Government Policies</strong> &mdash; Tax incentives, subsidies, industrial development zones (SEZs, NIMZs), and regulatory frameworks significantly shape industrial location. The <strong>Industrial Policy Resolution 1956</strong> (the 'commanding heights' of the state), the <strong>New Industrial Policy 1991</strong> (liberalisation, delicensing, FDI), and the <strong>Make in India</strong> initiative (2014) have all fundamentally influenced where and how industries develop.</li>\n`;
c += `<li><strong>Agglomeration Economies</strong> &mdash; The clustering of related industries in a region creates economies of scale and scope &mdash; shared infrastructure, labour pooling, knowledge spillovers, and input-output linkages. This is why industrial clusters persist even when the original locational advantages have disappeared. The Mumbai textile mills gave rise to the diamond cutting industry (the Surat diamond cluster); the Bengaluru IT cluster attracted tens of thousands of ancillary service providers.</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>Theories of Industrial Location</strong> &mdash; <span class="highlight">Weber's Theory of Industrial Location</span> (1909) is the classical model. Weber proposed that industries locate where the total transport cost (of raw materials and finished goods) and labour cost are minimised, subject to the 'agglomeration force' that pulls industries together. He introduced the concept of the 'locational triangle' &mdash; the optimum point between raw material sources and the market. <strong>Losch's Theory</strong> (1944) refined this by emphasising the demand side &mdash; industries locate where total revenue (from serving a market area) exceeds total cost. Losch introduced the concept of 'market areas' shaped like hexagons (the optimal shape to minimise competition and maximise market coverage). These theories, while formulated for early 20th century Germany, provide the conceptual vocabulary for understanding Indian industrial geography &mdash; the steel plants are 'raw material oriented' (Weber), while the IT hub of Bengaluru is 'market and agglomeration oriented' (Losch).</p>\n\n`;

c += `<div class="tip-box"><div class="tip-title">UPSC Focus: Industrial Location</div><div class="tip-text">The 'Iron and Steel' location question is the most frequently asked industrial geography question in UPSC Mains. Know the raw material linkages for each of the 5 SAIL plants (Bhilai, Rourkela, Durgapur, Bokaro, Burnpur) and the private plants (Jamshedpur, Vijayanagar, Vizag). Also understand why the Chhota Nagpur Plateau became 'India's Ruhr' &mdash; the coexistence of iron ore, coal, limestone, manganese, and the Damodar Valley power grid. Weber's theory explains this as the 'minimum transport cost' point. For the recent trend, note the shift towards coastal locations for steel plants (Vizag, Paradip, Krishnapatnam) &mdash; these are 'port-oriented' using imported coal and exporting steel, reflecting the globalisation of the industry.</div></div>\n\n`;

c += `<h3>Major Industrial Regions</h3>\n\n`;
c += `<p>India has several major industrial regions, each with a distinct specialisation based on historical, locational, and policy factors. These regions account for over 70% of India's industrial output and are the geographic nodes of the Indian economy.</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>Mumbai-Pune Industrial Region</strong> &mdash; The <span class="highlight">largest and most diversified industrial region in India</span>. Historical core: the cotton textile industry (the 'Manchester of India'), which grew from the 1850s with the opening of the Mumbai-Ahmedabad railway line and the cotton supply from the Deccan. Today, it encompasses automobiles (Pune: Tata Motors, Bajaj Auto, Mercedes-Benz), IT (the Hinjewadi IT Park, the 'Pune IT cluster'), chemicals, pharmaceuticals, and financial services (the Mumbai headquarters of the RBI, SEBI, NSE, BSE, and major banks). The region benefits from the Mumbai port (the largest container port), the Chhatrapati Shivaji Maharaj International Airport, and the Western Railway corridor.</li>\n`;
c += `<li><strong>Bengaluru Industrial Region</strong> &mdash; The <span class="highlight">'Silicon Valley of India'</span>, home to over 2,500 IT companies including Infosys, Wipro, TCS (largest IT campus in India), and all major MNC tech firms (Google, Microsoft, Amazon, Apple). The IT industry was catalysed by the STPI (Software Technology Parks of India) scheme of 1991, the availability of skilled engineering graduates (from IISc, IIT-M, and the numerous engineering colleges of Karnataka), and the early-mover advantage of Infosys (1981) and Wipro's entry into IT (1980). The region also has a strong manufacturing base: aerospace (HAL, the 'birthplace of Indian aviation'), defence (Bharat Electronics, BEL), machine tools (HMT, Kirloskar), biotechnology (Biocon, the largest biopharma company in Asia), and electrical equipment (BHEL).</li>\n`;
c += `<li><strong>Ahmedabad-Vadodara Industrial Region (Gujarat)</strong> &mdash; The <span class="highlight">'textile hub of India'</span> (the 'Manchester of the East'), with a specialisation in cotton textiles (the largest cotton textile centre after Mumbai), synthetic textiles (Surat is the 'Synthetic Silk City' of India), petrochemicals (the Gujarat Refinery, Reliance's Jamnagar Refinery &mdash; the largest in the world, the Gujarat Chemical Port), pharmaceuticals, engineering, and auto components. The region benefits from the longest coastline in India (1,600 km), 5 major ports (Kandla, Mundra, Pipavav, Bhavnagar, Porbandar), and the Delhi-Mumbai Industrial Corridor (DMIC) passing through it.</li>\n`;
c += `<li><strong>Delhi-NCR Industrial Region</strong> &mdash; The <span class="highlight">largest consumer market in India</span> (the Delhi-NCR population of 50 million). The industrial structure is diversified: manufacturing (Gurugram: Maruti Suzuki, the largest car manufacturer in India; Faridabad: tractor and auto parts; Ghaziabad: engineering; Noida: electronics and IT), IT (Gurugram and Noida IT parks), media and entertainment (Noida Film City), and services (the central government, corporate HQs, retail). The region's growth has been powered by the NH-8 (now the Delhi-Mumbai Expressway) corridor, the Indira Gandhi International Airport, and the Delhi Metro's connectivity.</li>\n`;
c += `<li><strong>Kolkata-Haldia Industrial Region</strong> &mdash; The <span class="highlight">'jute hub of India'</span>, with the Hooghly River belt hosting 80% of India's jute mills (the first jute mill was set up at Rishra in 1855). The traditional industries (jute, tea, paper, leather) have been supplemented by modern industries: petrochemicals (Haldia Petrochemicals), steel (the Haldia steel plant of JSW), fertilisers, and IT (the Salt Lake Sector-V IT hub, Kolkata's 'IT corridor'). The region is served by the Kolkata Port (the oldest, dating to 1870), the Haldia Dock complex, and the Netaji Subhas Chandra Bose International Airport.</li>\n`;
c += `<li><strong>Chennai-Bengaluru Industrial Corridor</strong> &mdash; This is the <span class="highlight">fastest-growing industrial corridor in South India</span>, linking the two major metropolitan economies. Chennai is the 'Detroit of India' (the largest automobile hub, with Hyundai, Ford, Renault-Nissan, BMW, Daimler, and Ashok Leyland all headquartered there), with a strong auto ancillaries cluster (over 1,500 auto component manufacturers in the Chennai-Bengaluru-Chittoor region). The corridor also includes the Sriperumbudur industrial park (focus on electronics and telecom equipment, Foxconn, Nokia, Samsung), the Ennore and Krishnapatnam ports, and the expanding Chennai airport.</li>\n`;
c += `<li><strong>Chhota Nagpur Industrial Belt</strong> &mdash; The <span class="highlight">'Ruhr of India'</span>, the mineral heartland of the country. This region, spanning eastern Jharkhand, northern Chhattisgarh, and western West Bengal, contains the richest concentration of minerals in India: iron ore (Singhbhum, Goa belt), coal (Damodar Valley), manganese, limestone, copper, and mica. The region hosts 4 of India's 5 integrated SAIL steel plants (Bhilai, Rourkela, Durgapur, Bokaro), the TISCO plant at Jamshedpur, and numerous power plants (coal-fired and hydro). The <strong>Damodar Valley Corporation (DVC)</strong>, modelled on the Tennessee Valley Authority (TVA), was set up in 1948 to manage the integrated development of the region &mdash; power generation, flood control, irrigation, and industrial water supply.</li>\n`;
c += `<li><strong>Madurai-Coimbatore-Bengaluru Axis</strong> &mdash; A crescent of industrial development across Tamil Nadu, Karnataka, and Kerala, specialising in textiles (Coimbatore: the 'Manchester of South India', the largest cotton textile centre in South India), engineering (Coimbatore: pump sets, wet grinders, foundries), IT (Bengaluru, Coimbatore, Kochi), and food processing (the fruit and vegetable belts of Tamil Nadu and Karnataka).</li>\n`;
c += `<li><strong>Tiruppur (Tamil Nadu)</strong> &mdash; The <span class="highlight">'Knitting City of India'</span>, the largest knitwear cluster in South Asia, producing 60% of India's knitwear exports (about $5 billion/yr). The region has a specialised ecosystem of 7,000+ small and medium units engaged in knitting, dyeing, printing, and garmenting, with a labour force of 600,000. The success of Tiruppur is a classic example of agglomeration economies and flexible specialisation in the Indian context.</li>\n`;
c += `</ul>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 7 (part 1) written. Total: ' + c.length + ' chars');
