const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

c += `<h4>Iron and Steel Industry</h4>\n\n`;
c += `<p>The iron and steel industry is the <span class="highlight">foundation of the modern industrial economy</span>. India is the <strong>2nd largest producer of steel in the world</strong> (after China), with a production of about <strong>120 million tonnes</strong> (crude steel) in 2023-24. The industry is valued at $100 billion and directly employs 2 million workers. India's steel industry is characterised by a dual structure: the <strong>integrated steel plants</strong> (which produce steel from raw materials &mdash; iron ore, coal, limestone &mdash; using the blast furnace-basic oxygen furnace route) and the <strong>secondary steel sector</strong> (electric arc/mini-blast furnaces using scrap/DRI). The integrated plants account for 45% of production, while the secondary sector accounts for 55%.</p>\n\n`;

c += `<p><strong>Integrated Steel Plants (ISPs)</strong> &mdash; There are 5 major integrated steel plants in the public sector (under SAIL &mdash; Steel Authority of India Limited) and several in the private sector:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Bhilai Steel Plant (Chhattisgarh)</strong> &mdash; The <span class="highlight">largest and most profitable SAIL plant</span> (4.6 mt/yr capacity). Established in 1959 with Soviet collaboration. Located on the Mumbai-Howrah railway line. Raw materials come from the Dalli-Rajhara iron ore mines (80 km), the Bhilai limestone mines, and coal from the Korba and Jharia fields. It is the sole producer of <strong>rails</strong> for the Indian Railways (1.5 mt/yr of world-class rails, exported to 20 countries).</li>\n`;
c += `<li><strong>Rourkela Steel Plant (Odisha)</strong> &mdash; The <span class="highlight">first public sector steel plant in India</span> (established 1959 with German collaboration). Capacity 4.5 mt/yr. Located near the power advantage of the Hirakud Dam and the iron ore of Sundergarh (Badampahar mines). Specialises in <strong>plate and pipe products</strong> (the only SAIL plant producing electrical steel sheets).</li>\n`;
c += `<li><strong>Durgapur Steel Plant (West Bengal)</strong> &mdash; Established 1959 with British collaboration. Capacity 2.2 mt/yr. Raw materials from the Bolani iron ore mines (Odisha) and coal from the Raniganj field.</li>\n`;
c += `<li><strong>Bokaro Steel Plant (Jharkhand)</strong> &mdash; The <span class="highlight">largest integrated steel plant in the public sector in Asia</span> at its establishment (1972, with Soviet collaboration). Capacity 4.5 mt/yr, expansion to 5.8 mt/yr under way. Located on the Kolkata-Delhi railway line, close to the Jharia coalfields and the Kiriburu iron ore mines (220 km).</li>\n`;
c += `<li><strong>Burnpur (West Bengal)</strong> &mdash; The IISCO (Indian Iron and Steel Company) plant, taken over by SAIL in 2006. Capacity 2.5 mt/yr. The oldest steel plant in India (started in 1918), now modernised with the 'Blast Furnace No. 5' (the largest in India, 7.2 m hearth diameter).</li>\n`;
c += `<li><strong>TISCO at Jamshedpur (Jharkhand)</strong> &mdash; The <span class="highlight">oldest and most efficient steel plant in India</span> (established 1907 by Jamsetji Tata, production started 1912). The plant is the flagship of the Tata Group's steel division (now Tata Steel). Capacity 11 mt/yr (the largest single-location steel plant in India). The location was chosen by Sir Dorabji Tata for its proximity to iron ore (Noamundi, 80 km), coal (Jharia, 100 km), limestone (Purnapani), manganese, and water (the Subarnarekha and Kharkai rivers). Jamshedpur is the only industrial city in India that is entirely managed by a private company (Tata Steel's Town Division).</li>\n`;
c += `<li><strong>JSW Vijayanagar (Karnataka)</strong> &mdash; The <span class="highlight">largest private sector steel plant in India</span> (capacity 12 mt/yr, expansion to 18 mt/yr under way), located in Bellary district, close to the iron ore mines of Bellary-Hospet. JSW also has plants at Dolvi (Maharashtra) and Salem (Tamil Nadu).</li>\n`;
c += `<li><strong>Vizag Steel (Andhra Pradesh)</strong> &mdash; The <span class="highlight">first coastal steel plant in India</span> (established 1982, the only shore-based integrated steel plant). Capacity 6.3 mt/yr. It uses imported coal (from Australia/Indonesia via the Vizag port) and domestic iron ore from the Bailadila mines (via the Vizag-Bailadila railway line). The Vizag Steel Plant is unique for being the first plant to use 100% continuous casting technology.</li>\n`;
c += `<li><strong>Salem Steel (Tamil Nadu)</strong> &mdash; A SAIL subsidiary specialising in <strong>stainless steel</strong> (1 mt/yr capacity, the largest stainless steel plant in India).</li>\n`;
c += `<li><strong>Bhadravati (Karnataka)</strong> &mdash; The <strong>Visvesvaraya Iron and Steel Plant</strong> (established 1923 by Sir M. Visvesvaraya as a ferrosilicon and steel plant), now under SAIL. It was the first plant in India to use the electric arc furnace route. Specialises in alloy and special steels.</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>Steel Policy and Performance</strong> &mdash; The <strong>National Steel Policy 2017</strong> targets <strong>300 million tonnes of crude steel production by 2030</strong> (from 120 mt in 2023, requiring a tripling of capacity). The policy emphasises the increase in per capita steel consumption from the current 75 kg (the global average is 220 kg, China's is 600 kg) to 160 kg by 2030. The policy also promotes the use of <strong>scrap-based steelmaking</strong> (the Steel Scrap Recycling Policy 2019 mandates recycling of 6 million tonnes/yr of scrap from ELVs/end-of-life vehicles) and the reduction of coking coal imports (currently 50 mt/yr, the largest cost for the industry). The 'Make in India' initiative has attracted $15 billion in FDI into the steel sector since 2014. India's steel exports (about 10 mt/yr) face anti-dumping duties in the US, EU, and Vietnam, while cheap steel imports from China (which exports 100 mt/yr of surplus capacity) threaten the domestic industry &mdash; leading to the imposition of anti-dumping duties and the quality control order (QCO) for 145 steel products from 2024.</p>\n\n`;

c += `<h4>Textile Industry</h4>\n\n`;
c += `<p>The textile industry is the <span class="highlight">oldest industry in India</span> and the <strong>second largest employer after agriculture</strong> (45 million workers directly, 100 million indirect). The sector is worth $150 billion (of which exports are $35 billion) and contributes 2% to the GDP. The industry is unique for its full value-chain presence: from natural fibre production (cotton, jute, silk, wool) to synthetic fibres (polyester, nylon, acrylic) to yarn, fabric, garments, and home textiles.</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>Cotton Textiles</strong> &mdash; The <span class="highlight">core of the Indian textile industry</span>, accounting for 40% of textile output. India is the <strong>largest producer of cotton in the world</strong> (about 35 million bales/yr, 170 kg each, mainly from Gujarat, Maharashtra, Telangana). The cotton textile industry is concentrated in the <strong>Mumbai-Ahmedabad belt</strong> (the 'Lancashire of the East'), the cotton-growing regions of Maharashtra and Gujarat. Spinning is highly capital-intensive (260 mills, 50 million spindles), while weaving is highly decentralised (4 million handlooms, 250,000 powerlooms, 500,000 shuttleless looms). The industry faces structural challenges: productivity is 40% of the Chinese level (the average spindle speed is 10,000 rpm in India vs 15,000 rpm in China), power costs are 2x higher than in Vietnam, and the Free Trade Agreements (FTAs) signed by Vietnam and Bangladesh with the EU provide them tariff-free access for garment exports while India pays 9-12% duties.</li>\n`;
c += `<li><strong>Synthetic/Man-Made Textiles</strong> &mdash; India is the <strong>2nd largest producer of polyester in the world</strong> (after China). <strong>Surat</strong> in Gujarat is the <span class="highlight">'Synthetic Silk City of India'</span>, producing 70% of the country's synthetic fabric. The city has a unique ecosystem of 500,000+ powerlooms, 5,000 dyeing and printing units, and the Surat Diamond industry's integrative logistics networks. The share of synthetics in India's textile consumption has risen from 30% to 45% over the past decade, driven by affordability and the shift towards sportswear and athleisure.</li>\n`;
c += `<li><strong>Jute Textiles</strong> &mdash; India is the <span class="highlight">largest producer of jute in the world</span> (1.5 million tonnes/yr, grown mainly in West Bengal, Assam, Bihar, and Odisha). The jute industry is concentrated in the <strong>Hooghly River belt</strong> of West Bengal, with about 80 mills mostly around Kolkata, Bhadreswar, and Kamarhati. Jute (the 'Golden Fibre') is valued for its biodegradability and is used in packaging (gunny bags for grain and fertiliser, 80% of consumption), carpet backing, and geo-textiles. The <strong>Jute Packaging Materials (JPM) Act 1987</strong> mandates the use of jute packaging for foodgrains and sugar, protecting the industry, though the share of jute has declined with the shift to synthetic packaging.</li>\n`;
c += `<li><strong>Woollen Textiles</strong> &mdash; The woollen industry is concentrated in <strong>Punjab</strong> (Ludhiana, the 'Manchester of India' for woollens &mdash; the largest producer of woollen knitwear, shawls, and blankets), <strong>Haryana</strong> (Panipat, the largest centre for woollen/synthetic carpets), <strong>Rajasthan</strong> (Bikaner, Jaipur for carpets and shawls), and <strong>Uttar Pradesh</strong> (Mirzapur-Bhadohi for hand-knotted carpets, the 'Carpet City of India', exporting 70% of India's hand-knotted carpets).</li>\n`;
c += `<li><strong>Silk Textiles</strong> &mdash; India is the <span class="highlight">2nd largest producer of silk in the world</span> (after China), producing 35,000 tonnes/yr. The four types of silk produced are <strong>Mulberry silk</strong> (Karnataka &mdash; Mysore, the largest producer, 45% of output; Tamil Nadu; Andhra Pradesh), <strong>Tussar silk</strong> (Jharkhand, Chhattisgarh, Odisha &mdash; the 'wild silk' produced by the Antheraea mylitta silkworm), <strong>Eri silk</strong> (Assam, Meghalaya &mdash; the 'peace silk', produced without killing the pupa), and <strong>Muga silk</strong> (Assam &mdash; the 'golden silk', exclusive to Assam, the only naturally golden-coloured silk in the world, with a GI tag). The famous silk varieties by location: <strong>Banaras silk</strong> (Varanasi, the most famous silk in India, the Banarasi brocade with gold and silver zari), <strong>Mysore silk</strong> (the 'Queen of Silks', known for its purity and softness), <strong>Bhagalpur silk</strong> (Bihar, known for Tussar silk of high quality), <strong>Kanchipuram silk</strong> (Tamil Nadu, the heaviest silk in India, with a zari border of silver and gold).</li>\n`;
c += `</ul>\n\n`;

c += `<h4>Sugar Industry</h4>\n\n`;
c += `<p>India is the <span class="highlight">2nd largest producer of sugar in the world</span> (after Brazil), producing about <strong>35 million tonnes</strong> annually (about 20% of global production). The sugar industry is the <strong>second largest agro-processing industry in India</strong> after cotton textiles, with 700+ sugar mills (300 in the cooperative sector, 250 in the private sector, 150 in the public sector). The industry is dominated by the cooperative model in Maharashtra (the Vasantdada Sugar Institute, the 'Harvard of Sugar') and the private sector in Uttar Pradesh.</p>\n\n`;

c += `<p>The sugar industry is <span class="highlight">seasonal</span> &mdash; the crushing season lasts only 4-5 months (November to March), after which the mills remain closed (unlike in Brazil where the crushing season is 8-9 months). This seasonality is a major structural weakness, leading to high fixed costs and low capacity utilisation (50-60%). The industry is <strong>raw-material-oriented</strong> &mdash; sugar mills are located close to sugarcane-growing areas because sugarcane is 95% water and loses weight drastically during transport. The 'recovery rate' (the percentage of sugar extracted from cane) varies from 8-12%, with Maharashtra and Tamil Nadu having the highest recovery rates (11.5%) due to tropical climate and better cane varieties, while UP has lower recovery rates (9.5%) due to sub-tropical climate.</p>\n\n`;

c += `<p><strong>Sugar Production by State</strong> &mdash; Uttar Pradesh (the largest producer, 45% of national output, 140 mills in the state &mdash; the highest concentration), Maharashtra (2nd, 25%, but leads in sugar recovery and the cooperative model), Tamil Nadu (3rd, 8%, highest recovery rate), Karnataka (4th, 8%), and Gujarat (5th). The traditional 'gur' and 'khandsari' (unrefined sugar) production is still significant, accounting for about 30% of sugarcane crushed, produced mainly in the decentralised village-level units (kolhus). The by-products of the sugar industry are economically important: <strong>bagasse</strong> (the fibrous residue after crushing) is used as fuel for cogeneration (power generation of 5,000 MW installed capacity) and for manufacturing paper and particleboard; <strong>molasses</strong> (the thick syrup residue) is fermented to produce alcohol, ethanol, and rum; and <strong>press mud</strong> (filter cake) is used as organic fertiliser.</p>\n\n`;

c += `<h4>Automobile Industry</h4>\n\n`;
c += `<p>India is the <span class="highlight">4th largest automobile market in the world</span> (after China, the US, and Japan, surpassing Germany in 2022), with annual production of 25 million vehicles (including 2-wheelers, 4-wheelers, commercial vehicles, and 3-wheelers). The industry contributes 7% to the GDP and employs 35 million people. The <span class="highlight">'Detroit of India'</span> is <strong>Chennai</strong> &mdash; the largest automobile hub with a 35% market share of the national automobile production. The Chennai Auto Cluster (the 300 sq km belt around Chennai-Oragadam-Sriperumbudur) hosts Hyundai (the largest passenger car exporter in India, with the second largest manufacturing plant in the world, 800,000 cars/yr), Ford (exports to 50 countries), Renault-Nissan (1,000 cars/day from the Oragadam plant), Daimler (the Chennai plant is the largest truck manufacturing plant in the world), BMW (the Chennai plant for the Indian market), and Ashok Leyland (the 2nd largest commercial vehicle manufacturer).</p>\n\n`;

c += `<p><strong>Major Players and Locations</strong> &mdash; <strong>Maruti Suzuki</strong> (Gurugram, 54% market share, the largest car manufacturer in India, with the Manesar and Gujarat plants), <strong>Hyundai</strong> (Chennai, the 2nd largest, 15% share, the largest passenger car exporter from India), <strong>Tata Motors</strong> (Pune, Sanand, 13% share, the leading commercial vehicle manufacturer, and the manufacturer of the 'Nano', the 'Nexon' &mdash; the best-selling electric car in India), <strong>Mahindra & Mahindra</strong> (Bengaluru, Nashik, the largest manufacturer of SUVs and tractors in India), <strong>Bajaj Auto</strong> (Pune, the 3rd largest motorcycle manufacturer in the world, the largest 3-wheeler and scooter manufacturer in India), and <strong>Hero MotoCorp</strong> (the largest 2-wheeler manufacturer in the world, based in Delhi, with the Haridwar plant producing 7 million motorcycles/yr).</p>\n\n`;

c += `<h4>IT & ITES Industry</h4>\n\n`;
c += `<p>The Indian IT industry is a <span class="highlight">global powerhouse</span>, contributing <strong>7.5% of India's GDP</strong> with export revenues of <strong>$150 billion</strong> (2023-24). The industry employs 5 million people directly and creates 12 million indirect jobs. The <span class="highlight">'Silicon Valley of India'</span> is <strong>Bengaluru</strong>, which alone accounts for 35% of IT exports, with over 2,500 IT companies in the city. The other major IT hubs are <strong>Hyderabad</strong> (the 'Cyberabad' &mdash; the HITEC City, the second largest IT exporter after Bengaluru, with Google, Microsoft, Amazon, Apple, and Infosys having large campuses), <strong>Chennai</strong> (the 'IT Corridor' along Old Mahabalipuram Road, Tidel Park), <strong>Pune</strong> (the Hinjewadi IT Park), <strong>Delhi-NCR</strong> (Gurugram and Noida), <strong>Mumbai</strong> (the Gigaplex Bandra Kurla Complex), <strong>Kolkata</strong> (Salt Lake Sector-V), and <strong>Ahmedabad</strong> (GIFT City for fintech).</p>\n\n`;

c += `<p>The IT industry is organised through <strong>STPI</strong> (Software Technology Parks of India, the 1991 government scheme that provided tax-free IT infrastructure &mdash; 100% export deduction under Section 10A/10B of the Income Tax Act, reliable power, and high-speed data connectivity) and <strong>SEZs</strong> (Special Economic Zones, the 2005 Act that replaced the STPI tax holiday with a different incentive structure). The industry body is <strong>NASSCOM</strong> (National Association of Software and Service Companies, founded 1988), which has played a critical role in policy advocacy, industry branding, and workforce development. The major firms are <strong>TCS</strong> (the largest IT services company in India and the 3rd largest in the world, market cap $180 billion), <strong>Infosys</strong> (the 2nd largest, the pioneer of the Indian IT model), <strong>Wipro</strong>, <strong>HCL</strong>, and <strong>Tech Mahindra</strong>.</p>\n\n`;

c += `<p><strong>Global Capability Centres (GCCs)</strong> &mdash; India hosts over <strong>1,600 GCCs</strong> (the in-house technology and business process units of global MNCs), the largest number in the world. The GCCs contribute $60 billion in exports (40% of IT exports) and employ 1.8 million people. The growth of GCCs is a response to the 'hybrid work' model and the need for deep-tech talent (AI, cloud, cybersecurity, data science), which the Indian talent ecosystem supplies in abundance. The top GCC hubs are Bengaluru, Hyderabad, the NCR, Chennai, and Mumbai.</p>\n\n`;

c += `<h4>Pharmaceutical Industry</h4>\n\n`;
c += `<p>The Indian pharmaceutical industry is the <span class="highlight">'Pharmacy of the World'</span>, the <strong>3rd largest by volume</strong> (after the US and China) and <strong>14th by value</strong> ($50 billion). India exports $25 billion worth of pharmaceuticals to 200+ countries (40% to the US, 20% to Europe, 15% to Africa, 10% to Asia). The industry is known for its <strong>generics</strong> (the manufacture of off-patent drugs) &mdash; India supplies 20% of the world's generic medicines by volume and 40% of the generic drugs used in the US. India's competitive advantage comes from its low manufacturing costs (40-60% lower than the US), the vast pool of English-speaking chemists and pharmacists, the strong IP regime for processes (the Indian Patents Act 1970 recognised only process patents, not product patents, until the TRIPS amendment of 2005, which allowed the Indian generics industry to flourish by reverse-engineering drugs), and the FDA-approved manufacturing facilities (the highest number of USFDA-approved plants outside the US).</p>\n\n`;

c += `<p><strong>Pharma Hubs</strong> &mdash; <strong>Hyderabad</strong> (the 'Bulk Drug Capital of India', the largest pharma cluster with over 800 companies including Dr Reddy's, Aurobindo, Hetero, Divi's, and the IKP Knowledge Park biotech cluster), <strong>Ahmedabad-Baroda</strong> (the second largest, with Cadila, Torrent, Sun Pharma &mdash; the largest pharma company in India by market cap), <strong>Mumbai</strong> (Glenmark, Cipla, Lupin, and the financial and regulatory headquarters of most major pharma companies), and <strong>Bengaluru</strong> (Biocon &mdash; the largest biopharma company in Asia, and Syngene &mdash; the largest CRO/contract research organisation in India). The <strong>Bulk Drugs</strong> hub is concentrated in <strong>Visakhapatnam</strong> (the JNPC pharma SEZ, the largest bulk drug park in India, with 50+ manufacturers) and <strong>Kakinada</strong> (the Andhra Pradesh MedTech Zone). The industry body is the <strong>Indian Pharmaceutical Alliance (IPA)</strong> (representing the top 24 pharma companies). The <strong>Jan Aushadhi</strong> scheme (Pradhan Mantri Bhartiya Janaushadhi Pariyojana, 2015) provides generic medicines at 50-90% cheaper prices through 10,000+ Jan Aushadhi Kendras, saving consumers Rs 20,000 crore annually.</p>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 7 (part 2) written. Total: ' + c.length + ' chars');
