$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 13: VIJAYANAGARA & BAHMANI ===================== -->
<h2 id="vijayanagara-bahmani">13. Vijayanagara Empire & Bahmani Sultanate (1336-1615)</h2>

<p>The <span class="highlight">Vijayanagara Empire</span> (City of Victory) and the <span class="highlight">Bahmani Sultanate</span> dominated the Deccan for over 200 years, locked in a continuous struggle for supremacy over the Raichur Doab (the fertile region between the Krishna and Tungabhadra rivers). The Vijayanagara Empire was the last great Hindu kingdom of medieval India — a wealthy, cosmopolitan empire that controlled the maritime trade of the southern Indian Ocean. Its capital, Vijayanagara (modern Hampi, Karnataka), was one of the largest and most magnificent cities of the medieval world. The Bahmani Sultanate was the first independent Islamic kingdom in the Deccan, established after a rebellion against Muhammad bin Tughlaq. The rivalry between Vijayanagara and Bahmani, and the eventual fragmentation of Bahmani into 5 successor sultanates (Bijapur, Golconda, Ahmadnagar, Bidar, Berar), shaped the history of the Deccan until the Mughal conquest.</p>

<h3>Vijayanagara Empire (1336-1615)</h3>

<p>The empire was founded by two brothers, <span class="highlight">Harihara I</span> and <span class="highlight">Bukka Raya I</span> (1336-1346), who were ministers of the Kakatiya kingdom (they were captured by Muhammad bin Tughlaq in 1323 during his Kakatiya campaign, converted to Islam, then reconverted to Hinduism under the influence of the sage Vidyaranya). They established the capital at Vijayanagara on the Tungabhadra river. The empire went through four dynasties: the <strong>Sangama</strong> (1336-1485), <strong>Saluva</strong> (1485-1505), <strong>Tuluva</strong> (1505-1570), and <strong>Aravidu</strong> (1570-1615). The greatest rulers were <strong>Deva Raya II</strong> (Sangama) and <strong>Krishnadeva Raya</strong> (Tuluva).</p>

<p><strong>Krishnadeva Raya</strong> (1509-1529) — the greatest Vijayanagara emperor. He conquered the Bahmani sultanates in a series of campaigns (captured the Raichur Doab, defeated Adil Shah of Bijapur), the Gajapati kingdom of Odisha (he married a Gajapati princess), and the Ummattur chiefs of Mysore. He was a great builder — the <strong>Vithala Temple</strong> at Hampi (with its iconic stone chariot, 56 musical pillars), the <strong>Hazarama Temple</strong> (with 1000 sculpted panels), the <strong>Lotus Mahal</strong> (Indo-Islamic architecture), and the <strong>Virupaksha Temple</strong> extension. He was a patron of Telugu and Sanskrit literature — his court had the <strong>Ashtadiggajas</strong> (Eight Great Poets of Telugu): <strong>Tenali Ramakrishna</strong> (the witty court poet, famous for his stories), Allasani Peddana (the 'Father of Telugu poetry' — Manucharitram), Nandi Thimmana (Parijathapaharanam), Madayyagari Mallana (Rajasekhara Charitram), Dhurjati (Kalahasti Mahatmya), Ayyalaraju Ramabhadrudu (Sakala Katha Sara Sangraham), Pingali Surana (Raghavapandaveeyam), and Ramarajabhushanudu (Kavyalankara Sangraham). Krishnadeva Raya himself wrote the <strong>Amuktamalyada</strong> (a Telugu epic on the life of the Tamil Alvar saint Andal — who was born in Srivilliputhur).</p>

<p>The <span class="highlight">city of Vijayanagara</span> was one of the wonders of the medieval world. The Portuguese traveller <strong>Domingo Paes</strong> (c. 1520) described it as 'the best-provided city in the world' — as large as Rome, with magnificent palaces, markets, temples, waterworks, and a population of 500,000. The city was organised into two parts: the 'sacred centre' (around the Virupaksha Temple on the river bank) and the 'royal centre' (the king's palace complex with the audience hall, the Mahanavami Dibba platform, the king's bath, the stables, and the treasury). The water supply was brought by aqueducts and canals from the Tungabhadra river to tanks and cisterns throughout the city. The <strong>Gajashala</strong> (elephant stables) could house 11 elephants. The city was protected by massive granite walls 10-15 feet thick. The <strong>Mahanavami Festival</strong> celebrated by the kings was a spectacular nine-night display of royal power — horsemen, elephants, dancers, fireworks, and the king distributing gifts.</p>

<p><strong>Administration and Economy</strong>: The empire was divided into <strong>mandalams</strong> (provinces), <strong>nadus</strong> (districts), and <strong>gramas</strong> (villages). The king was the supreme authority, aided by a council of ministers including the <strong>mahapradhana</strong> (prime minister) and the <strong>dandanayaka</strong> (commander-in-chief). Provincial governors (<strong>nayakas</strong>) were appointed by the king from the <strong>nayaka</strong> warrior class and were allowed personal armies — this decentralised system was the empire's strength and eventual weakness (the nayakas became independent after the Battle of Talikota). The economy was based on agriculture (extensive tank irrigation systems), the textile industry (the cotton of Vijayanagara was famous — the Portuguese exported cargoes of cloth from the port of Bhatkal), and maritime trade. The main ports were <strong>Goa</strong> (early), <strong>Bhatkal</strong>, <strong>Mangalore</strong>, <strong>Honavar</strong>, <strong>Calicut</strong>, and <strong>Nagapatam</strong>. Exports: spices, pepper, textiles (calico, chintz), rice, iron, sugar, and precious stones. Imports: horses (the most essential import — from Arabia and Persia through the port of Dabhol; Portuguese controlled the horse trade from the mid-16th century), copper, silk, pearls, and damask. The gold <strong>pagoda</strong> (Varaha coin) was the standard gold coin. The empire was wealthy — the king collected 6 million gold pagodas annually as land revenue (1/6th of produce).</p>

<p><strong>Decline</strong>: The empire was destroyed at the <strong>Battle of Talikota</strong> (also called the Battle of Rakkasagi-Tangadi, 23 January 1565). The combined armies of the five Deccan sultanates (Bijapur, Golconda, Ahmadnagar, Bidar, Berar) — who had finally united against Vijayanagara — defeated the Vijayanagara army under <strong>Rama Raya</strong> (Krishnadeva Raya's son-in-law, the de facto ruler). Rama Raya was captured and beheaded. The victorious armies sacked Vijayanagara city for six months — palaces, temples, markets were systematically destroyed (the fire of 1565 destroyed the city). The empire's capital was abandoned and the court moved to <strong>Penukonda</strong> (Andhra) and later <strong>Chandragiri</strong> (Tirupati). The Aravidu dynasty ruled a much-reduced kingdom until 1615, when the kingdom fragmented into the Nayaka kingdoms of Madurai, Tanjore, Gingee, Mysore, and Keladi.</p>

<h3>Bahmani Sultanate (1347-1527)</h3>

<p>The <strong>Bahmani Sultanate</strong> was founded by <strong>Alauddin Bahman Shah</strong> (also known as Hasan Gangu, a general of Muhammad bin Tughlaq who rebelled and established an independent state at Gulbarga, Karnataka, in 1347). The Bahmani sultanate lasted 180 years with 18 sultans. <strong>Mahmud Gawan</strong> (the prime minister under Muhammad Shah III Lashkari, 1463-1482) was the greatest Bahmani minister — he reorganised the administration, reduced the power of the nobles, expanded the territory, and patronised learning (the <strong>Madrasa of Mahmud Gawan</strong> at Bidar — a magnificent Persianate building, one of the finest in India). The Bahmani sultanate declined due to the struggle between the Deccani (old Indian Muslim) and Foreigner (Afghan, Turk, Persian) factions at court — Mahmud Gawan was executed in 1482 on charges of treason concocted by the Deccani faction. After 1490, the sultanate fragmented into <strong>Five Successor Sultanates</strong>:</p>

<div class="table-wrap"><table>
<tr><th>Sultanate</th><th>Founded By</th><th>Capital</th><th>Key Features</th></tr>
<tr><td><strong>Bijapur (Adil Shahi)</strong></td><td>Yusuf Adil Khan (1490)</td><td>Bijapur</td><td>Greatest ruler: Ibrahim Adil Shah II (1580-1627) — patron of art, literature, music; wrote the Kitab-i-Nauras. Famous Gol Gumbaz (tomb of Muhammad Adil Shah — the second largest dome in the world, 44m diameter, 51m high, 'Whispering Gallery'). Bijapur's architecture is the finest of the Deccan style — the Jumma Masjid, the Ibrahim Rauza, the Malik-e-Maidan cannon.</td></tr>
<tr><td><strong>Golconda (Qutb Shahi)</strong></td><td>Quli Qutb Shah (1518)</td><td>Golconda (Hyderabad)</td><td>Greatest ruler: Muhammad Quli Qutb Shah (1580-1612) — founded the city of Hyderabad (1591), built the Charminar (the iconic four-minaret gateway, 56m high, with a mosque on the top floor), the Mecca Masjid, and the Golconda Fort (the most impregnable fort in the Deccan, famous for its acoustic system — a handclap at the Fateh Darwaza could be heard a kilometer away at the Balahisar palace). Golconda was the diamond capital of the world — the Koh-i-Noor, the Hope Diamond, the Orlov, the Darya-i-Noor, and the Regent Diamond were all from the Golconda mines (Kollur, Panna, etc.).</td></tr>
<tr><td><strong>Ahmadnagar (Nizam Shahi)</strong></td><td>Malik Ahmad Nizam Shah I (1490)</td><td>Ahmadnagar</td><td>Greatest ruler: Burhan Nizam Shah I (1508-1553) — patron of learning, established the first printing press in India? Actually the printing press arrived later. Chand Bibi (regent 1595-1600) — the famous heroine who defended Ahmadnagar against the Mughals. Annexed by Shah Jahan in 1633 (the last of the Deccan sultanates to be annexed).</td></tr>
<tr><td><strong>Bidar (Barid Shahi)</strong></td><td>Amir Qasim Barid (1492)</td><td>Bidar</td><td>Smallest of the sultanates; known for the Bahmani architecture (the Madrasa of Mahmud Gawan, the Bidar Fort). Annexed by Bijapur in 1619.</td></tr>
<tr><td><strong>Berar (Imad Shahi)</strong></td><td>Fathullah Imad-ul-Mulk (1490)</td><td>Achalpur/Gawilgarh</td><td>Weakest; annexed by Ahmadnagar in 1574.</td></tr>
</table></div>

<div class="tip-box"><div class="tip-title">UPSCTip: The Battle of Talikota (1565) in context</div><div class="tip-text">The battle was important because: 1) It ended the Vijayanagara Empire — the last major Hindu kingdom. 2) It allowed the Deccan sultanates to remain independent for another century. 3) The sacking of Vijayanagara was one of the great destructions of a city in world history. 4) The Nayaka kingdoms that emerged after the collapse continued Vijayanagara's artistic and administrative traditions in Madurai, Tanjore, Gingee, and Mysore. 5) The battle opened the Deccan to Mughal conquest: by 1687, Aurangzeb had annexed Bijapur and Golconda.</div></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 13 written."
