const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

c += `<h4>Cement Industry</h4>\n\n`;
c += `<p>India is the <span class="highlight">2nd largest producer of cement in the world</span> (after China), with an installed capacity of <strong>600 million tonnes</strong> and production of about <strong>400 million tonnes/yr</strong>. The industry is critical for infrastructure development (the housing sector consumes 55% of cement, infrastructure 25%, commercial construction 15%, and the industrial sector 5%). The major cement-producing states are <strong>Madhya Pradesh</strong> (the largest, with 40+ plants in the Satna-Rewa-Katni belt, the 'Cement Belt of India'), <strong>Rajasthan</strong> (the 2nd largest, with the Nimbahera-Chittorgarh belt), <strong>Andhra Pradesh</strong> (the 3rd largest, with the Krishna-Telangana belt), <strong>Tamil Nadu</strong> (the 4th largest), <strong>Gujarat</strong> (the 5th largest), and <strong>Karnataka</strong>.</p>\n\n`;

c += `<p>The industry is dominated by 3 large groups: <strong>Ultratech Cement</strong> (part of the Aditya Birla Group, the largest cement company in India, with a capacity of 150 mt/yr, the 3rd largest in the world outside China), <strong>ACC</strong> (the oldest cement company in India, established in 1936, now part of the Adani Group, with a capacity of 80 mt/yr), and <strong>Ambuja Cements</strong> (now also part of the Adani Group, capacity 70 mt/yr). The cement industry is <span class="highlight">energy-intensive</span> (power and fuel account for 40% of the cost) and heavily regulated for emissions (the cement sector contributes 8% of India's CO2 emissions), with the government mandating the use of 10% blended cement (fly ash-based or slag-based) to reduce the carbon footprint.</p>\n\n`;

c += `<h4>Food Processing Industry</h4>\n\n`;
c += `<p>The food processing industry is the <span class="highlight">'Sunrise Sector'</span> of the Indian economy, identified by the government as a key driver of manufacturing growth and employment. The sector is valued at $500 billion (food retail market $900 billion), growing at 10-12% annually. India is the world's largest producer of milk (the Operation Flood legacy), the 2nd largest producer of fruits and vegetables, and the 3rd largest producer of fish. Despite this, the processing level is low: only 10% of agricultural produce is processed (compared to 60% in the US, 70% in the EU, and 30% in Thailand), resulting in massive post-harvest losses of Rs 1.5 lakh crore ($20 billion) annually.</p>\n\n`;

c += `<p>The <strong>Pradhan Mantri Kisan Sampada Yojana</strong> (PMKSY, launched 2017) is the flagship scheme for the sector, with a network of <strong>42 Mega Food Parks</strong> (each park serves as a cluster of food processing units with common infrastructure &mdash; cold storage, warehousing, testing labs, effluent treatment &mdash; and connects producers to processors to markets). Other schemes include the <strong>Production Linked Incentive (PLI) for Food Processing</strong> (Rs 10,900 crore for promoting ready-to-eat, ready-to-cook, and food ingredients), the <strong>Operation Greens</strong> (for stabilising the prices of onions, potatoes, and tomatoes through the value chain), and the <strong>Kisan Rail</strong> (for the rapid transport of perishable agricultural produce). The major food processing clusters are the <strong>milk processing</strong> belt (Gujarat, the 'White Revolution' hub of Anand, the Amul cooperative model; Punjab, Haryana, Uttar Pradesh), the <strong>fruit and vegetable processing</strong> belt (Maharashtra &mdash; Nashik for grapes, Ratnagiri for mangoes; Karnataka &mdash; Chikkaballapur for tomatoes; Jammu and Kashmir &mdash; the apple belt; Himachal Pradesh &mdash; the apple and stone fruit belt), and the <strong>fish processing</strong> belt (Andhra Pradesh &mdash; the largest seafood producer, especially shrimp; Kerala &mdash; the 'Marine Hub' of Cochin; Gujarat &mdash; the largest fish producer by volume; West Bengal &mdash; the inland fisheries hub).</p>\n\n`;

c += `<h4>MSME (Micro, Small, and Medium Enterprises)</h4>\n\n`;
c += `<p>The MSME sector is the <span class="highlight">'Backbone of the Indian Industry'</span>, contributing <strong>30% of India's GDP, 40% of exports, and 45% of manufacturing output</strong>. There are 6.3 crore MSMEs in India, employing 11 crore workers (the second largest employer after agriculture). The sector is classified under the <strong>MSMED Act 2006 as amended in 2020</strong>: Micro (investment up to Rs 1 crore, turnover up to Rs 5 crore), Small (investment up to Rs 10 crore, turnover up to Rs 50 crore), and Medium (investment up to Rs 50 crore, turnover up to Rs 250 crore).</p>\n\n`;

c += `<p>The MSME sector faces structural challenges: access to formal credit (only 16% of MSMEs have formal credit access; 65% rely on the informal sector), delayed payments (the small and medium enterprises are particularly vulnerable to cash flow disruptions from delayed payments by large corporations), technology obsolescence, and regulatory compliance burdens. The <strong>Aatmanirbhar Bharat Package</strong> (2020) announced a Rs 3 lakh crore collateral-free automatic loan scheme (the Emergency Credit Line Guarantee Scheme/ECLGS, since extended and expanded), a Rs 20,000 crore subordinate debt facility for stressed MSMEs, a Rs 50,000 crore equity infusion (the Fund of Funds for MSMEs), and the revision of the MSME definition to include higher turnover limits (to enable more enterprises to benefit from MSME-specific schemes without the fear of 'graduating' out of benefits). The <strong>PM Vishwakarma Yojana</strong> (2023) targets traditional artisans and craftspersons (carpenters, blacksmiths, potters, weavers, etc.) for skill development, concessional credit, and digital enablement.</p>\n\n`;

c += `<div class="table-wrap"><table>\n`;
c += `<tr><th>Industrial Region</th><th>Core Location</th><th>Key Industries/Specialisation</th><th>Locational Advantage</th></tr>\n`;
c += `<tr><td>Mumbai-Pune</td><td>Maharashtra</td><td>Textiles, IT, Automobiles, Finance, Pharma</td><td>Port, capital, skilled labour, market</td></tr>\n`;
c += `<tr><td>Bengaluru</td><td>Karnataka</td><td>IT, Aerospace, Biotech, R&D, Defence</td><td>STPI early mover, IISc/IIM talent pool, climate</td></tr>\n`;
c += `<tr><td>Ahmedabad-Vadodara</td><td>Gujarat</td><td>Textiles (cotton & synthetic), Petrochemicals, Pharma</td><td>Cotton belt, ports, DMIC corridor, entrepreneurial culture</td></tr>\n`;
c += `<tr><td>Delhi-NCR</td><td>Delhi, Haryana, UP</td><td>Auto (Maruti), IT, Media, Consumer goods, Services</td><td>Largest market, NH-48 corridor, IGI Airport, skilled labour</td></tr>\n`;
c += `<tr><td>Kolkata-Haldia</td><td>West Bengal</td><td>Jute, Tea, Petrochemicals, IT, Leather, Paper</td><td>Hooghly river, Kolkata port, jute belt, tea auction centre</td></tr>\n`;
c += `<tr><td>Chhota Nagpur</td><td>Jharkhand, Chhattisgarh</td><td>Iron & Steel, Power, Mining, Heavy Engineering</td><td>Mineral belt (iron ore, coal, limestone), DVC power</td></tr>\n`;
c += `<tr><td>Chennai-Bengaluru</td><td>Tamil Nadu, Karnataka</td><td>Auto (Detroit of India), IT, Electronics, Textiles</td><td>Chennai port, skilled labour, strong auto ancillaries cluster</td></tr>\n`;
c += `<tr><td>Tiruppur</td><td>Tamil Nadu</td><td>Knitwear, Garments (60% of India's knitwear exports)</td><td>Agglomeration economies, skilled labour, flexible specialisation</td></tr>\n`;
c += `<tr><td>Coimbatore</td><td>Tamil Nadu</td><td>Textiles (Manchester of South), Pumps, Engineering</td><td>Hydroelectric from Pykara, skilled cotton labour</td></tr>\n`;
c += `<tr><td>Hyderabad</td><td>Telangana</td><td>Pharma (Bulk Drug Capital), IT (Cyberabad), Biotech</td><td>HITEC City, pharma ecosystem, knowledge capital</td></tr>\n`;
c += `</table></div>\n\n`;

// ==================== SECTION 8 ====================
c += `<!-- ===================== SECTION 8: TRANSPORT AND COMMUNICATION ===================== -->\n`;
c += `<h2 id="transport">8. Transport & Communication</h2>\n\n`;

c += `<h3>Road Transport</h3>\n\n`;
c += `<p>Roads are the <span class="highlight">dominant mode of transport in India</span>, carrying 90% of passenger traffic and 65% of freight traffic. India has the <strong>2nd largest road network in the world</strong> (after the US), with a total length of <strong>62 lakh kilometres</strong> (about 6.2 million km). The road network density is about <strong>1.9 km per sq km</strong>, comparable to that of the US and higher than that of China (0.5 km/sq km). However, the quality of roads varies enormously &mdash; from world-class expressways to unpaved rural tracks.</p>\n\n`;

c += `<p>The road network is classified into <span class="highlight">six categories</span>:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>National Highways (NH)</strong> &mdash; The arterial network of 1.5 lakh km (about 2% of the road network by length), carrying <strong>40% of the total road traffic</strong>. The NHs are the responsibility of the central government and are managed by the <strong>National Highways Authority of India (NHAI)</strong>, established in 1988. NHAI is responsible for the development, maintenance, and operation of NHs. The funding model has shifted from budgetary allocation to a mix of toll-based financing (the 'user pay' principle), the Central Road Fund (a cess of Rs 2-0.50 per litre on petrol/diesel), the National Highways Inter-ministerial Committee (NHIC) for project approvals, and the <strong>InvIT</strong> (Infrastructure Investment Trust, 2023) for asset monetisation.</li>\n`;
c += `<li><strong>State Highways (SH)</strong> &mdash; The secondary road network (1.5 lakh km) connecting district headquarters and major towns within a state, built and maintained by the state Public Works Departments.</li>\n`;
c += `<li><strong>District Roads</strong> &mdash; Roads connecting taluka headquarters and major rural settlements to the state highway network (about 5 lakh km).</li>\n`;
c += `<li><strong>Rural Roads</strong> &mdash; The largest category by length (35+ lakh km), connecting villages to the road network. The <strong>Pradhan Mantri Gram Sadak Yojana (PMGSY)</strong>, launched in 2000, has built 7 lakh km of rural roads connecting 1.8 lakh villages (all habitations of 500+ in the plains and 250+ in the hills), at a cost of Rs 4 lakh crore. PMGSY has been credited with improving school enrolment (by 12%), increasing agricultural market access (by 25%), and promoting rural non-farm employment.</li>\n`;
c += `<li><strong>Expressways</strong> &mdash; The highest category of roads, with controlled access (no at-grade crossings), designed for high-speed traffic (100-120 km/hr). India has about 5,000 km of expressways, including the <strong>Delhi-Meerut Expressway</strong> (96 km, India's widest at 14 lanes), the <strong>Delhi-Mumbai Expressway</strong> (1,350 km, under construction, the longest expressway in India, reducing the Delhi-Mumbai travel time from 26 to 12 hours), the <strong>Purvanchal Expressway</strong> (341 km, UP), the <strong>Agra-Lucknow Expressway</strong> (302 km, the longest at the time of construction in 2017), the <strong>Dwarka Expressway</strong> (27 km, the first elevated expressway in India), and the <strong>Mumbai-Nagpur Samruddhi Mahamarg</strong> (701 km, the 'Birthplace of the Indian Expressway network' for Maharashtra's economic corridor).</li>\n`;
c += `<li><strong>Border Roads</strong> &mdash; Roads along the international borders (the 'Border Roads'), built and maintained by the <strong>Border Roads Organisation (BRO)</strong>, established in 1960. The BRO has built over 50,000 km of strategic roads in the Himalayan and desert border regions, including the <strong>Darbuk-Shyok-Daulat Beg Oldie (DS-DBO) Road</strong> in Ladakh (the highest motorable road in the world at 5,300 m, connecting the Karakoram sector).</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>Major Highway Projects</strong>:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>The Golden Quadrilateral (GQ)</strong> &mdash; The <span class="highlight">largest highway project in India</span> (launched in 2001 under the Vajpayee government), connecting the four metropolitan cities of Delhi-Mumbai-Chennai-Kolkata, covering 5,846 km. The GQ was completed in 2012 and reduced travel time between the metros by 40-50%. It is the backbone of India's logistics network, carrying about 25% of the country's freight traffic.</li>\n`;
c += `<li><strong>The North-South and East-West Corridor (NS-EW)</strong> &mdash; These two corridors connect Srinagar (north) to Kanyakumari (south) (4,076 km, the North-South Corridor) and Silchar (east) to Porbandar (west) (3,220 km, the East-West Corridor). The intersection of the two corridors is at Jhansi (Uttar Pradesh). The project was part of the <strong>National Highways Development Project (NHDP)</strong> (Phase I-VII), which aimed to upgrade 50,000 km of National Highways to 4-lane standards.</li>\n`;
c += `<li><strong>Bharatmala Pariyojana</strong> &mdash; The <span class="highlight">largest highway development programme in India</span> (launched 2017, Rs 10.6 lakh crore, covering 34,800 km), Phase I of which covers 26,000 km. The project focuses on: (a) the development of 50+ Economic Corridors (connecting major ports, production centres, and consumption centres), (b) the improvement of National Corridors (the GQ and NS-EW, upgrading to 6 lanes), (c) the development of Border Roads and International Connectivity roads (to Nepal, Bhutan, Bangladesh, Myanmar), (d) the improvement of Coastal Roads and Port Connectivity, and (e) the elimination of bottlenecks (bypasses for 120 towns). Bharatmala uses the <strong>Hybrid Annuity Model (HAM)</strong> for project implementation (the government pays 40% of the project cost during construction and annuities for 15 years, while the private developer arranges 60%, reducing the traffic risk for the private sector).</li>\n`;
c += `<li><strong>International Connectivity</strong> &mdash; The <span class="highlight">India-Myanmar-Thailand Trilateral Highway</span> (IMT-TH, 1,360 km from Moreh in Manipur to Mae Sot in Thailand, via Bagan and Mandalay in Myanmar, building the 'Sea of Japan' corridor extending to Cambodia, Laos, and Vietnam). The <strong>International North-South Transport Corridor (INSTC)</strong> (the 7,200 km corridor from Mumbai to St. Petersburg in Russia, via Iran and Azerbaijan, with the 'Chabahar Port' in Iran as the critical node &mdash; India operates the Shahid Beheshti terminal at Chabahar).</li>\n`;
c += `</ul>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 7 complete, section 8 started. Total: ' + c.length + ' chars');
