$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 7: POST-MAURYAN PERIOD ===================== -->
<h2 id="post-mauryan">7. Post-Mauryan Period (185 BCE-320 CE)</h2>

<p>The <span class="highlight">Post-Mauryan period</span> (also called the 'Middle Period' or 'Age of Small Kingdoms') saw the fragmentation of the Mauryan Empire into multiple successor states, the revival of Brahmanical religion and Vedic sacrifices, and extensive foreign contact through invasions and trade. This was the period of the <span class="highlight">Indo-Greeks</span>, <strong>Shakas (Scythians)</strong>, <strong>Parthians</strong>, <strong>Kushans (Yuezhi)</strong>, and indigenous dynasties like the <strong>Sungas</strong>, <strong>Kanvas</strong>, <strong>Satavahanas</strong>, and <strong>Hunas</strong>. It was also a period of great commercial and cultural expansion — Indian merchants and Buddhist monks traversed the Silk Route, establishing contacts with the Roman Empire, Central Asia, and Southeast Asia. The Periplus of the Erythraean Sea (c. 60 CE, an anonymous Greek text describing ports and trade routes on the Red Sea, East Africa, and the Indian coast) provides invaluable evidence of India's maritime trade.</p>

<h3>The Shunga Dynasty (185-73 BCE)</h3>

<p><strong>Pushyamitra Shunga</strong>, the Mauryan commander-in-chief, assassinated the last Mauryan king Brihadratha at a military review and founded the Shunga dynasty. The Puranas and the play Malavikagnimitram by Kalidasa mention him. He revived <span class="highlight">Vedic orthodoxy</span> — performed two Ashvamedha (horse) sacrifices (the Shunga horse sacrifice is mentioned in the Ayodhya inscription of Dhanadeva), restored the importance of Brahmins, and promoted Sanskrit. There is debate about his persecution of Buddhists (the Divyavadana, a Buddhist text, claims he offered 100 gold dinaras per Buddhist monk head and destroyed monasteries), but most historians consider this polemical exaggeration — the Sanchi and Bharhut stupas were expanded during Shunga rule, suggesting Buddhist patronage continued. His capital was Pataliputra (later shifted to Vidisha). He fought against the Indo-Greeks under Demetrius in the northwest, defending the Yamuna valley. His son <strong>Agnimitra</strong> (the hero of Kalidasa's Malavikagnimitram) ruled from Vidisha. The last Shunga king Devabhuti was killed by his minister Vasudeva Kanva (73 BCE).</p>

<h3>The Kanva Dynasty (73-28 BCE)</h3>

<p><span class="highlight">Vasudeva Kanva</span> founded a short-lived dynasty of 4 rulers. They ruled from Pataliputra over a much-reduced territory (Magadha and parts of UP). They followed Brahmanical religion. They were overthrown by the Satavahanas under <strong>Simuka</strong> or <strong>Gautamiputra Satakarni</strong> (c. 28 BCE). The Kanvas are historically insignificant — their main contribution was to mark the end of Magadha's political dominance, which now shifted westward to the Deccan (Satavahanas) and Ujjain (Western Kshatrapas).</p>

<h3>The Indo-Greeks (Bactrian Greeks, c. 200-10 BCE)</h3>

<p>After the collapse of the Mauryan Empire, Greek rulers from the Greco-Bactrian kingdom (established when the Greek satrap Diodotus declared independence from the Seleucid Empire c. 256 BCE) invaded India. <strong>Demetrius I</strong> (c. 190-180 BCE) invaded the Indus valley and Punjab, establishing an Indo-Greek kingdom at Taxila. <strong>Menander I (Milinda)</strong> (c. 165-145 BCE) was the greatest Indo-Greek ruler — famous for his dialogue with the Buddhist monk Nagasena (the Milindapanha — Questions of King Milinda, a classic of Buddhist literature). Menander's capital was at Sakala (Sialkot). He converted to Buddhism and is the only Greek king to be remembered in Indian texts. Indo-Greek rulers issued the earliest dated coins with bilingual legends (Greek on one side, Kharosthi on the other) and introduced the <strong>portrait coin</strong> — the first ruler portraits on Indian coinage. Their rule was confined to the Kabul valley, Punjab, and parts of eastern Afghanistan. They were eventually replaced by the Shakas and Yuezhi/Kushans. The Indo-Greeks contributed to the development of <span class="highlight">Gandhara art</span> — the fusion of Hellenistic and Indian artistic styles that produced the first anthropomorphic images of the Buddha in human form (previously, the Buddha was represented symbolically — by a footprint, throne, or umbrella).</p>

<h3>The Shakas (Scythians, c. 90 BCE-250 CE)</h3>

<p>The <span class="highlight">Shakas</span> were nomadic tribes from Central Asia (the Sacae or Scythians) who displaced the Indo-Greeks in the northwest and established several ruling houses: the <strong>Indo-Scythian</strong> rulers of Taxila (Maues, c. 85-60 BCE), the <strong>Western Kshatrapas</strong> (Satraps) of Ujjain (Nahapana, Chashtana, Rudradaman I — the most famous), and the <strong>Kardamaka family</strong>. <strong>Rudradaman I</strong> (c. 130-150 CE) of the Kardamaka family issued the famous <strong>Junagadh Rock Inscription</strong> (c. 150 CE) — the first long inscription in Sanskrit (all earlier ones were in Prakrit), which describes his repair of the Sudarshana lake (originally built by the Mauryas) during a severe storm. Rudradaman was a great patron of Sanskrit learning and culture; his inscription is the earliest evidence of proper Sanskrit in official records. The Western Kshatrapas ruled western India (Saurashtra, Malwa, Gujarat, Konkan, and parts of Rajasthan) until c. 410 CE, when they were conquered by the Gupta emperor Chandragupta II (Vikramaditya). They minted extensive silver coinage (drachmas with the king's bust on the obverse and a chaitya/stupa on the reverse) which shows they had access to rich silver mines and controlled trade routes to the Roman Empire. The Shaka era (used by the Indian government as the official national calendar, beginning 78 CE, adopted from the Saka dynasty) is named after these rulers.</p>

<h3>The Kushans (c. 30-375 CE)</h3>

<p>The <span class="highlight">Kushans</span> were a clan of the <strong>Yuezhi</strong> confederation — nomadic people from the Gansu region of western China, driven west by the Xiongnu (Huns) in the 2nd century BCE. They conquered the Greco-Bactrian kingdom, then the Indo-Greek territories, and established a vast empire stretching from Central Asia (Bactria/Afghanistan) to the Gangetic plain. Their empire connected the Silk Route — controlling both the overland routes through Central Asia and the sea routes through the Indus delta. Key rulers:</p>

<ul>
<li><strong>Kujula Kadphises</strong> (c. 30-80 CE): First Kushan ruler, unified the Yuezhi tribes, conquered Kabul valley, Kashmir, and the Parthian territories. Issued coins imitating Roman aurei. Called himself a 'Great King, King of Kings, Son of God, the Great Saviour' on a Rabatak inscription (Afghanistan).</li>
<li><strong>Vima Kadphises</strong> (c. 80-100 CE): Expanded into the Gangetic plain; introduced the first Indian gold coinage (modelled on Roman aurei); issued coins showing Shiva with a bull (Nandi) with the legend 'Siva' in Greek letters — the earliest representation of a Hindu deity on a coin. The Rabatak inscription records that he established the Kushan empire 'from the Kashi region to Saketa.'</li>
<li><span class="highlight">Kanishka</span> (c. 127-150 CE): The greatest Kushan ruler. His empire extended from Mathura to Central Asia, with two capitals — <strong>Purushapura</strong> (Peshawar) in summer and <strong>Mathura</strong> in winter. He is famous for <strong>convening the Fourth Buddhist Council</strong> in Kashmir (Kundalavana) under the chairmanship of Vasumitra and Asvaghosha, where the Mahavibhasha (a massive Sarvastivadin commentary on the Abhidharma) was compiled. He built the tallest stupa in the ancient world at Peshawar (the 'Kanishka Stupa', estimated at 150-180 metres tall — recorded by Xuanzang as the most magnificent in India; destroyed by Mahmud of Ghazni in 1000 CE). He patronised the <strong>Gandhara</strong> and <strong>Mathura</strong> schools of art (the famous Kanishka headless statue from Mathura, his coins with a standing Buddha). He was a great patron of Buddhism — the earliest known representation of the Buddha in human form appears on his coins (on a gold coin of Kanishka: the standing Buddha with the legend 'Boddo' in Greek script).</li>
<li><strong>Huvishka</strong> (c. 150-190 CE): Continued patronage of Buddhism; coins show a wide pantheon of Greek, Persian, Indian, and Zoroastrian deities — reflecting the Kushan role as cultural crossroads between east and west. The Kushan empire was connected to Rome through the Silk Route — massive amounts of Roman gold coins have been found in south India (indicating trade for pepper, spices, muslin, silk, and gems). Kushan art and architecture represent a fusion of Central Asian, Hellenistic, Iranian, and Indian elements.</li>
<li><strong>Vasudeva I</strong> (c. 190-230 CE): Last of the great Kushan rulers; later Kushans were weak and lost territory to the Sassanians (the Kushano-Sassanian period followed) and the rising Gupta empire (Samudragupta conquered the last Kushan remnants).</li>
</ul>

<h3>The Satavahanas (c. 200 BCE-250 CE)</h3>

<p>The <span class="highlight">Satavahanas</span> were the most important indigenous dynasty of the Deccan and south India after the Mauryas. They ruled from <strong>Pratishthana</strong> (Paithan, Maharashtra) over the Deccan plateau between the Narmada and Krishna rivers. They are also called the <strong>Andhras</strong> (in the Puranas). The Puranas list 30 kings over 460 years. Key rulers: <strong>Simuka</strong> (founder, c. 200-180 BCE), <strong>Gautamiputra Satakarni</strong> (c. 106-130 CE — the greatest, whose achievements are recorded in the Nasik Prashasti inscription composed by his mother Gautami Balashri — 'destroyed the Shakas, Yavanas, and Pahlavas; re-established the glory of the Satavahanas; stopped the contamination of the four varnas'), <strong>Vasishthiputra Pulumavi</strong> (c. 130-160 CE whose capital was Amravati — the site of the famous Amravati Stupa), <strong>Yajna Sri Satakarni</strong> (c. 165-195 CE — last strong ruler; reclaimed some territory from the Shakas). They were patrons of <strong>Brahmanical religion and Buddhism</strong> (practised Vedic rites with Brahmins, but also donated to Buddhist monasteries — the Nashik, Karle, and Kanheri caves were major Satavahana Buddhist sites). They issued lead coins (the first to extensively use lead, which was abundant in the Deccan) with boat and ship motifs (indicating maritime trade). They spoke Prakrit (all Satavahana inscriptions are in Prakrit), but Sanskrit literature also flourished under them — the <strong>Gatha Saptashati</strong> (Sattasai — 700 love verses in Maharashtri Prakrit) is attributed to King Hala (c. 20-35 CE). They participated in the <strong>Roman trade</strong> (the Periplus of the Erythraean Sea describes the Deccan ports of Barygaza/Bharuch and Muziris/Cranganore as major trade centres for pepper, pearls, spices, and textiles). The Satavahanas collapsed under Vakataka pressure in the 3rd century CE and were succeeded by the <strong>Vakatakas</strong> (in the northern Deccan) and the <strong>Ikshvakus</strong> (in the Krishna-Guntur delta).</p>

<h3>Foreign Invasions and Indian Responses</h3>

<p>The period saw the influx of Central Asian peoples (Shakas, Kushans, Huns) into India. They were gradually assimilated into Indian society — the Shakas adopted Indian religion (especially Buddhism), patronised Indian culture, and became part of the Kshatriya caste system through the Puranic genealogies. The term <strong>'Shaka'</strong> eventually became a generic term for barbarian/foreigner in Indian literature, but the Shakas of Ujjain (Western Kshatrapas) were fully integrated into the cultural mainstream. The <strong>Kushans</strong> were particularly important for their role in spreading Buddhism to Central Asia and China through the Silk Route — the Kushan monk <strong>Lokakshema</strong> (c. 147-189 CE) was the first translator of Mahayana Buddhist texts into Chinese. The Kushan royal dynastic title 'Devaputra' ('Son of God') was borrowed by Gupta rulers. The fusion of cultures is best seen in the art of <span class="highlight">Gandhara</span> (Greek/Buddhist) and <span class="highlight">Mathura</span> (Indian/Buddhist) — both schools produced the first human images of the Buddha during the Kushan period. The Gandhara school (influenced by Hellenistic realism) depicted the Buddha with curly hair, wavy robes, and Graeco-Roman facial features; the Mathura school (indigenous, more symbolic) depicted the Buddha as a robust, youthful figure with a shaven head and upright posture. These two schools set the iconographic conventions for all later Buddhist art across Asia.</p>

<h3>Trade with the Roman Empire</h3>

<p>The post-Mauryan period witnessed unprecedented maritime trade with the Roman Empire. The discovery of the monsoon winds by <strong>Hippalus</strong> (c. 50 CE) allowed ships to sail directly across the Indian Ocean from the Red Sea to the Malabar Coast. Major Roman trading settlements existed at <strong>Muziris</strong> (modern Kodungallur, Kerala — described in the Periplus as 'richly furnished with ships from Arabia and Greece'), <strong>Arikamedu</strong> (Pondicherry) — a Roman factory/trading station excavated by Sir Mortimer Wheeler, with Roman amphorae and Arretine ware), and <strong>Mangalore</strong>. <strong>Pliny the Elder</strong> (Natural History, c. 77 CE) complained that Roman trade with India cost the empire 100 million sesterces annually — '50 million sesterces of our money goes to India every year.' Roman gold coins (aurei and denarii) have been found in vast hoards in south India (the Kodungallur hoard, the Coimbatore hoard — with thousands of coins). Indian exports to Rome: pepper (40 ships annually from Muziris to the Red Sea according to Strabo), cinnamon, cardamom, ginger, sandalwood, ivory, pearls (from the Gulf of Mannar), precious stones (diamonds from Golconda, rubies from Myanmar), silk (from China via India), cotton textiles (from Bengal and Gujarat), and wild animals (tigers, elephants, monkeys for Roman games). Roman imports to India: gold and silver coins (which were melted down for jewellery), glassware (Roman glass has been found at Arikamedu, Nevasa, and Taxila), wine (amphorae at Arikamedu), coral, topaz, and slaves (though slavery was less central to the Indian economy). This trade declined after the 3rd century CE due to the Crisis of the Third Century in Rome, Sassanian Persian control of overland routes, and the shift of trade to the Axumite kingdom (Ethiopia).</p>

<div class="diagram-box"><pre>
  POST-MAURYAN DYNASTIES TIMELINE
  
  NORTH INDIA:
  Maurya (321-185 BCE)
    |--- Shunga (185-73 BCE)
    |       |--- Kanva (73-28 BCE)
    |       |--- Satavahana (south) absorbs Kanva
    |
  NORTH-WEST (Foreign dynasties):
  Indo-Greeks (200-10 BCE) → Shakas (90 BCE-250 CE) → Kushans (30-375 CE)
    |
  DECCAN/SOUTH:
  Satavahana (200 BCE-250 CE)
    |--- Vakataka (250-500 CE)
    |--- Ikshvaku (225-340 CE) - in Krishna delta
    |--- Chola, Chera, Pandya (sangam period, 300 BCE-300 CE)
</pre></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 7 written."
