$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 12: MUGHAL EMPIRE ===================== -->
<h2 id="mughal">12. Mughal Empire (1526-1707)</h2>

<p>The <span class="highlight">Mughal Empire</span> was the most powerful, wealthy, and culturally refined empire in Indian history — often called India's 'Second Classical Age' after the Guptas. The Mughals were of Turco-Mongol origin (descended from Timur on the father's side and Genghis Khan on the mother's side), but they rapidly became Indianised and cosmopolitan. The empire at its peak (under Akbar, Jahangir, Shah Jahan, and Aurangzeb) covered almost the entire Indian subcontinent — from Kabul in the west to Bengal in the east, and from Kashmir in the north to Kaveri in the south — with a population of 100-150 million people and a GDP that, according to Angus Maddison (economic historian), was 24.4% of world GDP in 1700 (larger than all of Europe combined). The Mughals created a distinctive architectural legacy (Taj Mahal, Red Fort, Agra Fort, Fatehpur Sikri, Humayun's Tomb, the Shalimar Gardens) and a system of administration and culture that shaped India's early modern history.</p>

<h3>Babur (1526-1530)</h3>

<p><strong>Zahir-ud-din Muhammad Babur</strong> was a Central Asian prince from Ferghana (modern Uzbekistan). He was descended from Timur (paternal) and Genghis Khan (maternal). He was forced out of his ancestral kingdom by the Uzbeks, captured Kabul (1504), and then invaded India at the invitation of Daulat Khan Lodi and Rana Sangha (who wanted him to overthrow Ibrahim Lodi but then expected him to leave). Babur defeated Ibrahim Lodi at the <strong>First Battle of Panipat</strong> (1526) using superior artillery (cannons, matchlocks) and the tulughma (flanking) tactic — a classic use of gunpowder weapons against a massed army of 100,000 soldiers. He then defeated Rana Sangha (the Rajput confederation led by the Rana of Mewar) at the <strong>Battle of Khanwa</strong> (1527) — a decisive victory that broke Rajput resistance and established Mughal supremacy in northern India. He also subdued the Afghan chiefs of Bengal and Bihar (the Battle of Ghaghra, 1529). Babur died in 1530 at age 47; he was buried first in Agra, then his remains were transferred to Bagh-e-Babur in Kabul (his chosen burial place). His memoirs, the <strong>Baburnama</strong> (written in Chagatai Turkish), is one of the great autobiographies of world history — candid, observant, and beautifully written (describing India's flora and fauna, his daily life, his wine-drinking, and the battle tactics).</p>

<h3>Humayun (1530-1540, 1555-1556)</h3>

<p><strong>Humayun</strong> inherited the empire but faced challenges from his three brothers (Kamran, Askari, Hindal) and the Afghan <strong>Sher Shah Suri</strong>. Humayun was an able scholar and astrologer but a poor general. Sher Shah defeated him at the <strong>Battle of Chausa</strong> (1539) and the <strong>Battle of Kannauj</strong> (1540). Humayun fled to Persia, where the Safavid Shah Tahmasp gave him refuge (he converted temporarily to Shi'ism to gain Persian military support). He recaptured Delhi in 1555 but died the next year — falling down the stairs of his library (the Sher Mandal, built by Sher Shah at the Purana Qila, Delhi) while hearing the call to prayer. His wife Hamida Banu Begum built the magnificent <strong>Humayun's Tomb</strong> in Delhi (completed 1572, a UNESCO World Heritage Site, the first great Mughal garden tomb, and the precursor of the Taj Mahal).</p>

<h4>Sher Shah Suri (1540-1545)</h4>

<p>Although not a Mughal, <span class="highlight">Sher Shah</span> is included here because his administrative reforms were adopted by Akbar and formed the foundation of the Mughal administration. An Afghan ruler, Sher Shah ruled the Delhi Sultanate for 5 years (interrupting the Mughal dynasty). His lasting achievements: <strong>Land revenue reforms</strong> — introduced the <strong>zabt</strong> system (measurement of land in bighas using the Sikandari gaz, classifying land into 3 types — good, middling, bad — and fixing the state's share at 1/3rd of the produce, payable in cash or kind). His revenue system was the direct blueprint for Akbar's Todar Mal's bandobast. <strong>Roads</strong> — built the Grand Trunk Road from Sonargaon (Bengal) to Peshawar (Afghan frontier), with 1700 sarai (rest houses) at every kos (2 mile) interval, each with separate accommodation for Hindus and Muslims, wells, and a mosque. The roads had fruit trees planted on both sides for shade. <strong>Coinage</strong> — issued the silver rupiya (178 grains, 11.5g), which became the standard Mughal currency and the ancestor of the modern Indian rupee. <strong>Administration</strong> — divided the empire into 47 sarkars (districts) each with a civil (shiqqdar) and military (faujdar) officer, and introduced criminal justice system (the muhtasib — a superintendent of public morals). He is buried at Sasaram, Bihar, in a magnificent tomb built in the middle of a lake — a masterpiece of Indo-Islamic architecture.</p>

<h3>Akbar the Great (1556-1605)</h3>

<p><span class="highlight">Jalal-ud-din Muhammad Akbar</span> is the greatest ruler of the Mughal dynasty — arguably the greatest ruler in Indian history. He ascended the throne at age 13 (after Humayun's death), with his guardian <strong>Bairam Khan</strong> as regent. Bairam Khan defeated the Hindu general Hemu (the last Hindu ruler of Delhi since the Delhi Sultanate) at the <strong>Second Battle of Panipat</strong> (1556) — Hemu was struck in the eye by an arrow and captured; Akbar's first great victory (he was only 14). Akbar dismissed Bairam Khan in 1560 and began his personal rule. His reign is divided into three phases: the conquest of central India and Rajputana (1560-1580), the systematic expansion into Gujarat, Bengal, and Sindh (1572-1585), and the conquest of the northwest and Deccan (1585-1605). Akbar's empire at his death: from Kabul to the Godavari, from Kashmir to the Narmada — most of northern and central India.</p>

<p><strong>Administrative Reforms</strong>: Akbar's government is the best-documented pre-modern administrative system in India, described in detail by <strong>Abul Fazl</strong>'s <strong>Ain-i-Akbari</strong> (the third volume of his Akbarnama). The empire was divided into <strong>subas</strong> (provinces, initially 12, later 15 — each governed by a subahdar/governor and a diwan/revenue officer), <strong>sarkars</strong> (districts), <strong>parganas</strong> (sub-districts — each with a shiqdar, munsif, qanungo), and <strong>villages</strong> (with muqaddam/headman, patwari/accountant, chaudhuri/revenue collector). The <strong>mansabdari system</strong> was the core of Mughal military-civil administration: every officer held a mansab (rank) indicating his zat (personal rank — salary) and sawar (cavalry troop — 2nd number indicating number of horsemen he maintained). Mansabs ranged from 10 to 7000 zat (princes held the highest). The system was introduced by Akbar in 1572-73 and became the framework of Mughal service (by 1595, there were 2,002 mansabdars). The <strong>land revenue system</strong> (Todar Mal's bandobast): measured all land using a standardised gaz (the Ilahi gaz, 33 inches), classified land into four categories (polaj — annually cultivated; parauti — fallow, left to recover for 1-2 years; chachar — left fallow for 3-4 years; banjar — uncultivable waste), and fixed cash rates based on the average of prices over 10-19 years. Revenue was 1/3rd of average produce. The <strong>Dahsala System</strong> was the final form — annual assessment of each village's production, with the state share fixed in cash. The system was efficient and effective: by 1605, Akbar had annual revenues of 3.6 crore rupees.</p>

<p><strong>Religious Policy — Din-i-Ilahi and Sulh-i-Kul</strong>: Akbar's religious policy is his most distinctive legacy. He was initially orthodox, but became increasingly influenced by the Sufi saint <strong>Shaikh Mubarak</strong> and his sons (Abul Fazl — his biographer and apologist, Faizi — his poet laureate), the Jain monk <strong>Hira Vijaya Suri</strong>, the Portuguese Jesuit missionaries (Rodolfo Acquaviva, Antonio Monserrate, Francisco Henriques — who were invited to Fatehpur Sikri for religious debates), the Zoroastrian scholar <strong>Dastur Meherji Rana</strong>, and Hindu philosophers. He built the <strong>Ibadat Khana</strong> (House of Worship) at Fatehpur Sikri (1575) for interfaith discussions. In 1579, he issued the <strong>Mahzar</strong> (Infallibility Decree), declaring himself the supreme religious authority in matters of Islamic law. In 1582, he introduced the <strong>Din-i-Ilahi</strong> (Divine Faith) — a syncretic religion combining elements of Islam, Hinduism, Zoroastrianism, Jainism, and Christianity, with Akbar as the spiritual leader. The Din-i-Ilahi was not a state religion — it had only 19 followers (birbals, abul fazl, etc.) and disappeared after Akbar's death. But it symbolised Akbar's vision of <strong>Sulh-i-Kul</strong> (Universal Peace/Total Reconciliation) — tolerance for all religions, abolition of jizya (1579), respect for Hindu festivals, translation of Hindu texts (Ramayana, Mahabharata into Persian), and integration of Rajputs and Hindus into the imperial elite. <strong>Rajput policy</strong>: Akbar married Rajput princesses (most famously Jodha Bai of Amber — daughter of Raja Bharmal, mother of Jahangir), appointed Rajput nobles (Raja Man Singh — governor of Bengal; Todar Mal — revenue minister; Birbal — his wazir), and gave them equal status with Muslim nobles. This policy was brilliantly successful — it secured Rajput loyalty for the Mughal dynasty for 150 years.</p>

<h3>Jahangir (1605-1627)</h3>

<p><strong>Nur-ud-din Muhammad Jahangir</strong> — 'Conqueror of the World.' He was addicted to wine and opium, but was a keen naturalist and patron of the arts. His reign is famous for his <strong>chain of justice</strong> (a gold chain with 60 bells, connected to the Shah Burj in Agra Fort — anyone could ring it and directly petition the emperor), his marriage to <strong>Nur Jahan</strong> (his 20th wife, a Persian noblewoman, who effectively ruled the empire for 15 years — the only Mughal empress to issue coins in her own name and have her name read in the khutba / Friday sermon). Nur Jahan's family (the Irani clique — her father Itimad-ud-Daula, her brother Asaf Khan, and Asaf Khan's daughter Mumtaz Mahal who married Prince Khurram/Shah Jahan) dominated the court. The empire expanded: the Mewar Rajputs (Rana Amar Singh) finally submitted (1615), and the Deccan campaigns continued. The British East India Company obtained permission to trade at Surat from Jahangir (1613 — the embassy of Sir Thomas Roe, who famously described Jahangir as 'the King of the World, the most glorious, the most magnificent, the most wise, the most just, the most learned, the most religious, the most merciful, the most charitable'). Jahangir's memoirs, the <strong>Tuzuk-i-Jahangiri</strong>, describe his passion for art (he could identify the artist of any miniature painting by seeing one eye!) and nature (he classified animals and birds). The <strong>Itimad-ud-Daula's Tomb</strong> at Agra (built by Nur Jahan for her father, 1622-28) is a masterpiece of pietra dura (marble inlay with semi-precious stones) that foreshadows the Taj Mahal.</p>

<h3>Shah Jahan (1628-1658)</h3>

<p><strong>Shahab-ud-din Muhammad Shah Jahan</strong> — 'King of the World.' His reign is the <span class="highlight">Golden Age of Mughal architecture</span>. He built the <strong>Taj Mahal</strong> (1632-1653) at Agra — the most famous monument in India (built for his queen Mumtaz Mahal, who died in childbirth; 20,000 workers worked on it for 22 years; the white marble with pietra dura inlay of 28 types of semi-precious stones; the 4 minarets are tilted slightly outward so they would fall away from the tomb in an earthquake). He built the <strong>Red Fort</strong> (Shahjahanabad, Delhi — 1639-1648), including the Diwan-i-Am (Hall of Public Audience) and the Diwan-i-Khas (Hall of Private Audience — inscribed with the famous line 'Agar Firdaus bar-rue zamin ast, hamin ast-o hamin ast-o hamin ast' — If there is Paradise on earth, it is this, it is this, it is this' by the poet Amir Khusrau). He built the <strong>Jama Masjid</strong> (Delhi, 1650-1656 — the largest mosque in India, capacity 25,000). He built the <strong>Shalimar Gardens</strong> (Lahore). His throne was the <strong>Peacock Throne</strong> (Takht-e-Taus) — the most magnificent throne in world history, made of gold, studded with 108 rubies, 116 emeralds, and the Koh-i-Noor diamond (the throne was looted to Persia by Nadir Shah in 1739). Shah Jahan also conquered the Deccan sultanates (Ahmadnagar annexed 1633; Golconda and Bijapur became tributaries). The Mughal army reached its peak under Shah Jahan — 200,000 cavalry, 4,000 war elephants. His reign was the height of Mughal cultural refinement — the music of Tansen (but Tansen was Akbar's court musician — actually Tansen died in 1589). But Shah Jahan's expenditure on architecture emptied the treasury. In 1657, he fell ill, and his sons Aurangzeb, Dara Shikoh, Shuja, and Murad fought the Mughal War of Succession. Aurangzeb defeated Dara Shikoh, captured Shah Jahan, and kept him imprisoned in the Agra Fort for 8 years, from where he could see the Taj Mahal. Shah Jahan died in 1666.</p>

<h3>Aurangzeb (1658-1707)</h3>

<p><strong>Muhi-ud-din Muhammad Aurangzeb</strong> — 'Ornament of the Throne' (Alamgir — World-Seizer). He ruled for 49 years — the longest reign of any Mughal emperor. His reign was the territorial peak of the empire (extending to its maximum extent: from Kashmir in the north to Madurai in the south, and from Kabul in the west to Chittagong in the east), but also the beginning of its terminal decline. His policies reversed Akbar's Sulh-i-Kul — he reimposed <strong>jizya</strong> (1679) on non-Muslims (a 2.5% tax on non-Muslims?), dismissed Hindu mansabdars (their percentage fell from 24% in 1658 to 6% in 1679), destroyed Hindu temples (Kashi Vishwanath at Varanasi — 1669; Somnath again — though the temple had been rebuilt after Mahmud of Ghazni; Keshav Dev at Mathura — 1670), and persecuted Sikhs (executed Guru Tegh Bahadur, 1675) and Shia Muslims. His Deccan policy involved constant warfare against the Marathas (Shivaji, Sambhaji — executed 1689, Rajaram), Bijapur (annexed 1686), and Golconda (annexed 1687). He spent the last 26 years of his life in the Deccan, fighting an endless guerrilla war against the Marathas that drained the imperial treasury. The empire became overextended — the war in the Deccan cost 100,000 men and 10 crores of rupees annually. After his death (1707 at Ahmednagar), the empire disintegrated rapidly. The Mughal Empire declined due to: <strong>Nadir Shah's invasion</strong> (1739 — the Peacock Throne, the Koh-i-Noor, and an estimated 700 million rupees worth of treasure looted), <strong>invasions by Ahmad Shah Abdali</strong> (1748-1767), the <strong>rise of the Maratha Confederacy</strong>, the <strong>Battle of Plassey</strong> (1757 — the British taking control of Bengal), and the systematic dismantling of Mughal authority by the British. The last Mughal emperor <strong>Bahadur Shah Zafar II</strong> (r. 1837-1857) was a British pensioner who was exiled to Rangoon after the Revolt of 1857 for nominally leading the rebellion.</p>

<div class="warn-box"><div class="warn-title">Historiographical Debate: Aurangzeb's 'Religious Bigotry'</div><div class="warn-text">Traditional historiography (e.g., Jadunath Sarkar) portrays Aurangzeb as a bigoted Sunni Muslim whose persecution of Hindus, Sikhs, and Shias alienated the non-Muslim subjects and caused the empire's decline. Revisionist historians (e.g., S. Moosvi, M. Athar Ali) argue: 1) Aurangzeb appointed more Hindus (especially Marathas and Rajputs) in his later reign than before. 2) Temple destruction was not a sweeping policy — many temples were destroyed only after rebellions (political, not religious, motivation; the temple was the symbol of royal authority). 3) Jizya was reimposed not out of religious zeal but because the treasury was exhausted by Shah Jahan's extravagance and the Deccan wars. 4) The majority of his officials were still Hindus and Rajputs. The truth is complex: Aurangzeb was a devout Sunni who enforced sharia more strictly than his predecessors, but he was also a practical ruler who employed Hindus and even patronised Hindu temples when politically useful. His lasting damage was political and strategic: he exhausted the treasury on the Deccan wars, destroyed the Mughal alliance with the Rajputs (the key to Akbar's success), and left the empire too weak to resist the British, Marathas, and Afghans.</div></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 12 written."
