const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

c += `<div class="table-wrap"><table>\n`;
c += `<tr><th>Port</th><th>State</th><th>Location/Coast</th><th>Key Features</th><th>Major Cargo</th></tr>\n`;
c += `<tr><td>Kandla (Deendayal)</td><td>Gujarat</td><td>Gulf of Kutch, West Coast</td><td>Largest major port by tonnage; developed as the 'substitute port' after Karachi partition; first SEZ in India (1965) at Kandla; tidal port</td><td>Crude oil, petroleum products, foodgrains, fertilisers, chemicals, textiles</td></tr>\n`;
c += `<tr><td>Mumbai</td><td>Maharashtra</td><td>Mumbai Harbour, West Coast</td><td>Largest natural harbour in India (the 'Prince's Dock, Victoria Dock'); busiest major port by ship traffic; oldest modern port (1873)</td><td>General cargo, containers, petroleum, chemicals, machinery</td></tr>\n`;
c += `<tr><td>JNPT (Nhava Sheva)</td><td>Maharashtra</td><td>Navi Mumbai, West Coast</td><td>Largest container port in India (55% of India's container traffic); developed to relieve congestion at Mumbai port; 6 container terminals (NSICT, NSIGT, APMT, etc.)</td><td>Containers (electronics, apparel, machinery, pharmaceuticals), vehicles</td></tr>\n`;
c += `<tr><td>Marmugao (Mormugao)</td><td>Goa</td><td>Zuari estuary, West Coast</td><td>Leading iron ore export port of India (before the 2012 mining ban); natural harbour protected by breakwaters</td><td>Iron ore, steel, manganese, general cargo</td></tr>\n`;
c += `<tr><td>New Mangalore</td><td>Karnataka</td><td>Gurpur River, West Coast</td><td>The only major port in Karnataka; developed in 1974 to serve the hinterland of Karnataka and northern Kerala; all-weather port</td><td>Iron ore, petroleum products (Mangalore Refinery), coffee, cashew, chemicals, fertilisers</td></tr>\n`;
c += `<tr><td>Cochin (Kochi)</td><td>Kerala</td><td>Vembanad Lake, West Coast</td><td>Natural harbour (the 'Queen of the Arabian Sea'); first Indian port developed as a major port (1928); Kochi LNG terminal (Petronet, 5 mt/yr); Kochi shipyard (largest in India by DWT); ICTT/International Container Transshipment Terminal at Vallarpadam (first in India)</td><td>Petroleum (crude and LNG), containers, fertilisers (FACT), spices, rubber, coffee, tea</td></tr>\n`;
c += `<tr><td>Chennai</td><td>Tamil Nadu</td><td>Coromandel Coast, East Coast</td><td>Largest major port on the east coast (the 'Madras port'); 2nd largest container port after JNPT; artificial harbour built on open coast with breakwaters (the longest in India at 4 km)</td><td>Containers, automobiles (largest car export port &mdash; Hyundai, Ford, Nissan), iron ore, fertilisers, general cargo</td></tr>\n`;
c += `<tr><td>Ennore (Kamarajar)</td><td>Tamil Nadu</td><td>Ennore Creek, East Coast</td><td>First corporate port in India (1999, under Ennore Port Limited, now Kamarajar Port Limited); deepest port on the east coast (17.5 m draft for cape-size vessels)</td><td>Coal (imported thermal coal for TNEB/NLC plants), iron ore (exports from Kudremukh), containers</td></tr>\n`;
c += `<tr><td>Visakhapatnam (Vizag)</td><td>Andhra Pradesh</td><td>Vizag Harbour, East Coast</td><td>Deepest port on the east coast (16.5 m draft); only major port in Andhra Pradesh; handles the largest tonnage of any east coast port; inner harbour (liquid cargo) and outer harbour (bulk and cape-size)</td><td>Iron ore (exports from Bailadila to Japan/Korea), petroleum (HPCL Vizag refinery), steel (Vizag Steel), fertilisers, alumina</td></tr>\n`;
c += `<tr><td>Paradip</td><td>Odisha</td><td>Paradip Harbour, East Coast</td><td>Largest port by tonnage on the east coast (150 mt/yr); deepest draft on the east coast (18 m); first major port to have 100% mechanised cargo handling</td><td>Coal (imported for NTPC, Hindalco), iron ore, steel, fertilisers, crude oil (Paradip Refinery of IOC, 15 mt/yr), LNG</td></tr>\n`;
c += `<tr><td>Kolkata</td><td>West Bengal</td><td>Hooghly River, East Coast</td><td>Oldest major port in India (operational since 1870); riverine port 232 km from the sea (Hooghly River); only major port on a tidal river; Haldia Dock (confluence of Hooghly and Haldi rivers) handles bulk cargo and petroleum</td><td>Jute, tea, steel, coal, foodgrains, fertilisers, petroleum products (Haldia), containers</td></tr>\n`;
c += `<tr><td>Tuticorin (VO Chidambaranar)</td><td>Tamil Nadu</td><td>Gulf of Mannar, East Coast</td><td>2nd largest port in Tamil Nadu; developed as a major port in 1974; artificial deep-sea harbour with 5 berths for cape-size vessels; coastal shipping to Sri Lanka and the Maldives</td><td>Coal (for NLC Neyveli), salt (from Tuticorin salt pans &mdash; largest salt-producing area in Tamil Nadu), fertilisers, foodgrains, containers, edible oils</td></tr>\n`;
c += `</table></div>\n\n`;

c += `<h4>Air Transport</h4>\n\n`;
c += `<p>India is the <span class="highlight">3rd largest aviation market in the world</span> (after the US and China), with domestic passenger traffic of 150 million and international traffic of 65 million (2023-24). The <strong>Airports Authority of India (AAI)</strong> manages 125 airports (25 international, 90 domestic, 10 customs), and the number is growing (target of 220 airports by 2030 under the UDAN scheme). The civil aviation sector contributes $150 billion to the economy (direct and indirect) and employs 7 million people.</p>\n\n`;

c += `<p><strong>Major Airlines and Market Structure</strong> &mdash; <span class="highlight">IndiGo</span> (InterGlobe Aviation) is the <strong>largest airline in India</strong> (60% market share, the 6th largest in the world by passengers carried, with a fleet of 350 Airbus planes and an order of 1,000 planes). The market is a 'duopoly' of IndiGo and <strong>Air India</strong> (owned by the Tata Group since 2022, after the historic privatisation of the national carrier in 2022 for Rs 18,000 crore). The merger of Air India with Vistara (the Tata-SIA joint venture) and AirAsia India in 2023-24 has created the 2nd largest airline group in India (about 30% market share). Other airlines include <strong>SpiceJet</strong> (the 3rd largest, under financial stress), <strong>Akasa Air</strong> (a low-cost carrier launched in 2022), and <strong>Zoom Air</strong> (regional). The aviation sector has been transformed by the entry of low-cost carriers (LCCs &mdash; IndiGo, SpiceJet, Akasa Air), which drove airfares down by 50% in real terms over the 2010s and made air travel accessible to the middle class for the first time.</p>\n\n`;

c += `<p><strong>UDAN (Ude Desh ka Aam Nagrik)</strong> &mdash; The <span class="highlight">Regional Connectivity Scheme</span> (launched 2016) aims to connect unserved and underserved airports, particularly in small towns, by providing viability gap funding (VGF) to airlines for operating flights on regional routes at subsidised fares (a cap of Rs 2,500 per seat for a 1-hour flight). Under 5 phases, 500+ routes have been awarded, connecting 100+ airports, of which 70+ have become operational. The key airports developed under UDAN include <strong>Kishangarh</strong> (Ajmer), <strong>Jalgaon</strong>, <strong>Bareilly</strong>, <strong>Kannur</strong>, <strong>Darbhanga</strong>, <strong>Pakyong</strong> (Sikkim &mdash; the first airport in the state, at 4,700 feet, one of the 5 highest in India), <strong>Hollongi</strong> (Arunachal Pradesh), and <strong>Mithi</strong> (Kutch).</p>\n\n`;

c += `<p><strong>Greenfield Airports</strong> &mdash; India has 7 operational greenfield airports built since 2000: <strong>Kochi</strong> (the first greenfield airport built by a public-private partnership, 1999, the Cochin International Airport &mdash; the model for PPP airports in India), <strong>Bengaluru</strong> (the Kempegowda International Airport, 2008, the 3rd busiest in India, operated by a private consortium, BIAL), <strong>Shamshabad/Hyderabad</strong> (the Rajiv Gandhi International Airport, 2008, the 4th busiest in India, operated by a private consortium, GHIAL), <strong>Mopa (Goa)</strong> (the 'Mopa International Airport' in North Goa, 2023, built to replace and supplement the Dabolim airport, operated by the GMR Group &mdash; a PPP with the Goa government), <strong>Navi Mumbai</strong> (the 'New Mumbai Airport' at Panvel, under construction since 2020, expected to open by 2026, the 2nd airport for Mumbai, designed for 90 million passengers/yr &mdash; the largest airport project in India), and <strong>Jewar</strong> (the Noida International Airport in UP, under construction, expected to open by 2026, the 1st airport in India with a partnership with the Zurich Airport International). The <strong>Kannur International Airport</strong> (Kerala, 2018) and <strong>Pakalbazar-Pakyong Airport</strong> (Sikkim, 2018) are other recent greenfield additions.</p>\n\n`;

c += `<p><strong>International Airports</strong> &mdash; The busiest international airports in India are <strong>Delhi (IGI)</strong> (the world's 2nd busiest by passenger traffic &mdash; Terminal 3 is the 6th largest terminal in the world, 60 million passengers/yr), <strong>Mumbai (CSIA)</strong> (the 2nd busiest, the world's 30th busiest, with the Terminal 2 'The Great Indian Terminal'), <strong>Bengaluru (KIA)</strong> (the 3rd busiest, the 27th busiest in the world), <strong>Chennai (MAA)</strong> (the 4th busiest), <strong>Kolkata (CCU)</strong> (the 5th busiest, the recently opened Terminal 2 by the Kolkata airport &mdash; 'the gateway to the Northeast'), <strong>Hyderabad (HYD)</strong> (the 6th busiest), and <strong>Kochi (COK)</strong> (the 7th busiest, the first in the world to be fully solar-powered).</p>\n\n`;

c += `<h3>Communication</h3>\n\n`;
c += `<p>India has the <span class="highlight">2nd largest telecommunications network in the world</span> (after China), with <strong>118 crore (1.18 billion) telecom subscribers</strong> (a tele-density of 85%), <strong>84 crore internet subscribers</strong>, and <strong>75 crore broadband subscribers</strong> (2024). The telecom revolution has been one of the most transformative developments in modern India, connecting the rural-urban divide, enabling the 'Digital India' vision, and creating the ecosystem for the IT-BPO, e-commerce, and fintech industries.</p>\n\n`;

c += `<p><strong>The Telecom Story</strong> &mdash; The sector was <span class="highlight">liberalised in 1994</span> (the National Telecom Policy, NTP), but real growth began with the entry of <strong>Reliance Jio</strong> in September 2016. Jio's entry with free voice calling and data at Rs 0.05/MB (compared to Rs 25/MB in 2015) triggered a <strong>price war</strong> that collapsed data prices by 95% (from Rs 250/GB to Rs 12/GB &mdash; the cheapest in the world) and forced a massive consolidation of the industry (from 15 operators in 2016 to 3 major operators today). India's average mobile data consumption is 20 GB/month (the highest in the world, driven by the Jio effect and the proliferation of social media, OTT video streaming, and UPI-based payments).</p>\n\n`;

c += `<p><strong>Major Telecom Operators</strong> &mdash; <strong>Reliance Jio</strong> (the largest, 45 crore subscribers, 4G/5G-only operator, with a pan-India footprint and a unique technology stack &mdash; the all-IP network, the 4G VoLTE from day one, the JioFiber broadband, and the JioMart e-commerce platform), <strong>Bharti Airtel</strong> (the 2nd largest, 35 crore subscribers, the oldest private operator, with a strong presence in the postpaid, enterprise (B2B), and broadband segments), and <strong>Vodafone Idea (Vi)</strong> (the 3rd largest, 20 crore subscribers, operating under severe financial stress &mdash; AGR/gross revenue dues of Rs 70,000 crore, the government has converted the AGR dues into equity (2023), making the government the largest shareholder in Vi at 33%). <strong>BSNL</strong> (Bharat Sanchar Nigam Limited, the state-owned operator, 10 crore subscribers) has been losing market share (from 70% in 2004 to 8% today) but is being revived with a Rs 1.6 lakh crore revival package (2022) for 4G technology deployment (using indigenous 4G technology developed by C-DoT and the TCS consortium), optical fibre expansion, and the monetisation of its 5 lakh km of optical fibre network (the largest in India).</p>\n\n`;

c += `<p><strong>Data Revolution and Digital India</strong> &mdash; The <span class="highlight">'Digital India' programme</span> (launched 2015) aims to transform India into a digitally empowered society and knowledge economy. Its three core pillars are: (a) digital infrastructure (the <strong>BharatNet</strong> project &mdash; the National Optical Fibre Network connecting 2.5 lakh gram panchayats with broadband at a cost of Rs 1.2 lakh crore, achieved 2 lakh connections by 2024), (b) digital governance and services (the <strong>UMANG</strong> app &mdash; the 'Unified Mobile App for New-age Governance', the <strong>DigiLocker</strong> &mdash; the paperless document platform, the <strong>Aadhaar-based e-KYC</strong>, the <strong>UPI</strong> &mdash; the Unified Payments Interface, the world's most successful real-time payment system, processing 10 billion transactions/month, the highest in the world), and (c) digital literacy (the 'Pradhan Mantri Gramin Digital Saksharta Abhiyan', the 'PMGDISHA' &mdash; the digital literacy programme for rural citizens).</p>\n\n`;

c += `<p><strong>5G in India</strong> &mdash; The <span class="highlight">5G spectrum auction</span> was held in July 2022 (the largest spectrum auction in India, 72 GHz of spectrum at a value of Rs 1.5 lakh crore, at a reserve price 30% lower than the 2016 floor to ensure viability). Reliance Jio and Airtel acquired the majority of the 5G spectrum (the 700 MHz, 3.5 GHz, and 26 GHz bands). 5G services were launched in October 2022, and the coverage reached 400+ cities by December 2023 (the fastest 5G roll-out in the world by population coverage, reaching 100 million users within 12 months &mdash; compared to 6 months for China and 24 months for the US). The 5G use cases include fixed wireless access (FWA) broadband (Jio AirFiber, Airtel Xstream), Industry 4.0 (smart factories, the '5G for India' initiative), autonomous vehicles, telemedicine (the '5G surgery' trial in 2023 at the AIIMS Delhi), smart agriculture (the '5G agri-drones'), and smart city applications (the '5G-enabled traffic management' in 20+ cities).</p>\n\n`;

c += `<div class="tip-box"><div class="tip-title">Transport for UPSC: Infrastructure and the Economy</div><div class="tip-text">The 'Infrastructure-Development-Employment' triangle is a core UPSC theme. The Golden Quadrilateral and the GQ/NS-EW (National Development Project) and the PMGSY and the BharatMala Phase I are the three largest road projects. The Eastern DFC and the Western DFC under the DFCC are the largest railway projects. The Sagarmala is the largest maritime project, and the UDAN is the largest aviation scheme. The 'Vande Bharat' train, the 'Mumbai-Ahmedabad Bullet Train' (the Shinkansen E5 series &mdash; 320 km/hr, 508 km, 12 stations, Rs 1.1 lakh crore &mdash; the first in India of the 'High-Speed Rail' from the Japanese partnership), and the RapidX (the 180 km/hr RRTS) are the three signature passenger rail projects. The National Infrastructure Pipeline (NIP) of Rs 111 lakh crore (7,400 projects, 2020-25) is the umbrella framework. The PM Gati Shakti (the 'National Master Plan for Multi-modal Connectivity', 2021, Rs 100 lakh crore) is the platform for integrated planning of transport projects &mdash; the 'Digital Master Planning' of the National Infrastructure &mdash; and is the single most important infrastructure exam theme for UPSC.</div></div>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 8 complete. Total: ' + c.length + ' chars');
