$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 16: REVOLT OF 1857 ===================== -->
<h2 id="revolt-1857">16. The Revolt of 1857</h2>

<p>The <span class="highlight">Revolt of 1857</span> (also called the First War of Independence by V. D. Savarkar, or the Sepoy Mutiny by British historians) was the largest and most serious armed resistance to British rule in India before the Mahatma Gandhi-led national movement. It began as a mutiny of sepoys (Indian soldiers in the British East India Company's army) at <strong>Meerut</strong> on 10 May 1857 and quickly spread across northern and central India — Delhi, Lucknow, Kanpur, Jhansi, Bareilly, Gwalior, and Awadh. The revolt was suppressed by the British by June 1858. The immediate cause was the greased cartridge controversy, but the deeper causes were political, economic, social, religious, and military grievances accumulated over 100 years of Company rule. The revolt led to the <strong>abolition of the East India Company</strong> (Government of India Act 1858) and the transfer of power to the British Crown — the beginning of the <strong>British Raj</strong> (direct rule by the British government under the Viceroy, the title of the Governor-General of India changed to 'Viceroy' from 1858).</p>

<h3>Causes of the Revolt</h3>

<ul>
<li><strong>Political causes</strong>: The British policy of 'Doctrine of Lapse' (introduced by Lord Dalhousie, Governor-General 1848-1856) — annexed states where the ruler died without a natural heir (Satara 1848, Sambalpur 1849, Udaipur 1852? Actually Chota Nagpur? Jhansi 1853, Nagpur 1854, Awadh 1856 — the largest and most controversial annexation, based on the charge of 'misgovernment'). The annexation of Awadh was particularly resented — the Nawab Wajid Ali Shah was exiled to Calcutta, and 60,000 soldiers and retainers were thrown out of work. The Mughal emperor Bahadur Shah Zafar was told that his dynasty would end after his death. Rani Lakshmibai's adopted son was denied the throne of Jhansi by Lord Dalhousie.</li>
<li><strong>Economic causes</strong>: Heavy land revenue (the British Permanent Settlement in Bengal, Ryotwari in Madras and Bombay, and Mahalwari in the North-West Provinces) bankrupted the peasantry; new revenue laws dispossessed zamindars; heavy taxes on Indian artisans and textile workers destroyed traditional industries (the British textile industry, with machine-made cloth, flooded India; Bengal's once-famous muslin industry was destroyed). The 'Drain of Wealth' (Dadabhai Naoroji's theory) — Indian wealth was systematically transferred to Britain as tribute, dividends, salaries of British officials, and purchase of British goods. Trade barriers destroyed Indian shipping, banking, and commerce.</li>
<li><strong>Social and religious causes</strong>: The British introduced Christian missionaries (the Charter Act of 1813 allowed them), established schools teaching Western education, passed the Religious Disabilities Act (1850) allowing converts to inherit ancestral property, and abolished sati (1829) and permitted widow remarriage (1856 — the Hindu Widows' Remarriage Act). These reforms, however progressive, were seen as interference in Hindu social customs. The British also enforced a law allowing conversion of the country (the Lex Loci Act of 1850 — actually the Religious Disabilities Act 1850). Rumours spread that the British planned to forcibly convert Indians to Christianity — the greased cartridge incident was seen as a deliberate attempt to defile both Hindus and Muslims.</li>
<li><strong>Military causes</strong>: Indian sepoys were discriminated against (lower pay, fewer promotion opportunities, and they could not rise above the rank of subedar). The General Service Enlistment Act (1856) required sepoys to serve overseas, which high-caste Hindus (especially Brahmins and Rajputs from Awadh and Bihar) considered a violation of caste rules (crossing the sea was considered polluting). The number of Indian soldiers in the Bengal Army was disproportionately high (the Bengal Army had 86,000 Indian soldiers vs 27,000 British), making a mutiny a serious threat.</li>
<li><strong>Immediate cause — The Greased Cartridge</strong>: The new Enfield rifle (Pattern 1853 Enfield) required the soldier to bite open the cartridge (which held the gunpowder). In early 1857, a rumour spread that the cartridges were greased with cow and pig fat — cow fat was offensive to Hindus (the cow is sacred), and pig fat was offensive to Muslims (pigs are unclean in Islam). The British attempted to correct the mistake (allowing soldiers to grease their own cartridges), but the damage was done. On 29 March 1857, <strong>Mangal Pandey</strong>, a sepoy at the Barrackpore (Kolkata) garrison, attacked his British officers. He was executed on 8 April. The 34th Native Infantry was disbanded. On 9 May 1857, 85 sepoys at Meerut were court-martialled and sentenced to 10 years' hard labour for refusing to use the cartridges. On 10 May, their comrades attacked the British officers, released the prisoners, and marched to Delhi.</li>
</ul>

<h3>Course of the Revolt</h3>

<div class="table-wrap"><table>
<tr><th>Centre</th><th>Leader</th><th>Key Events</th></tr>
<tr><td><strong>Delhi</strong></td><td>Bahadur Shah Zafar (figurehead); Bakht Khan (military commander from Bareilly)</td><td>The sepoys entered Delhi, proclaimed Bahadur Shah as Emperor of India. Bakht Khan commanded the rebel forces. The British recaptured Delhi on 20 September 1857 after three months of siege (the British force under John Nicholson and Archdale Wilson bombarded the city, broke through the Kashmere Gate). Bahadur Shah was captured and exiled to Rangoon, where he died in 1862. The British executed all male members of the Mughal royal family (the princes were shot at the Delhi Gate). The last Mughal emperor's trial was the first 'war crimes tribunal' in Indian history.</td></tr>
<tr><td><strong>Kanpur</strong></td><td>Nana Saheb (adopted son of the last Peshwa Baji Rao II, driven out by the British)</td><td>Nana Saheb led the rebellion, captured Kanpur, and proclaimed himself Peshwa. After the British relief force (under General Havelock and Sir James Outram) arrived, the rebel forces massacred British women and children (the Bibighar massacre, July 1857). The British under General Havelock recaptured Kanpur and carried out savage reprisals (they made captured rebels lick the blood of the victims before executing them).</td></tr>
<tr><td><strong>Lucknow</strong></td><td>Begum Hazrat Mahal (wife of Nawab Wajid Ali Shah)</td><td>The British Residency at Lucknow was besieged for 87 days (June-September 1857). The British garrison (under Sir Henry Lawrence, who died in the siege) defended the Residency. The relief force (under Havelock and Outram) reached Lucknow but was also trapped. A second relief force (under Sir Colin Campbell, Commander-in-Chief) finally rescued the garrison in November 1857. Begum Hazrat Mahal escaped to Nepal.</td></tr>
<tr><td><strong>Jhansi</strong></td><td>Rani Lakshmibai (Manikarnika Tambe — widow of Raja Gangadhar Rao)</td><td>The Rani of Jhansi was initially reluctant (she had agreed to accept British pension under Lord Dalhousie's orders after the annexation of Jhansi), but joined the rebellion when the British attacked her fort. She defended Jhansi heroically for two weeks against the British force under Sir Hugh Rose. She escaped from the fort (with her young son tied to her back, leaping from the fort on her horse — a famous episode) and joined the rebels at Gwalior. She was killed in battle on 17 June 1858 at Kotah-ki-Sarai. Sir Hugh Rose described her as 'the best and bravest of the rebel leaders.'</td></tr>
<tr><td><strong>Bareilly</strong></td><td>Khan Bahadur Khan</td><td>The Rohilla leader led the rebellion in Rohilkhand (Bareilly, Moradabad, Badaun). He was defeated and executed in 1858.</td></tr>
<tr><td><strong>Gwalior</strong></td><td>Tantia Tope (real name: Ramachandra Panduranga Tope)</td><td>The brilliant Maratha general and close associate of Nana Saheb. He was the most effective rebel leader after the capture of Delhi. He organised the capture of Gwalior Fort (June 1858, with Rani Lakshmibai and Rao Saheb), but was defeated by Sir Hugh Rose. He escaped and continued guerrilla warfare in central India (with the help of tribal leaders and peasants). He was betrayed by his trusted servant Man Singh, captured, and executed on 18 April 1859.</td></tr>
<tr><td><strong>Arrah (Bihar)</strong></td><td>Kunwar Singh (the zamindar of Jagdispur, age 80)</td><td>The most important leader from eastern India. He led the rebellion in Bihar, captured Arrah, and fought a brilliant guerrilla campaign. He was wounded and died at his home in Jagdispur on 26 April 1858 (he cut off his own wounded arm to prevent it from being captured).</td></tr>
</table></div>

<h3>Causes of Failure</h3>

<ul>
<li><strong>Lack of unified leadership</strong>: The rebels had no common plan or commander. The nominal emperor Bahadur Shah was old (82) and had no real authority. Different leaders fought their own local battles. The rebellion was confined to northern and central India — the south, the Deccan (Hyderabad, Mysore, Madras Presidency), Bengal, and most of the Punjab remained loyal to the British (the Sikhs did not join, and the Bengal zamindars, the Madras Army, the Bombay Army, and the Nizam of Hyderabad stayed loyal).</li>
<li><strong>Superior British resources</strong>: The British had reinforcements from England (via the Cape route — the Suez Canal was not yet built), the Punjab Sikh regiments, the Gurkha regiments (who were allowed to recruit from Nepal after the revolt — the British appreciated their neutrality), and the armies of loyal princely states (Sindhia of Gwalior, Holkar of Indore, the Nizam of Hyderabad, the Maharaja of Patiala). The British had superior artillery, better logistics, and the telegraph (which the British used to communicate faster than the rebels).</li>
<li><strong>Lack of mass support</strong>: The revolt was primarily a military uprising and a reactionary movement of the old feudal order (deposed kings, dispossessed zamindars, ex-soldiers). The educated middle class (the 'bhadralok') did not support it. The merchants and moneylenders, who had benefited from British rule, stayed loyal. The peasants were divided.</li>
<li><strong>No clear alternative</strong>: The rebels had no coherent vision for post-British India. Their goal was to restore the pre-British order — the Mughal Empire, the Peshwa's rule, and the old feudal arrangements — which had no future in the 19th century.</li>
</ul>

<h3>Consequences of the Revolt</h3>

<ul>
<li><strong>End of the East India Company</strong>: The Government of India Act 1858 abolished the Company and transferred all authority to the British Crown. The Secretary of State for India (a British Cabinet position) was given administrative control. The Governor-General of India was renamed the <strong>Viceroy</strong> (Lord Canning became the first Viceroy). The British Parliament now directly controlled India.</li>
<li><strong>Racial hatred intensified</strong>: The British regarded Indians with contempt and fear after the revolt. The 'divide and rule' policy was strengthened — the British deliberately favoured Muslims (who were seen as 'the martial race', alongside Sikhs and Gurkhas) over Hindus. The British ended their earlier policy of social reform (the Religious Disabilities Act 1850 was the last such act for decades) and became cautious about interfering in Indian social customs — they abandoned social legislation to win back the loyalty of the conservative classes.</li>
<li><strong>Changes in the army</strong>: The proportion of British troops to Indian troops was increased (1 British to 2 Indian, down from 1:6). The artillery was placed exclusively in British hands. The recruitment of soldiers was diversified to avoid concentrations of particular castes/regions (the 'martial races' theory was developed: Sikhs, Gurkhas, and Punjabi Muslims were preferred over Brahmins and Rajputs from Awadh and Bihar).</li>
<li><strong>Policy towards princes and zamindars</strong>: The Doctrine of Lapse was abandoned. The British guaranteed the rights of princes to adopt heirs. The princes became loyal feudatories of the British Crown. The zamindars were given full rights over their land. The British declared that they would not annex any more princely states — they became the 'natural allies' of the British.</li>
<li><strong>Policy towards the peasantry</strong>: The British realised that the 1857 revolt was partly caused by the impoverishment of the peasantry. The later Land Revenue Acts (e.g., the Bengal Tenancy Act 1885) gave some protection to tenants, but these were limited.</li>
<li><strong>Start of the nationalist movement</strong>: The 1857 revolt inspired the first generation of Indian nationalists. The 'Fist War of Independence' theory (V. D. Savarkar, 1909) argued that the revolt was a national uprising, not a mutiny. The memory of 1857 became a source of inspiration for the freedom struggle (the INA's battle cry 'Delhi Chalo' and later slogans like 'Jai Hind' were inspired by 1857).</li>
</ul>

<div class="warn-box"><div class="warn-title">Historiographical Debate: Was 1857 a National War of Independence?</div><div class="warn-text">V. D. Savarkar (in The Indian War of Independence, 1909) argued that the revolt was 'the first national war of independence' — a unified, national struggle against foreign rule. Modern historians disagree: the revolt was limited geographically, socially, and ideologically. It was largely confined to the Gangetic plain and central India. The southern, western, and eastern regions were untouched. The leaders fought for different and often contradictory goals (restoring the Mughal emperor, the Peshwa, or their own local kingdoms). There was no participation by the modern educated Indians (the future leaders of the Congress). Most historians now call it the 'Revolt of 1857' — a massive but ultimately traditional, backward-looking uprising, not a modern nationalist movement. However, it was the first large-scale collaboration of Hindus and Muslims against the British, laying the groundwork for the future composite nationalism of the Indian National Congress.</div></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 16 written."
