const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

c += `<h4>Railway Transport</h4>\n\n`;
c += `<p>Indian Railways (IR) is the <span class="highlight">4th largest railway network in the world</span> (after the US, China, and Russia), with a route length of <strong>67,000 km</strong>, 7,000 stations, and a daily passenger count of 23 million (the largest in the world) and freight load of 3 million tonnes/day. IR operates 12,000+ passenger trains and 7,000+ freight trains daily. The network carried 3.5 billion passengers and 1.2 billion tonnes of freight in 2023-24. IR is the <strong>largest employer in India</strong> (12 lakh employees) and the largest government-owned utility in the country.</p>\n\n`;

c += `<p><strong>Railway Gauges</strong> &mdash; India has three railway gauges: <strong>Broad Gauge</strong> (1,676 mm, 95% of the network, the standard for all mainline passenger and freight services), <strong>Metre Gauge</strong> (1,000 mm, less than 2% of the network, mainly in Rajasthan, Gujarat, and the hill regions, being progressively converted to broad gauge under 'Project Unigauge'), and <strong>Narrow Gauge</strong> (762 mm and 610 mm, the hill railways of the Nilgiris (the Ooty Mountain Railway, NH 1, a UNESCO World Heritage site), the Darjeeling Himalayan Railway (the 'Toy Train', NH 2, a UNESCO World Heritage site), the Kalka-Shimla Railway (NH 3, a UNESCO World Heritage site), and Matheran Hill Railway).</p>\n\n`;

c += `<p><strong>Zonal Organisation</strong> &mdash; IR is divided into <strong>17 zones</strong>, the largest being the Northern Railway (Delhi), Western Railway (Mumbai), Central Railway (Mumbai), Eastern Railway (Kolkata), Southern Railway (Chennai), South Central Railway (Secunderabad), and North Eastern Railway (Gorakhpur). Each zone is divided into divisions (69 total). The zone headquarters are located at Mumbai (WR and CR), Kolkata (ER, SER), Chennai (SR), Delhi (NR), Secunderabad (SCR), Gorakhpur (NER), Lucknow (NCR), Patna (ECR), Bilaspur (SECR), Bangalore (SWR), Jaipur (NWR), Hajipur (ECR), and Guwahati (NFR &mdash; the Northeast Frontier Railway).</p>\n\n`;

c += `<p><strong>Freight Operations</strong> &mdash; Freight is the <span class="highlight">primary revenue earner for IR</span> (65% of revenue from 23% of the traffic). The major freight commodities are coal (45% of freight revenue), iron ore (15%), cement (10%), foodgrains (7%), fertilisers (5%), petroleum (5%), and containerised cargo (5%). IR's market share of freight has declined from 85% in 1950 to 27% today (lost to road transport), due to the flexibility and speed of road transport and the structural inefficiency of cross-subsidising passenger fares (passenger fares cover only 45% of passenger costs, the deficit of Rs 60,000 crore/yr being borne by freight revenues &mdash; this 'cross-subsidy' means freight tariffs are 50% higher than road, discouraging freight from shifting to rail). The <strong>Dedicated Freight Corridors (DFCs)</strong> are designed to solve this by segregating freight from passenger traffic, allowing faster heavy-haul freight trains at 100 km/hr and reducing the cost of freight transport.</p>\n\n`;

c += `<p><strong>Dedicated Freight Corridors (DFCs)</strong> &mdash; The <span class="highlight">largest railway infrastructure project in India</span> (Rs 1.2 lakh crore, with Japanese and World Bank funding). The DFCC (Dedicated Freight Corridor Corporation of India) is implementing two corridors:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Eastern DFC</strong> &mdash; 1,856 km from <strong>Ludhiana (Punjab) to Dankuni (West Bengal)</strong> (via Son Nagar in Bihar), covering the coal and steel belt of the Damodar Valley and the industrial region of Punjab-Haryana-UP-Bihar. It will carry double-stack container trains (5.15 m height, the tallest in the world), electrified with 2x25 kV AC, with a design speed of 100 km/hr and a load capacity of 13,000 tonnes. The Eastern DFC will decongest the Delhi-Howrah trunk route (the busiest passenger route in the world, with 100+ trains/day).</li>\n`;
c += `<li><strong>Western DFC</strong> &mdash; 1,506 km from <strong>Dadri (UP) to JNPT (Mumbai)</strong> (via Palanpur), connecting the Delhi-NCR region with Gujarat's ports (Mundra, Kandla, JNPT, Pipavav). It is designed for double-stack container trains (particularly the ISO containers from the DMIC) and high-speed freight (the 'JNPT-Dadri' freight corridor, with a target of reducing transit time from 72 to 24 hours). The Western DFC has been partially operational (the Rewari-Madar section) and is expected to be fully completed by 2025.</li>\n`;
c += `</ul>\n`;
c += `<p>A further four DFCs are planned: the <strong>East-West Corridor</strong> (Kharagpur-Pune-Mumbai, serving the Kolkata-Mumbai industrial axis), the <strong>North-South Corridor</strong> (Delhi-Chennai), the <strong>East Coast Corridor</strong> (Kharagpur-Vijayawada), and the <strong>Southern Corridor</strong> (Chennai-Goa).</p>\n\n`;

c += `<p><strong>High-Speed Rail</strong> &mdash; The <span class="highlight">Mumbai-Ahmedabad High-Speed Rail (MAHSR) Corridor</span> (508 km, 12 stations, costing Rs 1.1 lakh crore) is the first bullet train project in India, using the Japanese Shinkansen E5 series (320 km/hr operational speed, 350 km/hr design). Work began in 2020, with a target of 2028 (delayed from 2023 due to land acquisition issues in Gujarat, with only 60% of the required land acquired as of 2024). The project uses Japanese technology and financing (the Japan International Cooperation Agency/JICA, a 30-year loan at 0.1% interest, with a 15-year moratorium). MahaRail (the Mumbai-Ahmedabad High-Speed Rail Company) is the implementing agency. The <strong>RapidX</strong> (the Regional Rapid Transit System, the 'RRTS' of the NCR) is a semi-high-speed regional rail system connecting Delhi with Meerut (82 km, 180 km/hr operational speed, the first operational section was inaugurated in 2023), Alwar, Sonipat, and Panipat. The <strong>Vande Bharat Express</strong> (Train 18) is India's first indigenous semi-high-speed train (160 km/hr, designed and manufactured at the Integral Coach Factory, Chennai). Over 50 Vande Bharat services now connect major cities across India, with the Vande Bharat sleeper version under development.</p>\n\n`;

c += `<p><strong>Strategic Railway Projects</strong>:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>The Kashmir Rail Link (USBRL)</strong> &mdash; The <span class="highlight">Udhampur-Srinagar-Baramulla Rail Link</span> (USBRL, 272 km, completed in phases from 2005 to 2024), connecting the Kashmir Valley to the Indian railway network. The project includes the <strong>Chenab Bridge</strong> (1,315 m long, 359 m high above the Chenab River &mdash; the <strong>highest railway bridge in the world</strong>, taller than the Eiffel Tower), the <strong>Pir Panjal Tunnel</strong> (T-49, 11.2 km, the longest railway tunnel in India), and the <strong>Anjikhad Bridge</strong> (a steel truss bridge). The final section (Katra-Banihal, 111 km) was completed in 2024, enabling train travel from Delhi to Srinagar for the first time.</li>\n`;
c += `<li><strong>The Bogibeel Bridge (Assam)</strong> &mdash; The <span class="highlight">longest rail-road bridge in India</span> (4.94 km over the Brahmaputra River in Dibrugarh district, Assam), inaugurated in 2018. It is a double-decker bridge (the lower deck carries two railway lines, the upper deck carries a 3-lane road), built to improve connectivity between the north and south banks of the Brahmaputra and enhance military logistics to the Line of Actual Control (LAC) in Arunachal Pradesh.</li>\n`;
c += `<li><strong>The Northeast Connectivity</strong> &mdash; IR has completed the conversion of all railway lines in the Northeast to broad gauge under 'Project Unigauge' and is building new lines connecting the capitals of all 8 states, including the <strong>Jiribam-Tupul-Imphal</strong> line (connecting Manipur, with the world's tallest pier bridge at 141 m), the <strong>Dimapur-Zubza</strong> line (Nagaland), the <strong>Bhairbi-Sairang</strong> line (Mizoram), and the <strong>Dudhnoi-Mendu</strong> line (Meghalaya).</li>\n`;
c += `</ul>\n\n`;

c += `<h4>Water Transport</h4>\n\n`;
c += `<p>Water transport is the <span class="highlight">cheapest mode of transport</span> (at 1/5th the cost of road for bulk goods) and the most energy-efficient (one litre of fuel moves 105 tonne-km by water, compared to 35 by road and 85 by rail). However, its share in India's transport modal mix is low: <strong>inland waterways</strong> carry just 0.1% of freight, and <strong>coastal shipping</strong> carries 6% (compared to 35-40% in the US/Europe and 60% in Japan/Indonesia). India's 7,500 km coastline, 14,500 km of potentially navigable inland waterways, and 12 major ports give it an enormous but underutilised potential for water transport.</p>\n\n`;

c += `<p><strong>Inland Waterways</strong> &mdash; The <span class="highlight">National Waterways Act 2016</span> declared <strong>111 National Waterways (NWs)</strong>, having a total length of about 20,000 km, of which about 5,000 km is currently navigable by mechanised vessels. The <span class="highlight">largest and most important waterway</span> is <strong>NW-1: the Ganga-Bhagirathi-Hooghly River</strong> (1,620 km from Allahabad to Haldia), declared a National Waterway in 1986. The <strong>Jal Marg Vikas Project</strong> (JMVP, the 'Waterway Development Project', funded by the World Bank at Rs 5,400 crore) is upgrading the NW-1 for 1,500-tonne vessels with a guaranteed depth of 3 m, the construction of multi-modal terminals at Varanasi (completed 2018), Sahibganj, and Haldia, and the development of the Farakka Navigation Lock. The <strong>NW-2: the Brahmaputra River</strong> (891 km from Sadiya to the Bangladesh border) carries 2 million tonnes of freight (mainly crude oil to the Digboi refinery, coal, and foodgrains). The <strong>NW-3: the Kerala West Coast Canal</strong> (205 km from Kollam to Kottapuram &mdash; the 'Kerala Backwaters') is the only waterway with comprehensive navigational infrastructure (locks, bridges, and terminals) and carries a significant tourist traffic. The <strong>NW-4: the Godavari and Krishna rivers</strong> (1,095 km) in Andhra Pradesh and Telangana, and the <strong>NW-5: the Mahanadi-Brahmani-Baitarani rivers</strong> (623 km) in Odisha, are under development. The implementing agency is the <strong>Inland Waterways Authority of India (IWAI)</strong>, established in 1986.</p>\n\n`;

c += `<p><strong>Coastal Shipping and Ports</strong> &mdash; India's maritime sector handles <strong>95% of India's trade by volume and 70% by value</strong>, with a total port traffic of about 1.5 billion tonnes. The <strong>Sagarmala Project</strong> (launched 2015, the 'National Perspective Plan for Port-led Development') is the flagship programme for the maritime sector, with 600+ projects at a cost of Rs 8 lakh crore. The six pillars of Sagarmala are: (a) port modernisation (deepening of channels, mechanisation of cargo handling, improvement of port connectivity), (b) port connectivity (rail, road, and coastal shipping links to the hinterland), (c) port-led industrialisation (Petroleum, Chemical and Petrochemical Investment Regions/PCPIRs, Coastal Economic Zones/CEZs), (d) coastal community development (coastal tourism, fisheries infrastructure), (e) coastal shipping and inland waterways (promoting the 'coastal shipping' as a viable alternative to road/rail), and (f) skill development for the maritime sector.</p>\n\n`;

c += `<h4>Major Ports of India</h4>\n\n`;
c += `<p>India has <strong>12 Major Ports</strong> (under the Central Government, governed by the Major Port Trusts Act 1963) and <strong>200+ Minor/Intermediate Ports</strong> (under the state governments). The major ports handled about 800 million tonnes of cargo in 2023-24 (55% of national port traffic). The minor ports, led by <strong>Mundra</strong> (the largest private port in India, operated by Adani Ports, handling 160 mt/yr &mdash; larger than any single major port), account for the remaining 45% and are growing at 2x the rate of major ports due to higher efficiency and private investment.</p>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 8 (part 1). Total: ' + c.length + ' chars');
