$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 17: INDIAN FREEDOM STRUGGLE ===================== -->
<h2 id="freedom-struggle">17. Indian Freedom Struggle (1885-1947)</h2>

<p>The <span class="highlight">Indian Freedom Struggle</span> was the world's largest non-violent mass movement for independence, led by the Indian National Congress under the leadership of Mahatma Gandhi, Jawaharlal Nehru, Sardar Patel, Subhas Chandra Bose, and others. The struggle unfolded through four phases: the <strong>Moderate phase</strong> (1885-1905), the <strong>Swadeshi/Militant phase</strong> (1905-1915), the <strong>Gandhian phase</strong> (1915-1935), and the <strong>Final phase</strong> (1935-1947). The partition of Bengal (1905), the Jallianwala Bagh massacre (1919), the Rowlatt Act (1919), and the Civil Disobedience Movement (1930-34) were key turning points. The struggle culminated in Indian independence on 15 August 1947, along with the partition of India and Pakistan — the largest mass migration in human history (approximately 15 million people displaced, 1 million dead in communal violence).</p>

<h3>Phase 1: The Moderates (1885-1905)</h3>

<p>The Indian National Congress was founded in 1885 by <strong>A. O. Hume</strong> (a retired British civil servant) and was presided over by <strong>W. C. Bonnerjee</strong> (the first Congress president — 72 delegates attended the first session). The Moderate leaders — <strong>Dadabhai Naoroji</strong> (the first Indian to be elected to the British House of Commons, 1892; president of the Congress 1886, 1893, 1906; author of 'Poverty and Un-British Rule in India' — the classic statement of the 'Drain of Wealth' theory — he calculated that India's annual tribute to Britain was £30 million), <strong>Gopal Krishna Gokhale</strong> (Gandhi called him his political guru; founder of the Servants of India Society, 1905 — the first Indian social work organisation), <strong>Pherozeshah Mehta</strong> (known as the 'Uncrowned King of Bombay'), <strong>Surendranath Banerjee</strong> (founded the Indian Association in Calcutta, 1876 — the first political organisation in Bengal; his book 'A Nation in Making'), <strong>Madan Mohan Malaviya</strong> (founder of Banaras Hindu University, 1916), and <strong>Badruddin Tyabji</strong> (the first Muslim president of Congress, 1887).</p>

<p>The Moderates believed in <strong>constitutional methods</strong> — petitions, resolutions, press campaigns, and delegations to England. Their demands: Indianisation of the civil service (the simultaneous holding of ICS exams in India — the ICS exam was held only in London until 1922), expansion of legislative councils (the Indian Councils Act 1892 allowed some elected Indians to provincial councils but with very limited powers), reduction of military expenditure, protection of Indian industries, and abolition of the salt tax. The Moderates were not seeking independence — they wanted self-government within the British Empire ('Home Rule' similar to Canada and Australia). Their achievements were modest (the Indian Councils Act 1892, 1909 — the Minto-Morley Reforms), but they created the political infrastructure and the idea of a single Indian nation. The Congress was dominated by middle-class professionals (lawyers, journalists, teachers, doctors) and had little mass following.</p>

<h3>Phase 2: The Swadeshi and Militant Phase (1905-1915)</h3>

<p>The <strong>Partition of Bengal</strong> (16 October 1905) by Lord Curzon (Viceroy 1899-1905) was the turning point. Curzon divided the province of Bengal (population 78 million) into East Bengal and Assam (Muslim-majority) and West Bengal (Hindu-majority) — officially for administrative convenience (Bengal was too large to govern), but actually to 'divide and rule' the politically active Bengali Hindus. The <strong>Swadeshi Movement</strong> was launched in protest. Key features: boycott of British goods (especially Manchester cloth and Liverpool salt), promotion of indigenous industries (especially textiles — the revival of handloom weaving), public meetings, processions, and the singing of Bande Mataram (written by Bankim Chandra Chattopadhyay in 1882 — became the national song). The movement spread beyond Bengal to the rest of India. It also saw the emergence of <strong>extremist/militant nationalism</strong> under <strong>Bal Gangadhar Tilak</strong> ('Swaraj is my birthright and I shall have it'), <strong>Bipin Chandra Pal</strong> (the great orator who gave 600 speeches promoting Swadeshi), <strong>Lala Lajpat Rai</strong> (Punjab leader — deported to Burma for 6 months without trial), and <strong>Aurobindo Ghosh</strong> (the revolutionary philosopher who escaped to Pondicherry and became a spiritual teacher).</p>

<p>The <strong>Muslim League</strong> was founded in 1906 (Dhaka, by Nawab Salimullah of Dhaka and Aga Khan) — initially loyal to the British, it demanded separate electorates for Muslims (granted in the Government of India Act 1909, Minto-Morley Reforms — Muslims were given separate electorates within the legislative councils). The <strong>Surat Split</strong> (1907) of the Congress into Moderates (Gokhale, Mehta) and Extremists (Tilak, Pal, Lajpat Rai) — the Moderates forced the Extremists out. The Split lasted until 1916 (Lucknow Pact) when the two wings reunited. The <strong>Morley-Minto Reforms</strong> (1909) introduced separate electorates for Muslims — the first official recognition of Muslims as a separate political community. The <strong>Delhi Durbar</strong> (1911, King George V) announced the reversal of Bengal's partition (the partition was annulled) and the transfer of the capital from Calcutta to Delhi (announced at the Coronation Durbar). The <strong>Ghadar Party</strong> (1913) was formed by Indian revolutionaries in the USA (Sikh farmers in California) under Lala Hardayal to overthrow British rule by armed revolution. The <strong>Komagata Maru incident</strong> (1914) — a ship of 376 Indian passengers (mostly Sikhs from Punjab) was turned back from Canada; upon arrival in Calcutta, they were fired upon by British police, killing 20. The <strong>Home Rule League Movement</strong> (1916) by Annie Besant and Tilak demanded self-government for India within the British Empire. Besant's Home Rule League was especially successful in Madras (she was the first woman president of the Congress in 1917).</p>

<h3>Phase 3: The Gandhian Phase (1915-1935)</h3>

<p><strong>Mohandas Karamchand Gandhi</strong> returned to India from South Africa (where he had led the Indian community against racial discrimination, 1893-1914) in January 1915. He was guided by his political guru Gopal Krishna Gokhale, who advised him to observe India for a year before speaking. His first major success was the <strong>Champaran Satyagraha</strong> (1917, Bihar) — he forced the British to abolish the exploitative tinkathia system (forced indigo cultivation — indigo planters forced peasants to grow indigo on 3/20th of their land, the 'tinkathia' system). Then the <strong>Kheda Satyagraha</strong> (1918, Gujarat) — he led the peasants of Kheda district in refusing to pay land tax due to crop failure. Then the <strong>Ahmedabad Mill Strike</strong> (1918) — he led textile mill workers in demanding a 35% wage increase; he used fasting for the first time as a political weapon. He adopted the title of <strong>Mahatma</strong> (great soul) — first used by the poet Rabindranath Tagore.</p>

<p><strong>The Rowlatt Satyagraha</strong> (1919) — the British passed the Rowlatt Act (the Anarchical and Revolutionary Crimes Act) in March 1919, allowing trial without jury and detention without trial for suspected revolutionaries. Gandhi called for a nationwide <strong>hartal</strong> (strike) on 6 April 1919. This was followed by the <strong>Jallianwala Bagh Massacre</strong> (13 April 1919, Amritsar, Punjab) — General Reginald Dyer ordered troops to fire on an unarmed crowd of 20,000 people (men, women, children) celebrating the Sikh festival of Baisakhi in a walled garden (Jallianwala Bagh). 379 people were killed and 1200 wounded (official figures; Indian sources estimate 1000+ killed). Dyer was relieved of command but was praised in the British House of Lords and received £20,000 from the public in Britain (collected by the Morning Post). Gandhi said the massacre 'shook the foundations of the British empire.' The <strong>Hunter Commission</strong> (appointed by the British) condemned Dyer's actions but no punishment was given.</p>

<p><strong>Non-Cooperation Movement</strong> (1920-1922) — the first mass movement led by Gandhi. The movement included: surrender of titles and honours, boycott of legislatures (elections were boycotted in 1921), courts, government schools and colleges, foreign goods, and promotion of hand-spinning (khadi) as a symbol of self-reliance. The <strong>Khilafat Movement</strong> (1919-1924) was merged with the Non-Cooperation Movement — Indian Muslims under the Ali brothers (Shaukat Ali and Muhammad Ali) led the protest against the British abolition of the Turkish Caliphate; Gandhi saw this as a great opportunity for Hindu-Muslim unity. The movement was massive — prisons overflowed. But it was suspended by Gandhi on 12 February 1922 after the <strong>Chauri Chaura incident</strong> (5 February 1922, Gorakhpur, UP) — a mob of peasants killed 22 policemen by setting the police station on fire. Gandhi insisted on non-violence as the core principle; he was arrested in March 1922 and sentenced to 6 years (served only 2 years — released in 1924 for appendicitis).</p>

<p><strong>Simon Commission</strong> (1928) — the British sent a commission under Sir John Simon to review constitutional reforms, but with no Indian members. Indians boycotted it (the slogan 'Simon Go Back' was coined). When the Commission visited Lahore, Lala Lajpat Rai was brutally lathi-charged (baton-charged) and died of his injuries. This led to the <strong>Dandi March</strong> — the climax of the nationalist movement. <strong>Purna Swaraj</strong> (Complete Independence) was demanded at the 1929 Congress session at Lahore under the presidency of Jawaharlal Nehru — 26 January 1930 was celebrated as the first Independence Day (now Republic Day).</p>

<p><strong>Civil Disobedience Movement</strong> (1930-1934) — Gandhi launched the <strong>Dandi March</strong> (12 March-6 April 1930) — he walked 240 miles from Sabarmati Ashram to Dandi on the Gujarat coast with 78 followers. At Dandi, he broke the salt law by picking up a handful of salt (the law gave the British a monopoly on salt manufacture). This was a brilliantly symbolic act — tax on salt affected every Indian, rich and poor. Thousands made salt illegally, and the movement spread across India. Gandhi was arrested (May 1930). The <strong>First Round Table Conference</strong> (London, 1930-31) was boycotted by the Congress. The <strong>Gandhi-Irwin Pact</strong> (5 March 1931) — Gandhi agreed to suspend the movement and attend the <strong>Second Round Table Conference</strong> (London, September-December 1931) — but the conference failed to produce a constitutional scheme acceptable to the Congress, especially on the issue of separate electorates for minorities (the Communal Award of 1932 by Ramsay Macdonald gave separate electorates to Muslims, Sikhs, Christians, Anglo-Indians, and the Depressed Classes/Scheduled Castes). Gandhi opposed the 'separate electorate' for the Depressed Classes (it would divide Hindu society) and began a 'fast unto death' in Yerawada Jail (September 1932). The <strong>Poona Pact</strong> (24 September 1932) between B. R. Ambedkar (representing the Depressed Classes) and Gandhi resulted in reservation of 148 seats for the Depressed Classes in provincial legislatures, but within the general Hindu electorate. The movement was withdrawn in 1934.</p>

<h3>Phase 4: The Final Phase (1935-1947)</h3>

<p>The <strong>Government of India Act 1935</strong> established provincial autonomy (granting elected Indian legislatures control over certain ministries, but with reserved British powers over defence, foreign affairs, and the budget). The 1937 elections brought Congress ministries in 7 of 11 provinces (Congress had a majority in UP, Bihar, Orissa, Madras, Central Provinces, and Bombay; and coalition governments in Assam and NWFP). The Congress ministries resigned in 1939 after Viceroy Lord Linlithgow declared India at war on the side of Britain without consulting the Congress — the <strong>August Offer</strong> (1940) and <strong>Cripps Mission</strong> (1942) failed to get Congress support for the war. The Muslim League under <strong>Muhammad Ali Jinnah</strong> (who had left the Congress in 1920 and took over the Muslim League in 1934) passed the <strong>Lahore Resolution</strong> (23 March 1940) demanding 'Pakistan' — separate independent states for Muslims in the north-west and north-east of India. The <strong>Quit India Movement</strong> (1942) — launched by Gandhi on 8 August 1942 at the Congress session in Bombay (the 'Do or Die' speech: 'I have only one pistol in this fight of truth and non-violence — the weapon of the people. I ask you to keep the light of freedom burning... Do or Die.').</p>

<p>The British arrested Gandhi, Nehru, and all Congress leaders immediately. The movement became leaderless and violent — there were attacks on government buildings, railways, and police stations. Underground leaders (Jayaprakash Narayan, Aruna Asaf Ali, Ram Manohar Lohia) organised guerrilla resistance. The movement was suppressed by force — 100,000 were arrested, 1000 killed. The <strong>Indian National Army (INA)</strong> under <strong>Subhas Chandra Bose</strong> (Netaji) — formed in 1943 with Japanese support in Singapore. The INA had 50,000 soldiers, including former British Indian Army soldiers taken as POWs. The INA's motto: 'Give me blood, and I will give you freedom.' The INA fought the British in Burma (the Battle of Imphal, 1944) but was defeated. The <strong>INA trials</strong> at Red Fort (1945-46) stirred massive public sympathy. The INA prisoners were defended by Bhulabhai Desai, Jawaharlal Nehru, and Tej Bahadur Sapru. The British sentenced three commanders to death but commuted them under public pressure. The INA demonstrated that Indians could fight the British — the British realised they could no longer rely on the loyalty of the Indian Army.</p>

<p>The <strong>Cabinet Mission Plan</strong> (1946) proposed a united India with a weak federal centre and provincial autonomy — both Congress and Muslim League initially accepted, but Nehru's statement rejecting the grouping of provinces led Jinnah to withdraw support and call for <strong>Direct Action Day</strong> (16 August 1946) — communal violence killed 5000 in Calcutta. Violence spread to Noakhali (East Bengal), Bihar, UP, and Punjab. Lord Mountbatten (the last Viceroy, appointed February 1947) decided that partition was the only solution. The <strong>Mountbatten Plan</strong> (3 June 1947) led to the <strong>Indian Independence Act 1947</strong> (passed 18 July 1947). India and Pakistan became independent on 14/15 August 1947. The partition created one of the largest and bloodiest forced migrations in history — 15 million people crossed the new borders, and 1 million died in the violence. <strong>Jawaharlal Nehru</strong> became the first Prime Minister of India; <strong>Muhammad Ali Jinnah</strong> became the first Governor-General of Pakistan; <strong>Lord Mountbatten</strong> stayed on as India's first Governor-General (until June 1948); <strong>Sardar Vallabhbhai Patel</strong> (the 'Iron Man of India') unified the 562 princely states into the Indian Union through a combination of diplomacy and military force.</p>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 17 written."
