$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 18: POST-INDEPENDENCE INDIA ===================== -->
<h2 id="post-independence">18. Post-Independence India (1947-2025)</h2>

<p>The <span class="highlight">History of Independent India</span> is the story of the world's largest democracy navigating the challenges of nation-building: integration of 565 princely states, the framing of the Constitution, linguistic reorganisation of states, economic development, foreign policy (Non-Alignment), wars with Pakistan and China, and the transition from a socialist to a market economy. India's journey from a poor, war-torn, famine-ridden nation in 1947 to the world's 5th largest economy in 2025 (projected) has been remarkable, though marred by persistent problems: poverty, communal violence, caste discrimination, corruption, and regional disparities.</p>

<h3>Integration of Princely States and the Making of the Constitution</h3>

<p><strong>Sardar Vallabhbhai Patel</strong> (the first Deputy Prime Minister and Home Minister) integrated the 562 princely states between 1947-1949 through the <strong>Instrument of Accession</strong> (the states surrendered defence, foreign affairs, and communications to India but retained internal autonomy). Three states resisted: <strong>Junagadh</strong> (its Muslim nawab acceded to Pakistan; India annexed it through a plebiscite in February 1948), <strong>Hyderabad</strong> (the Nizam refused accession; India annexed it through <strong>Operation Polo</strong>, September 1948 — a 5-day 'police action' by the Indian Army), and <strong>Jammu and Kashmir</strong> (Maharaja Hari Singh signed the Instrument of Accession to India in October 1947 after Pakistani tribesmen invaded Kashmir; the resulting <strong>First Indo-Pak War</strong> established the Line of Control; the UN-sponsored ceasefire of 1 January 1949 left Kashmir divided). The <strong>Constituent Assembly</strong> (headed by Dr. B. R. Ambedkar as Chairman of the Drafting Committee) completed the Constitution on 26 November 1949 (the longest written constitution in the world, 395 articles, 8 schedules originally, now 448 articles and 12 schedules). The Constitution came into effect on <strong>26 January 1950</strong> (Republic Day) — establishing India as a sovereign, socialist, secular, democratic republic with a parliamentary system of government.</p>

<h3>Jawaharlal Nehru Era (1947-1964)</h3>

<p><strong>Jawaharlal Nehru</strong>, India's first Prime Minister, shaped the political and economic framework of independent India. Key achievements: <strong>Non-Alignment</strong> (India did not join either the US-led NATO or the Soviet-led Warsaw Pact; Nehru, along with Tito of Yugoslavia, Nasser of Egypt, Sukarno of Indonesia, and Nkrumah of Ghana, founded the Non-Aligned Movement in 1961). <strong>Planned economy</strong> — the <strong>Planning Commission</strong> was established in 1950, and the <strong>Five Year Plans</strong> (based on the Soviet model) guided economic development: the First Plan (1951-56) focused on agriculture (the Bhakra Nangal Dam, Hirakud Dam); the Second Plan (1956-61) focused on heavy industry (steel plants at Bhilai, Durgapur, Rourkela; the Hydro-Electric projects; the Hindustan Machine Tools). <strong>Linguistic Reorganisation of States</strong> — the States Reorganisation Commission (1956) reorganised states on linguistic lines (14 states and 6 union territories). The <strong>Panchsheel</strong> principles (Five Principles of Peaceful Coexistence) were signed with China (1954). The <strong>Sino-Indian War</strong> (1962) — China invaded Ladakh and the North-East Frontier Agency (NEFA, now Arunachal Pradesh); the Indian Army was humiliatingly defeated. Nehru was deeply affected by the war and died in 1964.</p>

<h3>Lal Bahadur Shastri and Indira Gandhi (1964-1984)</h3>

<p><strong>Lal Bahadur Shastri</strong> (1964-66) — led India through the <strong>Second Indo-Pak War</strong> (1965). The war ended with the Tashkent Agreement (January 1966, by Soviet mediation). Shastri gave the slogan 'Jai Jawan, Jai Kisan' (Hail the soldier, Hail the farmer). He died suddenly in Tashkent after signing the agreement.</p>

<p><strong>Indira Gandhi</strong> (1966-1977, 1980-1984) — the first and only female Prime Minister of India. Her era was marked by: the <strong>Bangladesh Liberation War</strong> (1971) — India supported the Bengali rebellion against Pakistan; the <strong>Third Indo-Pak War</strong> led to the creation of Bangladesh (the Instrument of Surrender of the Pakistani Army signed in Dhaka on 16 December 1971). The <strong>Shimla Agreement</strong> (1972) established the Line of Control in Kashmir. <strong>Nationalisation of banks</strong> (1969 — 14 major banks were nationalised) and the <strong>abolition of princely privileges</strong> (the 26th Amendment, 1971 — the Privy Purse was abolished). The <strong>Indo-Soviet Treaty</strong> (1971) — a 20-year treaty of friendship with the USSR. The <strong>Nuclear test</strong> (1974) — India conducted its first nuclear test ('Smiling Buddha') at Pokhran, Rajasthan; India became a nuclear power. The <strong>Emergency</strong> (25 June 1975 - 21 March 1977) — Indira Gandhi declared an internal emergency, suspending civil liberties, arresting opposition leaders (JP Narayan, Morarji Desai, Atal Bihari Vajpayee), censoring the press, and forcibly implementing birth control (the coercive sterilisation campaign under Sanjay Gandhi was the Emergency's most unpopular policy, alienating Muslims and poor voters). After the Emergency was lifted (March 1977 elections), Indira Gandhi and the Congress were defeated by the <strong>Janata Party</strong> (the first non-Congress government). The Janata government (1977-79) under Prime Minister <strong>Morarji Desai</strong> fell due to internal conflicts. Indira Gandhi returned to power in 1980. Her second term was marked by the <strong>Punjab insurgency</strong> and the <strong>Operation Blue Star</strong> (June 1984) — the Indian Army entered the Golden Temple in Amritsar to flush out Sikh militants led by Jarnail Singh Bhindranwale. The operation killed 500+ (both militants and civilians) and damaged the Akal Takht. Indira Gandhi was assassinated by her Sikh bodyguards on 31 October 1984. The assassination sparked anti-Sikh riots in Delhi and other parts of India (the deadliest communal riots since Partition — 3,000+ Sikhs were killed; the Congress government was accused of involvement).</p>

<h3>Rajiv Gandhi and the Era of Coalitions (1984-2014)</h3>

<p><strong>Rajiv Gandhi</strong> (1984-1989) — swept to power by a sympathy wave. His achievements: introduced the <strong>New Education Policy</strong> (1986 — gave grants to the IITs, IIMs, and Central Universities), brought the <strong>Anti-Defection Law</strong> (1985 — preventing MLAs from switching parties), the <strong>Punjab Accord</strong> (1985 with Sant Longowal — elections and peace in Punjab), the <strong>Assam Accord</strong> (1985 — ended the Assam Movement against illegal Bangladeshi immigrants), introduced computerisation and the telecom revolution ('The Rajiv Gandhi years saw the arrival of the computer and the fax machine'), and the <strong>Panchayati Raj Act</strong> (73rd and 74th Amendments, 1992, passed after his death). But he faced the <strong>Bofors scandal</strong> (allegations of kickbacks in a Swedish howitzer contract), the <strong>Shah Bano case</strong> (he overturned the Supreme Court's judgment granting alimony to an 80-year-old Muslim woman — seen as Muslim-appeasement and created the Babri Masjid issue), and the <strong>LTTE conflict</strong> (India sent the IPKF to Sri Lanka, 1987-1990, to enforce the Indo-Sri Lanka Accord; the peacekeeping operation was a failure). Rajiv Gandhi was assassinated by an LTTE suicide bomber in Sriperumbudur (Tamil Nadu) on 21 May 1991 during an election campaign.</p>

<p>The <strong>Liberalisation Era</strong> (1991 onwards) — the 1991 balance of payments crisis (India had only 2 weeks of foreign exchange reserves) forced the government of Prime Minister <strong>Narasimha Rao</strong> and Finance Minister <strong>Manmohan Singh</strong> to implement economic reforms: the New Economic Policy (1991) — devaluation of the rupee, abolition of the license raj (industrial licensing was abolished for most industries), opening up to foreign investment, reduction of import tariffs, and privatisation of public sector enterprises. India's economy grew at 6-7% annually for the next two decades. The <strong>Babri Masjid demolition</strong> (6 December 1992) — the 16th-century mosque in Ayodhya was demolished by a mob of 150,000 kar sevaks (Hindu volunteers) who believed the site was the birthplace of Lord Rama. This led to the worst communal riots since 1947 (the 1993 Bombay blasts were a retaliatory act by the Mumbai underworld). The <strong>Hindu nationalist Bharatiya Janata Party (BJP)</strong> emerged as a major force after the demolition. The 1990s saw coalition governments: the <strong>United Front</strong> (1996-1998), the <strong>BJP-led National Democratic Alliance (NDA)</strong> under Prime Minister Atal Bihari Vajpayee (1998-2004) — the <strong>Pokhran II</strong> nuclear tests (May 1998, 5 nuclear explosions), the <strong>Kargil War</strong> (May-July 1999 — Pakistani soldiers and Kashmiri militants infiltrated into Indian territory in the Kargil district; India pushed them back, India lost 527 soldiers; Operation Vijay was a military success but exposed intelligence failures). The <strong>United Progressive Alliance (UPA)</strong> under Prime Minister Manmohan Singh (2004-2014) — the MGNREGA (2005 — 100 days of employment guarantee for rural households), the Right to Information Act (2005), the Indo-US Nuclear Deal (2008 — gave India access to nuclear fuel and technology despite not signing the NPT), and the 2G spectrum scam (2010 — the Comptroller and Auditor General estimated a 'presumptive loss' of ₹1.76 lakh crore in telecom spectrum allocation).</p>

<h3>Contemporary India (2014-2025)</h3>

<p><strong>Narendra Modi</strong> (Prime Minister from 2014) — the BJP won a majority in the 2014 (282 seats), 2019 (303 seats), and 2024 (240 seats — NDA coalition) Lok Sabha elections. Major policies: the <strong>Goods and Services Tax (GST)</strong> (2017 — India's biggest tax reform, implemented 1 July 2017, unified indirect taxes across states), the <strong>Demonetisation</strong> (8 November 2016 — the government banned ₹500 and ₹1000 notes, 86% of the currency in circulation, to combat black money, corruption, and counterfeit currency; the move caused massive hardship, cash shortages, and deaths of daily wage labourers; the economic impact was debated — GDP growth slowed to 6.6% in 2017). The <strong>Artillery of Abrogation of Article 370</strong> (5 August 2019 — the special status of Jammu and Kashmir was revoked, and the state was reorganised into two union territories — Jammu and Kashmir, and Ladakh). The <strong>Citizenship Amendment Act (CAA)</strong> (2019 — fast-track citizenship for non-Muslim illegal immigrants from Pakistan, Afghanistan, and Bangladesh) — led to widespread protests across India (the Shaheen Bagh protest, the Jamia Millia Islamia and Aligarh Muslim University student protests, and the deaths of 80 people in Uttar Pradesh violence). The <strong>Ayodhya Ram Temple</strong> (the Bhoomi Pujan was performed on 5 August 2020 by PM Modi, and the temple was opened to the public on 22 January 2024) — and the <strong>National Education Policy 2020</strong> (replaced the 1986 education policy with emphasis on multidisciplinary learning, mother tongue instruction, and vocational training). The COVID-19 pandemic (2020-2023) — India experienced the world's largest lockdown (21 March 2020, 1.3 billion people), a devastating second wave (April-May 2021, with shortages of oxygen, hospital beds, and vaccines; 400,000+ official deaths; likely 3-4 million actual excess deaths — a WHO report suggested 4.7 million excess deaths). India's foreign policy under Modi has been 'multi-aligned' — strengthening ties with the USA (the 'Quad' with US, Japan, Australia; the iCET), maintaining a balancing act with Russia (continued oil purchases after the Ukraine war, 2022-25), and pushing back against China (the 2020 Galwan Valley border clashes killed 20 Indian soldiers; the Doklam standoff 2017).</p>

<p>India in 2025 is the world's 5th largest economy (nominal GDP $4.1 trillion), the most populous country (1.44 billion), with a rapidly growing digital economy (the UPI — Unified Payments Interface processes 10 billion+ transactions per month, the world's highest), a leading space power (the Chandrayaan-3 moon landing, August 2023 — India became the 4th country to land on the moon and the first to land on the lunar south pole), and the world's largest democracy (910 million registered voters in the 2024 elections). Key challenges remain: unemployment (especially among youth), inequality (the top 1% owns 40%+ of the wealth), communal polarisation, environmental degradation (air pollution in Delhi is the world's worst), and agricultural distress (the farmer protests of 2020-2021 against the farm laws).</p>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 18 written."
