$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 9: EARLY MEDIEVAL & HARSHAVARDHANA ===================== -->
<h2 id="early-medieval">9. Early Medieval India & Harshavardhana (550-750 CE)</h2>

<p>The <span class="highlight">Early Medieval period</span> (c. 550-750 CE) in North India was characterised by political fragmentation, the dominance of Brahmanical feudalism, the decline of long-distance trade, and the emergence of new regional identities. After the collapse of the Guptas, no single empire controlled northern India. Instead, several regional kingdoms competed for supremacy, most notably <strong>Harshavardhana</strong> of Thanesar/Kannauj (c. 606-647 CE), the last great north Indian ruler before the Islamic invasions. This period also saw the rise of powerful kingdoms in the Deccan (the <strong>Chalukyas of Badami</strong>, the <strong>Pallavas of Kanchipuram</strong>, and the <strong>Rashtrakutas of Manyakheta</strong>) and South India (the <strong>Cholas</strong>, <strong>Cheras</strong>, and <strong>Pandyas</strong>). The period is documented by three major sources: the Chinese pilgrim <strong>Xuanzang (Hiuen Tsang)</strong> who visited India 629-645 CE and wrote detailed accounts of political, religious, and social conditions; <strong>Bana Bhatta's Harshacharita</strong> (the biography of Harsha); and numerous copper-plate inscriptions of the various dynasties.</p>

<h3>Harshavardhana (606-647 CE)</h3>

<p><strong>Pushyabhuti Dynasty</strong>: The Pushyabhutis of Thanesar (modern Kurukshetra district, Haryana) emerged as a regional power after the Gupta decline. <strong>Prabhakaravardhana</strong> (c. 580-605 CE) was the first significant ruler — his daughter Rajyashri married the Maukhari king Grahavarman of Kannauj. On Prabhakaravardhana's death, his elder son <strong>Rajyavardhana</strong> succeeded for a brief period (605-606 CE) but was killed by the Gupta king Devagupta of Malwa (who had also killed Grahavarman and imprisoned Rajyashri). At age 16, <strong>Harshavardhana</strong> (literally 'Joyous Prosperity') became king of Thanesar. He rescued his sister Rajyashri from the Vindhya forests where she had fled, married her to the Maukhari prince (or kept her as a regent), and united the Pushyabhuti and Maukhari kingdoms with his new capital at <strong>Kannauj</strong> (Kanyakubja on the Ganga — strategically located to control the Gangetic plain). He then waged a 6-year campaign (c. 606-612 CE) against the Gupta king Devagupta of Malwa and defeated him.</p>

<p>Harsha's empire at its peak covered <span class="highlight">most of northern India</span>: Punjab, Uttar Pradesh, Bihar, Bengal (he conquered Magadha and parts of Gauda/Bengal), Odisha, Malwa, Gujarat, and Rajasthan. He attempted to conquer the Deccan but was repulsed by the Chalukya king <strong>Pulakeshin II</strong> of Badami (the Aihole inscription of Pulakeshin II boasts of defeating Harsha in a battle on the Narmada — c. 620 CE — 'Harsha, whose elephants were frightened by the raging ocean of his army'). This is the only major military defeat Harsha suffered. Harsha's administration was based on the Gupta model but was more decentralised. He maintained a large army (60,000 war elephants, 100,000 cavalry — according to Xuanzang) and a well-organised bureaucracy. Land grants to Brahmins and Buddhist monasteries continued under a more structured feudal hierarchy — the term <strong>samanta</strong> (feudatory lord) became standardised.</p>

<p>Harsha was a <span class="highlight">patron of learning and culture</span>. He himself was a poet and playwright — three plays survive: <strong>Ratnavali</strong> (a love story), <strong>Nagananda</strong> (based on the story of the serpent Jivatoshaka sacrificing himself to Garuda, influenced by Buddhism — the Jataka about Jimutavahana), and <strong>Priyadarshika</strong> (a romantic comedy). He held a great cultural assembly at <strong>Kannauj</strong> in 643 CE, attended by Xuanzang, 18 tributary kings, 3000 monks (Buddhist, Hindu, Jain), and 1000 scholars — a magnificent imperial spectacle. He was a patron of Nalanda University (endowing 100 villages for its maintenance — Xuanzang studied there for 5 years). Harsha also hosted the <strong>Prayag Assembly</strong> at Allahabad every 5 years (the Mahamoksha Parishad or Kumbha Mela tradition?), where he distributed all his accumulated wealth to the poor — Xuanzang witnessed the assembly in 644 CE and described Harsha giving away everything, even his personal jewels. After Harsha's death (647 CE), his empire collapsed — the <strong>Arunashas</strong> (Chinese: Wang Hiuen-tse? Actually, a Chinese envoy named Wang Xuance came to Harsha's court in 646 CE, and after Harsha's death, the usurper Arjuna/Aluonu attacked Wang Xuece, who escaped to Tibet and returned with Tibetan and Nepalese troops to defeat Aluonu and take him captive to China — a remarkable story of Chinese-Tibetan intervention in India!).</p>

<h3>Harsha's Religion</h3>

<p>Harsha was a <span class="highlight">Vaishnava Hindu</span> in his personal faith (his seals describe him as 'a devotee of Shiva' and 'a worshipper of the sun' — his Harshacharita confirms he worshipped Surya, Shiva, and Buddha), but he was also a great patron of Buddhism (he built stupas, endowed monasteries, supported Nalanda, and hosted Buddhist councils). His seals show the figures of Lakshmi, Nandi (Shiva's bull), and the Garuda (Vishnu's crest). This syncretic attitude was typical of the period — kings patronised multiple religions to maintain social harmony. The Buddhist Mahayana tradition in particular flourished under Harsha (the Buddha was worshipped as a deity, especially in Nalanda). Xuanzang was honoured by Harsha and participated in the Kanauj assembly (the Buddhists won the debate).</p>

<h3>Major Kingdoms of the Deccan and South (550-750 CE)</h3>

<p><strong>Chalukyas of Badami (Vatapi)</strong> (c. 540-757 CE): Founded by <strong>Pulakeshin I</strong> (c. 540-566 CE) who fortified Badami (Bijapur district, Karnataka — a spectacular sandstone gorge fortress). The greatest ruler was <strong>Pulakeshin II</strong> (c. 610-642 CE) — the most powerful Deccan king of his time. The <strong>Aihole Inscription</strong> (recorded by court poet Ravikirti, composed in Sanskrit — the earliest dated Sanskrit inscription in the Deccan, 634 CE) details his conquests: he defeated the Kadambas of Banavasi, the Gangas of Mysore, the Alupas of South Canara, Harsha on the Narmada, and the Pallava king Mahendravarman I. He sent an embassy to the Persian king Khusrau II (recorded in Persian sources — the Tarikh-i-Tabari). His reign was a period of great architectural activity: the <strong>cave temples at Badami</strong> (the oldest surviving Hindu cave temples — Cave 3 dated to 578 CE, with a massive carved Varaha panel and the original paintings; Cave 1 with the famous Nataraja/Shiva dancing). The nearby <strong>megalithic temples at Aihole</strong> (the Lad Khan Temple, the Durga Temple — though the Durga Temple is actually a Buddhist chaitya-griha originally; 70+ temples, a 'museum of temple architecture') and <strong>Pattadakal</strong> (a UNESCO World Heritage Site with 10 temples — the Virupaksha Temple built by Queen Lokamahadevi to commemorate her husband Vikramaditya II's victory over Kanchipuram; the Mallikarjuna Temple). Pulakeshin II was defeated and killed by the Pallava king Narasimhavarman I (the Mamalla Pallava) in 642 CE at Badami. The Chalukyas recovered under <strong>Vikramaditya I</strong> (c. 654-681 CE) and <strong>Vikramaditya II</strong> (c. 733-746 CE) who conquered Kanchipuram three times. The dynasty ended with the rise of the Rashtrakutas (Dantidurga overthrew Kirtivarman II in 757 CE).</p>

<p><strong>Pallavas of Kanchipuram</strong> (c. 275-897 CE): The Pallavas ruled the Tondaimandalam region (northern Tamil Nadu and southern Andhra). They emerged as a major power in the 6th century under <strong>Mahendravarman I</strong> (c. 600-630 CE) — a great builder, musician, and poet (the Sanskrit farce Mattavilasa Prahasana is attributed to him). He was defeated by Pulakeshin II but was a great architectural innovator: he built the <strong>rock-cut cave temples at Mahabalipuram (Mamallapuram)</strong> and <strong>Mahendravadi</strong> (the Mandagapattu inscription of Mahendravarman I famously declares: 'Without using brick, timber, metal, or mortar' — it was a rock-cut temple dedicated to Brahma, Vishnu, and Shiva; a bold departure). His son <strong>Narasimhavarman I (Mamalla)</strong> (c. 630-668 CE) defeated the Chalukya king Pulakeshin II, occupied Badami, and assumed the title 'Vatapikonda' (Conqueror of Vatapi/Badami). He built the magnificent <strong>Pancha Rathas</strong> (Five Chariots — each a monolithic temple carved from a single rock in the shape of a ratha/chariot, dedicated to the Pandavas and Draupadi; the Dharmaraja Ratha, Bhima Ratha, Arjuna Ratha, Nakula-Sahadeva Ratha, and Draupadi Ratha) and the <strong>Descent of the Ganges</strong> (Arjuna's Penance — the world's largest bas-relief, a massive rock sculpture measuring 30m × 13m, depicting celestial beings, animals, and ascetics, with the descent of the holy river Ganga from the heavens). Later Pallava king <strong>Rajasimha</strong> (c. 700-728 CE) built the <strong>Shore Temple at Mahabalipuram</strong> (the oldest structural temple in Tamil Nadu, a UNESCO World Heritage Site). The Pallavas were great patrons of Sanskrit (unlike the Tamil Pandyas and Cholas who patronised Tamil). Dandin, the author of the Dashakumaracharita, was the court poet of Narasimhavarman II. The Pallava period also saw the rise of the <strong>Bhakti movement</strong> in Tamil Nadu: the 12 Alvars (Vaishnava saints — Andal, Nammalvar, Periyalvar, etc.) and 63 Nayanars (Shaiva saints — Appar, Sambandar, Manikkavasagar, Sundarar) composed devotional poetry in Tamil that shaped South Indian religious culture. The Pallavas were replaced by the Cholas under Aditya I (c. 897 CE).</p>

<h3>Economic and Social Changes in the Early Medieval Period</h3>

<p>The Early Medieval period saw the deepening of the <strong>land-grant (brahmadeya/agrahara) system</strong> — Brahmins, temples, and monasteries were granted tax-free land, which led to the proliferation of small-scale, subsistence agriculture and the decline of urban centres and long-distance trade. This is the period of <strong>Indian feudalism</strong> (a controversial term — R. S. Sharma's theory: the landed intermediaries and the hieratic systems of sub-infeudation led to political fragmentation, a closed village economy, and cultural decentralisation). <strong>Urban centres declined</strong> — most major Gupta-period cities (Pataliputra, Ujjain, Mathura) declined in population and importance. <strong>Trade guilds</strong> (shrenis) continued but were less powerful. <strong>Temple economy</strong> emerged as a major institution — temples became large landowners, employers, and redistributors of wealth; temple centres (Bhubaneswar, Puri, Kanchipuram, Madurai, Sri Rangam) became the new urban nuclei. The <strong>jati system</strong> became more rigid and complex with the proliferation of sub-castes based on occupation and region. <strong>Women's status</strong> continued to decline — the Brihaspati Smriti and Katyayana Smriti (both Gupta/post-Gupta) limited women's property rights, emphasised their dependence on men, and elevated the cult of pativrata (the ideal wife). The medieval practice of sati (widow-burning) became more common — the earliest Rajput sati stones (sati memorials) date from this period.</p>

<div class="example-box"><div class="ex-title">Key Inscriptions for UPSC</div><div class="ex-text">&#8226; <strong>Prayaga Prashasti</strong> (Allahabad Pillar Inscription) — Samudragupta, composed by Harishena<br>&#8226; <strong>Junagadh Rock Inscription</strong> — Skandagupta (repair of Sudarshana lake)<br>&#8226; <strong>Aihole Inscription</strong> — Pulakeshin II, composed by Ravikirti (634 CE)<br>&#8226; <strong>Mandagapattu Inscription</strong> — Mahendravarman I Pallava<br>&#8226; <strong>Gwalior Inscription</strong> — Mihirakula Huna ruler<br>&#8226; <strong>Nasik Prashasti</strong> — Gautamiputra Satakarni, composed by his mother<br>&#8226; <strong>Mandasor Inscription</strong> — Yashodharman (victory over Mihirakula)<br>&#8226; <strong>Rummindei Pillar Inscription</strong> — Ashoka's visit to Lumbini</div></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 9 written."
