$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 2: INDUS VALLEY CIVILIZATION ===================== -->
<h2 id="indus">2. Indus Valley Civilization (3300-1300 BCE)</h2>

<p>The <span class="highlight">Indus Valley Civilization (IVC)</span>, also called the <span class="highlight">Harappan Civilization</span> after its type site Harappa (first excavated by Daya Ram Sahni in 1921), is one of the three great early civilizations of the Old World alongside Mesopotamia and Egypt. It flourished in the basins of the Indus River and the Ghaggar-Hakra (the palaeo-Saraswati) river system, covering an area of over 1.5 million sq km - larger than Egypt and Mesopotamia combined. The civilization is notable for its extraordinarily advanced urban planning, standardized weights and measures, long-distance maritime trade networks, and a still-undeciphered script. The IVC is the earliest known urban culture of the Indian subcontinent, representing the <span class="highlight">First Urbanisation</span> of India. It was first identified when Daya Ram Sahni excavated at Harappa in 1921, followed by R.D. Banerji at Mohenjo-daro in 1922, leading to the discovery of a civilization contemporaneous with ancient Egypt and Mesopotamia.</p>

<h3>Chronology and Phases</h3>

<div class="table-wrap"><table>
<tr><th>Phase</th><th>Time Period</th><th>Key Characteristics</th></tr>
<tr><td><strong>Pre-Harappan / Early Harappan</strong></td><td>c. 3300-2600 BCE</td><td>Formative phase; agricultural settlements with pre-Harappan regional cultures (Amri, Kot Dijian, Hakra); beginning of urbanization; early writing symbols; emerging trade networks; preparation for the mature urban phase</td></tr>
<tr><td><strong>Mature Harappan</strong></td><td>c. 2600-1900 BCE</td><td>Peak period; fully developed urban centres with grid-plan streets; standardized brick sizes (1:2:4 ratio for sun-dried, 3:2:1 for fired); advanced drainage systems; standardized weights (binary-decimal system); Indus script (400-450 signs); extensive maritime trade with Mesopotamia, Persian Gulf, and Central Asia; organized state structures; craft specialization (bead-making, bronze casting, shell-working)</td></tr>
<tr><td><strong>Late Harappan</strong></td><td>c. 1900-1300 BCE</td><td>Decline phase; de-urbanization; shifting river courses (Ghaggar-Hakra drying); abandonment of cities; regionalization of material culture (Cemetery H culture in Punjab, Jhukar culture in Sindh, Rangpur culture in Gujarat); disappearance of script and standardized weights; movement of populations eastward to the Gangetic plain</td></tr>
</table></div>

<h3>Major Sites - Comprehensive Analysis</h3>

<div class="table-wrap"><table>
<tr><th>Site</th><th>Location</th><th>Excavator(s)</th><th>Key Findings</th><th>Significance for UPSC</th></tr>
<tr><td><strong>Harappa</strong></td><td>Sahiwal, Punjab (Pakistan)</td><td>Dayaram Sahni (1921); M.S. Vats (1926); Mortimer Wheeler (1946)</td><td>Granaries (12 in a row on brick platforms), working-class quarters (single-room tenements in rows), coffin burial (wooden coffin), seal with unicorn motif, circular brick working platforms for grain processing, cemetery H pottery, evidence of bead-making and shell-working</td><td>First discovered site (1921); gives the civilization its name; provides stratigraphic sequence through all three phases; Wheeler's excavations (1946) revealed fortifications, city wall, and the Cemetery H culture</td></tr>
<tr><td><strong>Mohenjo-daro</strong></td><td>Larkana, Sindh (Pakistan)</td><td>R.D. Banerji (1922); Mackay (1927); Wheeler (1950)</td><td><strong>Great Bath</strong> (12x7m, 2.4m deep, bitumen waterproofed, changing rooms), <strong>Dancing Girl</strong> (bronze, 11cm, lost-wax casting, left hand on hip), <strong>Priest-King</strong> (steatite, 18cm, beard, fillet headband, trefoil robe), <strong>Pashupati Seal</strong> (proto-Shiva), Great Granary (huge brick structure), Assembly Hall (27x27m pillared hall), College of Priests (75-room building), 700+ brick-lined wells, elaborate street drainage, multi-room houses with bathrooms</td><td>Largest excavated site (250+ ha, though much unexcavated); most advanced water management in ancient world; Pashupati seal crucial for religious history; Great Bath indicates ritual purification practices; highest concentration of wells in any ancient city</td></tr>
<tr><td><strong>Dholavira</strong></td><td>Kutch, Gujarat</td><td>J.P. Joshi (1967); R.S. Bisht (1990-2005)</td><td>Unique <strong>seven-stage water management</strong> system (2 dams, 16 reservoirs carved from living rock, wells, stepwells, channels, 3.5km long fortification wall), <strong>signboard</strong> (10 large gypsum inlaid letters, each 37cm high), stadium (280x45m), three-part city division (citadel, middle town, lower town), ten large inscriptions in Indus script</td><td>Largest IVC site in India (100+ ha); only site with three-part city division; the world's oldest signboard indicates widespread literacy; shows advanced hydraulic engineering capabilities; unique radial street plan in some sectors; each phase of construction visible in the stratigraphy</td></tr>
<tr><td><strong>Lothal</strong></td><td>Ahmedabad, Gujarat</td><td>S.R. Rao (1954-60)</td><td><strong>Dockyard</strong> (218x37m, 4m deep, inlet channel 12m wide with a lock-gate system), bead-making factory with kilns (produced millions of microbeads, heat-treated carnelian), Persian Gulf seal (circular button seal), twin burial (male and female), rice husk found in pottery, artificial mud-brick platform for the citadel (4m high)</td><td>Substantial evidence of maritime trade with Mesopotamia and the Gulf; the dockyard shows advanced hydraulic engineering with a planned inlet/outlet system; bead industry produced millions of microbeads with heat treatment of carnelian (800-1000 C); earliest known rice cultivation in IVC</td></tr>
<tr><td><strong>Rakhigarhi</strong></td><td>Hisar, Haryana</td><td>Amarendra Nath (1997-2000); Vasant Shinde (2013-16)</td><td>Largest IVC site (350+ hectares, potentially 450 ha), granaries with brick platforms, massive mud-brick platforms (30x30m), streets with covered drains (brick-lined, with manholes), burial site with 90+ graves (extended burials with north-south orientation, grave goods like pottery and beads), <strong>ancient DNA study</strong> (published in Cell, 2019)</td><td>Largest IVC site, surpassing Mohenjo-daro in size; aDNA study reveals genetic continuity between IVC populations and modern South Asian populations - no evidence of large-scale Aryan migration during the IVC period; crucial for understanding IVC population history</td></tr>
<tr><td><strong>Kalibangan</strong></td><td>Hanumangarh, Rajasthan</td><td>B.B. Lal (1961); B.K. Thapar</td><td><strong>Ploughed field</strong> (furrows preserved in a grid pattern suggesting cross-cultivation of two different crops), <strong>fire altars</strong> (7 in a row on a mud-brick platform, with ash and terracotta cakes), wooden drainage platforms, tiled floors, bricks bonded with gypsum mortar, both pre-Harappan and Harappan levels</td><td>Ploughed field gives earliest evidence of cross-cultivation in the world; fire altars indicate ritual activities - possibly fire worship or Soma sacrifice; the pre-Harappan level shows a different culture (Kot Dijian) than the Mature Harappan</td></tr>
<tr><td><strong>Banawali</strong></td><td>Hisar, Haryana</td><td>R.S. Bisht (1975)</td><td>Fortifications (defensive wall with bastions), barrel-shaped beads of faience and carnelian, toy cart in terracotta, inscribed copper fishhook, streets with covered drains, evidence of barley and wheat cultivation</td><td>Shows transition from Early to Mature Harappan; Indus script evidence on pottery graffiti; unique barrel-shaped beads suggest long-distance trade with Central Asia</td></tr>
<tr><td><strong>Surkotada</strong></td><td>Kutch, Gujarat</td><td>J.P. Joshi (1970)</td><td><strong>Horse bones</strong> (disputed identification - A.K. Sharma claimed evidence of Equus caballus, but this identification is contested by other archaeologists who argue they were wild ass - Equus hemionus or onager)</td><td>Horse evidence is crucial for the Aryan debate; most archaeologists now reject Equus caballus identification; the debate highlights how archaeology is sometimes politicized; the site also yielded a unique pottery style</td></tr>
<tr><td><strong>Chanhu-daro</strong></td><td>Sindh, Pakistan</td><td>N.G. Majumdar (1931); Mackay</td><td>Lapis lazuli and carnelian bead-making workshop (specialized craft area), metal tools (copper knives, axes, fishhooks, chisels), cosmetic vessels (ivory and shell), seal-cutting workshop</td><td>Called the 'Pompeii of the Indus' for the remarkable preservation of craft workshops; dedicated bead-making factory; evidence of shell-working industry; only IVC site without a citadel</td></tr>
<tr><td><strong>Kot Diji</strong></td><td>Sindh, Pakistan</td><td>Fazal Ahmad Khan (1955)</td><td>Early Harappan fortifications (massive stone and mud-brick defensive wall), pottery with pipal leaf designs, pre-Harappan occupation levels, stone arrowheads and blades</td><td>Type site of Kot Dijian culture - a precursor to Mature Harappan; earliest evidence of defensive walls in South Asia; shows the cultural continuity from early farming villages to urban centers</td></tr>
<tr><td><strong>Alamgirpur</strong></td><td>Meerut, Uttar Pradesh</td><td>Y.D. Sharma (1958)</td><td>Late Harappan pottery (painted grey ware, dishes-on-stand), terracotta cakes, beads, copper implements, brick structures</td><td>Easternmost limit of IVC (near Delhi); shows diffusion into Ganga-Yamuna Doab; suggests gradual movement of Harappan people eastward as the Ghaggar-Hakra dried up</td></tr>
<tr><td><strong>Amri</strong></td><td>Sindh, Pakistan</td><td>N.G. Majumdar</td><td>Pre-Harappan and Harappan culture layers separated by flood deposits, bull figurines, painted pottery with geometric designs</td><td>Type site of Amri culture - one of the earliest pre-Harappan cultures; shows the transition from rural agricultural settlement to urban Harappan</td></tr>
</table></div>

<h3>Urban Planning and Architecture</h3>

<p>Harappan cities were remarkably well-planned. The <span class="highlight">grid-iron street pattern</span> - streets running north-south and east-west at right angles - divided the city into rectangular blocks. Cities typically had a raised <strong>citadel</strong> (administrative-religious centre with public buildings on a high mud-brick platform) on the west and a <strong>lower town</strong> (residential area with houses, workshops, and bazaars) on the east. The main streets were up to <strong>10 metres wide</strong>, with smaller lanes (1-2m) branching off at right angles. Houses were built around a central courtyard, with rooms on all sides (typically 6-12 rooms per house), and were provided with bathrooms (brick floors with drains), wells (in the courtyard or on the street corner), and drainage connections to street drains. <span class="highlight">Standardized burnt bricks</span> were used across the entire civilization in a precise ratio of 1:2:4 (length:breadth:height) - sun-dried bricks for internal walls and fired bricks for external walls, drains, and wells. The <strong>drainage system</strong> was the most advanced in the ancient world - covered drains made of brick lined with gypsum plaster, with inspection holes (manholes covered with stone lids or bricks) at regular intervals for cleaning, connected every house to street drains and ultimately to brick-lined soak pits or city drains. The quality of the drainage system has no parallel in the contemporary Middle East - not even in Egypt or Mesopotamia. The Great Bath at Mohenjo-daro (11.88 x 7.01 x 2.43 metres) was lined with bitumen (natural tar) for waterproofing, surrounded by a portico of rooms and a colonnade, and had a well for water supply and a drain with a corbelled arch for outlet - it was likely used for ritual purification. <strong>Dholavira</strong>'s water management system is unparalleled in the ancient world - 16 reservoirs carved from rock, 2 dams across seasonal streams, stepwells, and an intricate channel system that captured and stored monsoon water, providing the city with a year-round water supply in a semi-arid region.</p>

<h3>Economy and Trade</h3>

<p><strong>Agriculture</strong> was the economic base - wheat (Triticum compactum), barley (Hordeum vulgare), peas, sesame, dates, melons, and <strong>cotton</strong> (Gossypium arboreum - India was the first region to cultivate cotton, attested at Mehrgarh from 6000 BCE). Rice was cultivated in Gujarat (Lothal, Rangpur). Evidence of plough cultivation comes from Kalibangan (furrowed field). <strong>Animal husbandry</strong> included cattle (zebu humped cattle - Bos indicus - dominant), buffalo, sheep, goat, pig, camel, elephant, and dog. The horse (Equus caballus) is debated - most archaeological evidence suggests it was absent or very rare.</p>

<p><strong>Trade</strong> was extensive, both internal and external. The <span class="highlight">Mesopotamian texts</span> (c. 2300-1800 BCE) refer to <strong>Meluhha</strong> (widely identified as the Indus region) as a source of carnelian, lapis lazuli, timber, ivory, peacocks, and monkeys. Indus seals have been found in Mesopotamian cities: Ur (14 seals), Kish, Tell Asmar, Nippur, and Susa. Trade goods included carnelian beads (heat-treated at Chanhu-daro and Lothal to produce the characteristic deep red colour), etched carnelian beads (a Harappan specialty made by a chemical process using alkali to create white patterns), lapis lazuli from Badakhshan (Afghanistan), turquoise from Iran, jade from Central Asia, and silver from Iran. The IVC maintained a trading outpost at <strong>Shortughai</strong> (Afghanistan) on the Amu Darya, which served as a gateway for lapis lazuli and tin from Central Asia - critical for making bronze. The <span class="highlight">Persian Gulf seals</span> (circular button seals with a central boss and two animals) found at Lothal and other port sites indicate a trade network involving ports along the Gulf.</p>

<p><strong>Weights and measures</strong> were standardized across the entire civilization. The weights (cubical chert stones with no markings) followed a binary-decimal system: ratios of 0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100, 200, 500. The smallest weight found is 0.856 grams (ratio 1) and the largest is 10.9 kg (ratio 11,700). A bronze measuring rod found at Mohenjo-daro (66.5 inches long, divided into 10 units of 6.7 inches each) suggests a standardized unit of length. This uniformity over such a vast area (1.5 million sq km) indicates a powerful central authority overseeing production and trade.</p>

<p><strong>Seals</strong> (typically square steatite seals 2-3 cm across, engraved with animal motifs and a line of Indus script at the top, with a perforated boss on the back for carrying) were used for trade and administrative purposes. The <strong>unicorn</strong> (a bull-like animal with one horn in profile, possibly an extinct species of wild cattle or aurochs) is the most common motif (appearing on 60% of all seals - around 1000 out of 1500+ known seals). Other motifs include the humped bull (zebu), elephant, tiger, rhinoceros, buffalo, goat, antelope, and the composite Pashupati figure. Seals were pressed into wet clay tags to seal goods - many seal impressions on clay tags have been found with cord marks on the back, showing they were attached to bundles of goods for identification during transit.</p>

<p><strong>Craft production</strong> was highly specialized. <strong>Bead-making</strong> reached extraordinary levels - Harappan bead-makers could produce carnelian beads as small as 0.5 mm in diameter with a perforation smaller than 0.3 mm. They heat-treated carnelian at controlled temperatures (800-1000 degrees C) in reducing kilns to change its colour from pale brownish to deep translucent red. <strong>Bronze casting</strong> used the lost-wax (cire-perdue) technique (Dancing Girl at Mohenjo-daro, Daimabad bronzes of chariot, elephant, rhinoceros, and buffalo). <strong>Shell-working</strong> produced bangles (shell bangles are found in abundance), inlay pieces, ladles, and decorative items. <strong>Pottery</strong> was wheel-made, with red ware (plain and painted) and black-and-red ware. Harappans also produced faience (a vitreous material, artificially made from quartz and alkali) for beads, ornaments, and tiny figurines.</p>

<h3>Religion and Beliefs</h3>

<p>Harappan religious practices are inferred from material remains rather than texts (since the script remains undeciphered). No temples or palaces have been identified, suggesting religion was domestic and personal rather than institutionalized. Key elements include:</p>
<ul>
<li><strong>Mother Goddess</strong> - terracotta female figurines with elaborate headdresses (fan-shaped, pannier-like), pinched noses, applique ornaments, and elaborate hairstyles, found in large numbers in almost every household. They likely represent a fertility goddess worshipped for domestic prosperity. Also called the 'Mother Goddess' since John Marshall first identified them in 1931.</li>
<li><strong>Pashupati Seal</strong> (Mohenjo-daro) - a seated figure in a yogic posture (cross-legged, arms extended, thumbs touching knees), wearing a horned headdress with three upward branches or plumes, surrounded by an elephant, tiger, rhinoceros, and buffalo, with two deer at the feet. Identified by John Marshall (1931) as <strong>proto-Shiva</strong> (<em>Pashupati</em> - Lord of Animals). This interpretation is debated - some scholars (like Asko Parpola) see it as a buffalo-horned deity or a 'Lord of the Beasts' figure common in Near Eastern iconography, while others argue it represents a deity in a yogic posture, possibly the earliest depiction of a yogic practice that later became associated with Shiva.</li>
<li><strong>Fire altars</strong> - at Kalibangan (7 in a row on a mud-brick platform) and Lothal (single brick platform), brick-lined pits with ash and burnt animal bones, indicating ritual fire worship. Some scholars connect these to the fire worship and Soma sacrifice of the later Vedic tradition.</li>
<li><strong>Tree worship</strong> - depictions on seals of the pipal tree (Ficus religiosa) with a deity inside the tree, or with a horned human figure standing reverently before it. The pipal tree later became sacred in Hinduism (the Bodhi tree in Buddhism as well).</li>
<li><strong>Phallus (Linga) and Yoni worship</strong> - conical and ring-shaped stone objects found at several sites (including Kalibangan and Harappa) suggest early forms of linga-yoni worship, later central to Shaivism.</li>
<li><strong>Burial practices</strong> - extended burials in a north-south orientation, with the head pointing north, grave goods (pottery, beads, copper mirrors, shell bangles, sometimes food offerings). At Lothal, evidence of <strong>joint burial</strong> (male and female together), possibly indicating the practice of sati or simultaneous death. At Harappa, a <strong>coffin burial</strong> (wooden coffin covered with reed matting). At Rakhigarhi, a large cemetery with both extended and pot burials. No suggestion of a belief in afterlife punishment or reward - grave goods indicate a belief that the dead needed their possessions in the next world.</li>
</ul>

<h3>The Indus Script - An Undeciphered Enigma</h3>

<p>The <span class="highlight">Indus script</span> remains <strong>undeciphered</strong>, one of the great unsolved puzzles of archaeology. It appears on steatite seals (the most common source - about 2000+ seal impressions), copper tablets, pottery graffiti (incised on pots before firing), and the famous Dholavira signboard. The script is <strong>pictographic</strong> (about 400-450 distinct signs, with some 600+ variations including compound signs) and was written <strong>right to left</strong> (determined by spacing patterns where signs are more crowded on the left side and the text begins on the right). Most inscriptions are short (average 4-5 signs, maximum 17 signs on the Dholavira signboard, which had 10 characters in a row). The <strong>Dravidian hypothesis</strong> (proposed by Asko Parpola, Iravatham Mahadevan, and others) argues that the underlying language is Proto-Dravidian, based on: structural analysis of the script, the survival of Dravidian place names in the Indus region (river names like Narmada, Tapti, Godavari show Dravidian etymologies), and the <span class="highlight">Rakhigarhi aDNA study</span> (2019, Cell) which found genetic continuity between IVC populations and modern South Indian Dravidian speakers. The <strong>Brahmi hypothesis</strong> (linking Indus script to the later Brahmi script) has been rejected by mainstream linguistics due to the 1500-year gap between the end of the Indus script and the earliest Brahmi inscriptions. The <strong>Sanskritic hypothesis</strong> (claiming the script encodes an early form of Sanskrit) has no scholarly support - the horse and chariot, central to Indo-Aryan culture, are absent from the IVC. Without a bilingual text, a full decipherment may not be achievable, though statistical analysis has identified patterns suggesting an agglutinative language (consistent with Dravidian).</p>

<h3>Decline of the IVC - Causes and Debates</h3>

<p>The decline of the IVC (c. 1900-1300 BCE) was a complex, multi-causal process that occurred over several centuries, not a single catastrophic event. The decline manifested as: abandonment of cities, disappearance of writing, collapse of inter-regional trade, decline of craft specialization, and regionalization of material culture (the uniform Harappan culture fragmenting into distinct regional styles). Four major theories dominate scholarly debate:</p>
<ul>
<li><strong>Climate Change (Monsoon Weakening)</strong> - the leading theory today. Palaeoclimatic evidence from Arabian Sea sediment cores, speleothems from Meghalaya caves (Mawmluh, Wah Shikhar), and lake cores from the Himalayas shows a gradual weakening of the Indian summer monsoon between 2200-1900 BCE, with a particularly sharp decline around 1900 BCE. This reduced rainfall in the Indus and Ghaggar-Hakra basins by 30-40%, making rain-fed agriculture unsustainable in the core IVC region. The Ghaggar-Hakra (the 'Saraswati' river of the Rigveda) was a monsoon-fed river that dried up completely, forcing abandonment of the Mature Harappan cities. Studies by IIT-Kharagpur, University of Cambridge, and Woods Hole Oceanographic Institution support this theory.</li>
<li><strong>Tectonic Activity</strong> - the Indian plate continues to collide with the Eurasian plate, causing ongoing tectonic movements that may have altered river courses and caused earthquakes. The Indus plain experienced tectonic uplift in some areas (causing flooding - Mohenjo-daro shows multiple flood deposits up to 2m thick) and subsidence in others, diverting the rivers that supported the cities.</li>
<li><strong>Ecological Degradation</strong> - the Harappans over-exploited natural resources: forests were cleared for brick-making (over 300 million bricks estimated at Mohenjo-daro alone would have required 30+ sq km of forest), over-grazing by the large cattle population, and soil salination due to intensive irrigation in a semi-arid climate led to declining agricultural yields that could no longer support the urban population.</li>
<li><strong>Trade Disruption</strong> - the intermediate Elamite period in Mesopotamia (c. 2000-1800 BCE) and the collapse of the Akkadian Empire disrupted the Indus-Mesopotamia trade network that had been a major source of wealth for the IVC elite. The decline of Mesopotamian trade reduced the demand for Harappan luxury goods (carnelian beads, timber, ivory), weakening the urban economy and the power of the trading elite who organized the cities.</li>
</ul>

<div class="warn-box"><div class="warn-title">Historiographical Controversy: The Aryan Theory</div><div class="warn-text">The <strong>Aryan Invasion Theory</strong> - proposed by Mortimer Wheeler (1946) based on: (a) a mass burial of 37 skeletons at Mohenjo-daro, (b) the Rigveda's description of 'Indra destroying cities' (purandara), and (c) the supposed introduction of horses and chariots by invading Aryans - is now <strong>completely rejected</strong> by mainstream archaeology. The 'massacre' skeletons are now interpreted as evidence of disease, floods, or secondary burials - they show no signs of weapon injuries. No evidence of an invading Aryan culture (horse remains, new pottery styles, weapons) has been found at IVC destruction levels. The <span class="highlight">Rakhigarhi aDNA study (2019, Cell)</span> conclusively shows genetic continuity between IVC populations and modern South Asians, with no evidence of large-scale migration from Central Asia during the IVC collapse. The <strong>Aryan Migration Theory</strong> (gradual, small-scale migration of Indo-Aryan speakers into India after the IVC decline, c. 2000-1500 BCE) is the current scholarly consensus. For UPSC, present the Migration Theory as the scholarly consensus while noting the Aryan Invasion Theory has been abandoned.</div></div>

<div class="example-box"><div class="ex-title">Why Students Lose Marks on IVC for UPSC</div><div class="ex-text">Common mistakes: (1) Calling IVC the 'Indus-Saraswati Civilization' as if the Vedic Saraswati and the IVC Ghaggar-Hakra are the same river - the Vedic Saraswati was likely a different, glacier-fed river; (2) Stating that IVC had 'temples' or 'palaces' - no monumental religious or royal architecture has been identified; (3) Claiming the Indus script has been 'deciphered' - it has NOT been deciphered; (4) Connecting IVC 'decline' to 'Aryan invasion' - this theory is rejected; (5) Calling the Pashupati seal definitively 'Shiva' - it is 'Proto-Shiva' and this interpretation is debated; (6) Saying the IVC was a 'peaceful civilization' - there is evidence of fortifications, weapons, and skeletal injuries, though militarism was less pronounced than in contemporary civilizations.</div></div>

<div class="diagram-box"><pre>
  INDUS VALLEY CIVILIZATION - KEY SITES MAP

  AFGHANISTAN------Shortughai (trading outpost)
       |
     Harappa --------Rakhigarhi (largest)
       |                |
  Mohenjo-daro    Kalibangan
       |
     Dholavira ----Lothal (dockyard)
       |
  Surkotada

  EXTENT: 1.5 million sq km | 1000+ sites identified
  Easternmost: Alamgirpur (Meerut, UP)
  Westernmost: Sutkagendor (Makran coast, Pakistan)
  Northernmost: Shortughai (Badakhshan, Afghanistan)
  Southernmost: Daimabad (Ahmadnagar, Maharashtra)
</pre></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 2 written."
