$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 14: MARATHA EMPIRE & SIKH CONFEDERACY ===================== -->
<h2 id="maratha-sikh">14. Maratha Empire & Sikh Confederacy (1674-1818)</h2>

<p>The <span class="highlight">Maratha Empire</span> was the last major indigenous Indian empire before the British conquest. It emerged from the guerrilla resistance to Mughal expansion in the Deccan under the leadership of <strong>Shivaji Bhonsle</strong> (1630-1680) — who founded the Maratha kingdom, established a navy, and challenged the Mughal and Bijapur authorities. After Shivaji's death, the Maratha state expanded under the <strong>Peshwas</strong> (Brahmin prime ministers of the Bhat family who became the de facto rulers) into a confederacy that controlled most of India by the mid-18th century — from the Indus to Bengal, from the Himalayas to the Kaveri. The Maratha defeat at the <strong>Third Battle of Panipat</strong> (1761) against Ahmad Shah Abdali broke their northward expansion, but they recovered and remained the dominant Indian power until the British conquered them in the Anglo-Maratha Wars (1775-1818). The Maratha navy under the <strong>Angre (Angria)</strong> family challenged the British, Portuguese, and Siddis (Janjira) for control of the Konkan coast.</p>

<h3>Shivaji (1630-1680)</h3>

<p><strong>Shivaji Bhonsle</strong> was born at the Shivneri Fort (near Junnar, Pune district) to <strong>Shahaji Bhonsle</strong> (a Maratha general serving in the Bijapur and Ahmadnagar armies) and <strong>Jijabai</strong>. He was trained by his mother and his guardian <strong>Dadaji Kondadev</strong>. From age 16, he began capturing forts in the Maval region (Torna, 1645 — his first conquest; Purandar, Rajgad, Sinhagad, etc.). His conflict with the Adil Shahi Sultanate of Bijapur began when Bijapur sent its general <strong>Afzal Khan</strong> to capture him in 1659. In the famous encounter at Pratapgad Fort, Shivaji killed Afzal Khan with tiger claws (wagh-nakh, a metal claw weapon) concealed in his hands, and the Maratha army routed the Bijapuri force. This established Shivaji as the foremost Maratha leader. He fought the Mughals from 1660 — Aurangzeb sent Jai Singh, Sisodia Rajput and Mughal general, to defeat him. Shivaji was forced to sign the <strong>Treaty of Purandar</strong> (1665) — surrendered 23 of his 35 forts and agreed to serve the Mughals. He visited Aurangzeb's court at Agra (1666), where he was insulted (given a low rank) and placed under house arrest. He famously escaped hidden in a fruit basket (or sweets basket — actually his escape involved hiding in a phon/dongle basket, but the 'fruit basket' is the most popular version; the actual method was that he and his son Sambhaji escaped from Agra in 1666 by hiding in baskets of sweets and fruit, carried by the Brahmins who brought them). He returned to the Deccan, made peace with the Mughals (1668-1670), and then launched a massive campaign of reconquest (1670-1674), recapturing all his former forts and more. He was formally <strong>crowned as Chhatrapati</strong> (Sovereign Emperor, Lord of the Umbrella) at <strong>Raigad Fort</strong> in 1674 with a grand ceremony — he established the <strong>Rajyabhisheka Shaka</strong> (Maratha Era). He built a navy (350 ships) based at the ports of <strong>Kolaba</strong>, <strong>Suvarnadurg</strong>, <strong>Vijaydurg</strong>, and <strong>Jaigad</strong>, with Kanhoji Angre (the Angre family) as his navy commander. He introduced a progressive administration: the <strong>Ashta Pradhan</strong> (Council of 8 Ministers — the Peshwa/Prime Minister, Amatya/Finance, Mantri/Records, Sumant/Foreign, Sachiv/Master of Ceremonies, Pandit Rao/Religious Affairs, Senapati/Military, Nyayadhish/Judiciary). He reformed revenue collection — the <strong>chauth</strong> (25% of revenue collected in areas not directly under Maratha rule, as protection money) and the <strong>sardeshmukhi</strong> (10% additional fee as overlord). His soldiers were paid in cash, not land grants, ensuring loyalty. He died in 1680 at Raigad, possibly from dysentery.</p>

<p>Shivaji is celebrated as a national hero who revived Hindu sovereignty after centuries of Muslim rule. His emphasis on guerrilla warfare (ganimi kava), his respect for women and religious places of all faiths, his fair treatment of peasants, his building of a navy to protect the Konkan coast, and his constitutional monarchy (the Ashta Pradhan with clearly defined duties) mark him as a remarkable ruler. The <strong>Shivaji icon</strong> was promoted by the Indian National Congress (Tilak, Savarkar) and later by the Maratha nationalist parties.</p>

<h3>The Peshwa Era (1713-1818)</h3>

<p>After Shivaji's death, his son <strong>Sambhaji</strong> (1680-1689) reigned — captured and executed by Aurangzeb (tortured for 40 days, then beheaded). His brother <strong>Rajaram</strong> (1689-1700) continued the war from the fortress of Gingee (Tamil Nadu — the only time Maratha forces operated deep in the south). Rajaram's widow <strong>Tarabai</strong> acted as regent for her son Shivaji II. In 1713, the Bhat family Brahmins took control: <strong>Balaji Vishwanath</strong> became the first Peshwa (prime minister) of the Maratha Empire and the actual ruler. His son <strong>Bajirao I</strong> (1720-1740) is the greatest Peshwa — his military campaigns are the most brilliant in 18th-century Indian history. He said: 'Strike at the trunk of the withering tree (the Mughal Empire), and the branches will fall of themselves.' He led the Maratha expansion into northern India — conquered Malwa (1728), Gujarat (1729-30), Bundelkhand (1729 — the treaty with Chhatrasal), and the Marathas sacked Delhi for the first time in 1737 (the Battle of Delhi — Maratha cavalry raided the suburbs of Delhi and defeated the Mughal army). He fought the Nizam of Hyderabad (at Bhopal, 1737, forcing the treaty of Doraha) and the Portuguese (Basin, 1739). He established Maratha dominance over Malwa, Gujarat, and Bundelkhand. His son <strong>Balaji Bajirao (Nanasaheb)</strong> (1740-1761) expanded the empire further — the Maratha empire reached its peak extent: from Attock (Pakistan) in the north to the Kaveri in the south. But Nanasaheb's general <strong>Sadashivrao Bhau</strong> led the Maratha army to the disastrous <strong>Third Battle of Panipat</strong> (14 January 1761), where the Marathas were crushed by Ahmad Shah Abdali (the Abdali Afghan army). The defeat destroyed the cream of the Maratha leadership (Sadashivrao Bhau, Vishwasrao, and 70,000 Maratha soldiers died) and ended their northern expansion. The Peshwa <strong>Madhavrao I</strong> (1761-1772) restored the Maratha power but died of tuberculosis at age 27. The Maratha state weakened due to internal factionalism (the rivalry between the Peshwa's widow Gopikabai and the minister Nana Phadnavis). The British defeated the Marathas in the <strong>Anglo-Maratha Wars</strong>: First (1775-1782 — inconclusive, Treaty of Salbai), Second (1803-1805 — decisive British victory: the British annexed Delhi and Agra, and the Marathas lost Orissa, Haryana, and the Doab; Treaties of Deogaon and Surji-Arjungaon), and Third (1817-1818 — final defeat: the Peshwa Bajirao II surrendered and became a British pensioner; the Maratha confederacy was dissolved). The Maratha Kingdom was annexed to the Bombay Presidency.</p>

<h3>The Sikh Confederacy (1708-1849)</h3>

<p>The <span class="highlight">Sikh religion</span> emerged in the Punjab in the 15th-16th centuries under ten Gurus from <strong>Guru Nanak</strong> (1469-1539) to <strong>Guru Gobind Singh</strong> (1666-1708). The Sikhs transformed into a military confederacy (the <strong>Misls</strong> — 12 separate Sikh states) in the 18th century after the execution of Guru Tegh Bahadur by Aurangzeb (1675) and the founding of the <strong>Khalsa</strong> (the collective body of baptised Sikhs) by Guru Gobind Singh in 1699 at Anandpur Sahib. The Khalsa was established through the <strong>Amrit Sanchar</strong> (baptism ceremony — five Sikhs offered to give their heads for the faith, the Panj Pyare/Five Beloved Ones, and were then baptised by Guru Gobind Singh himself). The Khalsa adopted the <strong>Five Ks</strong>: Kesh (uncut hair and beard), Kangha (wooden comb), Kara (iron/steel bracelet on the right wrist), Kacchera (shorts worn as underwear), Kirpan (ceremonial sword).</p>

<p>After Guru Gobind Singh's death (1708), the Sikhs fought a long guerrilla war against the Mughals and the Afghans (Ahmad Shah Abdali invaded Punjab 9 times, 1747-1769, and each time the Sikhs recovered their territories after he withdrew). The Sikh Misls (12 autonomous Sikh states) were established in the 1760s over the Punjab. The confederacy was led by the <strong>Dal Khalsa</strong> (the unified army of the Sikhs) which met in <strong>Sarbat Khalsa</strong> (the general assembly) at Amritsar, the spiritual centre. In 1801, <strong>Ranjit Singh</strong> (1780-1839) of the Sandhawalia Jat clan of the Sukerchakia Misl conquered the other Misls and established the <strong>Sikh Empire</strong> (the <strong>Khalsa Raj</strong>) with his capital at <strong>Lahore</strong>. He was crowned as <strong>Maharaja</strong> in 1801. He modernised his army (the Sikh Khalsa Army, trained by European mercenaries — the French generals Ventura, Allard, Court, and Avitabile; the Italian Paolo Avitabile; the German Honigberger — using the French military system). He signed the <strong>Treaty of Amritsar</strong> (1809) with the British East India Company, accepting the Sutlej as the boundary. His empire at its peak: the Punjab, Kashmir, Ladakh, Peshawar, Multan, Kangra, and the Khyber Pass. He was a tolerant ruler who appointed Hindus and Muslims to high office (his Prime Minister Dhian Singh Dogra was Hindu; his general Sham Singh Attariwala was Sikh; and he had a Muslim governor of Kashmir). He patronised the <strong>Harmandir Sahib (Golden Temple)</strong> at Amritsar — he covered it with gold leaf and marble (hence the name). After his death (1839), the empire was destabilised by assassination and succession wars. The British annexed the Sikh Empire after the <strong>First Anglo-Sikh War</strong> (1845-46 — Treaty of Lahore: the Sikhs ceded Kashmir to the British, who sold it to Gulab Singh Dogra for 7.5 million rupees) and the <strong>Second Anglo-Sikh War</strong> (1848-49 — the British annexed the entire Punjab).</p>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 14 written."
