$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 10: SOUTH INDIAN KINGDOMS ===================== -->
<h2 id="south-india">10. South Indian Kingdoms (750-1300 CE)</h2>

<p>The period from 750 to 1300 CE saw the emergence of South India as a major centre of political power, temple architecture, maritime trade, and Tamil/Bhakti culture. The most important dynasties were the <span class="highlight">Rashtrakutas</span> (Deccan), the <strong>Chola Empire</strong> (Tamil Nadu/Sri Lanka/Southeast Asia), the <strong>Chalukyas of Kalyani</strong> (Western Chalukya), the <strong>Kakatiyas</strong> (Warangal), the <strong>Hoysalas</strong> (Halebidu/Belur), and the <strong>Yadavas of Devagiri</strong>. The Chola Empire under Rajaraja I and Rajendra I was the most powerful — one of the greatest naval powers in Indian history, with control over Sri Lanka, the Maldives, and parts of the Malay Archipelago. This period also saw the flourishing of the <strong>Bhakti movement</strong> (Alvars and Nayanars), the spread of Srivaishnavism and Shaiva Siddhanta, and the codification of temple rituals and Agamic texts.</p>

<h3>The Chola Empire (c. 850-1279 CE)</h3>

<p>The Chola Kingdom of the Sangam period (c. 300 BCE-300 CE) had declined by the post-Sangam Kalabhra interregnum. The Chola resurgence began with <strong>Vijayalaya Chola</strong> (c. 850-871 CE), who captured Thanjavur from the Mutharaiyar chieftains. The dynasty reached its zenith under <strong>Rajaraja I</strong> (985-1014 CE) and his son <strong>Rajendra I</strong> (1014-1044 CE). Under them, the Chola empire stretched from the Godavari river in the north to Sri Lanka in the south, and across the Indian Ocean to Sumatra, Java, and the Malay Peninsula — making them the only Indian dynasty to rule an overseas empire.</p>

<p><span class="highlight">Rajaraja I</span> (985-1014 CE) — the greatest Chola ruler. He defeated the Cheras (the Chera Perumal kings of Kerala) and captured the Chera capital of Muziris; conquered the Pandyas of Madurai; annexed the northern part of Sri Lanka (the Chola kingdom of Anuradhapura — renamed Mummudi Chola Mandalam); and campaigned against the Western Chalukyas (Satyashraya) for control of the Raichur Doab. He was a great builder — the <strong>Brihadishwara Temple at Thanjavur</strong> (built 1003-1010 CE) is his greatest achievement: the tallest temple tower in India at the time (the vimana is 66m tall, capped by a single granite block weighing 80 tons, dragged up a 6.4km ramp), with a sanctum (garbhagriha) that is one of the largest in the world (the linga is 3.6m high). The temple is built entirely of granite — the first such large-scale granite temple in India. The temple's inscriptions (the longest set of inscriptions on any single structure in the world — thousands of lines on all four sides of the base) record the land grants, temple servants (devadasis), musicians, dancers, cooks, accountants, and the entire temple administration — providing a comprehensive picture of Chola society and economy. Rajaraja also conducted a comprehensive land survey (the <strong>Karikala Chola? No, Rajaraja's survey</strong> — recorded in the Tirumukkudal inscription — measured all lands, assessed their productivity, and recorded them in the 'Ulavai-k-kadai' register). He maintained a powerful navy that controlled the maritime trade of the Indian Ocean.</p>

<p><span class="highlight">Rajendra I</span> (1014-1044 CE) — extended the empire to its greatest territorial extent. He defeated the Pala king Mahipala of Bengal (the Gangaikonda Chola inscription records: '[He] marched through Odisha, killed the king of Kalinga, and reached the Ganges. He took the Ganges water for his new capital.'). He assumed the title <strong>Gangaikonda Chola</strong> (the Chola who conquered the Ganges) and built a new capital <strong>Gangaikonda Cholapuram</strong> (near Ariyalur, Tamil Nadu) — the temple there, the <strong>Gangaikonda Cholapuram Temple</strong>, is the second great Shiva temple built under Rajendra (the vimana is 55m tall, slightly smaller than Thanjavur but equally magnificent, with exquisite Chola bronzes). His greatest achievement was the <strong>naval expedition to Srivijaya</strong> (a powerful Buddhist thalassocracy based in Sumatra, controlling the Strait of Malacca — the trade route between China and India). In 1025 CE, Rajendra's navy attacked the Srivijayan kingdom, capturing its capital Kadaram (Kedah, Malaysia), and the kingdoms of Srivijaya, Pannai (Sumatra), Malaiyur (Malay Peninsula), and Tambralinga (southern Thailand). This expedition broke Srivijaya's monopoly on maritime trade and opened direct trade with China for the Cholas (a Chola embassy was sent to the Song Chinese emperor in 1077 CE). The Chola navy was also active against the Pandyas and the Singhalese kings.</p>

<p><strong>Chola Administration</strong>: The most detailed and well-documented system of local self-government in ancient India. The empire was divided into <strong>mandalams</strong> (provinces), <strong>valanadus</strong> (districts), <strong>nadus</strong> (sub-districts — typically 100-500 villages), and <strong>urs</strong> (villages). The most famous feature was the <strong>Uttaramerur Inscriptions</strong> (c. 920 CE) of Parantaka I, which describe the constitution of the village assembly (<strong>sabha/mahajana</strong>) — members were elected by lottery (kudavolai) from among those who met strict qualifications (land ownership, age (over 35), knowledge of Vedas, absence of moral probity issues, and disqualification of close relatives of current members). Sabhas managed local affairs: maintenance of irrigation tanks and canals, collection of taxes, management of temple lands, dispute resolution, and distribution of water. This system of village democracy was unique to the Chola period and has been cited as a model of indigenous democratic governance. The village assembly was subdivided into committees (variyams): the garden committee (tottavariyam), the tank committee (erivariyam), the annual committee (samvatsaravariyam), and the gold committee (ponnuvariyam). The king was the ultimate authority but village autonomy was respected as long as land revenue was paid.</p>

<p><strong>Chola Economy and Trade</strong>: Agriculture was highly developed with extensive irrigation — the <strong>Grand Anicut (Kallanai)</strong> on the Kaveri river (built by the Sangam Chola king Karikala, c. 150 CE) is still in use. The Kaveri delta was the rice bowl of South India. Trade with China flourished — Chola goods (pepper, cardamom, pearls, textiles, spices, ivory, sandalwood, rhinoceros horn, and especially black pepper) were highly prized in Song China. The Chera and Pandya ports of Muziris, Quilon (Kollam), and Kayal (on the Tamraparni river) handled this trade. Arab and Chinese merchants frequented Chola ports. The Chola <strong>bronze sculptures</strong> (especially the Nataraja — Shiva as Lord of the Dance) represent the highest achievement of Indian metalwork: the cast bronze figures (using the lost-wax process / cire-perdue method) are famous for their dynamic grace, the circular halo of fire, and the perfect proportion. Chola bronzes were not just art objects — they were processional deities (utsava murtis) carried in temple festivals.</p>

<h3>Other Major South Indian Dynasties</h3>

<div class="table-wrap"><table>
<tr><th>Dynasty</th><th>Capital</th><th>Period</th><th>Key Features</th></tr>
<tr><td><strong>Rashtrakutas</strong></td><td>Manyakheta (Gulbarga, Karnataka)</td><td>753-982 CE</td><td>Greatest ruler: Amoghavarsha I (814-878) — patron of Jain literature; Dantidurga founded by defeating Chalukyas; wrote the Kavirajamarga (earliest Kannada literary text). Also: Govinda III, Krishna I (built the Kailasa Temple at Ellora — the world's largest monolithic structure, carved from the top down, 30m high, the greatest rock-cut temple in India). Ellora Cave 16 (Kailasa) is a UNESCO World Heritage Site.</td></tr>
<tr><td><strong>Western Chalukyas</strong></td><td>Kalyani (Basavakalyan, Karnataka)</td><td>973-1189 CE</td><td>Also called Later Chalukyas. Greatest ruler: Vikramaditya VI (1076-1126) — his reign is the start of the Chalukya Vikrama Era. Patron of literature (Bilhana's Vikramankadeva Charita, Vijnaneshwara's Mitakshara — the most important Hindu legal commentary after Manu). Defeated the Cholas. Great temple builders: Mahadeva Temple at Itagi, Kasi Vishveshwara Temple at Lakkundi, Mallikarjuna Temple at Kuruvatti.</td></tr>
<tr><td><strong>Kakatiyas</strong></td><td>Warangal (Telangana)</td><td>1083-1323 CE</td><td>Greatest ruler: Ganapatideva (1199-1262) — brought most of Telangana and coastal Andhra under his rule, built the Thousand-Pillared Temple at Hanamkonda. Rudramadevi (1262-1289) — one of the few ruling queens in Indian history; she was known as Rudramba and ruled in her own right; defeated the Pandyas, the Yadavas, and the Chola king. Rudramadevi is shown in sculptures as a male/female composite. The Kakatiya dynasty was defeated by the Delhi Sultanate under Muhammad bin Tughlaq (1323). Famous for the Warangal Fort (built by Prola II), the Ramappa Temple, and the rock-cut Kirti Torana (ornamental gateways).</td></tr>
<tr><td><strong>Hoysalas</strong></td><td>Dwarasamudra (Halebidu, Karnataka)</td><td>1026-1343 CE</td><td>Greatest ruler: Vishnuvardhana (1108-1152) — built the Chennakeshava Temple at Belur (dedicated to Vishnu) and the Hoysaleswara Temple at Halebidu (dedicated to Shiva). The Hoysala style is distinct: star-shaped vimana, multiple small shrines, rich soapstone carvings with figures of gods, animals, and musicians covering every surface. Later rulers: Ballala II (defeated the Yadavas, the Pandyas, and the Cholas), Ballala III (defeated by the Delhi Sultanate in 1343). The Hoysalas are also famous for the Basadi (Jain temples).</td></tr>
<tr><td><strong>Yadavas of Devagiri</strong></td><td>Devagiri (Daulatabad, Maharashtra)</td><td>1187-1317 CE</td><td>Greatest ruler: Singhana (1200-1247) — patron of Sanskrit and Marathi literature; established independent Yadava kingdom after the decline of the Chalukyas. The Devagiri fort was considered the most impregnable in the Deccan. The Yadavas were defeated by Alauddin Khalji's general Malik Kafur (1308), who captured Devagiri and forced the Yadava king Ramachandra to become a vassal. The dynasty was the precursor of the Maratha identity — Marathi language and literature flourished under the Yadavas (the earliest Marathi inscription dates from their reign).</td></tr>
</table></div>

<div class="tip-box"><div class="tip-title">UPSC Mnemonic: Chola Dynasty Sequence</div><div class="tip-text"><strong>VERY PRECISE ROUTE</strong><br>V = Vijayalaya (850-871)<br>E = Aditya I (871-907) — conquered Pallavas<br>R = Parantaka I (907-955) — Uttaramerur<br>Y = Rajaraja I (985-1014) — Thanjavur temple<br>P = Rajendra I (1014-1044) — Gangaikonda Cholapuram<br>R = Kulottunga I (1070-1120) — grandson of Rajendra I, also of Eastern Chalukya lineage; united Vengi and Chola kingdoms<br>D = Rajendra III (1246-1279) — last Chola; Pandya king Jatavarman Sundara Pandya I defeated the Cholas</div></div>

<div class="warn-box"><div class="warn-title">The Chola Navy: Fact vs Fiction</div><div class="warn-text">The Chola naval expedition to Srivijaya (1025 CE) is well-attested through the Tanjavur inscription of Rajendra I and the Song Chinese records. However, there is no evidence of a standing navy or naval dockyards in the Chola period. The expedition was likely a large fleet of merchant ships requisitioned for the campaign — the Cholas did not maintain a separate naval establishment (unlike the Dutch East India Company or the Portuguese Armada). The Srivijaya expedition was a one-time long-range raid, not a sustained naval campaign. Nevertheless, it demonstrates the maritime technology and navigational skills of the Cholas. The real foundation of Chola maritime power was their control over the monsoon winds, knowledge of seasonal currents, and the extensive network of Chola guilds (the 'Five Hundred Lords of Ayyavolu' or the Ainoorruvar guild — a powerful merchant guild operating from Southeast Asia to the Red Sea).</div></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 10 written."
