$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 3: VEDIC AGE ===================== -->
<h2 id="vedic">3. Vedic Age (1500-500 BCE)</h2>

<p>The <span class="highlight">Vedic Age</span> is the period between the arrival of Indo-Aryan speakers in the Indian subcontinent and the emergence of urbanisation in the Gangetic plain. Our knowledge of this period comes primarily from the <strong>Vedic literature</strong> - the sacred texts of the Indo-Aryans. The period is divided into the <strong>Early Vedic (Rigvedic) Period</strong> (c. 1500-1000 BCE) and the <strong>Later Vedic Period</strong> (c. 1000-500 BCE). The Vedic age is the formative period of what became classical Hinduism - the caste system, the foundational texts, and the philosophical ideas that shaped Indian civilization for millennia. Scholars debate whether the Vedic culture emerged from indigenous development, small-scale migration, or a combination of both (the current scholarly consensus is the Aryan Migration Theory).</p>

<h3>Vedic Literature - Complete Classification</h3>

<div class="table-wrap"><table>
<tr><th>Category</th><th>Key Texts</th><th>Content and Significance</th></tr>
<tr><td><strong>Samhitas</strong></td><td>Rigveda, Samaveda, Yajurveda (Shukla and Krishna), Atharvaveda</td><td>Core collections of hymns (suktas), mantras, and rituals. The earliest layer of Vedic literature (c. 1500-1000 BCE). The Rigveda is the oldest Indo-European text in the world and contains 1028 hymns.</td></tr>
<tr><td><strong>Brahmanas</strong></td><td>Aitareya (Rigveda), Shatapatha (Yajurveda), Taittiriya (Yajurveda), Gopatha (Atharvaveda), Panchavimsha (Samaveda), etc.</td><td>Prose texts explaining the meaning and procedure of Vedic rituals. Emphasise sacrifice (yajna) as the cosmic power that sustains the universe. The Shatapatha Brahmana is the most important - contains creation myths, geographical details, early scientific knowledge, and the earliest reference to the concept of zero as a positional number.</td></tr>
<tr><td><strong>Aranyakas</strong></td><td>Part of each Veda: Aitareya, Shankhayana, Taittiriya, Brihad, etc.</td><td>'Forest texts' - esoteric, mystical interpretations of rituals meant for hermits and ascetics who had retired to the forest. Bridge between the ritualistic Brahmanas and the philosophical Upanishads. Focus on the inner meaning of sacrifices rather than external performance.</td></tr>
<tr><td><strong>Upanishads</strong></td><td>108 total, 13 principal: Isha, Kena, Katha, Prashna, Mundaka, Mandukya, Taittiriya, Aitareya, Chandogya, Brihadaranyaka, Shvetashvatara, Kaushitaki, Maitri</td><td>Philosophical treatises on the nature of reality (Brahman), the individual self (Atman), and liberation (Moksha). The foundation of Vedanta philosophy. The Mahavakyas include 'Tat Tvam Asi' (That Thou Art - Chandogya), 'Aham Brahmasmi' (I am Brahman - Brihadaranyaka), and 'Ayam Atma Brahma' (This Self is Brahman - Mandukya).</td></tr>
<tr><td><strong>Vedangas</strong></td><td>Shiksha (phonetics), Kalpa (ritual), Vyakarana (grammar), Nirukta (etymology), Chandas (metre), Jyotisha (astronomy)</td><td>'Limbs of the Vedas' - six auxiliary sciences for correct understanding and application of the Vedas. Panini's Ashtadhyayi (c. 500 BCE) is the most complete grammar of any ancient language and a foundational text in modern linguistics. Yaska's Nirukta (c. 600 BCE) is the first etymological dictionary in the world.</td></tr>
<tr><td><strong>Upavedas</strong></td><td>Ayurveda (medicine - Atharvaveda), Dhanurveda (military - Yajurveda), Gandharvaveda (music/dance - Samaveda), Sthapatyaveda (architecture - Rigveda)</td><td>Applied knowledge systems that developed alongside the Vedic tradition. Ayurveda is the oldest continuously practised medical system in the world (Charaka Samhita, Sushruta Samhita).</td></tr>
</table></div>

<h3>Detailed Analysis of the Four Vedas</h3>

<p><strong>1. Rigveda</strong> - The oldest and most important Veda. Composed c. 1500-1000 BCE in the Punjab region. Contains <strong>1028 hymns</strong> (suktas) divided into 10 books (Mandalas) with 10,600 verses. Books II-VII are the oldest (the 'family books', attributed to specific priestly families: Gritsamada, Vishwamitra, Vamadeva, Atri, Vasishtha, Bharadvaja). Book VIII: hymns of the Kanvas. Book IX: dedicated exclusively to <strong>Soma</strong> - the deified plant and ritual drink. Books I and X are the latest additions (c. 1000 BCE). Key deities: <strong>Indra</strong> (warrior god, 250 hymns - the most, rain, thunderbolt - slayer of Vritra the cosmic serpent, releases the waters), <strong>Agni</strong> (fire god, 200 hymns, messenger between humans and gods, priest of the gods, protects the home), <strong>Varuna</strong> (cosmic order - rita, moral judge, omniscient, all-seeing), <strong>Soma</strong> (deified plant of immortality, ritual drink), <strong>Mitra</strong> (contract, friendship), <strong>Ashvins</strong> (divine twin horsemen, healers, saviours from danger), <strong>Ushas</strong> (goddess of dawn, youthful, beautiful, drives away darkness), <strong>Maruts</strong> (storm gods, companions of Indra, 180+ are mentioned), <strong>Vayu</strong> (wind god), <strong>Prithvi</strong> (earth goddess), <strong>Dyaus Pita</strong> (sky father - cognate with Greek Zeus and Roman Jupiter). The <strong>Nasadiya Sukta</strong> (X.129) is a cosmogonic hymn questioning the origin of the universe - remarkable for its agnostic philosophical tone: 'Then there was neither non-existence nor existence... Who really knows who shall here proclaim it - whence was it produced, whence is this creation? The gods themselves are later than this creation, so who knows whence it arose?' The <strong>Purusha Sukta</strong> (X.90) describes the cosmic man whose body created the four varnas - a later interpolation (c. 1000-800 BCE) that provided divine sanction for the caste system. Women composers include Apala, Ghosha, Lopamudra, Vishvavara, and Sikata Nivavari.</p>

<p><strong>2. Samaveda</strong> - The 'Veda of Melodies'. Composed for chanting during Soma sacrifices. Contains 1549 verses, most from the Rigveda (only 75 are original), arranged according to musical notation. The seven notes (Sa, Re, Ga, Ma, Pa, Dha, Ni) known as sadaja, rishabha, gandhara, madhyama, panchama, dhaivata, nishada, are described. The foundation of Indian classical music (Hindustani and Carnatic traditions both trace to the Samaveda). The Samaga priest who chants the Samaveda was highly respected.</p>

<p><strong>3. Yajurveda</strong> - The 'Veda of Sacrificial Formulas'. Prose and verse formulas for the adhvaryu priest who performed the mechanical parts of sacrifice. Two recensions: <strong>Shukla (White) Yajurveda</strong> (Vajasaneyi Samhita, 40 chapters, containing the Isha Upanishad as its final chapter) and <strong>Krishna (Black) Yajurveda</strong> (Taittiriya Samhita, where the prose commentary and the mantra text are intermixed, containing the Taittiriya Upanishad). The White Yajurveda contains the famous <strong>Shiva Sankalpa Sukta</strong>.</p>

<p><strong>4. Atharvaveda</strong> - The 'Veda of Magical Formulas'. Composed c. 1000 BCE. Contains hymns for healing, protection, love, warfare, and domestic rituals. Divided into 20 books, 731 hymns, 6000 verses. Key for understanding folk religion and the beliefs of ordinary people (as opposed to the elite sacrificial religion of the Rigveda). Includes charms against diseases and demons, spells for prosperity (agriculture, trade, love), and philosophical hymns including the <strong>Prithvi Sukta</strong> (a magnificent hymn praising Earth as a living goddess - 'Truth, greatness, universal order, strength, consecration, creative fervor, spiritual exaltation, sacrifice, support the Earth') and the <strong>Skambha Sukta</strong> (on the cosmic pillar supporting the universe). Ayurveda traces its origins to the Atharvaveda, which contains the earliest references to the three doshas (vata, pitta, kapha).</p>

<h3>Early Vedic Period (1500-1000 BCE)</h3>

<p><strong>Geography</strong>: The Rigvedic people inhabited the <span class="highlight">Sapta-Sindhu</span> (Land of Seven Rivers) - the five major rivers of Punjab (Jhelum - Vitasta, Chenab - Asikni, Ravi - Parushni, Beas - Vipasa, Sutlej - Sutudri) plus the Indus (Sindhu) and the Saraswati. This region corresponds to present-day Punjab (both Indian and Pakistani), Haryana, and eastern Afghanistan. The term <strong>Aryavarta</strong> (Land of the Aryans) appears later in the Dharmashastras for the Ganga-Yamuna Doab. The Ganga is mentioned only once and the Yamuna three times in the Rigveda, indicating the Vedic people had not yet moved into the Gangetic plain.</p>

<p><strong>Polity</strong>: The basic political unit was the <strong>kula</strong> (family headed by kulapa), then <strong>grama</strong> (village under gramani), <strong>vis</strong> (clan under vispati), <strong>jana</strong> (tribe), and <strong>rashtra</strong> (kingdom). The king (<strong>rajan</strong>) was a tribal chieftain, not an absolute monarch. He was elected by the tribe and could be removed for incompetence. Two popular assemblies - <span class="highlight">Sabha</span> (council of elders, judicial functions, met in a special hall - sabhavati) and <span class="highlight">Samiti</span> (general assembly of the whole tribe, decided on war and peace, elected the king) - checked the king's power. The <strong>vidatha</strong> was the oldest folk assembly, distributing land, settling disputes, and performing religious functions. Women attended the Sabha and Samiti. The king had no standing army or bureaucracy - he relied on the tribe for military service and on voluntary offerings for income. The <strong>Battle of Ten Kings</strong> (Dasarajna) on the Ravi was won by King Sudas of the Bharata clan against ten allied tribes (Purus, Yadus, Turvasas, Anus, Druhyus, Alinas, Bhalanas, Pakhtas, Bhrigus, and Shimyu), establishing Bharata dominance that gave India its name (Bharatavarsha).</p>

<p><strong>Society</strong>: Society was tribal, kinship-based, and relatively egalitarian. The <span class="highlight">varna system</span> was nascent - based on occupation, not birth. The Purusha Sukta mentions four varnas but is widely accepted as a later addition (c. 1000-800 BCE). The order was: Brahmins (priests, teachers, scholars), Kshatriyas (warriors, rulers), Vaishyas (traders, farmers, cattle-keepers), Shudras (labourers, servants). Inter-varna marriages and occupational mobility were possible. <strong>Women enjoyed high status</strong> - could participate in Sabha and Samiti, choose husbands (svayamvara), remarry if widowed, undergo Vedic education including the upanayana sacred thread initiation, and compose hymns. Notable women: <strong>Lopamudra</strong> (wife of Rishi Agastya, composed hymns on marital harmony), <strong>Ghosha</strong> (daughter of Kakshivan, composed two hymns about curing skin disease), <strong>Apala</strong> (cured of skin disease by Indra, composed hymns), <strong>Gargi Vachaknavi</strong> (participated in philosophical debates at King Janaka's court - the Brihadaranyaka Upanishad describes her debating Yajnavalkya), <strong>Maitreyi</strong> (wife of Yajnavalkya, chose spiritual knowledge over wealth). Monogamy was normal; polygyny existed among chiefs; polyandry is not mentioned. Child marriage was absent - girls were married only after reaching puberty. The <strong>gotra</strong> (exogamous lineage traced to a rishi) system was just emerging, with only Brahmins claiming gotra status initially.</p>

<p><strong>Economy</strong>: <span class="highlight">Pastoral-cum-agricultural</span>. Cattle were the primary form of wealth and the standard of value - the Rigveda describes elaborate cattle raids (gavishthi, meaning 'desire for cows' later synonymous with 'war'). The cow was called aghnya ('not to be killed') and aditi ('not to be cut'). A wealthy man was gomat (possessor of cows). Prices were calculated in cows (a priest's fee was often 100-1000 cows). Agriculture was known but less important than pastoralism - barley (yava) was the main crop; no rice or wheat yet. The plough (sira) was drawn by oxen. Land belonged to the tribe collectively, not to individuals. The danastuti (praise of gifts) hymns describe kings giving priests gifts of cows, horses, gold, female slaves, and captured towns. <strong>Copper</strong> (ayas - red/bright metal) was the main metal; <strong>iron</strong> (krishna ayas - black metal) appears only later in the Atharvaveda.</p>

<p><strong>Religion</strong>: <span class="highlight">Nature worship</span> - deification of natural forces and phenomena. The Rigveda is essentially a collection of hymns to 33 gods (11 in heaven, 11 on earth, 11 in the atmosphere) who are all manifestations of natural phenomena. No temples, no idolatry, no image worship. The most important ritual was the <strong>soma sacrifice</strong> - pressing the soma plant (probably Ephedra or a similar hallucinogenic/energizing plant), offering it to the gods, and the priests drinking it. The concept of <strong>rita</strong> (cosmic law/order, truth) was central - the gods themselves, even the greatest, obeyed rita; Varuna was the guardian of rita ('the one who makes the sun shine' and 'the one who knows the path of birds in the sky'). Yajna (sacrifice) sustained the universe and the gods, providing a contractual relationship between humans and divinity through the priest. The afterlife was a shadowy existence in the realm of Yama (the first mortal/king of the dead, who chose mortality to show others the way). There was no concept of karma or samsara (rebirth) in the Rigveda - these developed later in the Upanishads.</p>

<h3>Later Vedic Period (1000-500 BCE)</h3>

<p><strong>Geography</strong>: The centre of culture shifted eastward to the <span class="highlight">Ganga-Yamuna Doab</span> and the upper Gangetic plain, the Kuru-Panchala region (modern Haryana and western Uttar Pradesh). Iron tools enabled the clearing of the dense forests of the Gangetic basin. Key regions: Kuru (Haryana/Delhi, with capital at Hastinapur), Panchala (western UP, with capitals at Ahichchhatra and Kampilya), Kosala (eastern UP, with Ayodhya), Videha (north Bihar/Mithila, where King Janaka's court was the centre of Upanishadic philosophy). The epic Mahabharata is set in this period, with the conflict between the Kauravas and Pandavas at Hastinapur.</p>

<p><strong>Polity</strong>: Kingship became <span class="highlight">hereditary and absolute</span>. The Sabha and Samiti declined - the Sabha became a judicial body of nobles, the Samiti a mere royal council. Three great sacrificial rituals legitimised the king's power: <span class="highlight">Rajasuya</span> (consecration ceremony, including anointment and symbolic milking of the cow, chariot race, dice game, lasted over a year), <span class="highlight">Ashvamedha</span> (horse sacrifice - the king's horse roamed free for a year with 400 warriors; any territory it crossed unchallenged became the king's; the climax involved sacrificing the horse and the queen performing a ritual with the dead horse), <span class="highlight">Vajapeya</span> (chariot race for rejuvenation of the king's strength, included ritual drinking of soma and required massive gifts to Brahmins). The Brahmins became enormously powerful by monopolising these rituals and interpreting Vedic texts. State formation began - the janapadas (territorial polities) emerged from the earlier tribal janas.</p>

<p><strong>Society</strong>: The <span class="highlight">varna system became rigid and birth-based</span>. Brahmins and Kshatriyas dominated. Vaishyas were reduced to tax-paying commoners. Shudras were reduced to servitude - not allowed to hear or recite the Vedas, perform sacrifices, or inherit property. Untouchables (Chandalas, outside the varna system) emerged at the bottom, performing polluting tasks like cremation, sweeping, and waste removal. The <span class="highlight">gotra system</span> became fixed - Brahmins claimed descent from one of eight primary rishis (Vasishtha, Bhrigu, Kashyapa, Gautama, Atri, Vishwamitra, Jamadagni, Bharadvaja) through an exogamous lineage system. The <strong>ashrama system</strong> (four stages of life: Brahmacharya - student celibate, Grihastha - householder, Vanaprastha - forest-dweller, Sannyasa - renouncer) crystallised in the Dharmasutras (c. 600-300 BCE). <strong>Women's status declined sharply</strong> - excluded from Sabha and Samiti, denied Vedic education and the sacred thread, child marriage became common ('a daughter should be married before puberty' - Grihya Sutras), widows could not remarry, and sati (widow burning) is mentioned in the Vishnu Dharmasutra and the Mahabharata's account of Madri's sati.</p>

<p><strong>Economy</strong>: <span class="highlight">Agriculture became primary</span>. The iron ploughshare and oxen enabled large-scale rice cultivation (rice became the staple). Irrigation (wells, tanks, channels) became common. Panini (c. 500 BCE) describes sophisticated agriculture with 8 types of rice and 6 types of barley. The <strong>king claimed a share (bhaga) of agricultural produce</strong> - the origin of land revenue (1/6th to 1/12th according to texts). Trade and craft specialisation increased: guilds (shreni) of merchants and artisans emerged, led by the sreshthin (banker/merchant prince). Silver coins (shatamana, 100 ratis = 11.5g) and gold ornaments (niska) were used as money. The Panchavimsha Brahmana mentions 16 types of grain and wealth measured in niskas.</p>

<p><strong>Religion</strong>: The elaborate sacrificial cult reached its peak - and became inaccessible to common people. The Shatapatha Brahmana states that 'the gods only accept offerings through Brahmins'. This priestly monopoly and the rising ritualism produced a reaction that gave rise to the <span class="highlight">Upanishads</span>. New deities emerged: <strong>Prajapati</strong> (the creator god, supreme in the Brahmanas, creator of the universe through tapas/heat), <strong>Rudra</strong> (the fierce storm god, precursor to Shiva, described as the 'Supreme Lord' - Ishvara - in the Shvetashvatara Upanishad), <strong>Vishnu</strong> (now a major god who measured the universe with three strides - the Vamana avatar), <strong>Brahma</strong> (the creator). The old Rigvedic devas (Indra, Varuna, Agni) declined. The doctrines of <strong>karma</strong> (actions determining rebirth) and <strong>samsara</strong> (cycle of rebirth) emerged in the Upanishads, transforming Indian religious thought entirely.</p>

<h3>The Upanishads - The Philosophical Revolution</h3>

<p>The <span class="highlight">Upanishads</span> (c. 800-400 BCE) mark a fundamental shift from sacrifice (yajna) to knowledge (jnana), from ritual to inner realisation, from polytheism to monism (advaita). The word 'Upanishad' means 'to sit down near' (a teacher). The central teachings that transformed Indian philosophy:</p>
<ul>
<li><strong>Brahman</strong> - The ultimate reality, infinite, unchanging, the ground of all existence. Described as Sat-Chit-Ananda (Being-Consciousness-Bliss). Beyond all categories: 'Neti, Neti' (Not this, not this). Brahman is the cosmic principle from which everything emanates, in which everything exists, and into which everything dissolves. The universe is not created by Brahman - it is an expression of Brahman, like a spider's web from the spider (Mundaka Upanishad).</li>
<li><strong>Atman</strong> - The individual self, the innermost essence of every being. The Mahavakyas teach the identity of Atman and Brahman: 'Tat Tvam Asi' (That Thou Art - Chandogya, Uddalaka's teaching to Shvetaketu through 9 examples including the seed, salt in water, and the banyan tree), 'Aham Brahmasmi' (I am Brahman - Brihadaranyaka, Yajnavalkya's declaration), 'Ayam Atma Brahma' (This Self is Brahman - Mandukya), 'Prajnanam Brahma' (Consciousness is Brahman - Aitareya). The goal of life is to realise this identity, which brings liberation (moksha).</li>
<li><strong>Karma</strong> - The universal law of cause and effect in the moral realm. Every action generates consequences that determine the conditions of future births. This is an impersonal, natural law, not administered by any deity.</li>
<li><strong>Samsara</strong> - The cycle of birth, death, and rebirth, driven by karma and ignorance (avidya). The Brihadaranyaka Upanishad describes the soul passing from one life to another 'like a caterpillar moving from blade to blade, drawing itself together as it goes'.</li>
<li><strong>Moksha</strong> - Liberation from samsara, attained only through knowledge (jnana) that Atman is Brahman, not through ritual or good works. A jivanmukta (one liberated while alive) is not limited by karma. The Katha Upanishad describes the path: 'The sharp edge of a razor is difficult to pass over - thus the wise say the path to salvation is hard.'</li>
</ul>

<div class="example-box"><div class="ex-title">Key Upanishadic Quotes for UPSC</div><div class="ex-text">&#8226; <strong>'Tat Tvam Asi'</strong> (That Thou Art) - Chandogya Upanishad: the essential identity of the individual self with ultimate reality, taught by Uddalaka to Shvetaketu.<br>&#8226; <strong>'Aham Brahmasmi'</strong> (I am Brahman) - Brihadaranyaka Upanishad: the self-declaration of the liberated soul by Yajnavalkya.<br>&#8226; <strong>'Prajnanam Brahma'</strong> (Consciousness is Brahman) - Aitareya Upanishad.<br>&#8226; <strong>'Ayam Atma Brahma'</strong> (This Self is Brahman) - Mandukya Upanishad (the shortest Upanishad, 12 verses on the syllable AUM).<br>&#8226; <strong>'Uttishthata, Jagrata, Prapya Varannibodhata'</strong> (Arise, awake, stop not till the goal is reached) - Katha Upanishad: Yama's instruction to Nachiketa about the path to wisdom.<br>&#8226; <strong>'Asato Ma Sadgamaya, Tamaso Ma Jyotirgamaya, Mrityor Ma Amritam Gamaya'</strong> (From the unreal lead me to the real, from darkness to light, from death to immortality) - Brihadaranyaka Upanishad: one of the most famous prayers in Hinduism.</div></div>

<h3>Comparative Table: Early Vedic vs Later Vedic</h3>

<div class="table-wrap"><table>
<tr><th>Feature</th><th>Early Vedic (1500-1000 BCE)</th><th>Later Vedic (1000-500 BCE)</th></tr>
<tr><td>Geography</td><td>Sapta-Sindhu (Punjab, Haryana, E. Afghanistan)</td><td>Ganga-Yamuna Doab, upper Gangetic plain (Kuru-Panchala, Kosala, Videha)</td></tr>
<tr><td>Political Organisation</td><td>Elective tribal monarchy; Sabha/Samiti powerful; no territorial states</td><td>Hereditary absolutism; rituals for legitimacy (Ashvamedha, Rajasuya); janapadas emerging</td></tr>
<tr><td>Varna System</td><td>Flexible, based on occupation; birth secondary</td><td>Rigid, birth-based; Brahmin domination; untouchability emerging</td></tr>
<tr><td>Women's Status</td><td>High - Vedic education, Sabha participation, svayamvara, widow remarriage</td><td>Declined - no Vedic education, child marriage, no remarriage, sati appears</td></tr>
<tr><td>Economy</td><td>Pastoral dominant; barley only; no iron; no coins; barter economy</td><td>Agriculture dominant; iron ploughshare; rice staple; guilds, coins (shatamana)</td></tr>
<tr><td>Religion</td><td>Nature worship; Indra/Agni/Varuna supreme; simple yajnas; no temples/idols</td><td>Ritualism; Prajapati, Rudra/Shiva ascendant; Brahmin monopoly; Upanishads emerge</td></tr>
<tr><td>Major Texts</td><td>Rigveda (early parts) only; no Brahmanas/Upanishads yet</td><td>All four Vedas; Brahmanas; Aranyakas; Upanishads; Vedangas begin</td></tr>
<tr><td>Social Institutions</td><td>Gotra nascent; tribal identity; no ashrama stages</td><td>Gotra system fixed; ashrama system (4 stages); hereditary occupations; jati emerging</td></tr>
<tr><td>Technology</td><td>Copper/ bronze only; no iron; horse-drawn chariot</td><td>Iron tools and weapons; horse and cavalry important</td></tr>
</table></div>

<div class="warn-box"><div class="warn-title">Historiographical Debate: Aryan Origins</div><div class="warn-text">The 'Aryan Invasion Theory' (AIT) has been abandoned by mainstream scholarship. The current consensus is the <strong>Aryan Migration Theory</strong> - a gradual, small-scale migration of Indo-European speakers into South Asia (c. 2000-1500 BCE). Vedic culture evolved from the interaction of Indo-Aryan migrants and indigenous populations. The 'Out of India Theory' (claiming Indo-European languages spread from India) has no support in archaeology, genetics, or linguistics. The Aryan debate is one of the most politicised in Indian history, with Hindutva ideologues promoting the indigeneity theory for political reasons. Scholars should rely on the evidence: linguistic (Indo-European language relationships), genetic (Ancestral North Indian component appearing c. 2000-1500 BCE), and archaeological (lack of violent discontinuity between IVC and post-IVC cultures, but changes in material culture consistent with cultural mixing).</div></div>

<div class="diagram-box"><pre>
  VEDIC LITERATURE - STRUCTURE

  SAMHITAS (Rig, Sama, Yajur, Atharva - mantra texts)
     |
  BRAHMANAS (Ritual manuals, prose explanations)
     |
  ARANYAKAS (Forest texts - esoteric/meditative)
     |
  UPANISHADS (Philosophy - the 'end of the Vedas'/Vedanta)
     |
  VEDANGAS (6 auxiliary sciences: phonetics, grammar, etc.)
     |
  SUTRAS (Dharmasutras, Grihyasutras - codes of conduct)
</pre></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 3 written."
