const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';

let c = fs.readFileSync(outPath, 'utf8');

c += `\n<h4>Petroleum and Natural Gas</h4>\n\n`;
c += `<p>India is the <span class="highlight">3rd largest consumer of oil in the world</span> (after the US and China), consuming about 5.5 million barrels/day (275 million tonnes/yr), but produces only about 0.7 million barrels/day (35 million tonnes/yr). This makes India <strong>85% import-dependent</strong> for crude oil. The domestic production comes from three major sedimentary basins:</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>Mumbai Offshore Basin (Bombay High)</strong> &mdash; The <span class="highlight">largest oil-producing region in India</span>, accounting for about 60% of domestic production. The <strong>Mumbai High</strong> (discovered in 1974 by the Russian drilling vessel Sagar Samrat) is a giant oil field about 160 km west of Mumbai, in the Arabian Sea, at water depths of 50-80 m. It was developed by <strong>ONGC</strong> (Oil and Natural Gas Corporation). Other fields in this basin include <strong>Ratna</strong>, <strong>R-12</strong>, <strong>Bassein</strong>, and <strong>Heera</strong>. The basin also has significant associated gas. The oil is light, sweet crude (low sulphur), ideal for refining. The Mumbai High produces about 200,000 barrels/day but is in a mature stage with declining output (peaked at 300,000 bpd in the 1990s).</li>\n`;
c += `<li><strong>Cambay Basin (Gujarat)</strong> &mdash; The <span class="highlight">second largest oil-producing region</span>, located in the Cambay Rift Valley (a failed rift from the Deccan volcanic period). The major oil fields are <strong>Ankleshwar</strong> (the largest onshore field in India, discovered in 1962), <strong>Kalol</strong>, <strong>Mehsana</strong>, <strong>Navagam</strong>, and <strong>Sanand</strong>. The basin also produces significant natural gas (about 40% of India's onshore gas). The fields are mature and producing at declining rates.</li>\n`;
c += `<li><strong>Krishna-Godavari (KG) Basin</strong> &mdash; The <span class="highlight">most important recent discovery province</span>, with vast natural gas reserves. The <strong>KG-D6</strong> block (operated by Reliance Industries, discovered in 2002) was the largest gas discovery in the world in 2002, with estimated reserves of 10 TCF (trillion cubic feet). Production peaked at 60 million standard cubic metres/day (mmscmd) in 2010 but declined sharply to 10 mmscmd by 2015 due to geological complexity and reservoir pressure issues. The KG basin also has significant oil discoveries (the 'N-9' discovery by ONGC in 2020). Recent discoveries by ONGC in the <strong>KG-OS-D4</strong> block (the 'Mahanadi deepwater') and by Reliance-BP in the <strong>KG-D6 R-Cluster</strong> and <strong>Satellite fields</strong> are expected to reverse the production decline from 2025 onward.</li>\n`;
c += `<li><strong>Assam-Arakan Basin</strong> &mdash; The <span class="highlight">oldest oil-producing region in Asia</span>. The <strong>Digboi</strong> field (discovered in 1889) is the oldest continuously producing oil field in the world, and the Digboi refinery (set up in 1901) is Asia's oldest refinery that is still operational. Other fields include <strong>Naharkatiya</strong> (discovered in 1953, the largest in Assam), <strong>Moran</strong>, <strong>Rudrasagar</strong>, <strong>Lakwa</strong>, and <strong>Geleki</strong>. The region produces a waxy, high-paraffin crude that is ideal for lubricants.</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>ONGC</strong> (Oil and Natural Gas Corporation, established 1956) is the <span class="highlight">largest oil and gas exploration and production company in India</span>, accounting for about 70% of domestic production. It operates the Mumbai High, the majority of the Cambay fields, and has made major discoveries in the KG Basin and the Mahanadi offshore. <strong>Indian Oil Corporation (IOC)</strong> is the largest oil refining and marketing company, operating 10 of India's 23 refineries, with a total refining capacity of about 80 million tonnes/yr. India's total <strong>refining capacity</strong> is about <strong>250 million tonnes/yr</strong> (the 4th largest in the world), significantly exceeding domestic production, with refineries processing both domestic and imported crude. The surplus refined products (<strong>petroleum product exports of about 60 million tonnes/yr</strong>, worth $50 billion) make India a major exporter of petrol, diesel, and aviation fuel to Asia, Africa, and Europe.</p>\n\n`;

c += `<p><strong>Strategic Petroleum Reserves (SPRs)</strong> are emergency crude oil storage facilities maintained by the <strong>Indian Strategic Petroleum Reserves Limited (ISPRL)</strong>. India has four SPR facilities with a total capacity of <strong>5.33 million tonnes</strong> (about 10 days of consumption): <strong>Visakhapatnam</strong> (1.33 MT, Andhra Pradesh, underground rock cavern), <strong>Mangalore</strong> (1.5 MT, Karnataka, rock cavern), <strong>Padur</strong> (2.5 MT, Karnataka, rock cavern), and <strong>Chandikhol</strong> (0.75 MT, Odisha, rock cavern &mdash; Phase II, completed 2024). A further 6.5 MT capacity is planned at two additional locations (Padur II and Rajkot). The total planned strategic reserve of 12 MT would cover about 22 days of consumption, still far short of the IEA-recommended 90-day reserve.</p>\n\n`;

c += `<h4>Nuclear Energy</h4>\n\n`;
c += `<p>Nuclear energy contributes about <strong>3% of India's electricity generation</strong> (7,500 MW installed capacity from 22 operational reactors across 7 nuclear power plants). The <span class="highlight">Indian nuclear power programme</span> is unique for its emphasis on the <strong>thorium-based fuel cycle</strong>, designed by <strong>Dr Homi Bhabha</strong> to utilise India's vast thorium reserves (the largest in the world) while bypassing the plutonium-based proliferation concerns.</p>\n\n`;
c += `<p><strong>Uranium</strong> is the primary fuel for India's current nuclear reactors. India's uranium reserves are modest (about 200,000 tonnes, the 15th largest in the world), concentrated in two regions:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Jharkhand</strong> &mdash; The <span class="highlight">Singhbhum Thrust Zone</span> contains the most important uranium deposits, at <strong>Jaduguda</strong> (the oldest, operational since 1967), <strong>Bhatin</strong>, <strong>Narwapahar</strong>, <strong>Turamdih</strong>, <strong>Bagjata</strong>, and <strong>Banduhurang</strong> (the first open-pit uranium mine in India). These are operated by the <strong>Uranium Corporation of India Limited (UCIL)</strong>.</li>\n`;
c += `<li><strong>Andhra Pradesh</strong> &mdash; The <strong>Tummalapalle</strong> uranium deposit (Kadapa district) is one of the largest in the world, with estimated reserves of 150,000 tonnes. It is a 'strata-bound' deposit, hosted in limestone, and is processed using a unique alkaline leaching method. The mine started production in 2012.</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>Thorium</strong> is India's <span class="highlight">most abundant nuclear resource</span>. India has about <strong>500,000 tonnes of monazite</strong> (the primary thorium-bearing mineral), the largest in the world, constituting about 25% of global thorium reserves. Monazite is a heavy mineral sand found along the Kerala coast (<strong>Chavara</strong> and <strong>Manavalakurichi</strong> in Kollam district), the Tamil Nadu coast, the Odisha coast (<strong>Chatrapur</strong> beach sands), and the Andhra Pradesh coast (<strong>Kakinada</strong> and <strong>Bheemunipatnam</strong> beach sands). The <strong>Indian Rare Earths Limited (IREL)</strong> extracts monazite from these beach sands and processes it to extract thorium and other rare earth elements. The <strong>Kollam district</strong> (Kerala) is particularly significant &mdash; the Chavara beach sands have the highest monazite concentration (up to 10% of the sand) in the world.</p>\n\n`;

c += `<p><strong>The 3-Stage Nuclear Power Programme</strong> was conceptualised by Dr Homi Bhabha in the 1950s to make India energy-independent using its thorium reserves:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Stage 1: Pressurised Heavy Water Reactors (PHWR)</strong> &mdash; These use natural uranium (0.7% U-235) as fuel and heavy water (D2O) as moderator and coolant. The spent fuel produces plutonium (Pu-239), which is the fuel for Stage 2. India has 18 operational PHWRs (the largest PHWR fleet in the world after Canada) at <strong>Tarapur</strong>, <strong>Rawatbhata</strong>, <strong>Kalpakkam</strong>, <strong>Kakrapar</strong>, <strong>Narora</strong>, and <strong>Kaiga</strong>.</li>\n`;
c += `<li><strong>Stage 2: Fast Breeder Reactors (FBR)</strong> &mdash; These use plutonium (from stage 1) as fuel and convert thorium (Th-232) into uranium-233 (U-233), the fuel for Stage 3. The <strong>Prototype Fast Breeder Reactor (PFBR)</strong> at Kalpakkam (500 MW, under commissioning since 2004) is India's first FBR and is designed to 'breed' more fuel (plutonium) than it consumes. It will be the critical technological bridge between Stage 1 and Stage 3.</li>\n`;
c += `<li><strong>Stage 3: Thorium-Uranium-233 Cycle</strong> &mdash; Advanced Heavy Water Reactors (AHWR) will use the Th-U233 fuel cycle. India is developing the AHWR-300 at the Bhabha Atomic Research Centre (BARC). This stage is expected to become commercially viable by 2040-50.</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>Nuclear Power Plants in India</strong> (7 major plants, 22 reactors, 7,500 MW installed):</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Tarapur (Maharashtra)</strong> &mdash; The first nuclear power plant in India (1969), with 2 Boiling Water Reactors (BWRs) of 160 MW each (originally 210 MW, downrated), and 2 PHWRs of 540 MW each (units 3&4, the largest PHWRs in India).</li>\n`;
c += `<li><strong>Rawatbhata (Rajasthan)</strong> &mdash; 6 units of PHWRs (100-220 MW each), including units 1&2 (the first PHWRs in India, built with Canadian collaboration), and units 5&6 (220 MW each, indigenous).</li>\n`;
c += `<li><strong>Kalpakkam (Tamil Nadu)</strong> &mdash; 2 PHWRs of 220 MW each (units 1&2) and the PFBR (500 MW, under commissioning). The Madras Atomic Power Station (MAPS).</li>\n`;
c += `<li><strong>Kakrapar (Gujarat)</strong> &mdash; 2 PHWRs of 220 MW each (units 1&2) and 2 PHWRs of 700 MW each (units 3&4, the largest indigenous PHWRs, unit 3 was commissioned in 2023).</li>\n`;
c += `<li><strong>Narora (Uttar Pradesh)</strong> &mdash; 2 PHWRs of 220 MW each.</li>\n`;
c += `<li><strong>Kaiga (Karnataka)</strong> &mdash; 4 PHWRs of 220 MW each (units 1-4).</li>\n`;
c += `<li><strong>Kudankulam (Tamil Nadu)</strong> &mdash; 2 VVER-1000 reactors (1,000 MW each, pressurised water reactors built with Russian collaboration, units 1&2 operational). Units 3-6 (1,000 MW each) are under construction, and Kudankulam will become the largest nuclear power station in India (6,000 MW).</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>Key Legal and Policy Frameworks</strong>:</p>\n`;
c += `<ul>\n`;
c += `<li><strong>Civil Liability for Nuclear Damage Act 2010 (Nuclear Liability Act)</strong> &mdash; This law creates a framework for civil liability in the event of a nuclear accident. It assigns primary liability to the operator (the plant owner) and allows the operator to sue the supplier in case of defective equipment. The law's provision for 'right of recourse' against the supplier (Section 17) was a contentious issue that delayed the implementation of the India-US Civil Nuclear Deal, as foreign suppliers (Westinghouse, GE, Areva) demanded indemnity from liability. The Act limits the operator's liability to Rs 1,500 crore (about $200 million), with the government bearing liability beyond that.</li>\n`;
c += `<li><strong>India-US Civil Nuclear Deal 2008</strong> &mdash; A landmark agreement that ended India's nuclear isolation since the 1974 Pokhran test. Under the deal, India agreed to separate its civilian and military nuclear facilities, place civilian facilities under IAEA safeguards, and sign the Additional Protocol. In return, the US agreed to provide India access to civil nuclear technology, fuel, and reactors. The deal was enabled by a 'waiver' from the <strong>Nuclear Suppliers Group (NSG)</strong> in 2008, allowing India to engage in civil nuclear trade despite being a non-signatory to the NPT. India's bid for full NSG membership (initiated in 2016) has been blocked by China citing the NPT non-proliferation norm.</li>\n`;
c += `</ul>\n\n`;

c += `<h4>Non-Conventional / Renewable Energy</h4>\n\n`;
c += `<p>India has set ambitious renewable energy targets: <span class="highlight">500 GW of non-fossil fuel capacity by 2030</span> (announced at COP-26, Glasgow, 2021), of which 280 GW is expected from solar, 140 GW from wind, and the remainder from hydro, biomass, and nuclear. As of 2024, India's installed renewable capacity (including large hydro) is about <strong>180 GW</strong>, making it the 4th largest renewable energy market in the world after China, the US, and Brazil.</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>Solar Energy</strong> &mdash; India has a solar energy potential of about 750 GW (equivalent to 5,000 trillion kWh/yr of solar radiation). The installed solar capacity is about <strong>75 GW</strong> (2024), making India the 5th largest solar market in the world. The <strong>National Solar Mission</strong> (part of the National Action Plan on Climate Change, launched 2010) set a target of 100 GW by 2030 (revised from 20 GW). The largest solar parks include <strong>Bhadla Solar Park</strong> (Rajasthan, 2.25 GW, the largest in the world), <strong>Pavagada Solar Park</strong> (Karnataka, 2 GW, also known as Shakti Sthala), <strong>Kurnool Solar Park</strong> (Andhra Pradesh, 1 GW), <strong>Rewa Solar Park</strong> (Madhya Pradesh, 750 MW, the first solar park to supply power to a metro system &mdash; Delhi Metro), and the proposed <strong>Ladakh Solar PV plant</strong> (7.5 GW, the largest planned solar installation in the world, at an altitude of 4,000 m in the cold desert, with transmission lines costing 3x the generation cost). The <strong>PM-KUSUM</strong> scheme promotes solar pumps in agriculture. <strong>Rooftop solar</strong> is promoted through the PM Surya Ghar Muft Bijli Yojana (2024).</li>\n`;
c += `<li><strong>Wind Energy</strong> &mdash; India has the <span class="highlight">4th largest installed wind capacity in the world</span> (after China, the US, and Germany), at about <strong>45 GW</strong>. The wind energy potential is estimated at 695 GW at 120 m hub height (NIWE estimate). The leading wind energy states are <strong>Tamil Nadu</strong> (the largest, with 10 GW), <strong>Gujarat</strong> (9 GW), <strong>Maharashtra</strong> (5 GW), <strong>Karnataka</strong> (5 GW), and <strong>Rajasthan</strong> (5 GW). Major wind farms include <strong>Muppandal</strong> (Tamil Nadu, 1,500 MW, the largest onshore wind farm in India), <strong>Jaisalmer Wind Park</strong> (Rajasthan, 1,064 MW), and the <strong>Kutch Wind Farm</strong> (Gujarat, 600 MW). The <strong>National Offshore Wind Energy Policy</strong> (2015) targets offshore wind in the Gulf of Khambhat and Gulf of Mannar, with a target of 30 GW by 2030 (though no offshore wind farm has been commissioned yet).</li>\n`;
c += `<li><strong>Hydroelectricity</strong> &mdash; India has a hydroelectric potential of about 145 GW (at 60% load factor), with installed capacity of <strong>47 GW</strong> (including 5 GW of small hydro). There are over 250 hydroelectric projects, the largest being <strong>Tehri Dam</strong> (Uttarakhand, 2,400 MW, the highest dam in India at 260 m), <strong>Bhakra Nangal</strong> (Punjab, 1,325 MW), and the <strong>Sardar Sarovar Dam</strong> (Gujarat, 1,450 MW). The share of hydro in India's electricity mix has declined from 40% in 1980 to about 10% today, due to environmental clearances, displacement issues, and the faster growth of thermal and renewable capacity. The <strong>Hydro Power Policy 2023</strong> classifies large hydro (above 25 MW) as renewable energy (previously it was separate), opening up hydro to renewable purchase obligations (RPO) benefits.</li>\n`;
c += `<li><strong>Biomass and Bioenergy</strong> &mdash; India produces about 500 million tonnes of agricultural residue annually, of which about 30% is surplus available for energy generation. The installed biomass power capacity (including bagasse co-generation) is about <strong>10 GW</strong>. Over 500 biomass power plants and bagasse co-generation plants are operational, with the highest concentration in Uttar Pradesh, Maharashtra, and Tamil Nadu. The <strong>National Biofuel Policy 2018</strong> targets 20% ethanol blending in petrol by 2025 (achieved 12% in 2024). The <strong>SATAT</strong> scheme promotes compressed biogas (CBG) from agricultural waste.</li>\n`;
c += `<li><strong>Geothermal Energy</strong> &mdash; India's geothermal potential is estimated at 10 GW, but installed capacity is negligible (less than 10 MW, demonstration plants only). The promising geothermal provinces are the <strong>Puga Valley</strong> (Ladakh, 130 &deg;C reservoir temperature), the <strong>Parvati Valley</strong> (Himachal Pradesh, the Manikaran hot springs at 100 &deg;C), the <strong>Cambay Rift</strong> (Gujarat, the hottest known geothermal reserve in India, at 200 &deg;C at 3 km depth), and the <strong>Damodar Valley</strong> (Jharkhand, the Bakreswar hot springs). The Geological Survey of India has identified 400 hot spring sites across the country.</li>\n`;
c += `<li><strong>Tidal and Wave Energy</strong> &mdash; India's potential is estimated at 8,000 MW (tidal) and 40,000 MW (wave), primarily in the Gulf of Khambhat (Gujarat, 7,000 MW, the highest tidal range in India at 10-12 m), the Gulf of Kutch (Gujarat, 1,200 MW), and the Sundarbans (West Bengal). No commercial tidal power plant has been established yet. The <strong>Kutch Tidal Power Project</strong> (250 MW) and the <strong>Khambhat Tidal Power Project</strong> (7,000 MW) are under feasibility study.</li>\n`;
c += `</ul>\n\n`;

c += `<p><strong>The International Solar Alliance (ISA)</strong> was launched jointly by <strong>India and France</strong> at the <strong>COP-21 Paris Summit</strong> (2015) as a coalition of solar-resource-rich countries (the 'Suryaputra' nations located between the Tropics of Cancer and Capricorn). The ISA is headquartered at <strong>Gurugram, India</strong> (the 'ISA Secretariat' in the National Institute of Solar Energy campus). The alliance has 120 signatory countries. Its goal is to mobilise $1,000 billion in solar energy investments by 2030, promote solar technology transfer, and develop common standards for solar equipment. The ISA is the first international organisation headquartered in India and is a treaty-based intergovernmental organisation under the UN. The <strong>World Solar Bank</strong> (proposed in 2020) is intended to provide concessional financing for solar projects in member countries.</p>\n\n`;

c += `<div class="warn-box"><div class="warn-title">The Energy Crisis and the Renewable Energy Transition</div><div class="warn-text">India's energy sector faces a structural trilemma: the simultaneous need for <strong>energy security</strong> (reliable 24x7 power for 1.4 billion people), <strong>energy affordability</strong> (the poorest 20% spend 8-10% of their income on energy), and <strong>environmental sustainability</strong> (India's per capita CO2 emissions are 2 tonnes, half the global average, but total emissions are the 3rd highest in the world). The 2021-22 coal crisis exposed the fragility of the coal-dependent power system &mdash; 135 of India's 165 coal-fired plants were operating on 'super-critical' coal stocks of less than 4 days. The renewable energy transition is accelerating, but faces challenges: the intermittent nature of solar and wind requires massive grid-scale battery storage (India has less than 5 GWh of battery storage capacity, against a requirement of 500+ GWh by 2030); the Green Energy Corridor (transmission infrastructure to carry renewable power from the resource-rich states like Rajasthan and Gujarat to the demand centres) is running 3 years behind schedule; and the financial health of DISCOMs (power distribution companies) &mdash; with accumulated losses of Rs 6 lakh crore ($80 billion) &mdash; constrains the ability to purchase renewable power at higher tariffs. The <strong>Energy Transition</strong> will require a 'just transition' for the 2 million workers in the coal mining and thermal power sectors, and for the coal-dependent states of Jharkhand, Odisha, Chhattisgarh, and West Bengal, where coal royalties constitute 15-20% of state revenues.</div></div>\n\n`;

c += `<div class="table-wrap"><table>\n`;
c += `<tr><th>Mineral</th><th>Top 3 Producing States</th><th>Major Mines/Deposits</th><th>India's Global Rank</th></tr>\n`;
c += `<tr><td>Iron Ore</td><td>Odisha, Chhattisgarh, Karnataka</td><td>Bailadila, Noamundi, Bellary</td><td>3rd (production), 4th (reserves)</td></tr>\n`;
c += `<tr><td>Manganese</td><td>Madhya Pradesh, Maharashtra, Odisha</td><td>Balaghat, Nagpur, Sundergarh</td><td>5th</td></tr>\n`;
c += `<tr><td>Copper</td><td>Rajasthan, MP, Jharkhand</td><td>Khetri, Malanjkhand, Singhbhum</td><td>Import-dependent</td></tr>\n`;
c += `<tr><td>Bauxite</td><td>Odisha, Gujarat, Jharkhand</td><td>Panchpatmali, Kutch, Lohardaga</td><td>5th</td></tr>\n`;
c += `<tr><td>Gold</td><td>Karnataka, Andhra Pradesh, UP</td><td>Hutti, Kolar (closed), Ramagiri</td><td>Negligible (import-dependent)</td></tr>\n`;
c += `<tr><td>Mica</td><td>Jharkhand, Rajasthan, Andhra Pradesh</td><td>Koderma, Bhilwara, Nellore</td><td>1st</td></tr>\n`;
c += `<tr><td>Coal</td><td>Chhattisgarh, Odisha, Jharkhand</td><td>Singrauli, Talcher, Korba, Jharia</td><td>2nd (production), 5th (reserves)</td></tr>\n`;
c += `<tr><td>Uranium</td><td>Jharkhand, Andhra Pradesh</td><td>Jaduguda, Tummalapalle</td><td>Import-dependent</td></tr>\n`;
c += `<tr><td>Thorium</td><td>Kerala, Tamil Nadu, Odisha</td><td>Chavara, Manavalakurichi</td><td>1st</td></tr>\n`;
c += `</table></div>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 6 complete. Total: ' + c.length + ' chars');
