$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 11: DELHI SULTANATE ===================== -->
<h2 id="delhi-sultanate">11. Delhi Sultanate (1206-1526 CE)</h2>

<p>The <span class="highlight">Delhi Sultanate</span> was the first major Islamic state in India, established after the Ghurid invasions. It comprised five successive dynasties: the <strong>Slave (Mamluk) Dynasty</strong> (1206-1290), the <strong>Khalji Dynasty</strong> (1290-1320), the <strong>Tughlaq Dynasty</strong> (1320-1414), the <strong>Sayyid Dynasty</strong> (1414-1451), and the <strong>Lodi Dynasty</strong> (1451-1526). The 'Sultanate' period is a crucial era of Indo-Islamic synthesis — in administration, architecture (the Delhi style: Qutb Minar, Alai Darwaza, the Tughlaqabad fort), culture (Persian as the court language, the emergence of Urdu as a vernacular, the arrival of Sufi saints like Nizamuddin Auliya), and the economy (the expansion of the iqta system, the demand for revenue in cash, the use of slave soldiers and war elephants). The Delhi Sultans ruled from Delhi over varying extents of territory — at its peak under Alauddin Khalji (r. 1296-1316) and Muhammad bin Tughlaq (r. 1324-1351), the Sultanate controlled most of the Indian subcontinent, though the Deccan and South India were largely independent from the 1340s onwards.</p>

<h3>Pre-Sultanate Invasions: Mahmud of Ghazni</h3>

<p><span class="highlight">Mahmud of Ghazni</span> (r. 997-1030 CE) was the first major Islamic invader of India. He was the ruler of the Ghaznavid Empire (centred in Ghazni, modern Afghanistan — a Turkic Sunni dynasty). Mahmud invaded India 17 times between 1000 and 1027 CE — but he was not a coloniser; he was a raider who plundered the wealth of India's temples and returned to Ghazni. His most famous raid was the <strong>attack on the Somnath Temple</strong> (Gujarat, 1025 CE), which he broke into and looted (Somnath was one of the 12 jyotirlingas — the idol was destroyed and carried to Ghazni). Other targets: Thanesar (1014), Mathura (1018), Kannauj (1019), Kalinjar (1022), Bari (1023). His invasions broke the power of the Hindu Shahi dynasty of Gandhara (King Jayapala committed suicide after defeat), exposed the military weakness of the fragmented Rajput kingdoms, and opened the northwest corridor for later Islamic incursions. Mahmud was a patron of Persian learning — his court at Ghazni included the great Persian poet Ferdowsi (who dedicated the Shahnameh to him) and the scientist Al-Biruni (who wrote the Kitab al-Hind — a detailed Arabic ethnography of Indian religion, philosophy, science, and social customs, the most important medieval source on India: 'The Hindus... are totally different from the Muslims... we believe in nothing in which they believe, and vice versa').</p>

<h3>Slave (Mamluk) Dynasty (1206-1290)</h3>

<p><strong>Qutb-ud-din Aibak</strong> (1206-1210) — a slave of Muhammad Ghori who was appointed viceroy of the Indian territories after Ghori's death (1206). He founded the Slave Dynasty and the Delhi Sultanate. Aibak constructed the <strong>Quwwat-ul-Islam Mosque</strong> (at the Qutb complex, Delhi — the earliest surviving mosque in India, built with materials from 27 demolished Jain and Hindu temples) and began the construction of the <strong>Qutb Minar</strong> (a minaret complex symbolising the might of Islam in India, 72.5m tall, 5 storeys, the tallest brick minaret in the world, begun by Aibak and completed by Iltutmish and Firuz Shah Tughlaq). Aibak died falling from a horse while playing polo (chaugan). <strong>Iltutmish</strong> (1211-1236) — the real founder of the Sultanate. He was Aibak's son-in-law and a slave of Turkish origin. He consolidated the Sultanate, suppressed rebellions, withstood the Mongol invasion threat (Genghis Khan's armies reached the Indus in 1221 but he did not advance into the Delhi Sultanate; Iltutmish wisely did not give refuge to the Khwarazm prince Jalaluddin Mangburni). He completed the Qutb Minar, standardised the coinage (the silver tanka — the first standardised currency of the Delhi Sultanate, which became the basis of the rupee), organised the ruling elite into the <strong>Forty (Chalisa)</strong> — a group of 40 Turkish slaves (the Turkan-i-Chihalgani) who served as his military commanders and administrators. He issued the first Sultanate coins with the Kalima (Islamic creed). His daughter <strong>Razia Sultana</strong> (1236-1240) became the first and only female ruler of the Delhi Sultanate. She was an able ruler who fought in battle, dressed like a man, and was deposed when she appointed a Habshi (Ethiopian) as commander-in-chief (the Turkish nobility rebelled). She was killed in battle near Kurukshetra. The later Slave dynasty rulers were weak — <strong>Balban</strong> (1266-1287) was the last great Slave king. He introduced rigorous court etiquette (sijda — prostration before the king, paibos — kissing the king's feet), a spy network, and the policy of 'blood and iron' to suppress rebellions and defend the northwest frontier against the Mongols (he built the Chhajju Khan? No, he organised the frontier defence). His theory of kingship was divine right — 'The shadow of God on Earth' (zill-i-ullah). He broke the power of the Forty (Chalisa) and centralised authority. He was a great patron of Persian poetry (the poet Amir Khusrau was his court poet). Balban's successors were weak, leading to the Khalji revolution.</p>

<h3>Khalji Dynasty (1290-1320)</h3>

<p><strong>Jalaluddin Khalji</strong> (1290-1296) — founded the Khalji dynasty after a coup against the Mamluks. He was old and merciful (he pardoned rebels, refused to execute his nephew Alauddin). His nephew and son-in-law <strong>Alauddin Khalji</strong> (1296-1316) murdered him and became the most powerful ruler of the Delhi Sultanate. Alauddin's reign marked the <strong>height of the Delhi Sultanate</strong> — he was the first Sultan to conquer the Deccan and South India. He sent his general <strong>Malik Kafur</strong> (a converted Hindu, originally a eunuch slave) on two campaigns: the first (1310) to Devagiri (Yadava), Warangal (Kakatiya), Dwarasamudra (Hoysala), and Madurai (Pandya); the second (1311) to the Pandya kingdom — Malik Kafur reached Rameswaram, the southernmost point in India. The Deccan kingdoms were plundered and forced to pay tribute (though direct control was limited). Alauddin's empire extended from Afghanistan to the Madurai region — the largest territory controlled by a Delhi Sultan.</p>

<p>Alauddin's <strong>administrative and economic reforms</strong> are famous: <strong>Market control</strong> (the most remarkable economic experiment in medieval India) — he fixed the prices of all goods from grain, cloth, to cattle and horses. Prices were maintained through a system of state granaries, licensing of traders, a market intelligence network (barids), and severe punishment for hoarding or profiteering (merchants were weighed and their bones broken for violations). The grain market at Delhi was a model of state regulation — farmers were forced to sell grain to the state at fixed prices, which was then distributed to soldiers and the urban population at controlled rates. <strong>Revenue reforms</strong> — surveyed agricultural land (using the measurement system of the Khurasani gaz, a standardised unit of land measurement) and introduced a fixed land tax of 50% of produce (kharaj — the highest rate in the Sultanate period). Tax was assessed on measured land (zabt), not on crop shares — the beginning of the zabti system that Akbar later perfected. <strong>Military reforms</strong> — introduced the daag (branding of horses) and chehra (descriptive roll of soldiers) system to prevent corruption in the army (soldiers were paid in cash directly — 234 tankas per year for a cavalryman). He kept a large standing army (only a 300,000-strong cavalry according to Amir Khusrau — though this may be exaggerated). He built the <strong>Alai Darwaza</strong> (the southern gateway to the Quwwat-ul-Islam mosque, 1311) — the first structure in India to use true Islamic arches and domes (the gateway is made of red sandstone with white marble inlay, a masterpiece of Islamic architecture). The Mongol threat was neutralised by defeating multiple invasions (1299, 1303, 1306, 1308) led by the Chagatai Mongols (the army under Zafar Khan repelled the Mongols near Delhi; after Alauddin's initial defeats, he adopted a scorched-earth policy in Punjab to deny Mongols resources).</p>

<h3>Tughlaq Dynasty (1320-1414)</h3>

<p><strong>Ghiyasuddin Tughlaq</strong> (1320-1325) — founded the Tughlaq dynasty. He built the <strong>Tughlaqabad Fort</strong> in Delhi (a massive, sloping stone fort with a 13-gate entry). He died when a wooden pavilion collapsed on him (or was assassinated by his son Muhammad in a palace conspiracy). <strong>Muhammad bin Tughlaq</strong> (1325-1351) — the most contradictory and controversial ruler. He was highly intelligent, a great scholar (knew logic, philosophy, astronomy, Persian, Arabic, Sanskrit), a calligrapher, and a poet. But his policies were disastrous: <strong>Transfer of capital</strong> (1327) — moved the capital from Delhi to Devagiri (renamed Daulatabad, Maharashtra) — an 1100 km forced march of the entire population, including women, children, and the elderly, through difficult terrain. Many died on the way. The capital was moved back to Delhi two years later because Daulatabad lacked water and was too far from the northern frontier to defend against Mongols. <strong>Token currency</strong> (1329) — introduced copper and brass coins (tankas) with the value of silver tankas, backed by the treasury. But the treasury did not control their minting — people counterfeited massive quantities of tokens from their homes, destroying the value of the currency. Trade collapsed. The experiment was abandoned, and Muhammad bin Tughlaq redeemed all tokens for silver (at enormous cost to the treasury). <strong>Taxation in the Doab</strong> — increased the land tax in the Ganga-Yamuna Doab from the standard 10-15% to 50-60% during a severe famine. The peasants rebelled; many died. <strong>Khurasan expedition</strong> — planned a massive campaign to conquer Khurasan, Afghanistan, and Iraq, for which he raised a huge army (costly, but the expedition was abandoned). <strong>Qarachil expedition</strong> — sent an army to the Kumaon hills (in the Himalayas) to conquer the Chinese border region — the army was destroyed by the climate and terrain, losing 100,000 soldiers. The kingdom rebelled everywhere: Bengal declared independence (1336), the Deccan (1347 — the Bahmani Sultanate founded by Alauddin Bahman Shah, a revolt by the Deccani amirs), South India (the Vijayanagara Empire founded by Harihara and Bukka, also 1336). When Muhammad bin Tughlaq died in 1351 (on campaign in Sindh), the Sultanate had lost most of its territories.</p>

<p><strong>Firuz Shah Tughlaq</strong> (1351-1388) — restored stability by reversing most of Muhammad bin Tughlaq's policies: reduced taxes, restored the iqta system, patronised the Ulama (Islamic scholars — he was deeply orthodox and persecuted Shias and non-Muslims, imposing jizya strictly). His reign was peaceful but the Sultanate's decline continued. He built extensively: the <strong>Firuz Shah Kotla</strong> fort in Delhi, the <strong>Ashoka Pillar</strong> (brought from Topra, Haryana, and erected at his capital), the <strong>Hauz Khas</strong> water tank, and the town of <strong>Jaunpur</strong> (named after his cousin? Actually after his patron, the Sufi saint Shaikh Sharfuddin of Kalyar? Or named after Muhammad bin Tughlaq's cousin? It was modelled on Cairo?). He established hospitals (Dar-ul-Shafa), public works (canals, wells, sarais), and a marriage fund for poor girls. The <strong>Timurid invasion</strong> (1398) by the Central Asian conqueror <strong>Timur (Tamerlane)</strong> — sacked Delhi, massacred 100,000 Hindu prisoners before the battle, destroyed the city, and emptied the treasury. The Sultanate never recovered from Timur's devastation.</p>

<h3>Sayyid and Lodi Dynasties (1414-1526)</h3>

<p><strong>Sayyid Dynasty</strong> (1414-1451) — four rulers who claimed descent from the Prophet Muhammad (the Prophet's lineage: sayyids). They were puppets of the powerful Afghan nobles and had no real authority beyond Delhi. <strong>Khizr Khan</strong> (1414-1421) founded the dynasty as a Timurid vassal. <strong>Lodi Dynasty</strong> (1451-1526) — the first Afghan dynasty of the Delhi Sultanate. <strong>Bahlul Lodi</strong> (1451-1489) was a capable ruler who expanded the kingdom into Gwalior, Jaunpur, and Bihar. <strong>Sikandar Lodi</strong> (1489-1517) was the greatest Lodi ruler — he founded the city of Agra (1504), shifted the capital from Delhi to Agra (to control the rebellious Doab and Rajputana), patronised learning (he commissioned the first medical work in Persian, and his court poet Mian Bheekh wrote...), and maintained a strong administration. He tried to impose strict Sunni orthodoxy (re-imposed jizya, destroyed some Hindu temples). <strong>Ibrahim Lodi</strong> (1517-1526) was the last Lodi ruler — his policies alienated the Afghan nobility (his general Daulat Khan Lodi invited Babur to invade India). He was defeated and killed by Babur at the <strong>First Battle of Panipat</strong> (21 April 1526), ending the Delhi Sultanate and beginning the Mughal Empire. The battle was a victory of Babur's superior tactics (tulughma — the flanking technique — and gunpowder/cannons — the first use of gunpowder weapons on the Indian subcontinent in a major battle) over Ibrahim Lodi's larger but unwieldy army.</p>

<div class="diagram-box"><pre>
  DELHI SULTANATE DYNASTIES
  
  MAMLUK (1206-1290)
    Qutb-ud-din Aibak → Iltutmish → Razia (1236-40) → Balban (1266-87)
    
  KHALJI (1290-1320)
    Alauddin Khalji (1296-1316) — Market reforms, Deccan conquests
    
  TUGHLAQ (1320-1414)
    Ghiyasuddin → Muhammad bin Tughlaq → Firuz Shah
    
  SAYYID (1414-1451)
  LODI (1451-1526)
    Bahlul → Sikandar → Ibrahim (killed at Panipat, 1526)
</pre></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 11 written."
