const fs = require('fs');
const outPath = 'C:\\Users\\Renjith\\AppData\\Local\\Temp\\opencode\\geo_sections_6_10.html';
let c = fs.readFileSync(outPath, 'utf8');

// ==================== SECTION 10 ====================
c += `<!-- ===================== SECTION 10: ECONOMIC GEOGRAPHY ===================== -->\n`;
c += `<h2 id="economic-geography">10. Economic Geography</h2>\n\n`;

c += `<h3>GDP and Regional Disparities</h3>\n\n`;
c += `<p>India's economic geography is characterised by <span class="highlight">deep regional disparities</span> in income, industrialisation, and human development. The Gross State Domestic Product (GSDP) is heavily skewed towards the western and southern states, while the eastern and northern states lag behind. The <span class="highlight">top GSDP states</span> (nominal GSDP, 2023-24) are <strong>Maharashtra</strong> ($450 billion, the largest, contributing 14% of India's GDP, with Mumbai as the financial capital), <strong>Tamil Nadu</strong> ($320 billion, the 2nd largest, the manufacturing and auto hub), <strong>Karnataka</strong> ($290 billion, the 3rd largest, the IT and pharma hub), <strong>Gujarat</strong> ($280 billion, the 4th largest, the manufacturing and petrochemicals hub), <strong>Uttar Pradesh</strong> ($260 billion, the 5th largest, the largest by population but only 5th by GSDP, with a per capita income of $1,300 &mdash; half the national average), and <strong>Delhi</strong> ($130 billion, the highest per capita income at $6,500). The <span class="highlight">bottom GSDP states</span> are <strong>Bihar</strong> ($95 billion, per capita income $800 &mdash; the lowest in India), <strong>Jharkhand</strong> ($70 billion), <strong>Chhattisgarh</strong> ($60 billion), <strong>Uttarakhand</strong> ($45 billion), and <strong>Manipur</strong> ($6 billion). The regional inequality is stark: the per capita income of Delhi ($6,500) is <strong>8 times</strong> that of Bihar ($800), and the difference has been widening (in 1990, the ratio was 4:1). The 'Southern and Western' states (Maharashtra, Tamil Nadu, Karnataka, Gujarat, Kerala, Telangana) have per capita incomes 2-3x the national average, while the 'Eastern and Northern' states (Bihar, UP, Jharkhand, Odisha, Assam, Rajasthan) are below the national average. The 'coastal vs inland' disparity is also significant: the coastal states (Gujarat, Maharashtra, Karnataka, Kerala, Tamil Nadu, Andhra Pradesh, Odisha, West Bengal) account for 60% of India's GDP from 20% of the land area, reflecting the locational advantage of maritime trade and FDI concentration in coastal regions.</p>\n\n`;

c += `<p>The regional disparities are a function of historical factors (the colonial pattern of industrialisation favouring the port cities of Mumbai, Chennai, and Kolkata), geographical factors (the mineral-rich Chhota Nagpur Plateau and the fertile Indo-Gangetic plain vs. the arid and mountainous regions), policy factors (the 'Green Revolution' benefitting Punjab, Haryana, and UP disproportionately), and the post-1991 liberalisation (which favoured states with better infrastructure, governance, and FDI attractiveness &mdash; Maharashtra, Karnataka, Tamil Nadu, Gujarat &mdash; over the BIMAROU &mdash; Bihar, Madhya Pradesh, Rajasthan, Odisha, Uttar Pradesh &mdash; states). The <strong>NITI Aayog's 'Aspirational Districts' Programme</strong> (2018, 112 districts across India) is the flagship policy response, focusing on the districts with the lowest development indicators (the 'lagging districts'). The 'Special Category Status' (for 11 states &mdash; Arunachal, Assam, Himachal, J&K, Manipur, Meghalaya, Mizoram, Nagaland, Sikkim, Tripura, Uttarakhand &mdash; which receive 90% grant component in central funding instead of 60% for general states) and the 'Special Development Packages' for the North East (the 'North East Special Infrastructure Scheme', NESIS, Rs 14,000 crore, and the 'Act East Policy') are other instruments to address regional disparities.</p>\n\n`;

c += `<h3>Planning in India</h3>\n\n`;
c += `<p>India's economic planning, since Independence, has shaped the geographical pattern of development. The <strong>Five-Year Plans</strong> (1951 to 2017, from the 1st Plan 1951-56 to the 12th Plan 2012-17) were the instrument of centralised economic planning, modelled on the Soviet system. The Planning Commission (established 1950, with the Prime Minister as Chairperson) formulated the plans, allocated resources to states, and monitored implementation. The first three plans (1951-65) focused on heavy industry and import-substitution (the 'Mahalanobis model', named after Prof P.C. Mahalanobis of the Indian Statistical Institute, who designed the 2nd Plan), leading to the establishment of the 'steel towns' (Bhilai, Rourkela, Durgapur, Bokaro), the 'industrial townships' (Jamshedpur, Ranchi, Sindri, Chittaranjan), and the 'river valley projects' (Bhakra Nangal, Hirakud, Damodar Valley Corporation). The Green Revolution (the 3rd and 4th Plans) concentrated agricultural investment in the 'wheat-belt' of Punjab, Haryana, and Western UP (the 'new agricultural strategy' of high-yielding seed varieties, fertiliser subsidies, and assured irrigation). The 5th Plan (1974-79) introduced the 'Garibi Hatao' (Poverty Alleviation) approach, the 6th Plan (1980-85) the 'Minimum Needs Programme', the 7th Plan (1985-90) the 'Food, Work, and Productivity' focus, and the 8th Plan (1992-97) the liberalisation of the economy (post-1991 reforms), moving away from central planning towards indicative planning.</p>\n\n`;

c += `<p>In <strong>2015</strong>, the Planning Commission was replaced by the <strong>NITI Aayog</strong> (National Institution for Transforming India), a policy think tank (not a resource-allocating body, as the Planning Commission was). The NITI Aayog's mandate is to: (a) replace the 5-year plan with a <strong>three-tier planning framework</strong> &mdash; a 3-year 'Action Plan', a 7-year 'Strategy', and a 15-year 'Vision' (the 'Vision 2030' &mdash; the 'New India 2022' &mdash; the 'Sustainable Development Goals/SDG' integration), (b) foster cooperative federalism (the 'Governing Council' of all Chief Ministers, meeting annually, is the highest decision-making body of the NITI Aayog), (c) design the 'Development Support Services to States' (the 'State Finance Commissions' and the 'District Planning Committees' for decentralised planning), and (d) create 'Sectoral Strategies' (the 'Technology and Innovation Hub', the 'Waste-to-Wealth Mission', the 'National Medical and Wellness Centres'). The NITI Aayog's flagship initiatives include the 'Aspirational Districts Programme' (112 districts), the 'Aspirational Blocks Programme' (500 blocks), the 'National Data and Analytics Platform' (NDAP), the 'SDG India Index & Dashboard' (tracking the SDG targets by state), and the 'India Innovation Index' (ranking states on innovation capacity).</p>\n\n`;

c += `<h3>Special Economic Zones (SEZs)</h3>\n\n`;
c += `<p>The <strong>SEZ Act 2005</strong> (the 'Special Economic Zones Act', passed in 2005, effective 2006) replaced the earlier Export Processing Zones (EPZs) regime with a comprehensive legal framework for SEZs. SEZs are geographically delimited areas with a special economic regulatory regime (tax exemptions, single-window clearance, labour law flexibilities, and infrastructure &mdash; the '25% land for processing area' rule) designed to promote exports, attract FDI, and create employment. As of 2024, there are <strong>379 SEZs</strong> (including 7 multi-product SEZs), with the <strong>largest operational SEZs</strong> being <strong>Reliance Haryana SEZ</strong> (1,500 hectares, the largest by area, covering the Delhi-NCR region for IT/ITES, biotech, and services), <strong>Mundra SEZ</strong> (Gujarat, the largest by output, operated by Adani Ports &mdash; a multi-product SEZ with a port, a refinery, a power plant, and manufacturing units), and <strong>Kandla SEZ</strong> (Gujarat, the first SEZ in India, established in 1965 as an EPZ, covering 1,000 hectares for textiles, chemicals, and engineering). The SEZ policy has been controversial: the 'land acquisition' issues (the protests at Nandigram, West Bengal, 2007, where the proposed SEZ of the Salim Group of Indonesia triggered large-scale protests and led to the cancellation of the project), the 'revenue loss' (the tax exemptions to SEZs cost the exchequer Rs 50,000 crore in foregone revenue), and the 'enclave effect' (the SEZs operate as 'islands of prosperity' disconnected from the surrounding regional economy). The SEZ policy was diluted in 2019 (the Minimum Alternate Tax/MAT of 18.5% was imposed on SEZ developers, the 'sunset clause' of 10 years for tax benefits expired, and the 'service export' exemption was withdrawn) &mdash; leading to a sharp decline in new SEZ approvals.</p>\n\n`;

c += `<h3>Industrial Corridors</h3>\n\n`;
c += `<p>The Industrial Corridor Development Programme is the <span class="highlight">largest spatial planning initiative in India</span>, designed to create 'smart industrial cities' along high-capacity transport corridors, linking the manufacturing hubs with ports, railways, and highways. The programme is implemented by the <strong>National Industrial Corridor Development Corporation (NICDC)</strong> and covers 11 industrial corridors:</p>\n\n`;

c += `<ul>\n`;
c += `<li><strong>Delhi-Mumbai Industrial Corridor (DMIC)</strong> &mdash; The <span class="highlight">flagship and the largest industrial corridor project</span> (1,500 km, covering 7 states: Delhi, Haryana, Rajasthan, Gujarat, Maharashtra, MP, UP), with the cooperation of <strong>Japan</strong> (the Japan International Cooperation Agency/JICA provided the master plan and funding). The DMIC runs parallel to the Western DFC and aims to develop 24 industrial nodes (the 'Smart Industrial Cities'), of which 7 are under development: <strong>Dholera</strong> (Gujarat, the first, a 'greenfield smart city', 920 sq km &mdash; the largest greenfield city in the world), <strong>Shendra-Bidkin</strong> (Maharashtra), <strong>Vikram Udyogpuri</strong> (MP, Ujjain), <strong>Bhiwadi-Rajgarh</strong> (Rajasthan), <strong>Neemrana</strong> (Rajasthan), <strong>Dadri-Noida-Ghaziabad</strong> (UP), and <strong>Greater Noida</strong> (UP). The DMIC is the largest FDI destination in India (attracting $60 billion in investment over the last 5 years) and is projected to create 25 million jobs by 2030.</li>\n`;
c += `<li><strong>Chennai-Bengaluru Industrial Corridor (CBIC)</strong> &mdash; The 560 km corridor linking Chennai (the 'Detroit of India') with Bengaluru (the 'Silicon Valley'). The key nodes are the <strong>Tumakuru Industrial Node</strong> (Karnataka, 5,000 acres, the first industrial park in the CBIC, focusing on aerospace and green technology) and the <strong>Krishnapatnam Industrial Node</strong> (Andhra Pradesh, a port-based industrial city). The CBIC is under implementation with the cooperation of the <strong>UK</strong> (the 'UK-India Industrial Corridor Partnership').</li>\n`;
c += `<li><strong>Bengaluru-Mumbai Economic Corridor (BMEC)</strong> &mdash; The 700 km corridor linking the two major economic centres, with the development of the <strong>Dharwad Industrial Node</strong> (Karnataka) and the <strong>Khed-Shirwal Industrial Node</strong> (Maharashtra).</li>\n`;
c += `<li><strong>Amritsar-Kolkata Industrial Corridor (AKIC)</strong> &mdash; The longest corridor (2,000 km), covering the Indo-Gangetic plain from Punjab to West Bengal, with 20+ nodes at Rajpura (Punjab), Alwar (Rajasthan), Agra (UP), Aligarh (UP), Kanpur (UP), Allahabad (UP), and Raghunathpur (West Bengal).</li>\n`;
c += `<li><strong>Vizag-Chennai Industrial Corridor (VCIC)</strong> &mdash; The 800 km corridor along the east coast, with the <strong>Kakinada SEZ</strong> (Andhra Pradesh), the <strong>Visakhapatnam Industrial Node</strong>, and the <strong>Srikalahasti Industrial Node</strong>.</li>\n`;
c += `<li><strong>Other corridors</strong> &mdash; The <strong>East Coast Economic Corridor</strong> (Kolkata to Tuticorin, with the assistance of the Asian Development Bank/ADB), the <strong>Hyderabad-Bengaluru Industrial Corridor</strong>, the <strong>Delhi-Nagpur Industrial Corridor</strong>, and the <strong>Extension of the DMIC to Indore</strong> (the 'DMIC-2' &mdash; the 400 km spur from Ahmedabad to Indore).</li>\n`;
c += `</ul>\n\n`;

c += `<h3>International Trade</h3>\n\n`;
c += `<p>India's international trade (merchandise trade) in 2023-24 was about <strong>$1,000 billion</strong> (exports $420 billion, imports $580 billion, trade deficit of $160 billion). India's share of global merchandise trade is about 2% (the 15th largest exporter and the 8th largest importer in the world). The <span class="highlight">top export items</span> are <strong>engineering goods</strong> (the largest category, $100 billion, including machinery, automobiles, auto components, steel, and aluminium), <strong>petroleum products</strong> ($80 billion, the surplus refined products from India's refineries, exported to Europe and Asia), <strong>chemicals and pharmaceuticals</strong> ($50 billion, including drugs, dyes, agrochemicals, and organic chemicals), <strong>gems and jewellery</strong> ($35 billion, the largest in the world by volume, from the Surat diamond cutting and polishing cluster), <strong>textiles and garments</strong> ($35 billion, including cotton textiles, readymade garments, carpets, and silk), and <strong>agricultural products</strong> ($25 billion, including rice (the largest exporter of basmati rice in the world), marine products, meat, tea, coffee, spices, and sugar). The <span class="highlight">top import items</span> are <strong>petroleum crude</strong> ($150 billion, the largest, 85% of domestic consumption is imported), <strong>gold</strong> ($45 billion, the 3rd largest consumer of gold in the world, mainly for jewellery and investment), <strong>electronics</strong> ($35 billion, including mobile phones, laptop/PC components, integrated circuits, and telecom equipment), <strong>machinery and mechanical appliances</strong> ($30 billion), <strong>chemicals and fertilisers</strong> ($20 billion, India is the 2nd largest consumer of fertilisers in the world, importing 30% of its urea, 60% of its DAP, and 90% of its potash), and <strong>coal</strong> ($25 billion, imported thermal coal for power plants and coking coal for steel plants).</p>\n\n`;

c += `<p><strong>Trade Partners</strong> &mdash; The <span class="highlight">top trade partners</span> (by total trade volume, 2023-24) are <strong>the United States</strong> ($120 billion, the largest, the biggest export destination for India, with a trade surplus of $40 billion), <strong>the United Arab Emirates</strong> ($80 billion, the 2nd largest, a major energy supplier and the gateway to the Gulf market, with a comprehensive bilateral trade agreement &mdash; the India-UAE CEPA &mdash; signed in 2022, the first comprehensive FTA of the Modi era), <strong>China</strong> ($110 billion, the 3rd largest but the <strong>largest source of India's trade deficit</strong>, at $65 billion), <strong>Saudi Arabia</strong> ($45 billion, the largest supplier of crude oil to India), <strong>Iraq</strong> ($35 billion, the 2nd largest oil supplier), <strong>Indonesia</strong> ($30 billion, the largest supplier of coal to India, and a source of palm oil and crude), <strong>Russia</strong> ($50 billion, the trade volume surged after the Ukraine conflict &mdash; India imports discounted Russian crude, coal, and fertilisers, the trade deficit with Russia is $40 billion), and the <strong>European Union</strong> ($120 billion, the largest trading bloc partner, with 27 countries, but India is yet to conclude the long-pending India-EU FTA, negotiations for which restarted in 2022 after a 9-year hiatus).</p>\n\n`;

c += `<p><strong>Trade Policy and FTAs</strong> &mdash; India's trade policy is marked by a shift from 'non-aligned protectionism' (the 'import-substitution' era, 1950-1991, when tariffs averaged 80% and the 'license raj' restricted trade) to 'cautious globalisation' (the post-1991 era, with tariffs reduced to the 10-15% range, but with selective protection through the 'tariff walls' and the 'non-tariff barriers' &mdash; the 'quality control orders', the 'BIS certification'). India has signed <strong>Free Trade Agreements (FTAs)</strong> with several countries and blocs: <strong>India-ASEAN FTA</strong> (2010, with the 10 ASEAN countries, the largest by membership), <strong>India-Japan CEPA</strong> (2011), <strong>India-Korea CEPA</strong> (2010), <strong>India-Malaysia CECA</strong> (2011), <strong>India-Singapore CECA</strong> (2005), <strong>India-UAE CEPA</strong> (2022, the new model FTA, with strong chapters on digital trade, intellectual property, and sustainability), <strong>India-Australia ECTA</strong> (2022, the 'Economic Cooperation and Trade Agreement' &mdash; the first FTA with a developed country in a decade, covering goods, services, and investment), and the <strong>India-EFTA TEPA</strong> (2024, the Trade and Economic Partnership Agreement with the 4 EFTA countries &mdash; Switzerland, Norway, Iceland, Liechtenstein, a $100 billion investment commitment over 15 years). India is currently negotiating FTAs with the <strong>European Union</strong> (the 'India-EU FTA', the most consequential but the most difficult, given the EU's demand for market access in dairy, wine, spirits, and the data protection standards), the <strong>United Kingdom</strong> (the 'India-UK FTA', with the target of $100 billion bilateral trade by 2030, negotiations ongoing for the 'early harvest' deal), and <strong>Canada</strong> (the 'India-Canada FTA', paused since 2023 due to political tensions). The <strong>World Trade Organization (WTO)</strong> rules (the most-favoured nation principle, the 'national treatment', the 'trade-related intellectual property rights/TRIPS', and the 'dispute settlement mechanism') provide the multilateral framework for India's trade policy, though India has been a vocal critic of the 'Doha Round' stasis and the 'non-transparent' 'plurilateral' negotiations (the 'Trade Facilitation in Services Agreement/TISA', the 'Information Technology Agreement/ITA-2').</p>\n\n`;

c += `<h3>Foreign Direct Investment (FDI)</h3>\n\n`;
c += `<p>Foreign Direct Investment (FDI) is a <span class="highlight">critical driver of India's economic growth</span>, bringing capital, technology, and managerial expertise. India received <strong>$70 billion in FDI</strong> in 2023-24 (the 5th largest FDI recipient in the world, after the US, China, Singapore, and the UK, according to UNCTAD's World Investment Report). The cumulative FDI inflows from 2000 to 2024 amount to <strong>$1,000 billion</strong>. The <span class="highlight">top FDI sectors</span> are <strong>services (financial, banking, insurance, outsourcing)</strong> ($100 billion, the largest, driven by the IT-BPO and the fintech sectors), <strong>computer software and hardware</strong> ($85 billion, the IT sector), <strong>construction (including infrastructure)</strong> ($50 billion, with the 'National Infrastructure Pipeline' and the 'Gati Shakti' attracting investment), <strong>telecom</strong> ($40 billion, driven by the Jio and Airtel capital expenditure for 4G/5G roll-out), <strong>trading</strong> ($35 billion, the wholesale and e-commerce sectors), and <strong>power</strong> ($30 billion, the renewable energy sector, particularly solar and wind). The <span class="highlight">top investor countries</span> are <strong>Mauritius</strong> (the largest, $150 billion, accounting for 25% of FDI stock, though much of this is 'round-tripping' &mdash; Indian companies routing investment through Mauritius to benefit from the Double Taxation Avoidance Agreement &mdash; the DTAA, and the capital gains tax exemptions, which were tightened by the 'Mauritius Protocol' of 2016 and the 'India-Mauritius DTAA amendment' of 2019), <strong>Singapore</strong> ($120 billion, the 2nd largest, now the primary route for FDI from Southeast Asia and China), <strong>Japan</strong> ($35 billion, the 3rd largest, with the Japanese companies dominating the auto sector &mdash; Suzuki, Toyota, Honda, Nissan), <strong>the US</strong> ($30 billion, the 4th largest, concentrated in IT, services, and the pharmaceutical R&D), <strong>the UK</strong> ($28 billion, the 5th largest, in energy, financial services, and the consumer goods), and the <strong>Netherlands</strong> ($25 billion, the 6th largest, driven by the investment of Shell and Unilever).</p>\n\n`;

c += `<p><strong>FDI Policy</strong> &mdash; India's FDI policy is governed by the <strong>Consolidated FDI Policy Circular</strong> (updated annually) and the <strong>Foreign Exchange Management Act (FEMA) 1999</strong>. The FDI regime is a <strong>hybrid system</strong>: most sectors are under the <strong>automatic route</strong> (100% FDI allowed without prior government approval &mdash; covering IT, telecom (100%), insurance (74% since 2021, with 100% for intermediaries), defence (74% automatic, up to 100% with government approval), banking (74% automatic), e-commerce (100% in the marketplace model, but 0% in the inventory-based model), aviation (100% for airports, 49% automatic for airlines), and the pharma (100% automatic for greenfield, 74% automatic for brownfield). The <strong>approval route</strong> (where prior government approval through the Foreign Investment Facilitation Portal/FIFP is required) applies to sectors such as the 'multi-brand retail' (51% with state government approval, but no state has permitted it yet), the 'media and broadcasting' (26-49% depending on the segment, with the Ministry of Information and Broadcasting approval), the 'mining and minerals' (100% automatic for most, but the 'strategic minerals' like lithium, cobalt, and the 'atomic minerals' require approval), and the 'private security agencies' (49% automatic, beyond that approval). The <strong>Production Linked Incentive (PLI) Scheme</strong> (2020, Rs 1.97 lakh crore for 14 sectors &mdash; mobile phones, electronics, pharma, automobiles, textiles, steel, solar PV modules, medical devices, etc.) is the most significant recent policy to attract FDI in manufacturing, offering cash incentives of 4-6% of incremental sales for 4-5 years, conditional on achieving the 'value addition' and 'employment' thresholds. The <strong>Make in India</strong> (2014), the <strong>Digital India</strong> (2015), and the <strong>Startup India</strong> (2016) are the three national campaigns that provide the policy and institutional framework for FDI attraction.</p>\n\n`;

fs.writeFileSync(outPath, c, 'utf8');
console.log('Section 10 complete. Total: ' + c.length + ' chars');
