$outFile = "C:\Users\Renjith\Desktop\icode (2)\pagepulse\new_sections.txt"

$html = @'
<!-- ===================== SECTION 1: PREHISTORIC INDIA ===================== -->
<h2 id="prehistoric">1. Prehistoric India</h2>

<p>The Indian subcontinent possesses one of the deepest and richest prehistoric records in the Old World, spanning nearly two million years. The study of India's Stone Age is crucial for UPSC because it establishes the foundational human occupation of the subcontinent and reveals early technological, cultural, and cognitive developments. The prehistoric period is broadly divided into the <span class="highlight">Palaeolithic</span> (Old Stone Age), <span class="highlight">Mesolithic</span> (Middle Stone Age), and <span class="highlight">Neolithic</span> (New Stone Age), followed by the <span class="highlight">Chalcolithic</span> (Copper-Stone Age) cultures that bridged prehistory and the Indus Valley Civilization. The pioneering work of Robert Bruce Foote (who discovered the first Palaeolithic tool at Pallavaram in 1863) and V.S. Wakankar (who discovered Bhimbetka in 1957) laid the foundation for Indian prehistoric studies.</p>

<h3>Palaeolithic Period (c. 2 mya - 10,000 BCE)</h3>

<p>The Palaeolithic is subdivided into Lower, Middle, and Upper phases based on tool technology, climate, and hominin species. <strong>Lower Palaeolithic</strong> (c. 2 mya - 100,000 BCE) is characterised by <span class="highlight">Acheulian handaxes</span>, cleavers, and choppers made on quartzite - hence the terms 'Madrasian' (for the handaxe culture) and 'Soanian' (for the pebble-tool culture) traditions. The earliest securely dated site is <span class="highlight">Attirampakkam</span> in Tamil Nadu, where stone tools dated to <strong>1.5 million years ago</strong> were found by Shanti Pappu and her team (published in <em>Nature</em>, 2011), pushing back Indian Palaeolithic occupation significantly and challenging the Out-of-Africa model by suggesting multiple dispersals of early hominins. Key Lower Palaeolithic sites include <strong>Bhimbetka</strong> (Madhya Pradesh) - a UNESCO World Heritage site with over 700 rock shelters showing continuous habitation from Lower Palaeolithic to Medieval times; <strong>Hunsgi-Baichbal Valleys</strong> (Karnataka), a dense cluster of Acheulian sites excavated by K. Paddayya revealing a <span class="highlight">living floor</span> with animal bones and stone tools in primary context; the <strong>Soan Valley</strong> (Pakistan, Punjab) - the type site of the Soanian industry, a non-Acheulian pebble-tool tradition using quartzite cobbles; <strong>Didwana</strong> (Rajasthan); and the <strong>Narmada Valley</strong> (Madhya Pradesh), where the only hominin fossil in India - the <em>Homo erectus</em> <strong>Narmada Man</strong> - was discovered in 1982 by Arun Sonakia. Evidence of fire has been found at <span class="highlight">Singi Talav</span> (Rajasthan), suggesting early hominin control of fire by at least 300,000 years ago.</p>

<p><strong>Middle Palaeolithic</strong> (c. 100,000 - 40,000 BCE) is marked by the shift from handaxes to <span class="highlight">flake-based tools</span> made using the Levallois technique - scrapers, points, and borers that were smaller, lighter, and more efficient than the heavy handaxes. Key sites include <strong>Nevasa</strong> (Maharashtra), <strong>Bhimbetka</strong> (upper shelters), <strong>Samnapur</strong> (Madhya Pradesh), the <strong>Luni Valley</strong> (Rajasthan), and the <strong>Belan Valley</strong> (Uttar Pradesh). Middle Palaeolithic tools indicate greater efficiency and hafting - attaching stone points to wooden shafts using resin or sinew. The transition to the Middle Palaeolithic in India shows continuity with the Lower Palaeolithic rather than replacement, suggesting a gradual evolution of local hominin populations rather than a new wave of migration. The <strong>Nevasian</strong> industry was first identified at Nevasa by H.D. Sankalia.</p>

<p><strong>Upper Palaeolithic</strong> (c. 40,000 - 10,000 BCE) is associated with <span class="highlight">modern humans (<em>Homo sapiens</em>)</span> and characterised by blade tools, burins (for engraving), and bone tools. Key sites: <strong>Bhimbetka</strong> (rich rock art - depictions of animals including bison, tigers, rhinoceroses, elephants, and deer, as well as hunting scenes, dancing human figures, and abstract patterns in white, red, and green mineral pigments across multiple shelters); <strong>Patne</strong> (Maharashtra) - ostrich eggshell beads and an engraved piece that represents the earliest art mobilier (portable art) in India; <strong>Kurnool Caves</strong> (Andhra Pradesh); and <strong>Batadomba Lena</strong> (Sri Lanka) showing early modern human presence c. 36,000 BCE. The <span class="highlight">Bhimbetka rock art</span> is among the oldest in the world and provides crucial insight into Upper Palaeolithic society - hunting scenes, communal dances, and what appear to be religious or shamanistic figures. The use of geometric patterns and cross-hatching suggests symbolic communication and possibly the earliest forms of graphic language.</p>

<h3>Mesolithic Period (c. 10,000 - 6,000 BCE)</h3>

<p>The Mesolithic marks a transition from hunting-gathering to food production, with a marked increase in <span class="highlight">microliths</span> - tiny geometric stone tools (crescents, triangles, trapezes, lunates, backed blades) used as arrowheads, spear barbs, and composite tools hafted into wood or bone using resin. The warming of the climate after the last Ice Age (the Pleistocene-Holocene transition, c. 12,000 BP) led to changes in flora (expansion of forests, grasslands), fauna (extinction of megafauna, adaptation of smaller species), and human settlement patterns (more permanent settlements near water sources). This period saw the first attempts at animal domestication and the beginnings of a more settled lifestyle.</p>

<p>Key Mesolithic sites include <strong>Bagor</strong> (Rajasthan) - the largest Mesolithic site in India (excavated by V.N. Misra), with five distinct cultural phases spanning Mesolithic to early Historic levels and early evidence of <strong>animal domestication</strong> (sheep, goat); <strong>Langhnaj</strong> (Gujarat) - microliths, burial practices with grave goods (shell bangles, beads of carnelian and agate, bone ornaments), and faunal remains indicating hunting of wild cattle, deer, and pig; <strong>Bhimbetka</strong> (continuation from Palaeolithic with abundant microlith assemblages showing the long-term occupation of this site); <strong>Sarai Nahar Rai</strong> and <strong>Mahadaha</strong> (Uttar Pradesh) - large Mesolithic settlements with burials, indicating community living and complex social organisation. Sarai Nahar Rai provides the <strong>earliest evidence of a massacre</strong> in Indian prehistory (a burial with 10 skeletons showing signs of violent death). <strong>Damdama</strong> (Uttar Pradesh) has yielded the largest number of human skeletons (over 100) from any Mesolithic site in India, with evidence of dental modification and bone pathologies. Rock art continued to flourish during the Mesolithic, particularly at Bhimbetka, with intricate scenes of honey collection (the earliest evidence anywhere in the world), group hunting with bows and arrows, and ritual/ceremonial activities.</p>

<div class="tip-box"><div class="tip-title">Key Fact for UPSC</div><div class="tip-text">Mesolithic sites in the Gangetic plains show evidence of the earliest rice cultivation at <strong>Lahuradewa</strong> (Uttar Pradesh), c. 7000 BCE, pushing back the antiquity of rice domestication in India significantly. The transition from hunting-gathering to agriculture was a gradual, regionally diverse process - not a sudden 'Neolithic Revolution' as once believed. The <strong>Bhimbetka</strong> rock shelter complex demonstrates the longest continuous human occupation in India, spanning from the Lower Palaeolithic to the Medieval period - a unique feature recognised by UNESCO world heritage status. The <strong>V.S. Wakankar</strong> discovery of Bhimbetka (1957) revolutionised Indian prehistory.</div></div>

<h3>Neolithic Period (c. 7000 - 2000 BCE)</h3>

<p>The Neolithic saw the full establishment of <span class="highlight">settled agriculture</span>, domestication of plants and animals, ground and polished stone tools, pottery-making, and permanent villages. The Indian Neolithic has distinct regional variants, each with unique characteristics determined by local geography, climate, and cultural traditions:</p>

<p><strong>1. Mehrgarh (Balochistan, Pakistan)</strong> - c. 7000-2000 BCE, the <span class="highlight">earliest Neolithic site in South Asia</span>. Excavated by Jean-Francois Jarrige (1974-1986), Mehrgarh provides a continuous sequence of 5000 years of occupation. Phase I (7000-5500 BCE) shows mud-brick houses (4-room rectangular structures), barley and wheat cultivation, domesticated goats, sheep, and cattle, and the earliest evidence of <strong>cotton cultivation</strong> (cotton fibres found preserved in a copper bead). Remarkably, <strong>dentistry</strong> was practised - drilled molars with concentric grooves (c. 6500 BCE) found in living patients, representing the earliest known dentistry in the world. Burials contained grave goods - baskets with bitumen coating, beads of turquoise and lapis lazuli, bone tools, and ornaments - indicating belief in an afterlife and long-distance trade. Phase II-III (5500-3500 BCE) shows sophisticated pottery (fine wheel-made ware, painted with geometric designs), terracotta figurines (seated female figurines with elaborate headdresses - the 'Mother Goddess' precursor), and evidence of long-distance trade in lapis lazuli (from Badakhshan, Afghanistan).</p>

<p><strong>2. Burzahom (Kashmir)</strong> - c. 3000-1500 BCE. Unique for its <span class="highlight">pit dwellings</span> - circular or rectangular pits dug 2-4 metres into the ground, with post-holes indicating a superstructure of wooden poles covered with mud and thatch for insulation against the cold Himalayan winter. Evidence of domesticated dog buried with its owner (the earliest known dog burial in India, c. 2300 BCE). Polished stone axes (including shouldered axes), bone tools (harpoons, needles, awls), and coarse grey pottery with mat impressions. The site reveals connections with Central Asia and northern China - both the pit-dwelling tradition and the burial practices (flexed burials covered with red ochre) show striking similarities with the Chinese Neolithic. The inhabitants practised both agriculture (wheat, barley, lentils, peas) and hunting (deer, wild goat, boar).</p>

<p><strong>3. Chirand (Bihar)</strong> - c. 2500-1500 BCE, on the Ghaghara River in the Gangetic plain. Extensive evidence of rice cultivation (domesticated Oryza sativa), cattle, sheep, goat, and pig domestication. Bone tools (arrowheads, fish hooks, harpoons), and elaborate pottery with geometric and floral designs painted in black and red. The site demonstrates the early importance of the Gangetic plains for rice agriculture, which later became the economic basis for the Mahajanapadas.</p>

<p><strong>4. Hallur (Karnataka) and Piklihal</strong> - Southern Neolithic (c. 3000-1000 BCE), characterised by hand-axe-like 'neoliths', <span class="highlight">ashmounds</span> (burnt cattle dung heaps that can be 5-10 metres high), and cattle-keeping as the dominant subsistence activity. The ashmounds remain an archaeological puzzle - some scholars (K. Paddayya) interpret them as seasonal cattle corrals that were ritually burned at the end of the grazing season, while others see them as permanent settlement features associated with ritual/ceremonial activities. Excavations at <strong>Budihal</strong> (Karnataka) have revealed a butchering floor with stone stools, choppers, and cut marks on bones, in association with an ashmound, suggesting communal feasting.</p>

<p><strong>5. Gufkral (Kashmir)</strong> - Another important Neolithic site with pit dwellings and surface dwellings, evidence of wheat, barley, and lentil cultivation, and domesticated sheep, goat, and cattle. The name means 'cave of the potter'.</p>

<p><strong>6. Brahmagiri (Karnataka)</strong> - A Southern Neolithic site excavated by Mortimer Wheeler, with evidence of cattle-keeping, polished stone axes (including the characteristic 'Brahmagiri type'), and a sequence from Neolithic to early historic periods, providing the first stratigraphic framework for South Indian archaeology.</p>

<h3>Chalcolithic Period (c. 3000 - 700 BCE)</h3>

<p>The Chalcolithic (Copper-Stone Age) represents the transition from stone to metal, with copper tools coexisting with stone. Chalcolithic cultures were regional, pre-urban or non-urban, and many were contemporaneous with or immediately preceded the Early Historic period. These cultures demonstrate the increasing complexity of society, with craft specialisation, inter-regional trade networks, and social stratification emerging.</p>

<p><strong>Major Chalcolithic Cultures of India:</strong></p>
<ul>
<li><strong>Ahar-Banas Culture</strong> (Rajasthan, c. 3000-1500 BCE): Known for <span class="highlight">black-and-red ware</span> (BRW) made with a unique double-firing technique, copper tools and objects, fortified settlements at Ahar, Balathal, and Gilund (with massive mud-brick fortifications 5m wide). Also called the 'Banas Culture'. Evidence of rice cultivation and a distinct painted pottery tradition with white designs on a red slip. At <strong>Gilund</strong>, a large complex of 54 rooms was uncovered, suggesting a centralised administrative or storage facility.</li>
<li><strong>Malwa Culture</strong> (Madhya Pradesh, c. 1900-1400 BCE): Type site <strong>Navdatoli</strong> on the Narmada River. Fine painted pottery - black designs on a red slip, with geometric (chevrons, triangles, wavy lines) and naturalistic (peacock, deer, tree) motifs. Wheat, barley, and lentil cultivation. Trade networks extending to the Deccan and Gujarat. Copper tools, beads of carnelian and jasper, and terracotta figurines.</li>
<li><strong>Jorwe Culture</strong> (Maharashtra, c. 1400-700 BCE): Type site <strong>Jorwe</strong> and <strong>Daimabad</strong> (where bronze chariots, elephants, and rhinoceroses were found - <span class="highlight">Daimabad bronzes</span>, c. 2000 BCE, created using the lost-wax casting technique). Painted pottery with geometric and floral designs in black on red. The site of <strong>Inamgaon</strong> has yielded the earliest evidence of a <strong>fortified settlement</strong> in the Deccan, with a mud-brick wall, a granary with storage pits, and a large house of the chief (with a raised platform). Burial practices include pot burials (urn burial of infants and children) and extended burials (adults) with grave goods. Three distinct phases of Jorwe culture have been identified at Inamgaon.</li>
<li><strong>Kayatha Culture</strong> (Madhya Pradesh, c. 2500-2000 BCE): Earliest Chalcolithic in the Malwa region. Distinctive painted pottery (buff-slipped ware with linear designs in brown/black). Copper tools and a developed stone blade industry. Evidence of mud fortification at Kayatha. Contemporary with the late Harappan period.</li>
<li><strong>Ochre Coloured Pottery (OCP) Culture</strong> (Ganga-Yamuna Doab, c. 2000-1500 BCE): Found at sites like <strong>Atranjikhera</strong>, <strong>Ambkheri</strong>, and <strong>Saipai</strong>. Pottery with an ochre-coloured wash (hence the name). Often associated with copper hoards - flat celts, harpoons, swords, anthropomorphic figures, and rings. The OCP culture represents the earliest known culture of the Ganga-Yamuna Doab and may be linked to the Late Harappan phase as Harappans migrated eastward.</li>
<li><strong>Painted Grey Ware (PGW) Culture</strong> (c. 1100-600 BCE): Associated with the later Vedic period and the Mahabharata-era sites. Found at <strong>Hastinapur</strong>, <strong>Mathura</strong>, <strong>Ahichchhatra</strong>, <strong>Kurukshetra</strong>, <strong>Kampilya</strong>, and <strong>Noh</strong>. Fine grey pottery painted with black geometric motifs (dots, dashes, concentric circles, wavy lines). Iron tools and weapons appear towards the end of the PGW period, signalling the transition to the Iron Age. The PGW culture is contemporary with the later Vedic period and represents the material culture of the Kuru-Panchala kingdom described in the Mahabharata. Rice, wheat, and barley cultivation; domesticated horse, cattle, sheep, goats; and evidence of horse riding.</li>
</ul>

<div class="table-wrap"><table>
<tr><th>Period</th><th>Time Range</th><th>Tool Types</th><th>Major Sites</th><th>Key Developments</th></tr>
<tr><td>Lower Palaeolithic</td><td>c. 2 mya - 100 kya</td><td>Handaxes, cleavers, choppers</td><td>Attirampakkam, Bhimbetka, Hunsgi, Soan Valley, Narmada Valley</td><td>First hominin occupation; Acheulian tradition; Narmada Man (Homo erectus)</td></tr>
<tr><td>Middle Palaeolithic</td><td>c. 100 - 40 kya</td><td>Flake tools, scrapers, points (Levallois)</td><td>Nevasa, Bhimbetka, Samnapur, Belan Valley, Luni Valley</td><td>Hafting; greater tool efficiency; Nevasian tradition</td></tr>
<tr><td>Upper Palaeolithic</td><td>c. 40 - 10 kya</td><td>Blade tools, burins, bone tools</td><td>Bhimbetka (rock art), Patne, Kurnool Caves</td><td>Homo sapiens; cave art; ostrich eggshell beads; symbolic behaviour</td></tr>
<tr><td>Mesolithic</td><td>c. 10 - 6 kya</td><td>Microliths (geometric composite)</td><td>Bagor, Langhnaj, Sarai Nahar Rai, Damdama, Adamgarh</td><td>Animal domestication; community burials; rice at Lahuradewa</td></tr>
<tr><td>Neolithic</td><td>c. 7000 - 2000 BCE</td><td>Ground/polished axes, pottery</td><td>Mehrgarh, Burzahom, Chirand, Hallur, Gufkral, Brahmagiri</td><td>Agriculture; cotton; dentistry; pit dwellings; ashmounds</td></tr>
<tr><td>Chalcolithic</td><td>c. 3000 - 700 BCE</td><td>Copper + stone tools, painted pottery</td><td>Navdatoli, Daimabad, Ahar, Kayatha, Atranjikhera, Hastinapur</td><td>BRW; copper hoards; Daimabad bronzes; PGW; fortified settlements</td></tr>
</table></div>

<div class="warn-box"><div class="warn-title">Historiographical Note</div><div class="warn-text">The three-age system (Stone-Bronze-Iron) was developed by Christian Jorgensen Thomsen (1836) for Danish museums. In India, Robert Bruce Foote (1863) discovered the first Palaeolithic tool at Pallavaram, Chennai. Modern research has problematised the rigid three-stage sequence - regional variations, overlapping technologies, and the gradual nature of transitions are now emphasised. The <strong>V.S. Wakankar</strong> discovery of Bhimbetka (1957) revolutionised Indian prehistory by revealing an unbroken sequence from Lower Palaeolithic to Medieval times. The transition from the Chalcolithic to the Iron Age in India was not uniform - iron appeared in the Gangetic plain by c. 1000 BCE (as evidenced at sites like Dadupur, Raja Nala Ka Tila, and Malhar) but was not used in South India until much later (c. 700-600 BCE).</div></div>

<div class="diagram-box"><pre>
  STONE AGE CHRONOLOGY OF INDIA

  2 mya ----- 100kya -- 40kya -- 10kya -- 6kya -- 2kya
   |            |        |        |       |       |
  LOWER       MIDDLE   UPPER    MESO    NEO    CHALCO
  Handaxes    Flakes   Blades   Micro   Ground  Copper
   |                                    |       |
  Attirampakkam  Nevasa  Patne   Bagor  Mehrgah Navdatoli
  +-- Bhimbetka continuous occupation --&gt;
</pre></div>

'@

$html | Add-Content -Path $outFile -Encoding UTF8
Write-Host "Section 1 written."
