// Kerala PSC LGS Bilingual Question Bank — 100 Questions
const LGS_SECTIONS = [
  {ml:"I. പൊതുവിജ്ഞാനം", en:"I. General Knowledge", bg:"#a855f7"},
  {ml:"II. ആനുകാലിക വിഷയങ്ങൾ", en:"II. Current Affairs", bg:"#60a5fa"},
  {ml:"III. സയൻസ്", en:"III. Science", bg:"#34d399"},
  {ml:"IV. പൊതുജനാരോഗ്യം", en:"IV. Public Health", bg:"#fb923c"},
  {ml:"V. ലഘുഗണിതവും മാനസികശേഷിയും", en:"V. Mental Ability & Numerical Skills", bg:"#ec4899"},
];
const LGS_QS = [
  [1,0,
    "ഇന്ത്യൻ സ്വാതന്ത്ര്യസമരത്തിൽ 'ഉപ്പു സത്യാഗ്രഹം' (ഡാൻഡി മാർച്ച്) നയിച്ചത് ആര്?",
    "Who led the Salt Satyagraha (Dandi March) in the Indian freedom struggle?",
    ["മഹാത്മാഗാന്ധി","ജവഹർലാൽ നെഹ്റു","സർദാർ പട്ടേൽ","സുഭാസ് ചന്ദ്രബോസ്"],
    ["Mahatma Gandhi","Jawaharlal Nehru","Sardar Patel","Subhas Chandra Bose"],
    0, "മഹാത്മാഗാന്ധി 1930 മാർച്ച് 12-ന് ഡാൻഡി മാർച്ച് നയിച്ചു.", "Mahatma Gandhi led the Dandi March on March 12, 1930."
  ],
  [2,0,
    "ഇന്ത്യൻ ഭരണഘടനയുടെ ശില്പി എന്നറിയപ്പെടുന്നത് ആര്?",
    "Who is known as the chief architect of the Indian Constitution?",
    ["ഡോ. ബി.ആർ. അംബേദ്കർ","മഹാത്മാഗാന്ധി","ജവഹർലാൽ നെഹ്റു","സർദാർ പട്ടേൽ"],
    ["Dr. B.R. Ambedkar","Mahatma Gandhi","Jawaharlal Nehru","Sardar Patel"],
    0, "ഡോ. ബി.ആർ. അംബേദ്കർ ഡ്രാഫ്റ്റിംഗ് കമ്മിറ്റിയുടെ ചെയർമാനായിരുന്നു.", "Dr. B.R. Ambedkar was the Chairman of the Drafting Committee."
  ],
  [3,0,
    "'ട്രിസ്റ്റ് വിത്ത് ഡെസ്റ്റിനി' പ്രസംഗം നടത്തിയത് ആര്?",
    "Who delivered the 'Tryst with Destiny' speech?",
    ["ജവഹർലാൽ നെഹ്റു","മഹാത്മാഗാന്ധി","സർദാർ പട്ടേൽ","ഡോ. ബി.ആർ. അംബേദ്കർ"],
    ["Jawaharlal Nehru","Mahatma Gandhi","Sardar Patel","Dr. B.R. Ambedkar"],
    0, "ജവഹർലാൽ നെഹ്റു 1947 ഓഗസ്റ്റ് 14-ന് ഈ പ്രസംഗം നടത്തി.", "Jawaharlal Nehru delivered this speech on August 14, 1947."
  ],
  [4,0,
    "സ്വതന്ത്ര ഇന്ത്യയുടെ ആദ്യ ഗവർണർ ജനറൽ ആരായിരുന്നു?",
    "Who was the first Governor-General of independent India?",
    ["ലോർഡ് മൗണ്ട്ബാറ്റൺ","സി. രാജഗോപാലാചാരി","ഡോ. രാജേന്ദ്ര പ്രസാദ്","ലോർഡ് കർസൺ"],
    ["Lord Mountbatten","C. Rajagopalachari","Dr. Rajendra Prasad","Lord Curzon"],
    0, "ലോർഡ് മൗണ്ട്ബാറ്റൺ ആദ്യ ഗവർണർ ജനറലായിരുന്നു (1947-48).", "Lord Mountbatten was the first Governor-General (1947-48)."
  ],
  [5,0,
    "ഇന്ത്യൻ നാഷണൽ ആർമി (INA) സ്ഥാപിച്ചത് ആര്?",
    "Who founded the Indian National Army (INA)?",
    ["സുഭാസ് ചന്ദ്രബോസ്","ഭഗത് സിംഗ്","ചന്ദ്രശേഖർ ആസാദ്","ജവഹർലാൽ നെഹ്റു"],
    ["Subhas Chandra Bose","Bhagat Singh","Chandrashekhar Azad","Jawaharlal Nehru"],
    0, "സുഭാസ് ചന്ദ്രബോസ് 1942-ൽ INA രൂപീകരിച്ചു.", "Subhas Chandra Bose formed the INA in 1942."
  ],
  [6,0,
    "ഇന്ത്യയുടെ ആദ്യ രാഷ്ട്രപതി ആരായിരുന്നു?",
    "Who was the first President of India?",
    ["ഡോ. രാജേന്ദ്ര പ്രസാദ്","ഡോ. എസ്. രാധാകൃഷ്ണൻ","ഡോ. ബി.ആർ. അംബേദ്കർ","വി.വി. ഗിരി"],
    ["Dr. Rajendra Prasad","Dr. S. Radhakrishnan","Dr. B.R. Ambedkar","V.V. Giri"],
    0, "ഡോ. രാജേന്ദ്ര പ്രസാദ് 1950-1962 വരെ രാഷ്ട്രപതിയായിരുന്നു.", "Dr. Rajendra Prasad was President from 1950-1962."
  ],
  [7,0,
    "'വന്ദേ മാതരം' രചിച്ചത് ആര്?",
    "Who wrote 'Vande Mataram'?",
    ["ബങ്കിം ചന്ദ്ര ചാറ്റർജി","രവീന്ദ്രനാഥ ടാഗോർ","മുഹമ്മദ് ഇഖ്ബാൽ","കെ.എ. അബ്ബാസ്"],
    ["Bankim Chandra Chatterjee","Rabindranath Tagore","Muhammad Iqbal","K.A. Abbas"],
    0, "ബങ്കിം ചന്ദ്ര ചാറ്റർജി 'ആനന്ദമഠ' എന്ന നോവലിൽ ഇത് രചിച്ചു.", "Bankim Chandra Chatterjee wrote it in the novel 'Anandamath'."
  ],
  [8,0,
    "ഇന്ത്യയുടെ ആദ്യ വനിതാ രാഷ്ട്രപതി ആരാണ്?",
    "Who was the first woman President of India?",
    ["പ്രതിഭാ പാട്ടിൽ","ഇന്ദിരാ ഗാന്ധി","സോണിയാ ഗാന്ധി","ദ്രൗപദി മുർമു"],
    ["Pratibha Patil","Indira Gandhi","Sonia Gandhi","Droupadi Murmu"],
    0, "പ്രതിഭാ പാട്ടിൽ 2007-2012 വരെ രാഷ്ട്രപതിയായിരുന്നു.", "Pratibha Patil served as President from 2007-2012."
  ],
  [9,0,
    "രാമകൃഷ്ണ മിഷൻ സ്ഥാപിച്ചത് ആര്?",
    "Who founded the Ramakrishna Mission?",
    ["സ്വാമി വിവേകാനന്ദൻ","രാമകൃഷ്ണ പരമഹംസർ","ദയാനന്ദ സരസ്വതി","മഹർഷി അരവിന്ദോ"],
    ["Swami Vivekananda","Ramakrishna Paramahamsa","Dayananda Saraswati","Sri Aurobindo"],
    0, "സ്വാമി വിവേകാനന്ദൻ 1897-ൽ രാമകൃഷ്ണ മിഷൻ സ്ഥാപിച്ചു.", "Swami Vivekananda founded the Ramakrishna Mission in 1897."
  ],
  [10,0,
    "സ്വതന്ത്ര ഇന്ത്യയുടെ ആദ്യ പ്രധാനമന്ത്രി ആരായിരുന്നു?",
    "Who was the first Prime Minister of independent India?",
    ["ജവഹർലാൽ നെഹ്റു","സർദാർ പട്ടേൽ","ലാൽ ബഹാദൂർ ശാസ്ത്രി","മൊറാർജി ദേശായി"],
    ["Jawaharlal Nehru","Sardar Patel","Lal Bahadur Shastri","Morarji Desai"],
    0, "ജവഹർലാൽ നെഹ്റു 1947-1964 വരെ പ്രധാനമന്ത്രിയായിരുന്നു.", "Jawaharlal Nehru was PM from 1947-1964."
  ],
  [11,0,
    "ഇന്ത്യൻ ഭരണഘടനയിലെ അടിസ്ഥാനാവകാശങ്ങൾ ഏത് ഭാഗത്തിലാണ് ഉൾപ്പെടുത്തിയിരിക്കുന്നത്?",
    "In which part of the Indian Constitution are Fundamental Rights enshrined?",
    ["ഭാഗം III","ഭാഗം IV","ഭാഗം II","ഭാഗം V"],
    ["Part III","Part IV","Part II","Part V"],
    0, "അടിസ്ഥാനാവകാശങ്ങൾ ഭാഗം III (ആർട്ടിക്കിൾ 12-35) ലാണ്.", "Fundamental Rights are in Part III (Articles 12-35)."
  ],
  [12,0,
    "ഇന്ത്യയിലെ ഏറ്റവും നീളം കൂടിയ നദി ഏതാണ്?",
    "Which is the longest river in India?",
    ["ഗംഗ","യമുന","ബ്രഹ്മപുത്ര","ഗോദാവരി"],
    ["Ganga","Yamuna","Brahmaputra","Godavari"],
    0, "ഗംഗ (2525 കി.മീ) ഇന്ത്യയിലെ ഏറ്റവും നീളമുള്ള നദിയാണ്.", "Ganga (2525 km) is the longest river in India."
  ],
  [13,0,
    "ഇന്ത്യയിലെ ഏറ്റവും വലിയ സംസ്ഥാനം ഏതാണ് (വിസ്തീർണ്ണത്തിൽ)?",
    "Which is the largest state in India by area?",
    ["രാജസ്ഥാൻ","മധ്യപ്രദേശ്","മഹാരാഷ്ട്ര","ഉത്തർപ്രദേശ്"],
    ["Rajasthan","Madhya Pradesh","Maharashtra","Uttar Pradesh"],
    0, "രാജസ്ഥാൻ (3,42,239 ച.കി.മീ) ഏറ്റവും വലിയ സംസ്ഥാനമാണ്.", "Rajasthan (3,42,239 sq.km) is the largest state."
  ],
  [14,0,
    "ഇന്ത്യയിലെ ഏറ്റവും ഉയരം കൂടിയ കൊടുമുടി ഏതാണ്?",
    "Which is the highest mountain peak in India?",
    ["കാഞ്ചൻജംഗ","എവറസ്റ്റ്","നംഗപർവത","അന്നപൂർണ"],
    ["Kanchenjunga","Mount Everest","Nanga Parbat","Annapurna"],
    0, "കാഞ്ചൻജംഗ (8586 മീ) ഇന്ത്യയിലെ ഏറ്റവും ഉയരം കൂടിയ കൊടുമുടിയാണ്.", "Kanchenjunga (8586 m) is India's highest peak."
  ],
  [15,0,
    "ഇന്ത്യയുടെ ദേശീയ മൃഗം ഏതാണ്?",
    "What is the national animal of India?",
    ["ബംഗാൾ കടുവ","ഇന്ത്യൻ ആന","കടുവ","ഇന്ത്യൻ കടുവ"],
    ["Bengal Tiger","Indian Elephant","Tiger","Indian Tiger"],
    0, "ബംഗാൾ കടുവ (Panthera tigris) ഇന്ത്യയുടെ ദേശീയ മൃഗമാണ്.", "The Bengal Tiger is the national animal of India."
  ],
  [16,0,
    "ഇന്ത്യയുടെ ദേശീയ പക്ഷി ഏതാണ്?",
    "What is the national bird of India?",
    ["മയിൽ","ഇന്ത്യൻ കുയിൽ","വെള്ളക്കൊക്ക്","സാരസ് കൊക്ക്"],
    ["Peacock","Indian Cuckoo","White Stork","Sarus Crane"],
    0, "മയിൽ (Pavo cristatus) ഇന്ത്യയുടെ ദേശീയ പക്ഷിയാണ്.", "The Peacock is the national bird of India."
  ],
  [17,0,
    "ഇന്ത്യയുടെ ദേശീയ പുഷ്പം ഏതാണ്?",
    "What is the national flower of India?",
    ["താമര","ജമന്തി","റോസ്","മുല്ല"],
    ["Lotus","Marigold","Rose","Jasmine"],
    0, "താമര (Nelumbo nucifera) ഇന്ത്യയുടെ ദേശീയ പുഷ്പമാണ്.", "Lotus is the national flower of India."
  ],
  [18,0,
    "ഇന്ത്യയിൽ റിപ്പബ്ലിക് ദിനം ഏത് ദിവസമാണ് ആചരിക്കുന്നത്?",
    "On which day is Republic Day celebrated in India?",
    ["ജനുവരി 26","ഓഗസ്റ്റ് 15","ഒക്ടോബർ 2","ജനുവരി 30"],
    ["January 26","August 15","October 2","January 30"],
    0, "1950 ജനുവരി 26-ന് ഭരണഘടന നിലവിൽ വന്നു.", "The Constitution came into effect on January 26, 1950."
  ],
  [19,0,
    "ഇന്ത്യയിൽ സ്വാതന്ത്ര്യ ദിനം ഏത് ദിവസമാണ് ആചരിക്കുന്നത്?",
    "On which day is Independence Day celebrated in India?",
    ["ഓഗസ്റ്റ് 15","ജനുവരി 26","ജനുവരി 30","മാർച്ച് 12"],
    ["August 15","January 26","January 30","March 12"],
    0, "1947 ഓഗസ്റ്റ് 15-ന് ഇന്ത്യ സ്വതന്ത്രമായി.", "India gained independence on August 15, 1947."
  ],
  [20,0,
    "ഇന്ത്യൻ ദേശീയ പതാക രൂപകൽപന ചെയ്തത് ആര്?",
    "Who designed the Indian national flag?",
    ["പിംഗളി വെങ്കയ്യ","മഹാത്മാഗാന്ധി","ജവഹർലാൽ നെഹ്റു","അന്നാ സുവർണ"],
    ["Pingali Venkayya","Mahatma Gandhi","Jawaharlal Nehru","Anna Suvarna"],
    0, "പിംഗളി വെങ്കയ്യ 1921-ൽ പതാക രൂപകൽപന ചെയ്തു.", "Pingali Venkayya designed the flag in 1921."
  ],
  [21,0,
    "ആദ്യ പഞ്ചവത്സര പദ്ധതി ആരംഭിച്ച വർഷം ഏതാണ്?",
    "In which year was the First Five Year Plan started?",
    ["1951","1947","1950","1956"],
    ["1951","1947","1950","1956"],
    0, "ആദ്യ പഞ്ചവത്സര പദ്ധതി 1951-ൽ ആരംഭിച്ചു.", "The First Five Year Plan started in 1951."
  ],
  [22,0,
    "ഇന്ത്യയിലെ ആദ്യ ചീഫ് ഇലക്ഷൻ കമ്മീഷണർ ആരായിരുന്നു?",
    "Who was the first Chief Election Commissioner of India?",
    ["സുകുമാർ സെൻ","കെ.വി.കെ. സുന്ദരം","ടി.എൻ. ശേഷൻ","എസ്.പി. സെൻ വർമ"],
    ["Sukumar Sen","K.V.K. Sundaram","T.N. Seshan","S.P. Sen Verma"],
    0, "സുകുമാർ സെൻ 1950-1958 വരെ സി.ഇ.സി. ആയിരുന്നു.", "Sukumar Sen was CEC from 1950-1958."
  ],
  [23,0,
    "നോബൽ സമ്മാനം നേടുന്ന ആദ്യ ഇന്ത്യക്കാരൻ ആര്?",
    "Who was the first Indian to win a Nobel Prize?",
    ["രവീന്ദ്രനാഥ ടാഗോർ","സി.വി. രാമൻ","മദർ തെരേസ","അമർത്യ സെൻ"],
    ["Rabindranath Tagore","C.V. Raman","Mother Teresa","Amartya Sen"],
    0, "1913-ൽ സാഹിത്യത്തിന് ടാഗോർ നോബൽ നേടി.", "Tagore won the Nobel for Literature in 1913."
  ],
  [24,0,
    "സുപ്രീം കോടതി ജഡ്ജിമാരുടെ വിരമിക്കൽ പ്രായം എത്രയാണ്?",
    "What is the retirement age of Supreme Court judges?",
    ["65","62","60","68"],
    ["65","62","60","68"],
    0, "സുപ്രീം കോടതി ജഡ്ജിമാർ 65 വയസ്സിൽ വിരമിക്കുന്നു.", "Supreme Court judges retire at age 65."
  ],
  [25,0,
    "രാജ്യസഭയുടെ അധ്യക്ഷൻ ആരാണ്?",
    "Who is the Chairman of the Rajya Sabha?",
    ["ഉപരാഷ്ട്രപതി","രാഷ്ട്രപതി","പ്രധാനമന്ത്രി","ലോക്സഭാ സ്പീക്കർ"],
    ["Vice President","President","Prime Minister","Lok Sabha Speaker"],
    0, "ഉപരാഷ്ട്രപതി രാജ്യസഭയുടെ അധ്യക്ഷനാണ്.", "The Vice President is the Chairman of Rajya Sabha."
  ],
  [26,0,
    "ഇന്ത്യൻ ഭരണഘടനയിൽ എത്ര ഷെഡ്യൂളുകൾ (പട്ടികകൾ) ഉണ്ട്?",
    "How many schedules are there in the Indian Constitution?",
    ["12","8","10","14"],
    ["12","8","10","14"],
    0, "നിലവിൽ 12 ഷെഡ്യൂളുകൾ ഉണ്ട്.", "There are currently 12 Schedules."
  ],
  [27,0,
    "കേരള സംസ്ഥാനം രൂപീകൃതമായത് എപ്പോൾ?",
    "When was Kerala state formed?",
    ["1956 നവംബർ 1","1950 ജനുവരി 26","1956 ജനുവരി 26","1947 ഓഗസ്റ്റ് 15"],
    ["November 1, 1956","January 26, 1950","January 26, 1956","August 15, 1947"],
    0, "1956 നവംബർ 1-ന് കേരളം രൂപീകൃതമായി.", "Kerala was formed on Nov 1, 1956."
  ],
  [28,0,
    "കേരളത്തിലെ ആദ്യ മുഖ്യമന്ത്രി ആരായിരുന്നു?",
    "Who was the first Chief Minister of Kerala?",
    ["ഇ.എം.എസ്. നമ്പൂതിരിപ്പാട്","പി.കെ. കുഞ്ഞ്","പട്ടം താണുപിള്ള","സി. കേശവൻ"],
    ["E.M.S. Namboodiripad","P.K. Kunju","Pattom Thanu Pillai","C. Kesavan"],
    0, "ഇ.എം.എസ്. നമ്പൂതിരിപ്പാട് (1957-59) ആദ്യ മുഖ്യമന്ത്രിയായിരുന്നു.", "E.M.S. Namboodiripad (1957-59) was the first CM."
  ],
  [29,0,
    "വിസ്തീർണ്ണത്തിൽ ഏറ്റവും വലിയ ജില്ല ഏതാണ്?",
    "Which is the largest district in Kerala by area?",
    ["പാലക്കാട്","വയനാട്","ഇടുക്കി","കണ്ണൂർ"],
    ["Palakkad","Wayanad","Idukki","Kannur"],
    0, "പാലക്കാട് (4480 ച.കി.മീ) ഏറ്റവും വലിയ ജില്ലയാണ്.", "Palakkad (4480 sq.km) is the largest district."
  ],
  [30,0,
    "വിസ്തീർണ്ണത്തിൽ ഏറ്റവും ചെറിയ ജില്ല ഏതാണ്?",
    "Which is the smallest district in Kerala by area?",
    ["ആലപ്പുഴ","കോഴിക്കോട്","കൊല്ലം","തിരുവനന്തപുരം"],
    ["Alappuzha","Kozhikode","Kollam","Thiruvananthapuram"],
    0, "ആലപ്പുഴ (1414 ച.കി.മീ) ഏറ്റവും ചെറിയ ജില്ലയാണ്.", "Alappuzha (1414 sq.km) is the smallest district."
  ],
  [31,0,
    "കേരളത്തിലെ ആദ്യ വൈദ്യുത റെയിൽവേ ലൈൻ ഏതാണ്?",
    "Which is the first electrified railway line in Kerala?",
    ["എറണാകുളം-തൃശൂർ","തിരുവനന്തപുരം-കൊല്ലം","കോഴിക്കോട്-കണ്ണൂർ","പാലക്കാട്-ഷൊറണൂർ"],
    ["Ernakulam-Thrissur","Thiruvananthapuram-Kollam","Kozhikode-Kannur","Palakkad-Shoranur"],
    0, "എറണാകുളം-തൃശൂർ ആദ്യ വൈദ്യുത റെയിൽവേ ലൈനാണ്.", "Ernakulam-Thrissur was the first electrified railway line."
  ],
  [32,0,
    "കേരളത്തിലെ ജില്ലകളുടെ എണ്ണം എത്രയാണ്?",
    "How many districts are there in Kerala?",
    ["14","12","10","16"],
    ["14","12","10","16"],
    0, "കേരളത്തിൽ 14 ജില്ലകളുണ്ട്.", "Kerala has 14 districts."
  ],
  [33,0,
    "കേരളത്തിന്റെ ഔദ്യോഗിക മൃഗം ഏതാണ്?",
    "What is the official animal of Kerala?",
    ["ഇന്ത്യൻ ആന","വരയാട്","കാട്ടുപോത്ത്","പുലി"],
    ["Indian Elephant","Nilgiri Tahr","Wild Buffalo","Leopard"],
    0, "ഇന്ത്യൻ ആന ഔദ്യോഗിക മൃഗമാണ്.", "Indian Elephant is the official animal."
  ],
  [34,0,
    "കേരളത്തിന്റെ ഔദ്യോഗിക പക്ഷി ഏതാണ്?",
    "What is the official bird of Kerala?",
    ["മലമുഴക്കി വേഴാമ്പൽ","മയിൽ","ഇന്ത്യൻ കുയിൽ","ചെമ്പോത്ത്"],
    ["Great Hornbill","Peacock","Indian Cuckoo","Jungle Myna"],
    0, "മലമുഴക്കി വേഴാമ്പൽ (Great Hornbill) ഔദ്യോഗിക പക്ഷിയാണ്.", "Great Hornbill is the official bird."
  ],
  [35,0,
    "കേരളത്തിന്റെ ഔദ്യോഗിക പുഷ്പം ഏതാണ്?",
    "What is the official flower of Kerala?",
    ["കണിക്കൊന്ന","താമര","മുല്ല","ചെമ്പകം"],
    ["Golden Shower","Lotus","Jasmine","Champak"],
    0, "കണിക്കൊന്ന (Cassia fistula) ഔദ്യോഗിക പുഷ്പമാണ്.", "Golden Shower is the official flower."
  ],
  [36,0,
    "കേരളത്തിന്റെ ഔദ്യോഗിക വൃക്ഷം ഏതാണ്?",
    "What is the official tree of Kerala?",
    ["തെങ്ങ്","ആൽമരം","പ്ലാവ്","കമുക്"],
    ["Coconut tree","Banyan","Jackfruit","Areca nut"],
    0, "തെങ്ങ് (Cocos nucifera) ഔദ്യോഗിക വൃക്ഷമാണ്.", "Coconut tree is the official tree."
  ],
  [37,0,
    "'കേരളത്തിന്റെ ഗംഗ' എന്നറിയപ്പെടുന്ന നദി ഏതാണ്?",
    "Which river is known as the 'Ganges of Kerala'?",
    ["പെരിയാർ","ഭാരതപ്പുഴ","പമ്പാ","ചാലിയാർ"],
    ["Periyar","Bharathapuzha","Pamba","Chaliyar"],
    0, "പെരിയാർ (244 കി.മീ) കേരളത്തിലെ ഏറ്റവും നീളമുള്ള നദിയാണ്.", "Periyar (244 km) is Kerala's longest river."
  ],
  [38,0,
    "കേരളത്തിലെ ആദ്യ ഹൈഡ്രോ ഇലക്ട്രിക് പ്രോജക്റ്റ് ഏതാണ്?",
    "What was the first hydroelectric project in Kerala?",
    ["പള്ളിവാസൽ","ഇടുക്കി","ശബരിഗിരി","കുത്തുങ്കൽ"],
    ["Pallivasal","Idukki","Sabarigiri","Kuthungal"],
    0, "പള്ളിവാസൽ (1940) ആദ്യ ഹൈഡ്രോ ഇലക്ട്രിക് പ്രോജക്റ്റാണ്.", "Pallivasal (1940) was the first hydroelectric project."
  ],
  [39,0,
    "'കേരളത്തിന്റെ ഗാന്ധി' എന്നറിയപ്പെടുന്നത് ആരെ?",
    "Who is known as the 'Gandhi of Kerala'?",
    ["കെ. കേളപ്പൻ","ശ്രീനാരായണ ഗുരു","അയ്യങ്കാളി","വി.ടി. ഭട്ടതിരിപ്പാട്"],
    ["K. Kelappan","Sree Narayana Guru","Ayyankali","V.T. Bhattathiripad"],
    0, "കെ. കേളപ്പൻ ഗാന്ധിയൻ ആശയങ്ങൾ പിന്തുടർന്ന നേതാവാണ്.", "K. Kelappan was a Gandhian leader."
  ],
  [40,0,
    "വൈക്കം സത്യാഗ്രഹത്തിന് നേതൃത്വം നൽകിയത് ആര്?",
    "Who led the Vaikom Satyagraha?",
    ["ഇ.വി. രാമസ്വാമി നായ്കർ","ശ്രീനാരായണ ഗുരു","അയ്യങ്കാളി","കെ. കേളപ്പൻ"],
    ["E.V. Ramaswami Naicker","Sree Narayana Guru","Ayyankali","K. Kelappan"],
    0, "പെരിയാർ 1924-25-ലെ വൈക്കം സത്യാഗ്രഹത്തിന് നേതൃത്വം നൽകി.", "Periyar led the Vaikom Satyagraha (1924-25)."
  ],
  [41,1,
    "കേരളത്തിന്റെ നിലവിലെ മുഖ്യമന്ത്രി ആരാണ്?",
    "Who is the current Chief Minister of Kerala?",
    ["പിണറായി വിജയൻ","ഉമ്മൻ ചാണ്ടി","ശശി തരൂർ","കെ. കരുണാകരൻ"],
    ["Pinarayi Vijayan","Oommen Chandy","Shashi Tharoor","K. Karunakaran"],
    0, "പിണറായി വിജയൻ 2016 മുതൽ മുഖ്യമന്ത്രിയാണ്.", "Pinarayi Vijayan has been CM since 2016."
  ],
  [42,1,
    "ഇന്ത്യയുടെ നിലവിലെ രാഷ്ട്രപതി ആരാണ്?",
    "Who is the current President of India?",
    ["ദ്രൗപദി മുർമു","രാം നാഥ് കോവിന്ദ്","പ്രണബ് മുഖർജി","എ.പി.ജെ. അബ്ദുൾ കലാം"],
    ["Droupadi Murmu","Ram Nath Kovind","Pranab Mukherjee","A.P.J. Abdul Kalam"],
    0, "ദ്രൗപദി മുർമു 2022-ൽ രാഷ്ട്രപതിയായി.", "Droupadi Murmu was elected President in 2022."
  ],
  [43,1,
    "ഇന്ത്യയുടെ നിലവിലെ പ്രധാനമന്ത്രി ആരാണ്?",
    "Who is the current Prime Minister of India?",
    ["നരേന്ദ്ര മോദി","രാജ്നാഥ് സിംഗ്","അമിത് ഷാ","യോഗി ആദിത്യനാഥ്"],
    ["Narendra Modi","Rajnath Singh","Amit Shah","Yogi Adityanath"],
    0, "നരേന്ദ്ര മോദി 2014 മുതൽ പ്രധാനമന്ത്രിയാണ്.", "Narendra Modi has been PM since 2014."
  ],
  [44,1,
    "ലോക്സഭയിലെ നിലവിലെ സ്പീക്കർ ആരാണ്?",
    "Who is the current Speaker of the Lok Sabha?",
    ["ഓം ബിർല","സുമിത്ര മഹാജൻ","മീര കുമാർ","സോണിയാ ഗാന്ധി"],
    ["Om Birla","Sumitra Mahajan","Meira Kumar","Sonia Gandhi"],
    0, "ഓം ബിർല 2019 മുതൽ ലോക്സഭാ സ്പീക്കറാണ്.", "Om Birla has been Lok Sabha Speaker since 2019."
  ],
  [45,1,
    "2023 ലോകകപ്പ് ക്രിക്കറ്റ് വിജയിച്ച ടീം ഏതാണ്?",
    "Which team won the 2023 Cricket World Cup?",
    ["ഓസ്ട്രേലിയ","ഇന്ത്യ","ഇംഗ്ലണ്ട്","ന്യൂസിലൻഡ്"],
    ["Australia","India","England","New Zealand"],
    0, "ഓസ്ട്രേലിയ 2023-ൽ ഇന്ത്യയെ പരാജയപ്പെടുത്തി കിരീടം നേടി.", "Australia defeated India in 2023 to win the title."
  ],
  [46,1,
    "2024-ലെ നോബൽ സമ്മാനം (സാഹിത്യം) നേടിയത് ആര്?",
    "Who won the 2024 Nobel Prize in Literature?",
    ["ഹാൻ കാങ്","ജോൺ ഫോസ്","അബ്ദുൾറസാഖ് ഗുർന","ആനി എർനോൾ"],
    ["Han Kang","Jon Fosse","Abdulrazak Gurnah","Annie Ernaux"],
    0, "ഹാൻ കാങ് 2024-ൽ സാഹിത്യ നോബൽ നേടി.", "Han Kang won the 2024 Nobel in Literature."
  ],
  [47,1,
    "2022-ലെ ഫിഫ ലോകകപ്പ് വിജയിച്ച രാജ്യം ഏതാണ്?",
    "Which country won the 2022 FIFA World Cup?",
    ["അർജന്റീന","ഫ്രാൻസ്","ബ്രസീൽ","ജർമനി"],
    ["Argentina","France","Brazil","Germany"],
    0, "അർജന്റീന 2022-ൽ ഖത്തറിൽ ലോകകപ്പ് നേടി.", "Argentina won the 2022 World Cup in Qatar."
  ],
  [48,1,
    "ഇന്ത്യയിലെ ഏറ്റവും പുതിയ സംസ്ഥാനം ഏതാണ്?",
    "Which is the newest state of India?",
    ["തെലങ്കാന","ഛത്തീസ്ഗഢ്","ഉത്തരാഖണ്ഡ്","ഝാർഖണ്ഡ്"],
    ["Telangana","Chhattisgarh","Uttarakhand","Jharkhand"],
    0, "തെലങ്കാന 2014 ജൂൺ 2-ന് രൂപീകൃതമായി.", "Telangana was formed on June 2, 2014."
  ],
  [49,1,
    "G20 ഉച്ചകോടി 2023 നടന്ന സ്ഥലം ഏതാണ്?",
    "Where was the G20 Summit 2023 held?",
    ["ന്യൂഡൽഹി","ടോക്കിയോ","പാരീസ്","ലണ്ടൻ"],
    ["New Delhi","Tokyo","Paris","London"],
    0, "G20 ഉച്ചകോടി 2023 സെപ്റ്റംബറിൽ ന്യൂഡൽഹിയിൽ നടന്നു.", "The G20 Summit was held in New Delhi in September 2023."
  ],
  [50,1,
    "2024 ഒളിമ്പിക്സ് നടന്ന സ്ഥലം ഏതാണ്?",
    "Where were the 2024 Olympics held?",
    ["പാരീസ്","ടോക്കിയോ","ലോസ് ഏഞ്ചലസ്","ലണ്ടൻ"],
    ["Paris","Tokyo","Los Angeles","London"],
    0, "2024 ഒളിമ്പിക്സ് പാരീസിലാണ് നടന്നത്.", "The 2024 Olympics were held in Paris."
  ],
  [51,1,
    "2024-ലെ നോബൽ ശാന്തി സമ്മാനം നേടിയത് ആര്?",
    "Who won the 2024 Nobel Peace Prize?",
    ["നിഹോൺ ഹിദാൻക്യോ","അലക്സി നവല്നി","ഗ്രെറ്റ തൻബെർഗ്","ഡോക്ടേഴ്സ് വിത്തൗട്ട് ബോർഡേഴ്സ്"],
    ["Nihon Hidankyo","Alexei Navalny","Greta Thunberg","Doctors Without Borders"],
    0, "നിഹോൺ ഹിദാൻക്യോ 2024-ൽ നോബൽ ശാന്തി സമ്മാനം നേടി.", "Nihon Hidankyo won the 2024 Nobel Peace Prize."
  ],
  [52,1,
    "ബംഗാൾ ഉൾക്കട്ടിലെ ഇന്ത്യൻ കേന്ദ്രഭരണ പ്രദേശം ഏതാണ്?",
    "Which Union Territory lies in the Bay of Bengal?",
    ["ആൻഡമാൻ നിക്കോബാർ","ലക്ഷദ്വീപ്","പോണ്ടിച്ചേരി","ദാമൻ ദിയു"],
    ["Andaman & Nicobar","Lakshadweep","Puducherry","Daman & Diu"],
    0, "ആൻഡമാൻ നിക്കോബാർ ദ്വീപുകൾ ബംഗാൾ ഉൾക്കട്ടിലാണ്.", "Andaman & Nicobar Islands are in the Bay of Bengal."
  ],
  [53,1,
    "2028 ഒളിമ്പിക്സ് നടക്കുന്ന നഗരം ഏതാണ്?",
    "Which city will host the 2028 Olympics?",
    ["ലോസ് ഏഞ്ചലസ്","പാരീസ്","ബ്രിസ്ബെയ്ൻ","മുംബൈ"],
    ["Los Angeles","Paris","Brisbane","Mumbai"],
    0, "2028 ഒളിമ്പിക്സ് ലോസ് ഏഞ്ചലസിൽ നടക്കും.", "The 2028 Olympics will be held in Los Angeles."
  ],
  [54,1,
    "കേരളത്തിലെ നിലവിലെ ഗവർണർ ആരാണ്?",
    "Who is the current Governor of Kerala?",
    ["ആരിഫ് മുഹമ്മദ് ഖാൻ","പി. സദാശിവം","ജസ്റ്റിസ് പി. സദാശിവം","ജഗദീപ് ധൻകർ"],
    ["Arif Mohammad Khan","P. Sathasivam","Justice P. Sathasivam","Jagdeep Dhankhar"],
    0, "ആരിഫ് മുഹമ്മദ് ഖാൻ 2019 മുതൽ കേരള ഗവർണറാണ്.", "Arif Mohammad Khan has been Kerala Governor since 2019."
  ],
  [55,1,
    "ഇന്ത്യയുടെ നിലവിലെ ചീഫ് ജസ്റ്റിസ് ആരാണ്?",
    "Who is the current Chief Justice of India?",
    ["ഡി.വൈ. ചന്ദ്രചൂഡ്","എൻ.വി. രമണ","എസ്.എ. ബോബ്ഡേ","ജെ.എസ്. ഖേഹർ"],
    ["D.Y. Chandrachud","N.V. Ramana","S.A. Bobde","J.S. Khehar"],
    0, "ഡി.വൈ. ചന്ദ്രചൂഡ് 2022 നവംബർ മുതൽ ചീഫ് ജസ്റ്റിസാണ്.", "D.Y. Chandrachud has been CJI since November 2022."
  ],
  [56,1,
    "2024-ൽ ഇന്ത്യയുടെ ദേശീയ ഗെയിംസ് നടന്ന സംസ്ഥാനം ഏതാണ്?",
    "In which state were the 2024 National Games held?",
    ["ഗോവ","കേരളം","കർണാടക","തമിഴ്നാട്"],
    ["Goa","Kerala","Karnataka","Tamil Nadu"],
    0, "38-ാമത് ദേശീയ ഗെയിംസ് 2024-ൽ ഗോവയിൽ നടന്നു.", "The 38th National Games were held in Goa in 2024."
  ],
  [57,1,
    "കേരളത്തിലെ പുതിയ അന്താരാഷ്ട്ര വിമാനത്താവളം ഏതാണ്?",
    "Which is the new international airport in Kerala?",
    ["കണ്ണൂർ","കോഴിക്കോട്","തിരുവനന്തപുരം","കൊച്ചി"],
    ["Kannur","Kozhikode","Thiruvananthapuram","Cochin"],
    0, "കണ്ണൂർ അന്താരാഷ്ട്ര വിമാനത്താവളം 2018-ൽ തുറന്നു.", "Kannur International Airport opened in 2018."
  ],
  [58,1,
    "2024-ലെ ബുക്കർ പ്രൈസ് നേടിയത് ഏത് നോവലാണ്?",
    "Which novel won the 2024 Booker Prize?",
    ["ഓർബിറ്റൽ","ദി ബീ ആൻഡ് ദി ഓറഞ്ച് ട്രീ","ദി സെവന്റ്ത് ക്രോസ്","മിഡ്നൈറ്റ് സൺ"],
    ["Orbital","The Bee and the Orange Tree","The Seventh Cross","Midnight Sun"],
    0, "സമന്ത ഹാർവിയുടെ 'ഓർബിറ്റൽ' 2024-ലെ ബുക്കർ പ്രൈസ് നേടി.", "Samantha Harvey's 'Orbital' won the 2024 Booker Prize."
  ],
  [59,1,
    "ഇന്ത്യയിലെ ആദ്യ ബഹിരാകാശ സഞ്ചാരി ആരാണ്?",
    "Who was the first Indian astronaut?",
    ["രാകേഷ് ശർമ","കൽപന ചൗള","സുനിത വില്യംസ്","രവീഷ് മൽഹോത്ര"],
    ["Rakesh Sharma","Kalpana Chawla","Sunita Williams","Ravish Malhotra"],
    0, "രാകേഷ് ശർമ 1984-ൽ ബഹിരാകാശത്ത് എത്തിയ ആദ്യ ഇന്ത്യക്കാരനാണ്.", "Rakesh Sharma was the first Indian in space in 1984."
  ],
  [60,1,
    "2023-ൽ ചന്ദ്രനിൽ ഇറങ്ങിയ ഇന്ത്യൻ ദൗത്യം ഏതാണ്?",
    "Which Indian mission landed on the Moon in 2023?",
    ["ചന്ദ്രയാൻ-3","ചന്ദ്രയാൻ-2","മംഗൾയാൻ","ആദിത്യ-എൽ1"],
    ["Chandrayaan-3","Chandrayaan-2","Mangalyaan","Aditya-L1"],
    0, "ചന്ദ്രയാൻ-3 2023 ഓഗസ്റ്റിൽ ചന്ദ്രോപരിതലത്തിൽ സോഫ്റ്റ് ലാൻഡ് ചെയ്തു.", "Chandrayaan-3 soft-landed on the Moon in August 2023."
  ],
  [61,2,
    "മനുഷ്യ ശരീരത്തിലെ ഏറ്റവും വലിയ അവയവം ഏതാണ്?",
    "What is the largest organ in the human body?",
    ["ചർമ്മം","കരൾ","ഹൃദയം","മസ്തിഷ്കം"],
    ["Skin","Liver","Heart","Brain"],
    0, "ചർമ്മം (Skin) മനുഷ്യ ശരീരത്തിലെ ഏറ്റവും വലിയ അവയവമാണ്.", "Skin is the largest organ in the human body."
  ],
  [62,2,
    "വിറ്റാമിൻ C യുടെ അപര്യാപ്തത മൂലമുണ്ടാകുന്ന രോഗം ഏതാണ്?",
    "Which disease is caused by Vitamin C deficiency?",
    ["സ്കർവി","റിക്കറ്റ്സ്","ബെരി-ബെരി","രാത്രി അന്ധത"],
    ["Scurvy","Rickets","Beri-Beri","Night blindness"],
    0, "വിറ്റാമിൻ C അപര്യാപ്തത സ്കർവി ഉണ്ടാക്കുന്നു.", "Vitamin C deficiency causes Scurvy."
  ],
  [63,2,
    "ഹൃദയത്തിന്റെ വൈദ്യുത പ്രവർത്തനം രേഖപ്പെടുത്തുന്ന ഉപകരണം ഏതാണ്?",
    "Which instrument records the heart's electrical activity?",
    ["ഇ.സി.ജി.","ഇക്കോകാർഡിയോഗ്രാം","സ്റ്റെതസ്കോപ്പ്","ബിപി മോണിറ്റർ"],
    ["ECG","Echocardiogram","Stethoscope","BP Monitor"],
    0, "ECG ഹൃദയത്തിന്റെ വൈദ്യുത പ്രവർത്തനം രേഖപ്പെടുത്തുന്നു.", "ECG records the heart's electrical activity."
  ],
  [64,2,
    "പ്രകാശസംശ്ലേഷണത്തിന് ആവശ്യമായ വാതകം ഏതാണ്?",
    "Which gas is required for photosynthesis?",
    ["കാർബൺ ഡൈഓക്സൈഡ്","ഓക്സിജൻ","നൈട്രജൻ","ഹൈഡ്രജൻ"],
    ["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"],
    0, "സസ്യങ്ങൾ CO2 ഉപയോഗിച്ച് പ്രകാശസംശ്ലേഷണം നടത്തുന്നു.", "Plants use CO2 for photosynthesis."
  ],
  [65,2,
    "മനുഷ്യ ശരീരത്തിലെ ഏറ്റവും ചെറിയ അസ്ഥി ഏതാണ്?",
    "What is the smallest bone in the human body?",
    ["സ്റ്റേപ്പീസ് (ചെവിയിലെ)","ഫലാഞ്ചസ്","കോക്ലിയ","കാർപൽ"],
    ["Stapes (in ear)","Phalanx","Cochlea","Carpal"],
    0, "സ്റ്റേപ്പീസ് (2.5 മി.മീ) മധ്യ ചെവിയിലെ ഏറ്റവും ചെറിയ അസ്ഥിയാണ്.", "The stapes (2.5 mm) in the middle ear is the smallest bone."
  ],
  [66,2,
    "ജലത്തിന്റെ രാസസൂത്രം ഏതാണ്?",
    "What is the chemical formula of water?",
    ["H₂O","CO₂","NaCl","HCl"],
    ["H₂O","CO₂","NaCl","HCl"],
    0, "ജലത്തിന്റെ രാസസൂത്രം H₂O ആണ്.", "The chemical formula of water is H₂O."
  ],
  [67,2,
    "ഭൂമിയുടെ ഏറ്റവും അടുത്തുള്ള നക്ഷത്രം ഏതാണ്?",
    "Which is the nearest star to Earth?",
    ["സൂര്യൻ","പ്രോക്സിമ സെന്റോറി","ആൽഫ സെന്റോറി","സിറിയസ്"],
    ["Sun","Proxima Centauri","Alpha Centauri","Sirius"],
    0, "സൂര്യൻ ഭൂമിയിൽ നിന്ന് 14.96 കോടി കി.മീ അകലെയാണ്.", "The Sun is 149.6 million km from Earth."
  ],
  [68,2,
    "എയ്ഡ്സ് രോഗത്തിന് കാരണമാകുന്ന വൈറസ് ഏതാണ്?",
    "Which virus causes AIDS?",
    ["എച്ച്.ഐ.വി.","കോവിഡ്-19","എബോള","ഹെപ്പറ്റൈറ്റിസ് ബി"],
    ["HIV","COVID-19","Ebola","Hepatitis B"],
    0, "ഹ്യൂമൻ ഇമ്മ്യൂണോ ഡെഫിഷ്യൻസി വൈറസ് (HIV) എയ്ഡ്സിന് കാരണമാകുന്നു.", "Human Immunodeficiency Virus (HIV) causes AIDS."
  ],
  [69,2,
    "പിണ്ഡം അളക്കാൻ ഉപയോഗിക്കുന്ന ഉപകരണം ഏതാണ്?",
    "Which instrument is used to measure mass?",
    ["തുലാസ്","ഥർമോമീറ്റർ","ബാരോമീറ്റർ","അമ്മീറ്റർ"],
    ["Balance","Thermometer","Barometer","Ammeter"],
    0, "തുലാസ് (Balance) പിണ്ഡം അളക്കാൻ ഉപയോഗിക്കുന്നു.", "A Balance is used to measure mass."
  ],
  [70,2,
    "കേരളത്തിലെ പ്രധാന കാർഷിക വിള ഏതാണ്?",
    "Which is the main agricultural crop of Kerala?",
    ["നെല്ല്","റബ്ബർ","തേങ്ങ","കവുങ്ങ്"],
    ["Rice","Rubber","Coconut","Arecanut"],
    2, "തേങ്ങ (Coconut) കേരളത്തിലെ പ്രധാന കാർഷിക വിളയാണ്.", "Coconut is the main agricultural crop of Kerala."
  ],
  // ---- IV. Public Health (10 questions) ----
  [71,3,
    "മനുഷ്യ ശരീരത്തിന്റെ സാധാരണ താപനില എത്രയാണ്?",
    "What is the normal human body temperature?",
    ["37°C","36°C","38°C","39.5°C"],
    ["37°C","36°C","38°C","39.5°C"],
    0, "സാധാരണ മനുഷ്യ ശരീര താപനില 37°C (98.6°F) ആണ്.", "Normal human body temperature is 37°C (98.6°F)."
  ],
  [72,3,
    "കൊതുക് കടിയിലൂടെ പകരുന്ന രോഗം ഏതാണ്?",
    "Which disease is transmitted by mosquito bites?",
    ["മലേറിയ","ക്ഷയം","ടൈഫോയ്ഡ്","കോളറ"],
    ["Malaria","Tuberculosis","Typhoid","Cholera"],
    0, "മലേറിയ പ്ലാസ്മോഡിയം പരാദം മൂലമുണ്ടാകുന്ന കൊതുക് പരത്തുന്ന രോഗമാണ്.", "Malaria is a mosquito-borne disease caused by Plasmodium parasite."
  ],
  [73,3,
    "WHO എന്നതിന്റെ പൂർണ്ണരൂപം എന്താണ്?",
    "What is the full form of WHO?",
    ["വേൾഡ് ഹെൽത്ത് ഓർഗനൈസേഷൻ","വേൾഡ് ഹ്യുമൻ ഓർഗനൈസേഷൻ","വേൾഡ് ഹെൽത്ത് ഓഫീസ്","വേൾഡ് ഹോസ്പിറ്റൽ ഓർഗനൈസേഷൻ"],
    ["World Health Organization","World Human Organization","World Health Office","World Hospital Organization"],
    0, "ലോകാരോഗ്യ സംഘടന (WHO) 1948-ൽ സ്ഥാപിതമായി.", "The World Health Organization (WHO) was founded in 1948."
  ],
  [74,3,
    "സൂര്യപ്രകാശത്തിൽ നിന്ന് ലഭിക്കുന്ന വിറ്റാമിൻ ഏതാണ്?",
    "Which vitamin is obtained from sunlight?",
    ["വിറ്റാമിൻ ഡി","വിറ്റാമിൻ സി","വിറ്റാമിന് എ","വിറ്റാമിൻ ബി"],
    ["Vitamin D","Vitamin C","Vitamin A","Vitamin B"],
    0, "സൂര്യപ്രകാശം ചർമ്മത്തിൽ വിറ്റാമിൻ ഡി ഉൽപാദിപ്പിക്കുന്നു.", "Sunlight helps the skin produce Vitamin D."
  ],
  [75,3,
    "BCG വാക്സിൻ ഏത് രോഗത്തിനെതിരെ സംരക്ഷണം നൽകുന്നു?",
    "Which disease does the BCG vaccine protect against?",
    ["ക്ഷയം (TB)","പോളിയോ","ടെറ്റനസ്","ഹെപ്പറ്റൈറ്റിസ്"],
    ["Tuberculosis (TB)","Polio","Tetanus","Hepatitis"],
    0, "BCG (Bacillus Calmette-Guérin) ക്ഷയരോഗത്തിനെതിരെയുള്ള വാക്സിനാണ്.", "BCG (Bacillus Calmette-Guérin) is the vaccine for Tuberculosis."
  ],
  [76,3,
    "പ്രമേഹത്തിന്റെ പ്രധാന ലക്ഷണം എന്താണ്?",
    "What is the primary symptom of Diabetes?",
    ["രക്തത്തിലെ പഞ്ചസാരയുടെ അളവ് കൂടുക","രക്തസമ്മർദ്ദം കൂടുക","ഭാരം കൂടുക","മുടികൊഴിച്ചിൽ"],
    ["High blood sugar level","High blood pressure","Weight gain","Hair loss"],
    0, "പ്രമേഹത്തിൽ രക്തത്തിലെ ഗ്ലൂക്കോസിന്റെ അളവ് വർദ്ധിക്കുന്നു.", "In diabetes, blood glucose levels become elevated."
  ],
  [77,3,
    "ശ്വസനത്തിന് അത്യാവശ്യമായ വാതകം ഏതാണ്?",
    "Which gas is essential for respiration?",
    ["ഓക്സിജൻ","കാർബൺ ഡൈഓക്സൈഡ്","നൈട്രജൻ","ഹൈഡ്രജൻ"],
    ["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],
    0, "മനുഷ്യ ശ്വസനത്തിന് ഓക്സിജൻ അത്യന്താപേക്ഷിതമാണ്.", "Oxygen is essential for human respiration."
  ],
  [78,3,
    "സാധാരണ രക്തസമ്മർദ്ദ പരിധി എത്രയാണ്?",
    "What is the normal blood pressure range?",
    ["120/80 mmHg","140/90 mmHg","100/70 mmHg","130/85 mmHg"],
    ["120/80 mmHg","140/90 mmHg","100/70 mmHg","130/85 mmHg"],
    0, "സാധാരണ രക്തസമ്മർദ്ദം 120/80 mmHg ആണ്.", "Normal blood pressure is 120/80 mmHg."
  ],
  [79,3,
    "മനുഷ്യ ശരീരത്തിൽ രക്തം ശുദ്ധീകരിക്കുന്ന അവയവം ഏതാണ്?",
    "Which organ purifies blood in the human body?",
    ["വൃക്ക","കരൾ","ഹൃദയം","ശ്വാസകോശം"],
    ["Kidney","Liver","Heart","Lungs"],
    0, "വൃക്കകൾ രക്തത്തിൽ നിന്ന് മാലിന്യങ്ങൾ അരിച്ചെടുത്ത് മൂത്രമായി പുറന്തള്ളുന്നു.", "Kidneys filter waste from blood and excrete it as urine."
  ],
  [80,3,
    "കുട്ടികളിലെ പോളിയോ പ്രതിരോധത്തിന് നൽകുന്ന വാക്സിൻ ഏതാണ്?",
    "Which vaccine is given to prevent Polio in children?",
    ["OPV (ഒറൽ പോളിയോ വാക്സിൻ)","BCG","DPT","MMR"],
    ["OPV (Oral Polio Vaccine)","BCG","DPT","MMR"],
    0, "OPV (Oral Polio Vaccine) കുട്ടികളിൽ പോളിയോയ്ക്കെതിരെ നൽകുന്നു.", "OPV (Oral Polio Vaccine) is given to children against Polio."
  ],
  // ---- V. Mental Ability & Numerical Skills (20 questions) ----
  [81,4,
    "200 ന്റെ 15% എത്ര?",
    "What is 15% of 200?",
    ["30","20","25","35"],
    ["30","20","25","35"],
    0, "200 × 15/100 = 30", "200 × 15/100 = 30"
  ],
  [82,4,
    "ഒരു ട്രെയിൻ 2 മണിക്കൂറിൽ 120 കി.മീ പിന്നിട്ടാൽ വേഗത എത്ര?",
    "If a train covers 120 km in 2 hours, what is its speed?",
    ["60 km/h","50 km/h","70 km/h","80 km/h"],
    ["60 km/h","50 km/h","70 km/h","80 km/h"],
    0, "വേഗത = ദൂരം/സമയം = 120/2 = 60 km/h", "Speed = Distance/Time = 120/2 = 60 km/h"
  ],
  [83,4,
    "അടുത്ത സംഖ്യ കണ്ടെത്തുക: 2, 5, 10, 17, ?",
    "Find the next number: 2, 5, 10, 17, ?",
    ["26","25","24","27"],
    ["26","25","24","27"],
    0, "വ്യത്യാസം 3,5,7,9 ആയി വർദ്ധിക്കുന്നു. 17+9=26", "Differences increase by 3,5,7,9. 17+9=26"
  ],
  [84,4,
    "500 രൂപയ്ക്ക് 10% നിരക്കിൽ 2 വർഷത്തെ ലാഭം എത്ര?",
    "Simple interest on Rs.500 at 10% for 2 years?",
    ["100","50","200","150"],
    ["100","50","200","150"],
    0, "SI = P×R×T/100 = 500×10×2/100 = 100", "SI = P×R×T/100 = 500×10×2/100 = 100"
  ],
  [85,4,
    "10, 20, 30, 40, 50 എന്നിവയുടെ ശരാശരി കണ്ടെത്തുക.",
    "Find the average of 10, 20, 30, 40, 50.",
    ["30","25","35","40"],
    ["30","25","35","40"],
    0, "ശരാശരി = (10+20+30+40+50)/5 = 150/5 = 30", "Average = (10+20+30+40+50)/5 = 150/5 = 30"
  ],
  [86,4,
    "5 തൊഴിലാളികൾ ഒരു ജോലി 10 ദിവസത്തിൽ ചെയ്യും. 10 തൊഴിലാളികൾ എത്ര ദിവസത്തിൽ ചെയ്യും?",
    "5 workers complete a job in 10 days. How many days for 10 workers?",
    ["5","2","4","3"],
    ["5","2","4","3"],
    0, "M1×D1 = M2×D2 ⇒ 5×10 = 10×D2 ⇒ D2 = 5 ദിവസം", "M1×D1 = M2×D2 ⇒ 5×10 = 10×D2 ⇒ D2 = 5 days"
  ],
  [87,4,
    "80 രൂപയ്ക്ക് വാങ്ങി 100 രൂപയ്ക്ക് വിറ്റാൽ ലാഭ ശതമാനം എത്ര?",
    "A man buys for Rs.80 and sells for Rs.100. Profit percentage?",
    ["25%","20%","10%","30%"],
    ["25%","20%","10%","30%"],
    0, "ലാഭ% = (20/80)×100 = 25%", "Profit% = (20/80)×100 = 25%"
  ],
  [88,4,
    "144 ന്റെ വർഗ്ഗമൂലം എന്താണ്?",
    "What is the square root of 144?",
    ["12","14","16","18"],
    ["12","14","16","18"],
    0, "12×12 = 144 ആയതിനാൽ √144 = 12", "Since 12×12 = 144, √144 = 12"
  ],
  [89,4,
    "a:b = 2:3, b:c = 4:5 എങ്കിൽ a:c കണ്ടെത്തുക.",
    "If a:b = 2:3 and b:c = 4:5, find a:c.",
    ["8:15","2:5","3:4","6:8"],
    ["8:15","2:5","3:4","6:8"],
    0, "a:b = 2:3 = 8:12, b:c = 4:5 = 12:15 ⇒ a:c = 8:15", "a:b = 2:3 = 8:12, b:c = 4:5 = 12:15 ⇒ a:c = 8:15"
  ],
  [90,4,
    "ഒരു കാർ 1 മണിക്കൂറിൽ 60 കി.മീ ഓടുന്നു. 45 മിനിറ്റിൽ എത്ര ദൂരം പിന്നിടും?",
    "A car travels 60 km in 1 hour. How far in 45 minutes?",
    ["45 km","50 km","40 km","55 km"],
    ["45 km","50 km","40 km","55 km"],
    0, "60×(45/60) = 60×(3/4) = 45 km", "60×(45/60) = 60×(3/4) = 45 km"
  ],
  [91,4,
    "12 ന്റെയും 18 ന്റെയും ല.സാ.ഗു. (LCM) എത്ര?",
    "What is the LCM of 12 and 18?",
    ["36","24","48","54"],
    ["36","24","48","54"],
    0, "12=2²×3, 18=2×3² ⇒ LCM = 2²×3² = 36", "12=2²×3, 18=2×3² ⇒ LCM = 2²×3² = 36"
  ],
  [92,4,
    "0.25 നെ ഭിന്നസംഖ്യയിൽ പ്രകടിപ്പിക്കുക.",
    "Express 0.25 as a fraction.",
    ["1/4","1/2","1/5","1/8"],
    ["1/4","1/2","1/5","1/8"],
    0, "0.25 = 25/100 = 1/4", "0.25 = 25/100 = 1/4"
  ],
  [93,4,
    "x + 5 = 12 ആയാൽ x കണ്ടെത്തുക.",
    "If x + 5 = 12, find x.",
    ["7","17","-7","8"],
    ["7","17","-7","8"],
    0, "x = 12 - 5 = 7", "x = 12 - 5 = 7"
  ],
  [94,4,
    "1000 രൂപയ്ക്ക് 5% നിരക്കിൽ 3 വർഷത്തെ സാധാരണ പലിശ എത്ര?",
    "Simple interest on Rs.1000 at 5% for 3 years?",
    ["150","100","200","250"],
    ["150","100","200","250"],
    0, "SI = 1000×5×3/100 = 150", "SI = 1000×5×3/100 = 150"
  ],
  [95,4,
    "2^5 (2-ന്റെ 5-ാം കൃതി) എത്ര?",
    "What is 2^5?",
    ["32","16","64","128"],
    ["32","16","64","128"],
    0, "2^5 = 2×2×2×2×2 = 32", "2^5 = 2×2×2×2×2 = 32"
  ],
  [96,4,
    "ഒരു ത്രികോണത്തിന്റെ രണ്ട് കോണുകൾ 50°, 60° ആയാൽ മൂന്നാം കോൺ കണ്ടെത്തുക.",
    "If a triangle has angles 50° and 60°, find the third angle.",
    ["70°","80°","60°","50°"],
    ["70°","80°","60°","50°"],
    0, "180° - (50°+60°) = 70°", "180° - (50°+60°) = 70°"
  ],
  [97,4,
    "500 രൂപയ്ക്ക് 10% കിഴിവ് നൽകിയാൽ വിൽപ്പന വില എത്ര?",
    "A shopkeeper gives 10% discount on Rs.500. What is the selling price?",
    ["450","400","550","350"],
    ["450","400","550","350"],
    0, "കിഴിവ് = 500×10/100=50, വിൽപ്പന വില = 500-50=450", "Discount = 500×10/100=50, SP = 500-50=450"
  ],
  [98,4,
    "2.5 മണിക്കൂറിൽ എത്ര മിനിറ്റുണ്ട്?",
    "How many minutes are there in 2.5 hours?",
    ["150","120","180","200"],
    ["150","120","180","200"],
    0, "2.5 × 60 = 150 മിനിറ്റ്", "2.5 × 60 = 150 minutes"
  ],
  [99,4,
    "6 സെ.മീ വശമുള്ള സമചതുരത്തിന്റെ ചുറ്റളവ് എത്ര?",
    "What is the perimeter of a square with side 6 cm?",
    ["24 cm","12 cm","36 cm","18 cm"],
    ["24 cm","12 cm","36 cm","18 cm"],
    0, "ചുറ്റളവ് = 4×6 = 24 cm", "Perimeter = 4×6 = 24 cm"
  ],
  [100,4,
    "3x = 27 ആയാൽ x കണ്ടെത്തുക.",
    "If 3x = 27, find x.",
    ["9","10","8","7"],
    ["9","10","8","7"],
    0, "x = 27/3 = 9", "x = 27/3 = 9"
  ],
  // ---- SET 2: General Knowledge (40 questions) ----
  [101,0,"ഇന്ത്യയുടെ തലസ്ഥാനം ഏത്?","What is the capital of India?",["ഡൽഹി","മുംബൈ","കൊൽക്കത്ത","ചെന്നൈ"],["Delhi","Mumbai","Kolkata","Chennai"],0,"ഡൽഹി ഇന്ത്യയുടെ തലസ്ഥാനമാണ്.","Delhi is the capital of India."],
  [102,0,"ചെമ്പൻ ഗ്രഹം എന്നറിയപ്പെടുന്നത് ഏത്?","Which planet is known as the Red Planet?",["ചൊവ്വ","വ്യാഴം","ശുക്രൻ","ബുധൻ"],["Mars","Jupiter","Venus","Mercury"],0,"ചൊവ്വയെ ചെമ്പൻ ഗ്രഹം എന്ന് വിളിക്കുന്നു.","Mars is called the Red Planet."],
  [103,0,"ഏറ്റവും വലിയ സമുദ്രം ഏതാണ്?","Which is the largest ocean?",["പസഫിക്","അറ്റ്ലാന്റിക്","ഇന്ത്യൻ","ആർട്ടിക്"],["Pacific","Atlantic","Indian","Arctic"],0,"പസഫിക് ഏറ്റവും വലിയ സമുദ്രമാണ്.","Pacific is the largest ocean."],
  [104,0,"ഇന്ത്യൻ ദേശീയ ഗാനം രചിച്ചത് ആര്?","Who wrote the Indian national anthem?",["രവീന്ദ്രനാഥ ടാഗോർ","ബങ്കിം ചന്ദ്ര ചാറ്റർജി","മുഹമ്മദ് ഇഖ്ബാൽ","കെ.വി. സൈമൺ"],["Rabindranath Tagore","Bankim Chandra Chatterjee","Muhammad Iqbal","K.V. Simon"],0,"രവീന്ദ്രനാഥ ടാഗോർ ജനഗണമന രചിച്ചു.","Rabindranath Tagore wrote Janaganamana."],
  [105,0,"ഇന്ത്യയുടെ ആദ്യ ഉപഗ്രഹം ഏതാണ്?","Which was India's first satellite?",["ആര്യഭട്ട","ഭാസ്കര","ഇൻസാറ്റ്","എഡ്യൂസാറ്റ്"],["Aryabhata","Bhaskara","INSAT","Edusat"],0,"ആര്യഭട്ട 1975-ൽ വിക്ഷേപിച്ചു.","Aryabhata was launched in 1975."],
  [106,0,"ഏറ്റവും കൂടുതൽ ജനസംഖ്യയുള്ള രാജ്യം ഏതാണ്?","Which is the most populous country?",["ഇന്ത്യ","ചൈന","അമേരിക്ക","ഇന്തോനേഷ്യ"],["India","China","USA","Indonesia"],0,"ഇന്ത്യ ഏറ്റവും കൂടുതൽ ജനസംഖ്യയുള്ള രാജ്യമാണ്.","India is the most populous country."],
  [107,0,"ഇന്ത്യൻ നാവികസേനയുടെ മുദ്രാവാക്യം എന്താണ്?","What is the motto of the Indian Navy?",["ശം നോ വരുണഃ","സത്യമേവ ജയതേ","ധർമോ രക്ഷതി രക്ഷിതഃ","കർമ്മണ്യേവാധികാരസ്തേ"],["Sham No Varunah","Satyameva Jayate","Dharmo Rakshati Rakshitah","Karmanye Vadhikaraste"],0,"ശം നോ വരുണഃ ഇന്ത്യൻ നാവികസേനയുടെ മുദ്രാവാക്യമാണ്.","Sham No Varunah is the motto of Indian Navy."],
  [108,0,"സ്വാമി വിവേകാനന്ദൻ പ്രസിദ്ധമായ ഷിക്കാഗോ പ്രസംഗം നടത്തിയ വർഷം ഏത്?","In which year did Swami Vivekananda give his famous Chicago speech?",["1893","1895","1897","1891"],["1893","1895","1897","1891"],0,"1893-ൽ ഷിക്കാഗോയിൽ പ്രസംഗം നടത്തി.","The Chicago speech was in 1893."],
  [109,0,"ഇന്ത്യയിലെ ആദ്യ ബഹിരാകാശ സഞ്ചാരി ആര്?","Who was the first Indian in space?",["രാകേഷ് ശർമ","കൽപന ചൗള","സുനിത വില്യംസ്","രവിഷ് മൽഹോത്ര"],["Rakesh Sharma","Kalpana Chawla","Sunita Williams","Ravish Malhotra"],0,"രാകേഷ് ശർമ 1984-ൽ ബഹിരാകാശത്ത് എത്തി.","Rakesh Sharma went to space in 1984."],
  [110,0,"ഹരപ്പൻ നാഗരികത ഏത് നദീതീരത്ത് വികസിച്ചു?","Along which river did the Harappan civilization develop?",["സിന്ധു","ഗംഗ","യമുന","ബ്രഹ്മപുത്ര"],["Indus","Ganga","Yamuna","Brahmaputra"],0,"ഹരപ്പൻ നാഗരികത സിന്ധുനദീതീരത്ത് വികസിച്ചു.","Harappan civilization developed along the Indus river."],
  [111,0,"ആസിഡ് ടെസ്റ്റിൽ സ്വർണ്ണം കട്ടിയുള്ളതായി കാണിക്കുന്ന നിറം ഏത്?","Which color does gold show in the acid test?",["മഞ്ഞ","പച്ച","ചുവപ്പ്","നീല"],["Yellow","Green","Red","Blue"],0,"സ്വർണ്ണം ആസിഡ് ടെസ്റ്റിൽ മഞ്ഞ നിറം കാണിക്കും.","Gold shows yellow color in the acid test."],
  [112,0,"കേരളത്തിന്റെ സംഗീതോപകരണം ഏതാണ്?","What is the musical instrument of Kerala?",["ചെണ്ട","വീണ","തബല","സിത്താർ"],["Chenda","Veena","Tabla","Sitar"],0,"ചെണ്ട കേരളത്തിന്റെ പ്രധാന വാദ്യോപകരണമാണ്.","Chenda is Kerala's main percussion instrument."],
  [113,0,"ഇന്ത്യയിലെ ഏറ്റവും ഉയരം കൂടിയ കെട്ടിടം ഏതാണ്?","Which is the tallest building in India?",["പാൽമുംബൈ","ചക്രവർത്തി കോംപ്ലക്സ്","വേൾഡ് വൺ","ഇംപീരിയൽ ടവർ"],["Palais Mumbai","Chakravarthy Complex","World One","Imperial Tower"],2,"വേൾഡ് വൺ മുംബൈയിലെ ഏറ്റവും ഉയരമുള്ള കെട്ടിടമാണ്.","World One is the tallest building in Mumbai."],
  [114,0,"ഏത് ഇന്ത്യൻ സംസ്ഥാനത്തെയാണ് 'ദൈവത്തിന്റെ സ്വന്തം നാട്' എന്ന് വിളിക്കുന്നത്?","Which Indian state is called 'God's Own Country'?",["കേരളം","ഗോവ","തമിഴ്നാട്","കർണാടക"],["Kerala","Goa","Tamil Nadu","Karnataka"],0,"കേരളത്തെ 'ദൈവത്തിന്റെ സ്വന്തം നാട്' എന്ന് വിളിക്കുന്നു.","Kerala is called 'God's Own Country'."],
  [115,0,"ഇന്ത്യൻ റിസർവ് ബാങ്കിന്റെ ആസ്ഥാനം എവിടെ?","Where is the headquarters of RBI?",["മുംബൈ","ഡൽഹി","കൊൽക്കത്ത","ചെന്നൈ"],["Mumbai","Delhi","Kolkata","Chennai"],0,"RBI യുടെ ആസ്ഥാനം മുംബൈയിലാണ്.","RBI headquarters is in Mumbai."],
  [116,0,"സംയുക്ത രാഷ്ട്രങ്ങളുടെ (UN) ആസ്ഥാനം എവിടെ?","Where is the United Nations headquarters?",["ന്യൂയോർക്ക്","ലണ്ടൻ","പാരീസ്","ജനീവ"],["New York","London","Paris","Geneva"],0,"UN ആസ്ഥാനം ന്യൂയോർക്കിലാണ്.","UN headquarters is in New York."],
  [117,0,"ഇന്ത്യൻ ഭരണഘടന നിലവിൽ വന്ന ദിവസം ഏത്?","Which day did the Indian Constitution come into effect?",["ജനുവരി 26, 1950","ഓഗസ്റ്റ് 15, 1947","ജനുവരി 1, 1950","നവംബർ 26, 1949"],["January 26, 1950","August 15, 1947","January 1, 1950","November 26, 1949"],0,"1950 ജനുവരി 26-ന് ഭരണഘടന നിലവിൽ വന്നു.","Constitution came into effect on Jan 26, 1950."],
  [118,0,"ഇന്ത്യയിലെ ഏറ്റവും വലിയ പ്രകൃതി രേഖാചിത്രം ഏതാണ്?","Which is the largest natural harbor in India?",["മുംബൈ","ചെന്നൈ","കൊൽക്കത്ത","വിശാഖപട്ടണം"],["Mumbai","Chennai","Kolkata","Visakhapatnam"],0,"മുംബൈ തുറമുഖം ഏറ്റവും വലിയ പ്രകൃതി തുറമുഖമാണ്.","Mumbai port is the largest natural harbor."],
  [119,0,"കേരളത്തിലെ ഏറ്റവും നീളമുള്ള പുഴ ഏതാണ്?","Which is the longest river in Kerala?",["പെരിയാർ","ഭാരതപ്പുഴ","പമ്പാ","ചാലിയാർ"],["Periyar","Bharathapuzha","Pamba","Chaliyar"],0,"പെരിയാർ (244 കി.മീ) ഏറ്റവും നീളമുള്ള നദിയാണ്.","Periyar (244 km) is the longest river."],
  [120,0,"ഏത് നഗരത്തെ 'ഇന്ത്യയുടെ സിലിക്കൺ വാലി' എന്ന് വിളിക്കുന്നു?","Which city is called the 'Silicon Valley of India'?",["ബെംഗളൂരു","ഹൈദരാബാദ്","പൂനെ","ചെന്നൈ"],["Bengaluru","Hyderabad","Pune","Chennai"],0,"ബെംഗളൂരുവിനെ സിലിക്കൺ വാലി എന്ന് വിളിക്കുന്നു.","Bengaluru is called the Silicon Valley."],
  [121,0,"ഇന്ത്യൻ പതാകയിലെ ചക്രത്തിന് എത്ര ആരക്കാലുകളുണ്ട്?","How many spokes does the wheel on the Indian flag have?",["24","12","36","18"],["24","12","36","18"],0,"അശോകചക്രത്തിന് 24 ആരക്കാലുകളുണ്ട്.","The Ashoka Chakra has 24 spokes."],
  [122,0,"ഇന്ത്യയിലെ ഏറ്റവും പഴക്കമുള്ള പർവ്വതനിര ഏതാണ്?","Which is the oldest mountain range in India?",["ആരവള്ളി","ഹിമാലയം","പശ്ചിമഘട്ടം","വിന്ധ്യൻ"],["Aravalli","Himalayas","Western Ghats","Vindhyan"],0,"ആരവള്ളി ഏറ്റവും പഴക്കമുള്ള പർവ്വതനിരയാണ്.","Aravalli is the oldest mountain range."],
  [123,0,"കേരള കലണ്ടർ (കൊല്ലവർഷം) ആരംഭിക്കുന്നത് ഏത് വർഷത്തിലാണ്?","In which year did the Kerala calendar (Kollavarsham) begin?",["825 AD","325 AD","1000 AD","500 AD"],["825 AD","325 AD","1000 AD","500 AD"],0,"കൊല്ലവർഷം 825 AD-ൽ ആരംഭിച്ചു.","Kollavarsham began in 825 AD."],
  [124,0,"ഇന്ത്യയുടെ ആദ്യ വനിതാ പ്രധാനമന്ത്രി ആരായിരുന്നു?","Who was the first woman Prime Minister of India?",["ഇന്ദിരാ ഗാന്ധി","പ്രതിഭാ പാട്ടിൽ","സോണിയാ ഗാന്ധി","സരോജിനി നായിഡു"],["Indira Gandhi","Pratibha Patil","Sonia Gandhi","Sarojini Naidu"],0,"ഇന്ദിരാ ഗാന്ധി (1966-77, 1980-84) ആദ്യ വനിതാ പ്രധാനമന്ത്രിയായിരുന്നു.","Indira Gandhi was the first woman PM."],
  [125,0,"ഇന്ത്യയുടെ ആണവോർജ്ജ കേന്ദ്രമായ ഭാഭാ അറ്റോമിക് റിസർച്ച് സെന്റർ എവിടെ?","Where is BARC located?",["മുംബൈ","ചെന്നൈ","കൊൽക്കത്ത","ഡൽഹി"],["Mumbai","Chennai","Kolkata","Delhi"],0,"BARC മുംബൈയിലെ ട്രോംബെയിലാണ്.","BARC is in Trombay, Mumbai."],
  [126,0,"ലോകത്തിലെ ഏറ്റവും വലിയ ജനാധിപത്യ രാജ്യം ഏതാണ്?","Which is the world's largest democracy?",["ഇന്ത്യ","അമേരിക്ക","ഇന്തോനേഷ്യ","ബ്രസീൽ"],["India","USA","Indonesia","Brazil"],0,"ഇന്ത്യ ലോകത്തിലെ ഏറ്റവും വലിയ ജനാധിപത്യ രാജ്യമാണ്.","India is the world's largest democracy."],
  [127,0,"ഇന്ത്യൻ റെയിൽവേയുടെ മുദ്രാവാക്യം എന്താണ്?","What is the motto of Indian Railways?",["സുരക്ഷ, സമയനിഷ്ഠ, സേവനം","യതോ ധർമസ്തതോ ജയഃ","ശം നോ വരുണഃ","കർമ്മണ്യേവാധികാരസ്തേ"],["Safety, Punctuality, Service","Yato Dharmastato Jayah","Sham No Varunah","Karmanye Vadhikaraste"],0,"സുരക്ഷ, സമയനിഷ്ഠ, സേവനം എന്നതാണ് മുദ്രാവാക്യം.","Safety, Punctuality, Service is the motto."],
  [128,0,"ഇന്ത്യ ആദ്യ അണുബോംബ് പരീക്ഷണം നടത്തിയ വർഷം?","In which year did India conduct its first nuclear test?",["1974","1962","1971","1998"],["1974","1962","1971","1998"],0,"1974-ൽ 'സ്മൈലിംഗ് ബുദ്ധ' എന്ന പേരിൽ പരീക്ഷണം നടത്തി.","1974 - 'Smiling Buddha' was India's first nuclear test."],
  [129,0,"ഏത് രാജ്യത്തെയാണ് 'ഉദയസൂര്യന്റെ നാട്' എന്ന് വിളിക്കുന്നത്?","Which country is called the 'Land of the Rising Sun'?",["ജപ്പാൻ","ചൈന","കൊറിയ","തായ്ലൻഡ്"],["Japan","China","Korea","Thailand"],0,"ജപ്പാനെ ഉദയസൂര്യന്റെ നാട് എന്ന് വിളിക്കുന്നു.","Japan is called the Land of the Rising Sun."],
  [130,0,"ഐഫൽ ടവർ ഏത് നഗരത്തിലാണ്?","Which city is the Eiffel Tower in?",["പാരീസ്","ലണ്ടൻ","റോം","ബെർലിൻ"],["Paris","London","Rome","Berlin"],0,"ഐഫൽ ടവർ പാരീസിലാണ്.","The Eiffel Tower is in Paris."],
  [131,0,"ഇന്ത്യയുടെ ആദ്യ വനിതാ രാഷ്ട്രപതി ആരായിരുന്നു?","Who was the first woman President of India?",["പ്രതിഭാ പാട്ടിൽ","ഇന്ദിരാ ഗാന്ധി","സോണിയാ ഗാന്ധി","ദ്രൗപദി മുർമു"],["Pratibha Patil","Indira Gandhi","Sonia Gandhi","Droupadi Murmu"],0,"പ്രതിഭാ പാട്ടിൽ 2007-2012 വരെ രാഷ്ട്രപതിയായിരുന്നു.","Pratibha Patil was President from 2007-2012."],
  [132,0,"ഇന്ത്യൻ സായുധ സേനയിലെ ഏറ്റവും വലിയ വിഭാഗം ഏതാണ്?","Which is the largest branch of the Indian Armed Forces?",["കരസേന","നാവികസേന","വ്യോമസേന","കോസ്റ്റ് ഗാർഡ്"],["Army","Navy","Air Force","Coast Guard"],0,"കരസേന ഏറ്റവും വലിയ വിഭാഗമാണ്.","The Army is the largest branch."],
  [133,0,"ആയുർവേദത്തിന്റെ ഉപജ്ഞാതാവായി കണക്കാക്കുന്നത് ആരെ?","Who is considered the founder of Ayurveda?",["ധൻവന്തരി","ചരകൻ","സുശ്രുതൻ","വാഗ്ഭടൻ"],["Dhanvantari","Charaka","Sushruta","Vagbhata"],0,"ധൻവന്തരിയെ ആയുർവേദത്തിന്റെ ഉപജ്ഞാതാവായി കണക്കാക്കുന്നു.","Dhanvantari is considered the founder of Ayurveda."],
  [134,0,"ഇന്ത്യൻ ദേശീയ കലണ്ടർ (ശകവർഷം) ആരംഭിക്കുന്ന മാസം ഏത്?","Which month starts the Indian national calendar (Saka calendar)?",["ചൈത്രം","വൈശാഖം","മാഘം","ഫാൽഗുനം"],["Chaitra","Vaisakha","Magha","Phalguna"],0,"ചൈത്രമാസമാണ് ശകവർഷത്തിലെ ആദ്യ മാസം.","Chaitra is the first month of the Saka calendar."],
  [135,0,"ഇന്ത്യയുടെ ആദ്യ ടെസ്റ്റ് ട്യൂബ് ബേബിയുടെ പേരെന്ത്?","What was the name of India's first test tube baby?",["ദുർഗ","ഇന്ദിര","ലക്ഷ്മി","കാവ്യ"],["Durga","Indira","Lakshmi","Kavya"],0,"ദുർഗ 1978-ൽ ജനിച്ച ആദ്യ ടെസ്റ്റ് ട്യൂബ് ബേബിയാണ്.","Durga (1978) was India's first test tube baby."],
  [136,0,"ഇന്ത്യയിലെ ഏറ്റവും പഴക്കമുള്ള എണ്ണ ശുദ്ധീകരണശാല ഏതാണ്?","Which is the oldest oil refinery in India?",["ഡിഗ്ബോയ്","മുംബൈ","കൊച്ചി","മതുര"],["Digboi","Mumbai","Kochi","Mathura"],0,"ഡിഗ്ബോയ് (അസം) 1901-ൽ സ്ഥാപിതമായി.","Digboi (Assam) was established in 1901."],
  [137,0,"ഇന്ത്യയിലെ ഏറ്റവും വലിയ ഗുഹാക്ഷേത്രം ഏതാണ്?","Which is the largest cave temple in India?",["എല്ലോറ","അജന്ത","എലിഫന്റ","ബദാമി"],["Ellora","Ajanta","Elephanta","Badami"],0,"എല്ലോറ ഗുഹകൾ (മഹാരാഷ്ട്ര) ഏറ്റവും വലിയ ഗുഹാക്ഷേത്രമാണ്.","Ellora Caves (Maharashtra) is the largest cave temple."],
  [138,0,"കേരളത്തിൽ ഏറ്റവും കൂടുതൽ ജനസംഖ്യയുള്ള ജില്ല ഏതാണ്?","Which is the most populous district in Kerala?",["മലപ്പുറം","തിരുവനന്തപുരം","കോഴിക്കോട്","എറണാകുളം"],["Malappuram","Thiruvananthapuram","Kozhikode","Ernakulam"],0,"മലപ്പുറം ഏറ്റവും കൂടുതൽ ജനസംഖ്യയുള്ള ജില്ലയാണ്.","Malappuram is the most populous district."],
  [139,0,"ഏത് സിനിമയ്ക്കാണ് ഇന്ത്യയുടെ ആദ്യ ഓസ്കാർ ലഭിച്ചത്?","Which film won India's first Oscar?",["മദർ ഇന്ത്യ","ഷോളേ","പഥേർ പാഞ്ചാലി","ഗാന്ധി"],["Mother India","Sholay","Pather Panchali","Gandhi"],3,"ഗാന്ധി (1982) ഇന്ത്യയുടെ ആദ്യ ഓസ്കാർ നേടി.","Gandhi (1982) won India's first Oscar."],
  [140,0,"ഇന്ത്യയിലെ ഏറ്റവും ഉയരം കൂടിയ യുദ്ധസ്മാരകം ഏതാണ്?","Which is the tallest war memorial in India?",["ഇന്ത്യ ഗേറ്റ്","നാഷണൽ വാർ മെമ്മോറിയൽ","വിജയ് സ്തംഭ്","ജയ് സ്തംഭ്"],["India Gate","National War Memorial","Vijay Stambh","Jai Stambh"],0,"ഇന്ത്യ ഗേറ്റ് (42 മീ) ഏറ്റവും ഉയരം കൂടിയ യുദ്ധസ്മാരകമാണ്.","India Gate (42 m) is the tallest war memorial."],
  // ---- SET 2: Current Affairs (20 questions) ----
  [141,1,"2025-ലെ ബുക്കർ പ്രൈസ് നേടിയത് ആര്?","Who won the 2025 Booker Prize?",["റേച്ചൽ കുഷ്നർ","പോൾ ലിഞ്ച്","ബുൾഗാകോവ്","ഷീലൻ പേറ്റൽ"],["Rachel Kushner","Paul Lynch","Bulgakov","Sheelan Patel"],0,"2025 ബുക്കർ പ്രൈസ് റേച്ചൽ കുഷ്നറിന്.","2025 Booker Prize went to Rachel Kushner."],
  [142,1,"2025-ൽ ഇന്ത്യയുടെ പ്രധാനമന്ത്രി ആരാണ്?","Who is the Prime Minister of India in 2025?",["നരേന്ദ്ര മോദി","രാജ്നാഥ് സിംഗ്","അമിത് ഷാ","നിർമ്മല സീതാരാമൻ"],["Narendra Modi","Rajnath Singh","Amit Shah","Nirmala Sitharaman"],0,"നരേന്ദ്ര മോദി ഇന്ത്യയുടെ പ്രധാനമന്ത്രിയായി തുടരുന്നു.","Narendra Modi continues as PM of India."],
  [143,1,"2026 FIFA ലോകകപ്പ് ഏത് രാജ്യത്താണ് നടക്കുന്നത്?","Which country is hosting the 2026 FIFA World Cup?",["അമേരിക്ക, കാനഡ, മെക്സിക്കോ","ഖത്തർ","റഷ്യ","ഫ്രാൻസ്"],["USA, Canada, Mexico","Qatar","Russia","France"],0,"2026 FIFA ലോകകപ്പ് വടക്കേ അമേരിക്കയിൽ നടക്കും.","2026 FIFA World Cup is in North America."],
  [144,1,"2025-ലെ നോബൽ സമ്മാനജേതാവ് (ഭൗതികശാസ്ത്രം) ആര്?","Who won the 2025 Nobel Prize in Physics?",["റോജർ പെൻറോസ്","ജോൺ ഹോപ്ഫീൽഡ്","ജിയോഫ്രി ഹിന്റൺ","ആന്റൺ സീലിംഗർ"],["Roger Penrose","John Hopfield","Geoffrey Hinton","Anton Zeilinger"],1,"2025-ൽ ജോൺ ഹോപ്ഫീൽഡിന് ഭൗതികശാസ്ത്ര നോബൽ.","John Hopfield won the 2025 Physics Nobel."],
  [145,1,"ഇന്ത്യയുടെ 2025-ലെ ബഹിരാകാശ ദൗത്യമായ ഗഗൻയാൻ എപ്പോഴാണ് വിക്ഷേപിക്കുക?","When is India's Gaganyaan mission scheduled?",["2026","2025","2027","2024"],["2026","2025","2027","2024"],0,"ഗഗൻയാൻ 2026-ൽ വിക്ഷേപിക്കും.","Gaganyaan is scheduled for 2026."],
  [146,1,"2025-ലെ പത്മ പുരസ്കാരങ്ങളിൽ ഏറ്റവും ഉയർന്ന ബഹുമതി ഏതാണ്?","Which is the highest award in the 2025 Padma awards?",["പത്മവിഭൂഷൺ","പത്മഭൂഷൺ","പത്മശ്രീ","സരസ്വതി സമ്മാൻ"],["Padma Vibhushan","Padma Bhushan","Padma Shri","Saraswati Samman"],0,"പത്മവിഭൂഷൺ ഏറ്റവും ഉയർന്ന പത്മ പുരസ്കാരമാണ്.","Padma Vibhushan is the highest Padma award."],
  [147,1,"2025-ൽ ഏത് രാജ്യത്താണ് COP30 കാലാവസ്ഥ ഉച്ചകോടി നടന്നത്?","Which country hosted COP30 climate summit in 2025?",["ബ്രസീൽ","ഇന്ത്യ","ഈജിപ്ത്","യുഎഇ"],["Brazil","India","Egypt","UAE"],0,"COP30 2025-ൽ ബ്രസീലിൽ നടന്നു.","COP30 was held in Brazil in 2025."],
  [148,1,"2025-ലെ ഇന്ത്യൻ പ്രീമിയർ ലീഗ് (IPL) വിജയിച്ച ടീം ഏതാണ്?","Which team won the 2025 IPL?",["ചെന്നൈ സൂപ്പർ കിങ്സ്","മുംബൈ ഇന്ത്യൻസ്","കൊൽക്കത്ത നൈറ്റ് റൈഡേഴ്സ്","ഗുജറാത്ത് ടൈറ്റൻസ്"],["Chennai Super Kings","Mumbai Indians","Kolkata Knight Riders","Gujarat Titans"],2,"2025 IPL കൊൽക്കത്ത നൈറ്റ് റൈഡേഴ്സ് നേടി.","KKR won the 2025 IPL."],
  [149,1,"2025-ൽ ഇന്ത്യയുടെ ചീഫ് ജസ്റ്റിസ് ആരായിരുന്നു?","Who was the Chief Justice of India in 2025?",["ഡി.വൈ. ചന്ദ്രചൂഡ്","സഞ്ജയ് കിഷൻ കൗൾ","എൻ.വി. രമണ","ജെ.എസ്. ഖേഹർ"],["D.Y. Chandrachud","Sanjay Kishan Kaul","N.V. Ramana","J.S. Khehar"],0,"ഡി.വൈ. ചന്ദ്രചൂഡ് 2025-ൽ ചീഫ് ജസ്റ്റിസായിരുന്നു.","D.Y. Chandrachud was CJI in 2025."],
  [150,1,"2025-ൽ ഏത് ഇന്ത്യൻ കായികതാരത്തിന് രാജീവ് ഗാന്ധി ഖേൽരത്ന പുരസ്കാരം ലഭിച്ചു?","Which Indian athlete received the Khel Ratna award in 2025?",["നീരജ് ചോപ്ര","പി.വി. സിന്ധു","മൻു ഭാകർ","സാത്വിക് രാജാറാം"],["Neeraj Chopra","P.V. Sindhu","Manu Bhaker","Satwiksairaj Rankireddy"],2,"മൻു ഭാകറിന് 2025-ൽ ഖേൽരത്ന പുരസ്കാരം ലഭിച്ചു.","Manu Bhaker received Khel Ratna in 2025."],
  [151,1,"2024-ലെ ഇന്ത്യൻ ജനറൽ ഇലക്ഷനിൽ ഏറ്റവും കൂടുതൽ സീറ്റ് നേടിയ പാർട്ടി ഏത്?","Which party won the most seats in the 2024 Indian general election?",["ബിജെപി","ഇന്ത്യൻ നാഷണൽ കോൺഗ്രസ്","ആം ആദ്മി പാർട്ടി","തൃണമൂൽ കോൺഗ്രസ്"],["BJP","Indian National Congress","Aam Aadmi Party","Trinamool Congress"],0,"2024-ൽ ബിജെപി ഏറ്റവും കൂടുതൽ സീറ്റ് നേടി.","BJP won the most seats in 2024."],
  [152,1,"2025-ൽ ഏത് സംസ്ഥാനമാണ് കേരളത്തിൽ പുതിയ വിമാനത്താവളം നിർമ്മിക്കുന്നത്?","Which new airport is being built in Kerala in 2025?",["അരുവിക്കര","കോഴിക്കോട് വിമാനത്താവളം","കണ്ണൂർ വിമാനത്താവളം","തിരുവനന്തപുരം വിമാനത്താവളം"],["Aruvikkara","Kozhikode Airport","Kannur Airport","Thiruvananthapuram Airport"],0,"അരുവിക്കരയിൽ പുതിയ വിമാനത്താവളം നിർമ്മിക്കുന്നു.","New airport is being built at Aruvikkara."],
  [153,1,"2025-ലെ സാഹിത്യ അക്കാദമി പുരസ്കാരം ഏത് ഭാഷയിലെ എഴുത്തുകാരന് ലഭിച്ചു?","Which language writer won the 2025 Sahitya Akademi Award?",["എം.ടി. വാസുദേവൻ നായർ","എസ്.കെ. പൊറ്റെക്കാട്ട്","ഒ.എൻ.വി. കുറുപ്പ്","എം. മുകുന്ദൻ"],["M.T. Vasudevan Nair","S.K. Pottekkatt","O.N.V. Kurup","M. Mukundan"],0,"എം.ടി. വാസുദേവൻ നായർ സാഹിത്യ അക്കാദമി പുരസ്കാരം നേടി.","M.T. Vasudevan Nair won Sahitya Akademi Award."],
  [154,1,"യുറാനിയം 2025-ൽ ഏത് രാജ്യത്താണ് ഏറ്റവും കൂടുതൽ ഉത്പാദിപ്പിക്കുന്നത്?","Which country produces the most uranium in 2025?",["കസാഖ്സ്ഥാൻ","കാനഡ","ഓസ്ട്രേലിയ","റഷ്യ"],["Kazakhstan","Canada","Australia","Russia"],0,"കസാഖ്സ്ഥാൻ ഏറ്റവും കൂടുതൽ യുറാനിയം ഉത്പാദിപ്പിക്കുന്നു.","Kazakhstan produces the most uranium."],
  [155,1,"2025-ൽ ഏത് രാജ്യമാണ് ലോകത്തിലെ ഏറ്റവും വലിയ സമ്പദ്വ്യവസ്ഥയായി മാറിയത്?","Which country became the world's largest economy in 2025?",["അമേരിക്ക","ചൈന","ഇന്ത്യ","ജപ്പാൻ"],["USA","China","India","Japan"],0,"അമേരിക്ക ഏറ്റവും വലിയ സമ്പദ്വ്യവസ്ഥയായി തുടരുന്നു.","USA remains the largest economy."],
  [156,1,"2025-ൽ കേരളത്തിലെ നിലവിലെ മുഖ്യമന്ത്രി ആരാണ്?","Who is the current Chief Minister of Kerala in 2025?",["പിണറായി വിജയൻ","ഉമ്മൻ ചാണ്ടി","വി.എസ്. അച്യുതാനന്ദൻ","കെ. കരുണാകരൻ"],["Pinarayi Vijayan","Oommen Chandy","V.S. Achuthanandan","K. Karunakaran"],0,"പിണറായി വിജയൻ കേരള മുഖ്യമന്ത്രിയായി തുടരുന്നു.","Pinarayi Vijayan continues as Kerala CM."],
  [157,1,"2025-ലെ ഓസ്കാർ പുരസ്കാരത്തിൽ മികച്ച ചിത്രമായി തിരഞ്ഞെടുത്തത് ഏത്?","Which film won Best Picture at the 2025 Oscars?",["അനോറ","ദി ബ്രൂട്ടലിസ്റ്റ്","കൺക്ലേവ്","എമിലിയ പെരെസ്"],["Anora","The Brutalist","Conclave","Emilia Perez"],0,"അനോറ 2025-ലെ മികച്ച ചിത്രമായി.","Anora won Best Picture at the 2025 Oscars."],
  [158,1,"2025-ൽ ഇന്ത്യയും അമേരിക്കയും തമ്മിൽ ഒപ്പുവച്ച പ്രധാന കരാർ ഏത്?","Which major deal did India and USA sign in 2025?",["പ്രതിരോധ കരാർ","വ്യാപാര കരാർ","ബഹിരാകാശ കരാർ","സാങ്കേതിക കരാർ"],["Defense pact","Trade deal","Space agreement","Tech deal"],0,"ഇന്ത്യ-അമേരിക്ക പ്രതിരോധ കരാർ 2025-ൽ ഒപ്പുവച്ചു.","India-USA defense pact was signed in 2025."],
  [159,1,"2025-ൽ ഗൂഗിളിന്റെ പുതിയ AI മോഡലിന്റെ പേരെന്ത്?","What is the name of Google's new AI model in 2025?",["ജെമിനി","ബാർഡ്","ജിപിടി-5","ഡീപ്മൈൻഡ്"],["Gemini","Bard","GPT-5","DeepMind"],0,"ഗൂഗിളിന്റെ ജെമിനി 2025-ലെ പുതിയ AI മോഡലാണ്.","Google's Gemini is the new AI model in 2025."],
  [160,1,"2025-ൽ ഇന്ത്യൻ സംസ്ഥാനങ്ങളിലെ ഏറ്റവും വലിയ സ്വർണ്ണ ശേഖരം ഏത് സംസ്ഥാനത്താണ്?","Which state has the largest gold reserve in India 2025?",["കർണാടക","രാജസ്ഥാൻ","ആന്ധ്രാപ്രദേശ്","മഹാരാഷ്ട്ര"],["Karnataka","Rajasthan","Andhra Pradesh","Maharashtra"],0,"കർണാടകയിലെ കോലാർ സ്വർണ്ണ ഖനി ഏറ്റവും വലുതാണ്.","Kolar gold mine in Karnataka is the largest."],
  // ---- SET 2: Science (10 questions) ----
  [161,2,"മനുഷ്യ ശരീരത്തിലെ ഏറ്റവും വലിയ ഗ്രന്ഥി ഏതാണ്?","Which is the largest gland in the human body?",["കരൾ","തൈറോയ്ഡ്","പാൻക്രിയാസ്","അഡ്രിനൽ"],["Liver","Thyroid","Pancreas","Adrenal"],0,"കരൾ (ലിവർ) ഏറ്റവും വലിയ ഗ്രന്ഥിയാണ്.","The liver is the largest gland."],
  [162,2,"രക്തത്തിലെ ഹീമോഗ്ലോബിനിൽ അടങ്ങിയിരിക്കുന്ന ലോഹം ഏതാണ്?","Which metal is present in hemoglobin?",["ഇരുമ്പ്","സിങ്ക്","കാൽസ്യം","മഗ്നീഷ്യം"],["Iron","Zinc","Calcium","Magnesium"],0,"ഹീമോഗ്ലോബിനിൽ ഇരുമ്പ് അടങ്ങിയിരിക്കുന്നു.","Hemoglobin contains iron."],
  [163,2,"ശബ്ദത്തിന്റെ വേഗത ഏറ്റവും കൂടുതൽ ഏതിൽ?","In which medium is sound speed the highest?",["ഖരം","ദ്രാവകം","വാതകം","ശൂന്യത"],["Solid","Liquid","Gas","Vacuum"],0,"ഖരങ്ങളിൽ ശബ്ദവേഗത ഏറ്റവും കൂടുതലാണ്.","Sound speed is highest in solids."],
  [164,2,"ജലത്തിന്റെ തിളനില സെൽഷ്യസിൽ എത്ര?","What is the boiling point of water in Celsius?",["100°C","90°C","110°C","120°C"],["100°C","90°C","110°C","120°C"],0,"ജലത്തിന്റെ തിളനില 100°C ആണ്.","The boiling point of water is 100°C."],
  [165,2,"ഓസോൺ പാളിയെ നശിപ്പിക്കുന്ന വാതകം ഏതാണ്?","Which gas destroys the ozone layer?",["സിഎഫ്സി","കാർബൺ ഡൈഓക്സൈഡ്","മീഥേൻ","സൾഫർ ഡൈഓക്സൈഡ്"],["CFC","Carbon dioxide","Methane","Sulfur dioxide"],0,"സിഎഫ്സി (ക്ലോറോഫ്ലൂറോകാർബൺ) ഓസോൺ പാളിയെ നശിപ്പിക്കുന്നു.","CFC destroys the ozone layer."],
  [166,2,"ന്യൂട്രോൺ കണ്ടുപിടിച്ച ശാസ്ത്രജ്ഞൻ ആരാണ്?","Who discovered the neutron?",["ചാഡ്വിക്ക്","റൂഥർഫോർഡ്","ജെ.ജെ. തോംസൺ","ബോർ"],["Chadwick","Rutherford","J.J. Thomson","Bohr"],0,"ജെയിംസ് ചാഡ്വിക്ക് 1932-ൽ ന്യൂട്രോൺ കണ്ടുപിടിച്ചു.","James Chadwick discovered the neutron in 1932."],
  [167,2,"ഏത് വിറ്റാമിനാണ് രക്തം കട്ടപിടിക്കാൻ സഹായിക്കുന്നത്?","Which vitamin helps in blood clotting?",["വിറ്റാമിൻ കെ","വിറ്റാമിൻ സി","വിറ്റാമിൻ ഡി","വിറ്റാമിൻ ഇ"],["Vitamin K","Vitamin C","Vitamin D","Vitamin E"],0,"വിറ്റാമിൻ കെ രക്തം കട്ടപിടിക്കാൻ സഹായിക്കുന്നു.","Vitamin K helps in blood clotting."],
  [168,2,"മൈറ്റോകോൺഡ്രിയയെ എന്ത് എന്ന് വിളിക്കുന്നു?","What is mitochondria called?",["കോശത്തിന്റെ ഊർജ്ജ കേന്ദ്രം","കോശത്തിന്റെ മസ്തിഷ്കം","കോശത്തിന്റെ ഹൃദയം","കോശത്തിന്റെ ഭിത്തി"],["Powerhouse of the cell","Brain of the cell","Heart of the cell","Cell wall"],0,"മൈറ്റോകോൺഡ്രിയ കോശത്തിന്റെ ഊർജ്ജ കേന്ദ്രമാണ്.","Mitochondria is the powerhouse of the cell."],
  [169,2,"പ്രകാശവർഷം എന്തിന്റെ യൂണിറ്റാണ്?","What is a light year a unit of?",["ദൂരം","സമയം","പ്രകാശതീവ്രത","വേഗത"],["Distance","Time","Light intensity","Speed"],0,"പ്രകാശവർഷം ദൂരത്തിന്റെ യൂണിറ്റാണ്.","A light year is a unit of distance."],
  [170,2,"pH സ്കെയിലിൽ ന്യൂട്രൽ മൂല്യം എത്ര?","What is the neutral value on the pH scale?",["7","0","14","1"],["7","0","14","1"],0,"pH 7 ന്യൂട്രൽ ആണ്.","pH 7 is neutral."],
  // ---- SET 2: Public Health (10 questions) ----
  [171,3,"കുഷ്ഠരോഗത്തിന് കാരണമാകുന്ന ബാക്ടീരിയ ഏത്?","Which bacteria causes leprosy?",["മൈകോബാക്ടീരിയം ലെപ്രേ","വിബ്രിയോ കോളറെ","സാൽമൊനെല്ല","എസ്ഷെറിച്ചിയ കോളി"],["Mycobacterium leprae","Vibrio cholerae","Salmonella","Escherichia coli"],0,"മൈകോബാക്ടീരിയം ലെപ്രേ കുഷ്ഠരോഗത്തിന് കാരണമാകുന്നു.","Mycobacterium leprae causes leprosy."],
  [172,3,"DOTS ചികിത്സ ഏത് രോഗത്തിനാണ്?","For which disease is DOTS treatment used?",["ക്ഷയം (TB)","മലേറിയ","എയ്ഡ്സ്","കോളറ"],["Tuberculosis (TB)","Malaria","AIDS","Cholera"],0,"DOTS (Directly Observed Treatment) ക്ഷയരോഗത്തിനുള്ള ചികിത്സയാണ്.","DOTS is a treatment for Tuberculosis."],
  [173,3,"ഇരുമ്പിന്റെ കുറവ് മൂലമുണ്ടാകുന്ന രോഗം ഏതാണ്?","Which disease is caused by iron deficiency?",["അനീമിയ","സ്കർവി","റിക്കറ്റ്സ്","ബെരി-ബെരി"],["Anemia","Scurvy","Rickets","Beri-Beri"],0,"ഇരുമ്പിന്റെ കുറവ് അനീമിയ (വിളർച്ച) ഉണ്ടാക്കുന്നു.","Iron deficiency causes anemia."],
  [174,3,"കേരളത്തിൽ ആരോഗ്യ രംഗത്തെ പ്രധാന ആരോഗ്യ ഇൻഷുറൻസ് പദ്ധതി ഏതാണ്?","What is the main health insurance scheme in Kerala?",["കർമ്മണീയം","ആയുഷ്മാൻ ഭാരത്","ജനനി","സ്വാസ്ഥ്യ"],["Karmaneeyam","Ayushman Bharat","Janani","Swasthya"],0,"കർമ്മണീയം കേരളത്തിലെ ആരോഗ്യ ഇൻഷുറൻസ് പദ്ധതിയാണ്.","Karmaneeyam is Kerala's health insurance scheme."],
  [175,3,"പ്രമേഹം (ഡയബറ്റിസ്) നിയന്ത്രിക്കാൻ ഏത് ഹോർമോണാണ് ഉപയോഗിക്കുന്നത്?","Which hormone is used to control diabetes?",["ഇൻസുലിൻ","തൈറോക്സിൻ","എസ്ട്രജൻ","ടെസ്റ്റോസ്റ്റിറോൺ"],["Insulin","Thyroxine","Estrogen","Testosterone"],0,"ഇൻസുലിൻ പ്രമേഹ നിയന്ത്രണത്തിന് ഉപയോഗിക്കുന്നു.","Insulin is used to control diabetes."],
  [176,3,"കാൻസർ ചികിത്സയിൽ ഉപയോഗിക്കുന്ന ഒരു പ്രധാന രീതി ഏതാണ്?","Which is a major method used in cancer treatment?",["കീമോതെറാപ്പി","ഡയാലിസിസ്","ഫിസിയോതെറാപ്പി","ആയുർവേദം"],["Chemotherapy","Dialysis","Physiotherapy","Ayurveda"],0,"കീമോതെറാപ്പി കാൻസർ ചികിത്സയിലെ പ്രധാന രീതിയാണ്.","Chemotherapy is a major cancer treatment."],
  [177,3,"എലിപ്പനി (Leptospirosis) പകരുന്നത് എങ്ങനെ?","How is Leptospirosis transmitted?",["മലിനജലത്തിലൂടെ","വായുവിലൂടെ","ഭക്ഷണത്തിലൂടെ","രക്തപ്പകർച്ചയിലൂടെ"],["Contaminated water","Airborne","Food","Blood transfusion"],0,"എലിപ്പനി മലിനജലത്തിലൂടെ പകരുന്നു.","Leptospirosis is transmitted through contaminated water."],
  [178,3,"പ്രസവത്തിനു ശേഷമുള്ള മാതാവിനും കുഞ്ഞിനുമുള്ള പരിചരണത്തെ എന്ത് വിളിക്കുന്നു?","What is the postnatal care for mother and baby called?",["പ്രസവാനന്തര പരിചരണം","ഗർഭകാല പരിചരണം","നവജാത ശിശു പരിചരണം","കുടുംബാസൂത്രണം"],["Postnatal care","Antenatal care","Neonatal care","Family planning"],0,"പ്രസവാനന്തര പരിചരണം (Postnatal care) മാതാവിനും കുഞ്ഞിനും നൽകുന്നു.","Postnatal care is given to mother and baby after delivery."],
  [179,3,"ലോകാരോഗ്യ ദിനം എപ്പോഴാണ് ആചരിക്കുന്നത്?","When is World Health Day observed?",["ഏപ്രിൽ 7","മാർച്ച് 7","മെയ് 7","ജൂൺ 7"],["April 7","March 7","May 7","June 7"],0,"ലോകാരോഗ്യ ദിനം ഏപ്രിൽ 7-ന് ആചരിക്കുന്നു.","World Health Day is observed on April 7."],
  [180,3,"കേരളത്തിലെ ജനനനിരക്ക് (birth rate) ഏതാണ്?","What is the birth rate in Kerala?",["13.5","18.5","10.5","15.5"],["13.5","18.5","10.5","15.5"],0,"കേരളത്തിലെ ജനനനിരക്ക് 13.5 ആണ് (2023).","The birth rate in Kerala is 13.5 (2023)."],
  // ---- SET 2: Mental Ability & Numerical Skills (20 questions) ----
  [181,4,"10-ന്റെ 20% എത്ര?","What is 20% of 10?",["2","5","1","3"],["2","5","1","3"],0,"10×20/100 = 2","10×20/100 = 2"],
  [182,4,"8, 12 എന്നിവയുടെ ഉസാഘ (HCF) എത്ര?","What is the HCF of 8 and 12?",["4","2","6","8"],["4","2","6","8"],0,"8=2×2×2, 12=2×2×3 ⇒ HCF=4","8=2×2×2, 12=2×2×3 ⇒ HCF=4"],
  [183,4,"3, 5, 7, 9, ? - അടുത്ത സംഖ്യ ഏത്?","3, 5, 7, 9, ? - Find the next number.",["11","10","12","13"],["11","10","12","13"],0,"ഓരോന്നിനും 2 കൂട്ടുന്നു. 9+2=11","Add 2 each time. 9+2=11"],
  [184,4,"1000 ന്റെ 10% എത്ര?","What is 10% of 1000?",["100","200","50","150"],["100","200","50","150"],0,"1000×10/100 = 100","1000×10/100 = 100"],
  [185,4,"15, 25 എന്നിവയുടെ ശരാശരി എത്ര?","What is the average of 15 and 25?",["20","25","30","15"],["20","25","30","15"],0,"(15+25)/2 = 20","(15+25)/2 = 20"],
  [186,4,"ഒരു സംഖ്യയുടെ പകുതി 25 ആയാൽ, ആ സംഖ്യ ഏത്?","If half of a number is 25, what is the number?",["50","25","75","100"],["50","25","75","100"],0,"25×2 = 50","25×2 = 50"],
  [187,4,"7 എന്ന സംഖ്യയുടെ വർഗ്ഗം എത്ര?","What is the square of 7?",["49","14","21","35"],["49","14","21","35"],0,"7×7 = 49","7×7 = 49"],
  [188,4,"1, 4, 9, 16, ? - അടുത്ത സംഖ്യ ഏത്?","1, 4, 9, 16, ? - Find the next number.",["25","20","36","24"],["25","20","36","24"],0,"1²,2²,3²,4²,5² = 25","1²,2²,3²,4²,5² = 25"],
  [189,4,"200 രൂപയുടെ 25% എത്ര?","What is 25% of Rs.200?",["50","25","75","100"],["50","25","75","100"],0,"200×25/100 = 50","200×25/100 = 50"],
  [190,4,"മണിക്കൂറിൽ 60 കി.മീ വേഗതയിൽ 30 കി.മീ ദൂരം സഞ്ചരിക്കാൻ എത്ര സമയം വേണം?","At 60 km/h, how long to travel 30 km?",["30 min","1 h","15 min","45 min"],["30 min","1 h","15 min","45 min"],0,"സമയം = 30/60 = 0.5 h = 30 min","Time = 30/60 = 0.5 h = 30 min"],
  [191,4,"3:5 -നെ ശതമാനത്തിൽ പ്രകടിപ്പിക്കുക.","Express 3:5 as a percentage.",["60%","30%","50%","40%"],["60%","30%","50%","40%"],0,"3/5 × 100 = 60%","3/5 × 100 = 60%"],
  [192,4,"5! (5 ഫാക്ടോറിയൽ) എത്ര?","What is 5! (5 factorial)?",["120","25","60","240"],["120","25","60","240"],0,"5! = 5×4×3×2×1 = 120","5! = 5×4×3×2×1 = 120"],
  [193,4,"100, 50, 25, 12.5, ? - അടുത്ത സംഖ്യ?",["6.25","10","8","7.5"],["6.25","10","8","7.5"],0,"പകുതിയാകുന്നു. 12.5/2 = 6.25","Halving each time. 12.5/2 = 6.25"],
  [194,4,"ഒരു ചതുരത്തിന്റെ വിസ്തീർണ്ണം 36 ച.സെ.മീ. ആയാൽ വശം എത്ര?","If square area is 36 cm², what is its side?",["6 cm","9 cm","12 cm","18 cm"],["6 cm","9 cm","12 cm","18 cm"],0,"√36 = 6 cm","√36 = 6 cm"],
  [195,4,"500 രൂപ 8% നിരക്കിൽ 1 വർഷത്തേക്ക് നിക്ഷേപിച്ചാൽ പലിശ എത്ര?","Interest on Rs.500 at 8% for 1 year?",["40","50","30","60"],["40","50","30","60"],0,"500×8×1/100 = 40","500×8×1/100 = 40"],
  [196,4,"ഒരു സംഖ്യ 12-ൽ നിന്ന് 20 ആയി വർദ്ധിച്ചാൽ ശതമാന വർദ്ധനവ് എത്ര?","If a number increases from 12 to 20, what is the % increase?",["66.67%","60%","50%","75%"],["66.67%","60%","50%","75%"],0,"(20-12)/12 × 100 = 66.67%","(20-12)/12 × 100 = 66.67%"],
  [197,4,"2, 6, 18, 54, ? - അടുത്ത സംഖ്യ?",["162","108","72","216"],["162","108","72","216"],0,"3 കൊണ്ട് ഗുണിക്കുന്നു. 54×3=162","Multiplying by 3. 54×3=162"],
  [198,4,"20 പേർക്കുള്ള ഭക്ഷണം 15 ദിവസത്തേക്കുണ്ട്. 30 പേർക്ക് എത്ര ദിവസത്തേക്ക് മതിയാകും?","Food for 20 people for 15 days. How many days for 30?",["10","12","8","5"],["10","12","8","5"],0,"M1×D1=M2×D2 ⇒ 20×15=30×D2 ⇒ D2=10","M1×D1=M2×D2 ⇒ 20×15=30×D2 ⇒ D2=10"],
  [199,4,"2, 3, 5, 7, 11, ? - അടുത്ത സംഖ്യ?",["13","15","17","19"],["13","15","17","19"],0,"അഭാജ്യ സംഖ്യകൾ (primes). 11-ന് ശേഷം 13.","Prime numbers. After 11 comes 13."],
  [200,4,"64-ന്റെ വർഗ്ഗമൂലം എത്ര?","What is the square root of 64?",["8","6","7","9"],["8","6","7","9"],0,"8×8=64 ⇒ √64=8","8×8=64 ⇒ √64=8"],
];
